index.d.ts

fixes #10724 
This PR adds missing methods type declarations to:
- `ValidationError`: `addError` & `constructor`
- `ValidatorError`: `constructor`

fix(types): add missing methods to `ValidationError` & `ValidatorError` classes

---

lib/helpers/timestamps/setupTimestamps.js
test/timestamps.test.js

**Summary**
If I set schema like the code below, then it won't pass the condition of 
L56 at `mongoose/lib/helpers/timestamps/setupTimestamps.js`
so I changed `!this.get(createdAt)` into `!this.$__getValue(createdAt)`to set proper timestamps.
```
const schema = Schema({
createdAt: {
type: Schema.Types.Number,
get: (createdAt) => new Date(createdAt * 1000),
},
updatedAt: {
type: Schema.Types.Number,
get: (updatedAt) => new Date(updatedAt * 1000),
},
name: String
}, {
timestamps: { currentTime: () => Math.floor(now / 1000) }
});
```

fix createdAt set condition

---

lib/model.js
test/model.translateAliases.test.js

**Summary**
A fix for issue #10770. `translateAliases` wouldn't pick up nested sub-schemas if the key it just observed wasn't an alias itself.
**Examples**
I amended the translateAliases test case to include an example of the behaviour and made sure it failed before and passed afterwards.

Amending Model.translateAliases to observe non-aliased sub schemas

---

docs/faq.md

**Summary**
Starting in mongoose 6x, you don't need to use markModified anymore (reference: https://mongoosejs.com/docs/migrating_to_6.html#arrays-are-proxies)
Would it make sense to remove it from FAQ? Is this going to change for the latest (6x) docs only?

docs: remove array indexes section from FAQ

---

package.json

And support working with other minor versions.
**Summary**
If the including package has both mongoose and mongodb installed with different versions, it leads to errors on build.
**Examples**
```
myfile.ts(40,31): error TS2345: Argument of type 'import("node_modules/mongoose/node_modules/mongodb/mongodb").ChangeStream<any>' is not assignable to parameter of type 'import("node_modules/mongodb/mongodb").ChangeStream<any>'.
The types of 'options.session.clientOptions.autoEncrypter' are incompatible between these types.
```

chore: upgrade to mongodb driver 4.1.2

---

docs/css/mongoose5.css
docs/discriminators.md
docs/faq.md
docs/guide.md
docs/middleware.md
docs/models.md
docs/plugins.md
docs/queries.md
docs/subdocs.md
docs/tutorials/findoneandupdate.md
docs/typescript.md
docs/typescript/schemas.md
docs/validation.md
website.js

Using marked's built-in slugify function ensures the links would not be broken.
Manual links are still supported, e.g.
```
<h3 id="order"><a href="#order">Save/Validate Hooks</a></h3>
```
However note that this syntax doesn't work (didn't work previously either)
```
```
Also makes the CSS better:
* You can hover any part of the link + the "hidden" side where the icon appears
* Handles h4, h1 and FAQ
Removes as much as possible "manual" links, but some remain (mostly HTML ones I believe, didn't want to check each one that it wouldn't break a link)

Enhance docs section linking

---

index.d.ts

**Summary**
Currently `mongoose.models` can not be explictly typed. So, `mongoose.models.Cat` will always have the type `Model<any>`.
This change enables users to explicitly type `mongoose.models`.
**Examples**
Create a file `mongoose.d.ts` in your codebase:
```ts
declare module 'mongoose' {
interface Models {
Cat: CatModel; // CatModel is something like `interface CatModel extends Model<CatDocument>`
}
}
```
You the type for `mongoose.models.Cat` will be `CatModel`, …

feat: support extending type for mongoose.models

---

lib/cursor/AggregationCursor.js
lib/cursor/QueryCursor.js
lib/utils.js
test/query.cursor.test.js

**Summary**
The 'end' event should be emit before 'close' event.
See [PR](https://github.com/Automattic/mongoose/pull/10906) from master.
Issue: https://github.com/Automattic/mongoose/issues/10902#event-5500362317
**Examples**

[gh-10902 v5] Emit end event in before close

---

docs/migrating_to_6.md
lib/schematype.js

Add SchemaType `set` breaking change in v6 migration guide

---

index.d.ts

**Summary**
The Query `set` method does not function properly in TypeScript projects. It currently only supports, the `string, value` implementation, but not the `object` only implementation. See https://github.com/Automattic/mongoose/blob/5.x/lib/query.js#L1835-L1848 for reference.
**Examples**
```ts
// Does not work
Model.updateOne({ id }).set({ name: 'new' });
// Works
Model.updateOne({ id }).set('name', 'new');
```

Fix ts types for query set

---

index.d.ts

**Summary**
This adds the [clone](https://github.com/Automattic/mongoose/blob/da1f4bdc8e7fceb248c07287ea76131c9e011616/lib/query.js#L242) method to the typings for `Query` as it was missing.
**Examples**
```ts
Model.find().clone()
```
Typescript Error: `Property 'clone' does not exist on type 'Query<any, any, {}, any>'`
[All tests passed.](https://github.com/asportnoy/mongoose/actions/runs/1401455220)

fix(types): add clone to query

---

lib/document.js

**Summary**
Fixed small typo in `Document.prototype.toObject()` api docs.
**Examples**

Fixed typo in document.js

---

package.json

**Summary**
Required to build with TypeScript 4.5 (mongodb/node-mongodb-native#3004)

chore: upgrade to mongodb driver 4.1.4

---

lib/document.js

**Summary**
The link on the site for Mixed schema type, was linking me to the old github pages page, you might have another type of fix, but this is the fix I found
**Examples**

docs(document.js): fix link leading to old github pages site

---

index.d.ts

**Summary**
The Schema's clone function does not preserve the typing (and on its best case, it loses the name of the type and just types the cloned schema as a nameless object)
**Examples**
Before:
clone returns an untyped schema (or at best it returns an object but the type name/interface/class is lost)
After:
clone returns a typed schema which can be the original type or a type that extends the base type (would work for type extending it with partial params)

Fix Schema's clone function typing

---

index.d.ts
lib/aggregate.js
test/aggregate.test.js

MongoDB 4.4 introduces new $unionWith aggregation operator to union the results of multiple different queries into one result set. The documentation can be find [here](https://docs.mongodb.com/manual/reference/operator/aggregation/unionWith).
This PR offers this new pipeline operator as a chaining method to Aggregate.
Working Example:
```js
model.aggregate()
.unionWith({
coll: 'users',
pipeline: [
{
$match: {_id: 1}
}
]
})

add unionWith method to aggregate

---

lib/helpers/projection/isSubpath.js
lib/query.js
test/helpers/projection.test.js
test/query.test.js

Closes #10628, including new documentation.
**Summary**
This PR allows you to remove fields from a projection that have previously been added. `query.select({ a: 1, b: 1 }).select({ b: 0 })` now produces the valid projection `{ a: 1 }` instead of the invalid projection `{ a: 1, b: 0 }`.
**Examples**
Check out the tests.

 Support removing fields from projections

---

index.d.ts

**Summary**
When using mongoose w/ typescript it's not possible to create models w/ instance methods.
**Examples**
https://github.com/Automattic/mongoose/issues/10358#issuecomment-861779692
```ts
import { Schema, Model, createConnection } from 'mongoose'
interface ITestModel {
name: string
}
interface InstanceMethods {
iMethod1: (param1: string) => string
iMethod2: (param1: string) => string
}
interface TestModel extends Model<ITestModel, {}, InstanceMethods> {
sMethod1: (param1: string) => string
sMethod2: (param1: string) => string
}
const ModelSchema = new Schema<ITestModel, TestModel, undefined, InstanceMethods>({ // <-- add `InstanceMethods` here
name: String
})
ModelSchema.statics.sMethod1 = function() {
this.sMethod2('test')
}
ModelSchema.statics.sMethod2 = function() {} …
```

fix(index.d.ts): Allow model creation with instance methods

---

index.d.ts

**Summary**
When mongoose is used from JS, there's no way to pass a type param; this was causing return types to always be `any`. This change makes the type parameter optional, as it was before.

fix(index.d.ts): make populate type param optional

---

lib/index.js

I think this is the right place to update the docs seen on https://mongoosejs.com/docs/api.html#mongoose_Mongoose-set
**Summary**
This small part of the docs is inaccurate, I believe. 
By default, strict is set to true, and strictQuery is set to the value of strict, so strictQuery is true by default.

docs: fix default value of strictQuery

---

docs/populate.md

Docs mistakenly reference foreign field "band" but the foreign field in the example is "author"

Fix typo in populate docs

---

lib/options/SchemaTypeOptions.js

**Summary**
This is a ridiculous PR and I'm sorry for wasting your time. I haven't worked with upstream repos before.  While teaching myself MongoDB I was reading the docs and saw the duplicated "path" in the docs.  I decided to figure out how to fork, update, and PR back into the original repo.  Once I got as far as this PR I was going to just delete my repo and forget about it, but I decided what the heck...
**Examples**
This is a documentation comment "fix" only.

Remove duplicate "path" in comment.

---

lib/helpers/populate/assignVals.js
lib/helpers/populate/getModelsMapForPopulate.js
lib/model.js
lib/utils.js
test/model.populate.test.js

Re: #10856
**Summary**
From the discussion of #10856, we want to support populating partially denormalized subdocuments. 
```javascript
const blogPostSchema = Schema({
title: String,
author: {
// Denormalize `_id` and `name` from User, but if you `populate('author')`, you should get the other properties
type: new Schema({ _id: Number, name: String }),
ref: 'User'
}
});
```
PR is a little rougher than I'd like, I would still like to improve a couple of things: a `cloneArrays()` function for the `if (Array.isArray(unpopulatedValue)) { ... }` case to handle deep arrays, make this less of an edge case in `getModelsMapForPopulate()`, and make sure this still works with arrays that contain subdocuments. But enough to review the general idea.
One key issue/design decision: if you …

feat(populate): support `ref` on subdocuments

---

index.d.ts

**Summary**
Using more and more aggregations in our projects, I decided to type accurately every pipeline stage according to the last mongodb documentation.
Now I'm proposing it for the mongoose package.
It does not narrow what cannot be narrowed ([expressions](https://docs.mongodb.com/manual/meta/aggregation-quick-reference/#std-label-aggregation-expressions) for example, are still typed with `any`).
Only Pipeline stages are typed, pipeline operators types are not implemented, as this would require a lot of work.
**Example**
Following the first aggregation example in the MongoDB doc: https://docs.mongodb.com/manual/core/aggregation-pipeline/#complete-aggregation-pipeline-example
With a model `Order` that implements the following interface: 
```ts
{ 
_id: ObjectId, 
productName: string, …
```

fix(index.d.ts): types for aggregation pipeline stages

---

lib/model.js

**Summary**
When doing copy/paste of the example
```
const numAdventures = Adventure.estimatedDocumentCount();
```
there is no expected numeric value assigned to the `numAdventures`. By adding `await` there will be one.
https://mongoosejs.com/docs/api.html#model_Model.estimatedDocumentCount

docs(model.estimatedDocumentCount): add `await` into example to get value from the Query

---

index.d.ts

In docs is clearly state that the default value for `toJSON()` and `toObject()` options is `{ transform: true, flattenDecimals: true }`. Also, it's possible to use `{ transform: false }` to stop document transformation.

fix(index.d.ts): add boolean type for transform option

---

index.d.ts

**Summary**
The code below is generating a error:
```
const data = model.aggregate([
{
$match: {
somevalue: "string"
}
},
{
$unionWith: {
coll: "some.collection",
pipeline: [
{
$match: {
someField: "someValue"
}
}
]
}
}
]);
```
Error:
```
Type '{ $match: { someField: string; }; }[]' is not assignable to type 'AddFields | Bucket | BucketAuto | CollStats | Count | Facet | GeoNear | GraphLookup | Group | ... 20 more ... | undefined'.
Property '$unwind' is missing in type '{ $match: { someField: string; }; }[]' but required in type 'Unwind'.ts(2322)
```
Currently, the `pipeline` property is not an array.
More info here: #11069

fix(index.d.ts): make pipeline property from $unionWith an array

---

lib/query.js

**Summary**
`Query.prototype.transform` documentation changed. An old method name `map` was replaced with `transform`.
Resolves #11093

Query.prototype.transform documentation fix, resolves #11093

---

index.d.ts

Fix #11088 
Fix #11099
Changed type to
```
$project: { _id?: 0 | false; [field: string]: any } | {_id: 1 | true}
```
:heavy_check_mark:  OK
```
{
$project: {
_id: 1,
}
}
```
:heavy_check_mark:  OK
```
{
$project: {
_id: 0,
someField: 1
}
}
```
:x: Error
```
{
$project: {
_id: 1,
someField: 1
}
}
```

fix(index.d.ts) treat _id like other fields in $project

---

lib/helpers/query/castUpdate.js
test/model.update.test.js

fix: allow use type string in $unset update with aggregation pipeline

---

lib/connection.js

For some situation, the mongo server host is dynamic and we need to create a new mongodb client when the current client is disconnected, so it's much better if we can call `setClient` multiple times.
```js
const createMongoClient = async () => {
const host = await service.discover('mongodb.host');
const uri = `mongodb://${host.uri}/test`;
const mongoClient: MongoClient = await MongoClient.connect(uri, {
autoReconnect: false,
});
client.setClient(mongoClient);
client.once('disconnected', async () => {
mongoClient.close();
// @ts-ignore   we need to get rid of this
client.client = null;
while(true) {
await sleep(3 * 1e3);
try {
if (client.readyState === mongoose.STATES.disconnected) {
await createMongoClient();
}  
break;
} catch (err) {
console.error(err);
}
}        
});
}
await …
```

Better for service discovery

---

index.d.ts

Fixes #11109.
Thanks to @gabrie-allaigre
Correctly assign types of whenMatched case according to official docs:
https://docs.mongodb.com/manual/reference/operator/aggregation/merge/

fix(index.d.ts): fix typings in Merge stage

---

lib/index.js
test/typescript/global.ts

**Summary**
It is declared as an enum in ts definitions, but did not really work.
**Examples**
This code passes ts compilation, but crashes on runtime:
```typescript
import { Connection, ConnectionStates } from 'mongoose';
// ...
return (this.connection.readyState !== ConnectionStates.connected);
```

fix(index): export ConnectionStates

---

lib/model.js
test/model.populate.test.js

**Summary**
findByIdAndUpdate should not work with an undefined id, if an update is specified. Resolves #10964
**Examples**
I added a test to demonstrate this change.

Fix findByIdAndUpdate behavior with undefined id

---

index.d.ts

**Summary**
This PR is the follow-up PR for: #11059 and for #11124 
All explicitly defined keys should always follow the type defined at the index signature. So having `any` as a type for `_id` was just a hidden error.
Even more, `_id` as a key in the member of union type was redundant.

Follow-up fix of TS index signature definition for Group type.

---

index.d.ts

**Summary**
This is a typescript type-only change.
Currently, the type definition for each sub-pipeline within a `{ $facet: ... }` aggregation pipeline stage is baked in to the overall definition of the Facet stage. 
We've got a situation where we'd like to pass these sub-pipeline arrays around, ideally in a type-safe way. Currently, that requires a bit of boilerplate to keep typescript happy; with this change, we should just be able to say, for example:
```ts
import * as mongoose from "mongoose";
export function Query(resultsFacet: mongoose.FacetPipelineStage[]) {
return db.myCollection.aggregate([{
$facet: { results: resultsFacet },
}]);
}
```
Happy to change the name of this type if `FacetPipelineStage` doesn't make sense. 
Thank you for the great project 😀

Export a Separate Type for PipelineStage Types Allowed in Facet Aggregation Sub-Pipelines

---

index.d.ts

**Summary**
`Query.projection` should return `this` for correct completion while method chaining.
Introduced here: https://github.com/Automattic/mongoose/commit/d7aaa5568330e2dcadde7ae6847bff1522f3ae4e

types: Fix return type of `projection` method

---

lib/index.js

Solved the issue #11089 . Now the `Mongoose.prototype.Document()` Document link points to the  https://mongoosejs.com/docs/api.html#Document

documentation: fixed broken link

---

index.d.ts

Types are not accurate for all available deep populate possibilities.

fix(index.d.ts): deep populate

---

docs/populate.md

Added a section that explains how to populate multiple paths in middleware.
**Summary**
This is a pretty common use case, yet it is not really straight forward to achieve, so I believe that the solution to the problem should definitely be in the documentation.

Update docs to include the section about populating multiple paths in middleware

---

.github/ISSUE_TEMPLATE.md
docs/faq.md

Updated docs and issue templates for new FAQs

---

lib/utils.js
package.json

Replace ms with faster @lukeed/ms

Replace ms with faster @lukeed/ms

---

lib/aggregate.js
lib/document.js
lib/drivers/node-mongodb-native/collection.js
lib/model.js
lib/query.js
lib/schematype.js
lib/statemachine.js
lib/utils.js
package.json

Remove the package "sliced" in favor of native functions.

remove sliced

---

lib/index.js
lib/model.js
lib/validoptions.js
test/index.test.js

Why can't I do `await Model.listIndexes().length` off the rip but instead have to save it to a variable? Just curious.

Sync indexes global option

---

package.json
tools/repl.js

To run unit tests locally i added the option to start a mongodb-memory-server.
`npm run mongo` and voilá
if you want to run e.g. mongo 4.4.12 you would do 
`npm run mongo -- 4.4.12`

add mongodb-memory-server to test easier locally. 

---

index.d.ts
lib/connection.js

fix: memory-leak in .transaction()

---

lib/helpers/path/setDottedPath.js
test/helpers/setDottetPath.test.js

Improve perf of setDottetPath
var0 = old
var1 = new
```
authorizationResponse
var0 x 30,093,641 ops/sec ±1.66% (86 runs sampled)
var1 x 123,402,415 ops/sec ±0.42% (95 runs sampled)
authorizationResponse.stan
var0 x 4,020,169 ops/sec ±0.43% (90 runs sampled)
var1 x 5,329,115 ops/sec ±0.50% (91 runs sampled)
```
benchmark:
```
'use strict';
const Bench = require('benchmark');
const { expect } = require('chai');
function setDottedPathVar0(obj, path, val) {
const parts = path.indexOf('.') === -1 ? [path] : path.split('.');
let cur = obj;
for (const part of parts.slice(0, -1)) {
if (cur[part] == null) {
cur[part] = {};
}
cur = cur[part];
}
const last = parts[parts.length - 1];
cur[last] = val;
};
function setDottedPathVar1(obj, path, val) {
if (path.indexOf('.') === -1) {
obj[path] = val; …
```

perf: improve setDottedPath

---

lib/cast.js

There was a remark to remove a code block if we upgraded to bson4....

remove obsolete code after upgrading to bson4

---

lib/cast.js
lib/helpers/query/cast$expr.js
test/helpers/query.cast$expr.test.js

Mostly for comparisons, like `$eq`, etc. like in #10662 .
Missing support for a few things, like `$dateFromString` and similar operators, which we can add. But primarily wanted to support casting comparisons of paths and literals, which is what this PR does.

Casting for `$expr` in queries

---

lib/utils.js

This PR modifies the deepEqual check in mongoose. It checks a regex for all 6 flags of a Regex.
As it is more strict, it could be breaking(?)

check for all flags in a regex deepequal

---

package.json
test/shard.test.js

We use chalk only in one place: To write in red, that we dont run the sharding tests. We just need to use the correct escape character, which can be easily googled, to write in red color. 
Reduces the potential risk of a supply chain attack.

chore: remove chalk as devDependency

---

package.json
test/model.findOneAndUpdate.test.js

uuid reports some Math.random sec-vuln. So upgraded it and used the builtin parse from 8.3 uuid to replace the not maintained uuid-parse package. 
Reduce Supply Chain Attack Risks.

chore: remove uuid-parse, upgrade uuid

---

package.json

mocha 9.1.3 throws a npm audit warning. Upgrading to mocha 9.2.0 resolves this issue.

chore: upgrade mocha to 9.2.0

---

package.json
test/aggregate.test.js

We did not use semver. I took the chance to make the onlyTestAtOrAbove-method more readable (well in my opinion atleast ;).

chore: remove semver from dev dependencies

---

package.json
test/docs/lean.test.js

object-sizeof is an unnecessary dependency, which does not even return the correct memory footprint of a variable in v8/node. To determine the correct size of a variable, we can use the serialize method of v8 and use the length property of the Buffer to determine the actual size of the variable, when stored in v8.

chore: replace object-sizeof with native v8.serialize(...).length

---

package.json

This PR adds back nyc to mongoose. Maybe the first step to also use a github action for test coverage?

chore: add back nyc

---

lib/document.js
test/document.test.js

**Summary**
When a schema included a subdocument that had a default value of empty
object and that subdocument itself included some defaults, the
subdocument was always null if a query was run with a dotted path
projection to the subdocument's default values.
Check not only that the curent path being evaluated to have defaults
applied, but also check if the current path is part of the included
children in the projection.
**Examples**
A test has been provided that fails before the change, but assume the following Schemas:
```javascript
const childSchema = new mongoose.Schema({
name: {
type: mongoose.Schema.Types.String,
default: () => 'child',
},
});
const parentSchema = new mongoose.Schema({
name: mongoose.Schema.Types.String,
child: {
type: …
```

fix: set default for dotted path projection

---

docs/guide.md

**Summary**
This option has been deprecated in 6.0. It doesn't show up in code files any more when searching the repo, so I guess removing the docs is a good thing to do.
> If you're making a change to documentation, do **not** modify a `.html` file directly. Instead find the corresponding `.pug` file or test case in the `test/docs` directory.
The modified file is the only place the Github search finds the option `useNestedStrict`, therefore I edited that directly. Maybe it can be updated by recompiling the docs as well?
**Examples**
None

Docs: Remove documentation for `useNestedStrict`

---

docs/compatibility.md

Based on the conversation in #11302, I assume Mongoose 6 is compatible with MongoDB 4. Update docs so people know that a safe upgrade is possible.

Mark Mongoose 6 as compatible with MongoDB 4

---

lib/helpers/clone.js
package.json
test/helpers/clone.test.js

Cloning an regexp does not need an external library.

perf: remove regexp-clone

---

lib/types/array/ArrayWrapper.js

Hyperlink for `Document.equals()` on this page: https://mongoosejs.com/docs/api/array.html#mongoosearray_MongooseArray-pull leads to (https://mongoosejs.com/docs/api/api.html#document_Document-equals) which is a 404 not found page.
The pull request intends to fix the broken link.

Fix: Broken Link

---

lib/types/array/methods/index.js

The edit on Github button on this page: https://mongoosejs.com/docs/api/array.html#mongoosearray_MongooseArray-pull where I actually found the broken link #11337 is itself a broken link :|
I found another file with similar contents, not exactly sure which one corresponds to the actual website docs, so decided to modify this as well.

Fix: Broken Link (#11337) +1

---

.github/workflows/test.yml
CONTRIBUTING.md
package.json

This is a PR following the tsd PR. We don't need to symlink any more, yeah!

remove npm script for symlinking mongoose

---

docs/connections.md

Minimal grammar fix.
'reconnect to a the replica' -> 'reconnect to the replica'
**Summary**
Fixes grammar in sentence.
**Examples**
doc change

Remove double determiners in connections docs.

---

package.json

remove js-yaml dependency

---

docs/deprecations.md
lib/query.js

Fixed broken link from findandmodify method deprecation to version 5.x

Broken link from findandmodify method deprecation

---

types/index.d.ts

**Summary**
Fix this issue #11372 by adding all the possible types to highlight path ($search operator) following [MongoDB specs](https://docs.atlas.mongodb.com/atlas-search/highlighting/#std-label-highlight-ref)
**Examples**
Code provided in the issue is now working fine
```typescript
import {Model, model, Schema} from "mongoose";
interface IUser {
name: string;
firstName: string;
search(query: string): any;
}
// 2. Create a Schema corresponding to the document interface.
const schema = new Schema<IUser>({
firstName: { type: String, required: true },
name: { type: String, required: true },
});
schema.static("search", function(this: Model<IUser>, query: string) {
return this.aggregate([
{
$search: {
highlight: {
path : ["name", "firstname"], // "name" works fine
},
index: "searchLucene", …
```

fix $search highlight path option type

---

lib/cursor/AggregationCursor.js
lib/cursor/QueryCursor.js

The tc39 async iterator helpers spec adds `.map` to async iterators and Node added support for that.
As part of spec compliance Node uses defineProperty to add these properties.
This PR fixes setting `.map` in Mongoose over the property.
As a side note: it might make sense for Mongoose to deprecate `.map` since it's mutative which makes it named the same but with a different behavior from the tc39 iterator helpers proposal `.map`
Fixes: https://github.com/Automattic/mongoose/issues/11377

fix Node.js 17.5 compatibility

---

lib/cast/number.js
lib/helpers/query/cast$expr.js

Dont know if this is improving the overall performance, but should I improved some parts.
omitUndefined is now about 5 - 10 % faster
isPath is now about 40 % faster.
Benchmarks and their result:
```javascript
'use strict';
const Benchmark = require('benchmark');
function omitUndefinedVar1(val) {
const keys = Object.keys(val);
for (const key of keys) {
if (val[key] === void 0) {
delete val[key];
}
}
}
function omitUndefinedVar2(val) {
const keys = Object.keys(val);
for (let i = 0, len = keys.length; i < len; ++i) {
(val[keys[i]] === void 0) && delete val[keys[i]];
}
}
new Benchmark.Suite()
.add('var1 valid', function () {
const a = omitUndefinedVar1({
a: undefined,
b: null,
c: undefined,
d: 'a',
fa: 234,
ferfe:234234,
adcverg:234234
})
})
.add('var1 valid2', function () {
const a = …
```

improve performance of cast$expr

---

lib/cast.js
lib/connection.js
lib/document.js
lib/drivers/node-mongodb-native/collection.js
lib/error/cast.js
lib/helpers/document/compile.js
lib/index.js
lib/model.js
lib/query.js
lib/queryhelpers.js
lib/schema.js
lib/schema/SubdocumentPath.js
lib/schema/array.js
lib/schema/documentarray.js
lib/schematype.js
lib/types/array/methods/index.js
lib/types/map.js

With this PR I replaced the get-method with fast property access were it is possible. I know that it looks not so sexy like the get call, but it has performance improvements as we dont need to split the path, traverse an array and stuff.
before:
$ MONGOOSE_DEV=1 node benchmarks/clone.js 
Simple x 140,319 ops/sec ±1.35% (92 runs sampled)
AllSchema x 23,986 ops/sec ±1.26% (90 runs sampled)
MONGOOSE_DEV=1 node benchmarks/validate.js 
invalid x 22,726 ops/sec ±0.62% (95 runs sampled)
valid x 61,786 ops/sec ±0.71% (93 runs sampled)
after
$ MONGOOSE_DEV=1 node benchmarks/clone.js 
Simple x 196,277 ops/sec ±0.72% (92 runs sampled)
AllSchema x 28,769 ops/sec ±0.41% (94 runs sampled)
$ MONGOOSE_DEV=1 node benchmarks/validate.js 
invalid x 23,488 ops/sec ±2.98% (95 runs sampled)
valid x 69,983 …

perf: use fast property access instead of get were possible

---

lib/aggregate.js
lib/helpers/query/isOperator.js

isOperator in aggregate used a .some() method to iterate over the only key in the array, so now it access it directly. Also added a null check for better safety...
the isOperator helper method used .startsWith method, which is slower than just checking the first character of the string. So I replaced it. 
It appears, the isOperator in aggregate and isOperator for queries have the same behaviour somehow, but the one for queries checks for the "special keys". Are those keys also special for the aggregation stage?

impr: isOperator

---

lib/helpers/query/hasDollarKeys.js

Small refactoring of hasDollarKeys
- added a name to the function
- the typecheck now uses !== instead of !=, as we just switched the conditions in the if-clause. So no implicit conversion of nullish values.
- uses direct character comparison instead of startsWith.

impr: hasDollarKeys

---

docs/migrating_to_6.md

docs(migration guide): add model.exists breaking change returning doument instead of boolean

---

docs/populate.md

**Summary**
I was initialy looking for some documentation for a custom "filter" on populate virtuals. I couldn't find one anywhere.
My use case is the following : I need a virtual field for a filtered part of a collection (e.g. author's `posts` with `archived: false` property).

docs(populate): add virtual populate `match` option documentation

---

lib/document.js
lib/schematype.js

It is basically replacing the forEach with classic for loop
before
```
MONGOOSE_DEV=1 node validate
invalid x 23,482 ops/sec ±3.63% (89 runs sampled)
valid x 75,238 ops/sec ±0.58% (91 runs sampled)
```
after
```
MONGOOSE_DEV=1 node validate
invalid x 27,460 ops/sec ±0.91% (89 runs sampled)
valid x 76,128 ops/sec ±0.69% (93 runs sampled)
```

perf: improve validation sync and async by replacing forEach with classic for loops

---

test/types/schema.test.ts
types/index.d.ts

Added declaration for the `supressReservedKeysWarning`  schema property.
**Summary**
This PR adds a declaration for the `suppressReservedKeysWarning` schema option added in version 6.

chore: update declarations for schema options

---

benchmarks/validate.js

We were missing the async validations in the benchmarks. This one adds the async validation paths

chore: add async benchmarks for validate

---

lib/helpers/isAsyncFunction.js
test/helpers/isAsyncFunction.test.js

I was playing around and realized that isAsyncFunction is using utils.inspect and startsWitht. So I tested the benchmark/validate and got
```
MONGOOSE_DEV=1 node validate
invalid x 24,186 ops/sec ±0.62% (92 runs sampled)
valid x 76,020 ops/sec ±0.59% (92 runs sampled)
```
So I replaced startsWith with indexOf which is about 10 times faster than startsWith and benchmarked again:
```
MONGOOSE_DEV=1 node validate
invalid x 24,283 ops/sec ±3.05% (94 runs sampled)
valid x 76,428 ops/sec ±0.50% (95 runs sampled)
```
No performance gain, despite we know that indexOf is about 10 x faster indicates that we have a different bottleneck, utils.inspect.
So I thought: Ok, there is a call to utils.inspect which is basically stringifying the function to just check if the string begins with …

perf: improve isAsyncFunction

---

test/types/connection.test.ts
types/Connection.d.ts
types/index.d.ts

This PR extracts the Connection Typings
With the first commit I extract the typings from Connection from index.d.ts into a new Connection.d.ts. 
With the second commit I do the actual improvements.
The order of the function overloads are according to Typescript Do's and Don'ts, so basically by most arity to least arity.
Attributes like pass, user, models etc. were set to readonly. nobody should use them directly for manipulating the internals of mongoose. If there is some reason to modify them, a developer should use the corresponding methods.
Just check the second commit to see relevant changes.
Also added typings tests.

Improve Connection Typings

---

CHANGELOG.md

@vkarpov15 
Now that I'm merging a few pull requests, I presume we need to change how we're building the changelog.
I presume that previously, you used to add an item to a local changelog and then ship it once you release a new version. If that's the case, we'd need to have a shared source we both can write to so we don't miss a thing.

chore: add missing item from 6.2.3 changelog

---

docs/timestamps.md

The doc mentions that both `$setOnInsert` and `$set` are used for `createdAt`. I believe it's a mistake. It should be `$set` for `updatedAt`

$set is used for updatedAt [Timestamps]

---

test/types/aggregate.test.ts
types/index.d.ts

When using TypeScript, calling `model.aggregate().sort("-name")` generates the following error:
```
Argument of type 'string' is not assignable to parameter of type 'Record<string, 1 | -1 | { $meta: "textScore"; }>'
```
This PR also adds support for mongoose sort keywords: `asc`, `ascending`, `desc` and `descending` (according to the [current implementation](https://github.com/Automattic/mongoose/blob/18cb0bed7256784701d7b75e160707895a0e50db/lib/aggregate.js#L573) and  the mongoose docs).

fix(typescript): `aggregate.sort()` accepts a string but also `{ field: 'asc'|'ascending'|'desc'|'descending' }`

---

test/docs/lean.test.js

**Summary**
Fixed length comparaison between POJO and Mongoose doc in lean.test.js

fix: length comparaison in lean.test.js

---

types/index.d.ts

https://github.com/Automattic/mongoose/issues/11473
**Summary**
**Examples**

Typescript no Type Hint for overriding Query.

---

test/types/middleware.test.ts
types/index.d.ts

If I understood #11449 correctly, the ability to type the hook function is not given, because the types are not exposed.

Impr: export and refactor types of PreMiddlewareFunction, PreSaveMiddlewareFunction, PostMiddlewareFunction, ErrorHandlingMiddlewareFunction

---

test/types/populate.test.ts
test/types/queries.test.ts
types/index.d.ts

Should resolve https://github.com/Automattic/mongoose/issues/11496
@Uzlopak

fix: improve populate type narrowing 

---

lib/model.js

**Summary**
The `Model.findOneAndReplace` examples had the wrong params passed to them.
`conditions` instead of `filter` and `replacement`.
**Example**
```javascript
A.findOneAndReplace(conditions)
```
When in reality it should be:
```javascript
A.findOneAndReplace(filter, replacement)
```

fix: Model.findOneAndReplace docs

---

.github/workflows/test.yml
lib/model.js
test/model.test.js
test/types/models.test.ts
test/types/schema.test.ts
types/index.d.ts

Resolves #11229 
Didnt know if I should just add expiresAfterSeconds which does only pass through the value to createCollection or like we do it in indexes with expires where we also handle date strings. So I implemented both. Removing is easier than adding.
Added unit test

fix: add missing timeseries expiration handling

---

docs/middleware.md

**Summary**
This edit removes a minor typo from the `Middleware` [guide](https://mongoosejs.com/docs/middleware.html#types-of-middleware).
**Examples**
Minor typo; example not needed.

correct typo in middleware.md

---

types/index.d.ts

Added strictPopulate to PopulateOptions, otherwise given option can't be used in TS projects when enforcing types.
**Summary**
When using populate in mongoose 6, the types for populate options might've been overlooked. ```PopulateOptions``` interface is missing `strictPopulate` prop, so I added one, with description from the doc. Otherwise I can't use populate with given option.
**Examples**
```
await DocumentModel.findById('some_id')
.populate({
match: { somePath: { $ne: undefined } } 
path: 'somePath',
strictPopulate: false
})
```
Previously this was not allowed in typescript dev environment due to enforcing of types, and a type error was thrown.
Now I added the respective type and all works.
***For future reference***
It seems that the `options?: any` seems to be unnecessary and …

Add strictPopulate type to PopulateOptions

---

docs/populate.md

"on:" is a reserved keyword which fails on execution, therefore modelId: would be the correct key and works well
**Summary**
This PR will make the documentation example codes bug free as the current syntax gave error ```Error: `on` may not be used as a schema pathname```
**Examples**
NA

Incorrect Example Syntax - Dynamic References via `refPath`

---

docs/search.js
package.json
website.js

This fixes the breaking changes in [v3](https://github.com/markedjs/marked/releases?page=3#:~:text=tokens%20(%232166)%20(bc400ac)-,BREAKING%20CHANGES,-Drop%20support%20for) (Node 10 support dropped), and [v4](https://github.com/markedjs/marked/releases/tag/v4.0.0), `const { marked } = require('marked')` instead of `const marked = require('marked');`

chore(deps-dev): bump marked from 2.1.3 to 4.0.12

---

.eslintrc.json

This PR includes the following files/folders to be automatically linted. Is there a reason to not want to lint those?
* website.js
* benchmarks
* tools

chore(eslint): include tools, website.js and benchmarks to eslint config

---

test/types/populate.test.ts
types/index.d.ts

Regarding https://github.com/Automattic/mongoose/issues/11532 https://github.com/Automattic/mongoose/issues/11518 https://github.com/Automattic/mongoose/issues/11585

Fix: Populate query return type.

---

test/types/queries.test.ts
types/index.d.ts

**Summary**
This improves the type for lastErrorObject, this helps to use the correct values as there is for example no modifiedCount or other things that a simple updateOne returns.
**Examples**
```ts
// findOneAndUpdate with rawResult: true
const result = Model.findOneAndUpdate(query, { $inc: { occurence: 1 } },  { upsert: true, returnDocument: 'after', rawResult: true });
// should work
updateResult.lastErrorObject?.upserted
// should throw error
updateResult.lastErrorObject?.modifiedCount
```

types: improve lastErrorObject typing for rawResults

---

lib/cursor/QueryCursor.js
lib/error/eachAsyncMultiError.js
lib/helpers/cursor/eachAsync.js
test/helpers/cursor.eachAsync.test.js
types/cursor.d.ts

`continueOnError` option for `eachAsync()`

---

docs/3.0.x/docs/helpers/filters.js
docs/3.0.x/docs/helpers/highlight.js
docs/3.1.x/docs/helpers/filters.js
docs/3.1.x/docs/helpers/highlight.js
docs/3.1.x/docs/source/api.js
docs/3.2.x/docs/helpers/filters.js
docs/3.2.x/docs/helpers/highlight.js
docs/3.2.x/docs/source/api.js
docs/3.3.x/docs/helpers/filters.js
docs/3.3.x/docs/helpers/highlight.js
docs/3.3.x/docs/source/api.js
docs/3.4.x/docs/helpers/filters.js
docs/3.4.x/docs/helpers/highlight.js
docs/3.4.x/docs/source/api.js
docs/3.5.x/docs/helpers/filters.js
docs/3.5.x/docs/helpers/highlight.js
docs/3.5.x/docs/source/api.js
docs/search.js
docs/source/api.js
package.json
website.js

This PR fixes the breaking changes from upgrading to [v10](https://github.com/highlightjs/highlight.js/blob/main/VERSION_10_UPGRADE.md) and [v11](https://github.com/highlightjs/highlight.js/blob/main/VERSION_11_UPGRADE.md).
The only downside is IE11 support being dropped in v10 which I think is fine.
I also tested the rendering manually on my machine, and the docs highlighting is identical to the one in production.

chore(deps-dev): upgrade highlight.js from 9.18.3 to 11.5.0

---

.github/workflows/test.yml

**Summary**
Fix #11308. We've considered adding a code coverage workflow over the years, but never have because we don't have permissions on the Automattic org to add a tool like Coveralls. However, using GitHub actions, we can upload artifacts associated with a workflow, which means we can at least create an HTML zip of code coverage output on each run. You can then download the zip output from the GitHub workflow summary page. For example, [here's the summary page for 405a7f9](https://github.com/Automattic/mongoose/actions/runs/2085815809), here's a screenshot of the output from 405a7f9 after downloading.
@Uzlopak 
**Examples**

Code coverage workflow

---

docs/typescript.md

docs(typescript): add note about deprecating extends Document

---

.github/workflows/test.yml
.github/workflows/tidelift-alignment.yml

- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
>Pin actions to a full length commit SHA
>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
[How do I validate these pinned actions?](https://gist.github.com/naveensrinivasan/ca008c07279176acce28969fb77d056f)
Also, dependabot supports upgrading based on SHA. https://github.com/ossf/scorecard/pull/1700
Signed-off-by: …

Pin actions to a full length commit SHA

---

test/docs/virtuals.test.js

Unnecessary output of the mongo operations when running unit tests, because I guess somebody forgot to remove the debug option.

disable debug option in virtuals unit test

---

lib/types/array/methods/index.js

fix: typo in methods/index.js

---

lib/document.js

I actually dont understand why the key ordre is so important. Nevertheless, this implementatoin is faster.
without reordering:
MONGOOSE_DEV=1 node create.js 
CheckItem x 201,161 ops/sec ±1.00% (92 runs sampled)
Board x 182 ops/sec ±0.82% (83 runs sampled)
before:
MONGOOSE_DEV=1 node create.js 
CheckItem x 170,092 ops/sec ±1.35% (90 runs sampled)
Board x 168 ops/sec ±1.22% (80 runs sampled)
after:
MONGOOSE_DEV=1 node create.js 
CheckItem x 195,166 ops/sec ±0.41% (96 runs sampled)
Board x 174 ops/sec ±1.29% (80 runs sampled)
So we get pretty close to the non-ordered object.

perf: improve perf of key order

---

lib/index.js

fix jsdoc for mongoose.createConnection

---

.github/workflows/test.yml

node 18 is out, node 17 is history. time to change the CI/CD platform matrix for node

use node 18 instead of node 17 in CI/CD

---

tsconfig.json
types/connection.d.ts
types/index.d.ts

mongodb.Collection and mongodb.ChangeStream now both require that their type arguments `extend mongodb.Document`. This requires adding this constraint in a few places.
Fixes #11687

Update mongodb-dependent type parameters

---

lib/types/DocumentArray/methods/index.js
lib/types/array/methods/index.js

@vkarpov15 is there any reason why in the `array` and `DocumentArray` methods we shouldn't call `markModified` before actually write the new value for the given path?
I understand that in order to mark something as modified we must have updated it before. However I do not know how we could keep track of the previous values when updating a single value from a nested array.
This pull request is motivated by this issue: https://github.com/Automattic/mongoose/issues/11644
In this comment there is detailed info and repro: https://github.com/Automattic/mongoose/issues/11644#issuecomment-1094891011
In this pull request, calling `markModified` before writing the new value for the given path, we can keep track of the changes when updating a single value of a nested array.
Example:
```javascript …
```

Call markModified before setting changes in Array  and in DocumentArray methods

---

test/types/document.test.ts
types/document.d.ts

Related to : https://github.com/Automattic/mongoose/issues/11598

Refactor doc.populate FN type.

---

package.json
tsconfig.json

@mohammad0-0ahmad reported that with this [change](https://github.com/Automattic/mongoose/commit/5194756664665a6bc4ed5769d300f3a9d1e6f2c3)  the intellisense in vscode atleast in our typescript tests is broken. 
I dont understand why the include was done anyway. tsd is not using the configuration in tsconfig.json but from the tsc-configuration in package.json. 
Maybe @sandersn can give a clue why he added include instruction to tsconfig.json

remove include in tsconfig.json

---

lib/helpers/immediate.js
lib/helpers/isAsyncFunction.js
package.json
webpack.config.js

Re: #11584
**Summary**
With #11584, there were a few issues that popped up in the browser build:
1. Missing `Buffer`
2. Missing `process`
3. Looks like Babel was failing on `isAsyncFunction()`
**Examples**

fix: fix browser build for Webpack 5

---

test/types/lean.test.ts
types/document.d.ts
types/index.d.ts

**Summary**
Per #11761 `.toObject` doesn't add `_id` to the document if it is missing; this fixes that.
**Examples**
See unit tests in the code

Feature/ts lean missing doc fixes #11761 without killing LeanDocument

---

package.json
webpack.config.js

- use buffer v.5.7.1 as a devDependency so that the version matches the buffer package from mongodb.
- use alias in webpack on bn.js to reduce redundancy, saving about 260 kb
before:
after:
before:1048 kb
after: 781 kb

optimize size of browser bundle, use buffer v.5.7.1 package to match buffer package of mongodb in browser bundle

---

test/model.test.js

I guess the collection name results some interference with the replicaset tests. Maybe the collection is after running all the normal unit tests full with data, resulting that it takes more then 10 seconds. 
I merge this, if the test pass, as it is not a massive change.

chore: fix automated replicaset tests in CI/CD pipeline

---

types/connection.d.ts

The documentation and the code of Connection.deleteModel() tells, that
it accepts a string and a RegExp. So, the types should accept a RegExp
as well.
**Summary**
At the moment `moongoose.connection.deleteModel(/.+/)` is not working in the test code in one of my typescript repositories, because of a type error. The javascript code of `deleteModel` tells, that a RegExp is accepted, but the current types only allow a string as parameter. My current workaround is `mongoose.connection.deleteModel(<string><unknown>/.+/)`, what is not ideal in my opinion.
**Examples**
The following line should work in typescript as well:
`mongoose.connection.deleteModel(/.+/)`

fix: 🐛 Types of Connection.deleteModel()

---

test/types/connection.test.ts

Following the advice of github user Uzlopak to add a test, that
Connection.deleteModel is accepting a RegExp as well.
**Summary**
Yesterday, I have submitted a fix for the types of Connection.deleteModel(), because the javascript code accepts a RegExp and not just a string. The fix is already merged, but a reviewer asked me to add a test and gave me an advice how to do it.
**Examples**
This was exactly the advice how to add a test:
`expectType<Connection>(conn.deleteModel(/.+/));`

test: 💍 Add missing test for type of Connection.deleteModel()

---

docs/populate.md

**Summary**
Populate happens asynchronously and should be awaited.

docs(populate): find populate method should be awaited

---

test/types/connection.test.ts
types/connection.d.ts

The documentation and code say it accepts "options" as a second parameter, but the type definition doesn't allow it.
**Summary**
The documentation lists [Connection.prototype.transaction()](https://mongoosejs.com/docs/api/connection.html#connection_Connection-transaction) as accepting an `options` parameter (and this [is indeed the case](https://github.com/Automattic/mongoose/blob/3b943b2a3f0d7a92e4ef22a7d4584859235c1d54/lib/connection.js#L468)), but the type definition doesn't allow it.
This is particularly problematic for using this function with [causally consistent sessions](https://www.mongodb.com/docs/manual/core/read-isolation-consistency-recency/#causal-consistency), given that the default read concern is `local`, because it prevents setting the `readConcern` at anything other …

Fix: Type of Connection.transaction()

---

lib/helpers/clone.js
lib/helpers/common.js
lib/helpers/discriminator/areDiscriminatorValuesEqual.js
lib/schema/decimal128.js
lib/types/DocumentArray/methods/index.js
lib/types/array/methods/index.js
lib/types/map.js
lib/utils.js

**Summary**
When dealing with external schemas, i.e. a mongoose schema created inside another module, `instanceOf` may not work.
This results in the value of ObjectIds in the schema being converted to strings when saving to the database.
**Examples**
I have a monorepo project with pnpm. One module `lib` contains a schema, which I use to create a model in my program. 
Both my program and the imported `lib` module have the same `bson`, `mongoose` and `mongodb` versions.

fix(document): fix ObjectId conversion for external schemas

---

lib/document.js
test/types/populate.test.ts
types/document.d.ts

Fix #11758
**Summary**
Right now, if you instantiate a document with manually populated paths, there's no way to indicate that a path is manually populated as opposed to just an ObjectId.
```ts
const parent = new ParentModel({
nestedChild: new NestedChildModel({ name: 'test' }),
name: 'Parent'
})
parent.nestedChild; // always ObjectId, even if manually populated
```
With this PR, you can at least do:
```
const parent = new ParentModel({
nestedChild: new NestedChildModel({ name: 'test' }),
name: 'Parent'
}).$assertPopulated<{ nestedChild: NestedChild }>('nestedChild')
doc.nestedChild.name; // string
```
which will make TypeScript work correctly, and also correctly throw a runtime error if 'nestedChild' isn't populated. What do you think @AbdelrahmanHafez @Uzlopak ?
**Examples**

feat(types+document): add `$assertPopulated()` for working with manually populated paths in TypeScript

---

lib/helpers/isBsonType.js
test/helpers/isBsonType.test.js

Following the PR by @coyotte508 this PR improves the isBsonType function by avoiding the use of the actually heavy get-function.

perf: improve isBsonType

---

.eslintrc.json

Till https://github.com/typescript-eslint/typescript-eslint/pull/5135 gets released, turn off the infix-ops option of eslint.

chore: ignore infix-ops in eslint 

---

lib/schema/objectid.js

**Summary**
PR #11841 changed a whole bunch of checks for `instanceof ObjectId` to
use the `isBsonType()` function instead. Unfortunately some were missed
in the `./lib/schema/objectid.js` file.
Convert the remaining `instanceof` checks in `objectid.js` to use the
`isBsonType()` check instead so that all `ObjectId`s created from any
`bson` modules should validate/cast properly.
This was found because my nested document with required ObjectIds
started failing validation when I loaded the documents from JSON files
in my tests using `bson.EJSON` after the release of 6.3.4 -> 6.3.5.
**Examples**
This test when run in a project that depends on `mongoose` and `bson`
will fail before this fix and work afterward.
```js
const { EJSON } = require('bson'); …
```

Fix ObjectId `instanceof` checks

---

types/query.d.ts

**Summary**
Sorting by text score is a special case. See https://www.mongodb.com/docs/manual/reference/method/cursor.sort/#text-score-metadata-sort
This fixes a type error caused by 6.3.5
**Examples**
This code fails with 6.3.5:
```ts
const cities = await InseeCity.find({ $text: { $search: req.query.query as string } })
.sort({ score: { $meta: "textScore" } })
```
It used to work

fix(types): Allow sorting by text score

---

lib/helpers/timestamps/setupTimestamps.js
lib/index.js
lib/validoptions.js
test/index.test.js
test/types/base.test.ts
types/mongooseoptions.d.ts

re https://github.com/Automattic/mongoose/pull/10267#issuecomment-861542490

feat(base): add support to set default immutable for createdAt globally

---

docs/guide.md
docs/typescript/query-helpers.md
docs/typescript/schemas.md
docs/typescript/statics-and-methods.md
docs/typescript/statics.md
lib/schema.js
test/document.test.js
test/model.test.js
test/query.test.js
test/types/create.test.ts
test/types/document.test.ts
test/types/models.test.ts
test/types/populate.test.ts
test/types/queries.test.ts
test/types/schema.test.ts
test/types/utility.test.ts
tsconfig.json
types/document.d.ts
types/index.d.ts
types/inferschematype.d.ts
types/models.d.ts
types/query.d.ts
types/schemaoptions.d.ts
types/utility.d.ts

Do you have any suggestions or ideas to be implemented in this PR, please leave a comment :slightly_smiling_face:
You can install mongoose including this feature by running:
```shell
npm i Automattic/mongoose#pull/11563/head
```
- Auto schema type inference & create function:
- InferSchemaType utility & supporting custom type key:

Feature: Infer schema type automatically.

---

types/models.d.ts
types/schematypes.d.ts

-- Fix instance created from model returned from discriminator having type 'any'
-- Fix model created from discriminator not inheriting the properties from the base model
**Summary**
A model created from a discriminator does not have types for the "document" (save, find, etc) as the original model does and does not inherit the properties from the base model
**Examples**
```typescript
type EventSchema = {
time: Date
}
const eventSchema = new mongoose.Schema<EventSchema>({ time: Date }, options);
const Event = mongoose.model('Event', eventSchema);
type ClickedLinkEventSchema = {
url: string
}
const clickedLinkEventSchema = new mongoose.Schema<ClickedLinkEventSchema>({ url: String }, options)
const ClickedLinkEvent = Event.discriminator('ClickedLink', clickedLinkEventSchema);
const …
```

fix: Discriminator generic type not being passed to schema

---

.github/workflows/tidelift-alignment.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

types/helpers.d.ts

**Summary**
A simple typescript definition fix.
**Rationale**
`isObjectIdOrHexString` in the `any` position is used by typescript, resulting in a `false` when passed arguments of type `mongodb.ObjectId | string` - and typescript or typescript-eslint will complain in certain circumstances, such unreachable code. Similar with isValidObjectId
**Examples**

fix(types): improve helpers typings

---

lib/document.js
lib/helpers/updateValidators.js
lib/model.js
lib/schema/documentarray.js
lib/statemachine.js
test/document.test.js
test/schema.documentarray.test.js

Fix #11770
**Summary**
In #11770 I made a note that we leave subdocuments in `init` state after `save()` to work around some issues like #6818. That is technically incorrect, because `init` should only be used for paths that are loaded from the database. The underlying issue comes down to the fact that array subdocument paths' `doValidate()` function doesn't run validation on paths in the document.
In this PR, I made it so that the embedded schema type in document arrays have a `doValidate()` that is the same as `SubdocumentPath`'s. In order to support this change, needed to fix a couple of places where we relied on the old behavior in update validators and `Model.validate()`.
Future work: make array subdocument paths a separate class, and make primitive arrays also validate all their …

fix: make `doValidate()` on document array elements run validation on the whole subdoc

---

test/types/middleware.test.ts
types/aggregate.d.ts
types/index.d.ts

-- Fix post hook using PostMiddlewareFunction generic type without passing T to ResType
**Summary**
The type for the 'post hook' middleware is passing the `T` only to the first argument of the PostMiddlewareFunction (the `this` type), not to the second, resulting on the `ResType` defaulting to `any`
**Examples**
```typescript
type User = {
name: string
}
const userSchema = new Schema<User>({ ... })
userSchema.post('validate', (doc, next) => {
// doc has type 'any'
})
userSchema.post('validate', (doc, next) => {
// doc has type 'User'
})
```

fix: post hook 'res' param with type any

---

lib/connection.js
lib/driver.js
lib/index.js
lib/query.js
lib/utils.js
test/index.test.js
test/types/populate.test.ts
types/index.d.ts

**Summary**
Right now overwriting the Mongoose driver is a bit messy, because 1) `Connection` and `Collection` aren't changed when you do `mongoose.driver.set()`, and 2) driver is always global, so no way to have 2 Mongoose instances with the same driver in the same process.
**Examples**
You can now do `mongoose.setDriver()` without any extra work to use a different driver.

feat(mongoose): add `setDriver()` function to allow overwriting `driver` in a more consistent way

---

lib/index.js
package.json
test/query.middleware.test.js

Fix #11426
Fix #8393
**Summary**
Right now there's no way to overwrite the result of a function in a `post()` hook. For example, there's no way to use `filter()` to modify a `find()` result in a `post('find')` hook.
There's also no way to "cancel" an operation in a pre hook without throwing an error. Which is inconvenient, because there are some use cases where it would be great to skip executing the underlying function (local caching, memorizing results, etc.)
This PR adds `overwriteMiddlewareResult()` for the former, and `skipMiddlewareFunction()` for the latter, from https://github.com/vkarpov15/kareem/pull/30 .
@AbdelrahmanHafez @Uzlopak what do you think about the naming and overall idea?
**Examples**
See tests

feat: add `skipMiddlewareFunction()` and `overwriteMiddlewareResult()` for skipping and modifying middleware results

---

test/types/models.test.ts
types/models.d.ts

**Summary**
This re-adds the possibility to pass `undefined` as projection to the `find` method of models.
**Examples**
```ts
Project.find({}, undefined, { limit: 5 });
```
(see the added tests for more details)

[Types] Re-add the possibility to pass undefined for projection in Model.find

---

test/types/PipelineStage.test.ts
test/types/expressions.test.ts
types/expressions.d.ts
types/pipelinestage.d.ts

types: Update Expression Typings

---

test/types/PipelineStage.test.ts
types/expressions.d.ts
types/pipelinestage.d.ts

**Summary**
Builds upon https://github.com/Automattic/mongoose/pull/11956 and reverts part of it.
`$match` is supposed to be a regular filter; it's not an aggregation expression.
Fixes #11980 
Fixes #11973

Fix $match typings

---

.eslintrc.json
test/types/document.test.ts
types/models.d.ts

Fix #11960
Please take a look @mohammad0-0ahmad
**Summary**
In #11563, it looks like the model constructor pulls types from the parameter to the model constructor, which is very wrong. @hasezoey reported that this also causes issues for Typegoose.
The tests in `document.test.ts#L195-L196` are also wrong, `unExistProperty` shouldn't be defined on the document instance. See the below script:
```javascript
void async function main() {
await mongoose.connect('mongodb://localhost:27017');
const Test = mongoose.model('Test', mongoose.Schema({ name: String }));
const doc = new Test({ name: 'test', unExistProperty: 1 });
console.log(doc);
console.log(doc.name); // 'test'
console.log(doc.unExistProperty); // undefined
await mongoose.disconnect();
}();
``` …

fix(types): avoid adding non-existent properties from model constructor for typegoose

---

types/indexes.d.ts

**Summary**
Currently the types for index option `weights` was defined as `AnyObject` which allows only string keys and any value type, but with this change `string | number` keys are allowed (i dont know if indexes support this, please review) and explicitly set the value type to `number`, because that is the only type mongodb accepts (from what i know)
**Examples**
```ts
sch.index({ field1: 1 }, { weights: { field1: 10 } });
```

fix(types): change index "weights" to be more explicit

---

lib/index.js
lib/schema.js

**Summary**
For some of the methods which are mentioned below we didn't  give space between markdown tag as a result it's not being rendered properly in the documentation.
I've searched the entire codebase, it seems like we've issues in the following methods which are addressed in this PR.
- skipMiddlewareFunction
- overwriteMiddlewareResult
- discriminator
- removeIndex
- clearIndexes
**Examples**
For example, this is how the api for `skipMiddlewareFunction` is rendered right now
And after the fix, it'll be

Fix broken h4 markdown tags for example in documentation 

---

test/types/document.test.ts

**Summary**
This PR extends the types test that was initially added for #11960, with more tests and another case
**WARNING**: this PR is currently set to fail because of the new case, so i dont think it is good to merge it yet
---
Edit:
the first commit extends the initial test case to actually test what the reproduction repository of the mentioned issue had problematic
the second commit duplicates the test for `new` to also test `create` (which was not updated yet)

Extend types test for #11960

---

docs/guide.md
lib/schematype.js

**Summary**
As per https://github.com/Automattic/mongoose/issues/8895 and https://github.com/Automattic/mongoose/pull/8896 it seems index options such as `-1` are available at the path level. Updating the documentation accordingly.
**Examples**
N/A

Add path level descending index example in docs

---

.eslintrc.json
test/model.querying.test.js
test/model.test.js

**Summary**
This change is to make coding style more consistent by only allowing up to `2` empty lines after each other

Add ESLint rule `no-multiple-empty-lines` and apply it

---

benchmarks/benchjs/casting.js
benchmarks/benchjs/delete.js

fix benchmark

---

types/models.d.ts
types/query.d.ts

**Summary**
This is a documented feature. Users should be able to configure
createdAt and updatedAt separately when making a query from TypeScript.
**Examples**
Allow code like this to compile:
```typescript
const result = await Token.findOneAndUpdate(
{ uid },
{ $set: { field: value }, $setOnInsert: { createdAt: new Date('2022-01-01T00:00:00.000Z') } },
{ session, upsert: true, new: true, timestamps: { createdAt: false, updatedAt: true } },
).exec();
```

fix(types): allow using an object to configure timestamps

---

types/models.d.ts

**Summary**
Both findOneAndReplace and findOneAndUpdate support the rawResult
option, which changes the return type to include more information from
the MongoDB driver. Add an overload for findOneAndReplace to support
rawResult in a way similar to findOneAndUpdate.
**Examples**
Allow code like this to compile:
```typescript
const result = await models.OCPISession.findOneAndReplace(
{ uid },
{ uid, field: value },
{ session, rawResult: true, upsert: true, new: true },
).exec();
console.log(result.lastErrorObject?.upserted);
```

fix(types): support findOneAndReplace with rawResult

---

lib/schema.js

**Summary**
Add `String[]` as a available type for `Schema.prototype.pre` and `Schema.prototype.post`.
Also fixes those parameter to not have a parameter name.
fixes #11989

Add `String[]` as type in jsdoc for `Schema.prototype.pre/post`

---

docs/source/api.js
lib/error/messages.js
lib/model.js
lib/query.js
lib/schema.js
lib/schematype.js
lib/types/DocumentArray/methods/index.js
lib/types/subdocument.js

**Summary**
- refactor all `@receiver` tags into proper jsdoc tags where needed
- changes case `receiver` in `docs/source/api` to be a warning and no-op
- also change handling of case `property` to properly use types instead of trying to parse them from the string (now properly uses arrays and other symbols)
re https://github.com/Automattic/mongoose/pull/12024#pullrequestreview-1026843166

Refactor all `@receiver` tags to proper jsdoc tags

---

lib/schema.js

**Summary**
This PR improves the JSDOC of `lib/schema.js` in various way:
- add missing jsdoc tags
- add missing types from jsdoc tags
- add new-lines after headers to be consistent
- improve descriptions

style(schema): touch-up jsdoc

---

.github/workflows/test.yml
lib/model.js

This is both faster and gives better visibility on PRs, I want to see whether the PR is good or not, but right now if there is an extra space I have to wait for the person who submitted the PR to fix it before I can see if it introduces breaking changes.

chore(workflow): make tests run even if lint fails

---

test/types/expressions.test.ts
types/expressions.d.ts

[$switch](https://www.mongodb.com/docs/manual/reference/operator/aggregation/switch/#mongodb-expression-exp.-switch) statements accept `branches` instead of the current `$branches`, `case` instead of `$case`, and `default` instead of `$default`.

fix(types): fix $switch expression type

---

test/types/PipelineStage.test.ts
types/expressions.d.ts

Aggregation pipeline types currently don't accept the valid 
`$addFields: { myFieldName: { $let: { /* $let expression goes here */ } } }`
This PR fixes that, although I'm not sure if adding `Expression.Let` follows the desired structure for types.

fix(types): add $let as a possible expression to $addFields

---

test/types/schema.test.ts
types/inferschematype.d.ts

Related to: [12030](https://github.com/Automattic/mongoose/issues/12030)

Improve Auto typed schema.

---

lib/index.js

The list of options for Mongoose.prototype.set() does not include sanitizeFilter(), [which has been added since version 6](https://thecodebarbarian.com/whats-new-in-mongoose-6-sanitizefilter.html).
The option has been added.

added sanitizeFilter() to mongoose.set() options

---

lib/helpers/topology/isAtlas.js

**Summary**
Use ServerDescription methods for getting server host and port instead of parsing hostname,
which did not work properly.
**Examples**
Closes #12063

fix: isAtlas check not working properly

---

lib/model.js

**Summary**
This PR Improves the JSDOC of `lib/model.js`.
Changes include:
- fix missing types from `@param` tags
- changes some examples from callback-style to await-style
- moves options to `@param` tags
- change some things to make the style consistent
- renames parameter `o` to `opts` for `mapReduce` to be more clear what that parameter does
There are some added TODO's, because i was not sure what type they were

Model JSDOC Touch-Up

---

lib/helpers/model/castBulkWrite.js
lib/model.js
lib/utils.js
test/model.test.js
test/types/models.test.ts
types/models.d.ts

fixes #12059
I also refactored `bulkSave` to use async/await instead of the ugly promise chain, even though I wrote it, I find it difficult to read.
This comes with the downside of shorter stack traces, hopefully, this is not an issue.
@vkarpov15 
There is a test failing, `bulkSave` calls `bulkWrite` with `timestamps` false, so mongoose sends the writeOperations to MongoDB without `updatedAt` or `createdAt`, but the documents in memory still have `updatedAt` and `createdAt` that is inconsistent with the database.
This happens when we `document.schema.s.hooks.execPre('save',...)`. Do you know if there is a way to make pre-save hook not update timestamps? or pass an option to it? pre-post hooks seem like a blackbox to me and for years I couldn't figure out how they work.

feat(model): allow passing `timestamps` option to `Model.bulkSave(...)`

---

lib/document.js
lib/helpers/firstKey.js
lib/internal.js
lib/model.js
test/document.test.js
types/document.d.ts

Fix #11915
**Summary**
See #11915. Right now, there's no way to use [`$inc`](https://www.mongodb.com/docs/manual/reference/operator/update/inc/) with `save()`. `doc.num += 2` becomes a `$set`.
With this change, you can explicitly increment a given path, and when you `save()`, Mongoose will send a `$inc`.
**Examples**
```javascript
const schema = new Schema({
counter: Number
});
Test = db.model('Test', schema);
await Test.create({ counter: 0 });
const doc = await Test.findOne();
assert.strictEqual(doc.counter, 0);
const doc2 = await Test.findOne();
doc2.counter = 1;
await doc2.save();
doc.$inc('counter');
await doc.save();
const res = await Test.findById(doc);
assert.equal(res.counter, 2);
```

feat(document): add `$inc()` helper that increments numeric paths

---

docs/api_split.pug
docs/css/api.css

**Summary**
This PR adds basic Output of `@deprecated` as a follow-up to #12024 which added `@deprecated` handling
Currently looks like this (directly after the header):
fixes #12080
PS: i am not great at styles, so this is just basic, but it is there at least

docs(api_split): add basic DEPRECATED output

---

docs/api_split.pug

**Summary**
This changes Documentation Parameter names from "someOption" to `someOption`, which in my opinion is better to read
before:
after:
<details>
<summary>before/after with darkreader</summary>
before:
after:
</details>

docs(api_split.pug): add "code" to parameter name

---

docs/api_split.pug
docs/source/api.js
lib/schema.js

**Summary**
This PR adds JSDOC `@see` handling (in mongoose specific way) and output to the documentation
the following matches apply for the custom `@see` handling:
```txt
"@see External Links http://someurl.com/" -> "External Links"
"@see External https://someurl.com/" -> "External"
"@see Id href #some_Some-method" -> "Id href"
"@see Local Absolute /docs/somewhere" -> "Local Absolute"
"@see No Href" -> "No Href"
"@see https://someurl.com" -> "" (uses fallback "No text")
"@see Some#Method #something" -> "Some#Method"
```
This PR also does some things i noticed while going through:
- add `:` to `Parameters` list to be consistent with other `h5`
- add proper link to `Schema.prototype.plugin`
As a side-effect, this also addresses some things mentioned in #12111

Add "@see" handling and output to documentation

---

lib/schematype.js

**Summary**
while going through the code for #12140, i noticed that 2 functions were saying they always return `this`, which was not actually true for 1 case (in each function), this PR fixes that

fix(schematype): actually always return "this" where specified

---

docs/connections.md
docs/deprecations.md
docs/documents.md
docs/guide.md
docs/middleware.md
docs/migrating_to_5.md
docs/models.md
docs/populate.md
docs/queries.md
docs/schematypes.md
docs/tutorials/lean.md
docs/tutorials/query_casting.md
examples/mapreduce/mapreduce.js
lib/aggregate.js
lib/browser.js
lib/cast.js
lib/collection.js
lib/connection.js
lib/document.js
lib/index.js
lib/model.js
lib/query.js
lib/schematype.js
lib/virtualtype.js
types/connection.d.ts

**Summary**
This PR does:
- touch-up some more file for JSDOC, for:
- `lib/aggregate.js`
- `lib/cast.js`
- `lib/collection.js`
- `lib/connection.js`
- `lib/document.js`
- replace all old (broken) links `#\w+_\w+\.` to be `#\w+_\w+-` (from `#model_Model.find` to `#model_Model-find`)

Touch-up JSDOC of some more files

---

.github/workflows/benchmark.yml
package.json

Use the latest release of ts-benchmark.
Reasons:
- Fix some issues related to GitHub integration.
- Add ability to benchmark the target branch of the pull request. "Helpful if target branch is not the master branch is our case."
Screenshots:
This show how the result will be look like when creating a PR against 6.5 branch for instance instead of master.

ts-benchmark

---

lib/cursor/ChangeStream.js
lib/model.js
test/model.test.js
types/models.d.ts

Fix #11936
**Summary**
Automatically hydrate `fullDocument` if `hydrate: true` is set, but only if you call `Model.watch()`. `Connection.prototype.watch()` doesn't support `hydrate: true`.
Helpful because 1) it might be hard to figure out what function you need to call to init a Mongoose document without setting anything modified or firing setters, 2) this makes it easier for us to add a global `hydrateFullDocument` option so we can do this on all `Model.watch()` calls by default.
**Examples**

feat(model): add `hydrate` option to `Model.watch()` to automatically hydrate `fullDocument`

---

lib/connection.js
test/connection.test.js

Fix #12047
**Summary**
The [`Model.init()` function](https://mongoosejs.com/docs/api/model.html#model_Model-init) is responsible for:
1. Calling `createCollection()` to ensure the Model's underlying collection exists, unless `autoCreate = false`
2. Calling `createIndexes()` to ensure the indexes defined in the Model's schema exist, unless `autoIndex = false`
Mongoose calls `Model.init()` when you create a model using `mongoose.model()` or `Collection.prototype.model()`. The `createCollection()` and `createIndexes()` calls are queued up until Mongoose connects to MongoDB.
The issue is that, if you close a connection and then reconnect to a different database or cluster, Mongoose won't re-run `init()`. Because 1) Mongoose only runs `init()` when you call `model()`, and 2) Mongoose stores a …

fix(connection): re-run `Model.init()` if re-connecting after explicitly closing a connection

---

lib/error/validation.js
lib/helpers/model/pushNestedArrayPaths.js
lib/model.js
test/model.test.js
test/model.update.test.js
types/models.d.ts

Fix #11945
**Summary**
We're adding a couple of model helpers that make it easier to access various Mongoose features without creating a full document. We already have `Model.validate()` and `Model.applyDefaults()`. `Model.validate()` does some casting, but doesn't return a casted object. This `Model.castObject()` function takes in a POJO, and casts it to the given schema, _except_ for creating Mongoose-specific data structures like document arrays and subdocuments. `castObject()` should return a POJO.
**Examples**
```javascript
const Test = db.model('Test', mongoose.Schema({
_id: false,
num: Number,
nested: {
num: Number
},
subdoc: {
type: mongoose.Schema({
_id: false,
num: Number
}),
default: () => ({})
},
docArr: [{
_id: false,
num: Number
}]
}));
const obj = {
num: '1',
nested: { num: …
```

feat(model): add `castObject()` function that casts a POJO to the model's schema

---

lib/helpers/update/applyTimestampsToChildren.js
test/timestamps.test.js

Fix #12119
**Summary**
#12119 is due to the fact that `applyTimestampsToChildren()` stops when it finds a schema that doesn't have `timestamps: true`. With this PR, `applyTimestampsToChildren()` will keep going to find any child schemas that have `timestamps: true`.
**Examples**

fix(timestamps): set timestamps on child schema when child schema has timestamps: true but parent schema does not

---

lib/types/buffer.js

**Summary**
This PR changes in `buffer.js` a `.split` call into a `utils.each` call for defining functions, to be consistent

style(buffer): change ".split" to "utils.each" for defining methods

---

.github/workflows/tidelift-alignment.yml

**Summary**
This PR disabled the workflow `tidelift-alignment` on forks, because it would otherwise always run but error because of missing secrets.

chore(tidelift-alignment): run only in main repository, not in forks

---

lib/model.js
test/query.test.js

Fix #12143
**Summary**
Right now populate doesn't work if you use `lean: { transform: function myTransform(doc) { ... } }` and `myTransform` deletes `_id`. That's because the lean transform runs before populate's `_assign()` step, and `_assign()` needs `_id` (or whatever the foreign field for populate is) to figure out where to put the populated documents.
This is similar to #9175, where we had to also remove the foreign field from the projection, and just delete the projected-out field in memory after `_assign()`.
**Examples**

fix(model+query): handle populate with lean transform that deletes `_id`

---

docs/compatibility.md

**Summary**
This PR changes `compatibility.md` to use a table instead of a list, which is sorted from newest to oldest
<details>
<summary>Before / After Screenshots</summary>
Before (master):
After (this pr):
</details>

docs(compatibility): change to use a table

---

docs/api_split.pug

**Summary**
(continuation of https://github.com/Automattic/mongoose/pull/12145#issuecomment-1194372064)
This PR adds code blocks to the headers and the index list:
<details>
<summary>Headers</summary>
before:
after:
</details>
<details>
<summary>Index List</summary>
before:
after:
</details>
PS: yes this change does not screw up any anchor ids or click-ablility

Docs: add "code" to Headers (and index list)

---

docs/api_split.pug
docs/css/api.css

**Summary**
This PR adds "code" blocks to the API sidebar entries (and increases padding)
<details>
<summary>Screenshots</summary>
before:
without extra padding:
final with 2px extra padding (top-bottom):
</details>
PS: i am not sure on the spacing, please review if the spacing is OK or needs to be changed

docs(api_split.pug): add "code" to sidebar entries

---

docs/further_reading.md

**Summary**
This PR does:
- update MDN blog post image (old image is not available anymore)
- fix md style problems (extra spaces)
- change from deprecated img `border` property to css property
- change div-clear-br-br to just hr
- change div-clear to be a class and as a seperator
<details>
<summary>Before / After Screenshots</summary>
Before (master):
After (this pr):
</details>

Re-Style `further_reading.md`

---

test/types/schema.test.ts
types/index.d.ts

**Summary**
This PR adds types for plugin options to be automatically inferred, if defined, with possibility to overwrite.
This inferring is currently strict, because if it would not be then on the first definition it would just overwrite the inferred type and only intellisense suggestions would remain.

fix(types): add schema plugin option inference

---

test/types/models.test.ts
types/models.d.ts

**Summary**
Found issue when trying to perform a `bulkWrite` using `$addToSet`. The mongodb definition of `AnyBulkWriteOperation`requires the type to be passed to accept any input to $addToSet
**Examples**
See test

fix(types): pass type to mongodb bulk write operation

---

test/types/models.test.ts
types/connection.d.ts
types/index.d.ts

**Summary**
It is not possible to define a model with both generic `TInstanceMethods` and `TQueryHelpers`. There is a mismatch between generics for the `model` and the the `Schema`.
**Examples**
See type test for example

fix(types): map correct generics from model to schema

---

lib/model.js

**Summary**
This PR changes a `for(-index)` to a `for-of`, which removes the need for 2 variables and should make use of the [iterable-symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#iterating_over_other_iterable_objects) (this `for-of` is supported since nodejs 0.12.0 according to MDN)
i dont quite know the impact on performance, because there was no existing benchmark, and i believe the change would not be noticeable when having a active mongodb connection (and i dont know enough about mongoose to everything required)

style(model): update for-index loop to a for-of loop

---

lib/cursor/ChangeStream.js

**Summary**
This PR tries to fix the errors `Uncaught TypeError: Cannot read properties of undefined (reading 'fullDocument')` that were often thrown in ReplicaSet tests, see [This Run](https://github.com/Automattic/mongoose/runs/7662155766?check_suite_focus=true) as a example.
PS: i dont know if this fully fixes it, but it should at least help

fix(ChangeStream): try to fix "cannot read property fullDocument of undefined"

---

docs/api.pug
docs/api_split.pug
docs/js/api-bold-current-nav.js

**Summary**
This PR does:
- move script from `api.pug` to own file
- apply moved script to both `api.pug` and `api_split.pug` (see #12217)
- update script to current names & conditions
- update script to use more modern js
<details>
<summary>Screenshot</summary>
now (`Connection.prototype.close()` is bold):
</details>

docs: highlight current top-most visible header in navbar

---

types/models.d.ts

Smaller alternative fix to #12212.
Also fixes #12213, but unsafely when the model's type parameter allows null or undefined.

Make bulkWrite's type parameter conditional

---

lib/cursor/ChangeStream.js

**Summary**
There is an issue when using a `ChangeStream` in a replica set, you'll get an `undefined` error when you try to call `mongoose.disconnect()`:
```js
await mongoose.connect(`mongodb://${host}:${port}/?replicaSet=${rset}`, {
autoIndex: false,
});
const changeStream = mongoose.connection.watch(pipeline, {
fullDocument: "updateLookup",
});
const stream = changeStream.on("change", (change) => {
console.log(change);
});
await stream.close();
await mongoose.disconnect(); // `data.fullDocument` is undefined
```
The issue was introduced in one of the commits from versions 6.4.7 to 6.5.0, as stated in #12169. This PR fixes this by correctly addressing where the options are coming from.
**Examples**
Here's the result for the current version:
Here's the result for the fix:
Closes #12169

fix: Update ChangeStream hydration condition

---

test/types/connection.test.ts
test/types/document.test.ts
types/connection.d.ts

**Summary**
This PR apply the changes from #11563 to `connection.model`
fixes #12129
PS: for now i have just let the old `connection.model` types stay there as fallbacks, i dont know if they can be removed without breaking something

fix(types): apply changes from #11563 to "connection.model"

---

test/types/plugin.test.ts
types/connection.d.ts
types/index.d.ts

**Summary**
Found more problems when working with typescript and plugins. Since the Schema type sets default values (empty object) for `TInstanceMethods`, `TQueryHelpers` and `TStaticMethods` we need to be able to pass along these types when trying to create query helpers/virtuals/methods/statics.
This PR also contains the fix for Schema and model mismatch. Will rebase this if the other PR gets accepted.
**Examples**
Added `plugin.tests.ts` for examples

fix(types): better typescript support for schema plugins

---

docs/subdocs.md

**Summary**
Fix a typo in the Subdocuments guide. Specifically, replace the contraction ("it's") with the possessive form ("its").
**Examples**
N/A

docs(subdocs): Fix typo

---

docs/geojson.md

**Summary**
This PR changes `geojson.md` to not have a duplicate `native-inline` div (SPONSOR), which always gets added through `website.js`
see [Using GeoJSON](https://mongoosejs.com/docs/geojson.html) for the current way it is added (before PR is merged)

docs(geojson.md): remove duplicate "sponsor" div

---

docs/js/navbar-search.js

Clicking the search button to search anything under the API section that contains the URL like **mongoosejs.com/docs/api/<name.html>** will redirect to the 404 page not found.
In the [navbar js code](https://github.com/Automattic/mongoose/blob/master/docs/js/navbar-search.js) that has onClick function which redirects to **'search.html?q=' + encodeURIComponent(q); -> https://mongoosejs.com/docs/api/search.html?q=find** but it should redirect to **https://mongoosejs.com/docs/search.html?q=find**
Changing ```location.href = 'search.html?q=' + encodeURIComponent(q);``` **to** ```location.href = '/docs/search.html?q=' + encodeURIComponent(q);``` will resolve the issue.

Fix search url

---

test/types/PipelineStage.test.ts
types/pipelinestage.d.ts

fix(types): allow $search in $lookup pipeline stages for MongoDB v6.x support

---

lib/browserDocument.js
lib/connection.js
lib/document.js
lib/schema.js

**Summary**
This pull request updates the Node.js EventEmitter url 
From https://nodejs.org/api/events.html#events_class_events_eventemitter 
to https://nodejs.org/api/events.html#class-eventemitter

Update Node.js EventEmitter url

---

lib/document.js

**Summary**
This PR adds `String[]` as possible jsdoc parameter for `Document.depopulate`

style(document): add "String[]" to Document.depopulate as jsdoc parameter type

---

types/connection.d.ts

**Summary**
This PR syncs the types for `.model` for `index.d.ts` and `connection.d.ts` for the single-no-constraint-generic overload

fix(types): sync single-generic-no-constraint "model" between "index.d.ts" and "connection.d.ts"

---

lib/index.js

On the [API Mongoose page](https://mongoosejs.com/docs/api/mongoose.html) `Mongoose#createConnection` and `Schema.SchemaTypes` links are outdated. The sections no longer exist on the same page but are elsewhere. Update with the correct links which are now:
https://mongoosejs.com/docs/schematypes
https://mongoosejs.com/docs/api.html#mongoose_Mongoose-createConnection

fix: update links on api docs

---

test/types/connection.test.ts
types/connection.d.ts

**Summary**
This PR applies the changes from #12125 (and also adapts the tests for `connection.model`)

[types] Apply #12125 to Connection

---

lib/schema.js
test/schema.test.js

Fix #12281 
patch for prototype pollution vulnerability CVE-2022-2564 The CVS score is 7.0.
This patch is [already available](https://github.com/Automattic/mongoose/commit/a45cfb6b0ce0067ae9794cfa80f7917e1fb3c6f8) in version 6.4.6 , downporting it for 5.x

CVE-2022-2564 vulnerability for version 5.x

---

types/index.d.ts
types/models.d.ts
types/query.d.ts

**Summary**
Fixes up #10349. Before this PR:
```
$ ./node_modules/.bin/tsc --extendedDiagnostics gh-10349.ts 
Files:                         126
Lines of Library:            27583
Lines of Definitions:        53181
Lines of TypeScript:            20
Lines of JavaScript:             0
Lines of JSON:                   0
Lines of Other:                  0
Nodes of Library:           118533
Nodes of Definitions:       142841
Nodes of TypeScript:            89
Nodes of JavaScript:             0
Nodes of JSON:                   0
Nodes of Other:                  0
Identifiers:                 92346
Symbols:                    177166
Types:                       76289
Instantiations:             334872
Memory used:               204744K
Assignability cache size:    26192
Identity cache size: …
```

Speed up TypeScript perf

---

lib/connection.js
lib/drivers/node-mongodb-native/collection.js
lib/drivers/node-mongodb-native/connection.js
lib/model.js
test/document.isselected.test.js
test/document.populate.test.js
test/document.test.js
test/document.unit.test.js
test/model.discriminator.test.js
test/schema.test.js
test/types.document.test.js
test/types.documentarray.test.js

Re: #9056
**Summary**
With this change and `--unstable`, I've been able to successfully execute crud operations on Deno v1.24.3.
```javascript
import { createRequire } from "https://deno.land/std/node/module.ts";
const require = createRequire(import.meta.url);
console.log(mongoose.version);
run().catch(err => {
console.error(err);
process.exit(-1);
});
const Test = mongoose.model('Test', mongoose.Schema({ name: String }));
await Test.deleteMany({});
await Test.create({ name: 'foo' });
console.log(await Test.findOne());
await mongoose.disconnect();
}
```
```
$ deno run --allow-read --allow-env --allow-net --unstable ./test.js 
6.5.2
model {
"$__": InternalCache { …
```

Use setPrototypeOf() instead of __proto__ to allow running on Deno

---

lib/connection.js
lib/drivers/node-mongodb-native/collection.js
lib/drivers/node-mongodb-native/connection.js
lib/model.js
test/document.isselected.test.js
test/document.populate.test.js
test/document.test.js
test/document.unit.test.js
test/model.discriminator.test.js
test/schema.test.js
test/types.document.test.js
test/types.documentarray.test.js

Reverts Automattic/mongoose#12313

Revert "Use setPrototypeOf() instead of __proto__ to allow running on Deno"

---

lib/model.js
test/model.populate.test.js

**Summary**
A bug that I ran into earlier today. If you `populate()` on a discriminator model and set the `populate` option to a string as follows:
```javascript
return Log.find({}).
populate({
path: 'activity',
populate: 'postedBy'
}).
sort({ seq: -1 });
```
You'll get the following error:
```
TypeError: Cannot create property 'strictPopulate' on string 'postedBy'
```
This fixes that case
**Examples**

fix(populate): handle specifying recursive populate as a string with discriminators

---

lib/model.js

change the word `opts` to `ops` in documentation
**Summary**
Only change to a documentation typo
**Examples**

Documentation: typo fix

---

lib/schema/documentarray.js
test/types.documentarray.test.js

Fix #12264
**Summary**
@AbdelrahmanHafez you're right that https://github.com/Automattic/mongoose/commit/4c85c7008677db89ee9eb142785a09076a548a14 is the root cause of #12264. I think the `skipId` change is a bug, because that change makes it so that init-ing an array subdocument skips the `_id` default, but not any other defaults.
**Examples**

Make ArraySubdocuments apply `_id` defaults on init

---

lib/helpers/path/flattenObjectWithDottedPaths.js
test/document.test.js

Fix #12220
**Summary**
The issue is that `flattenObjectWithDottedPaths()` drills down into Mongoose maps, which leads to infinite recursion because, among other things, maps have an instance of `Schema`, and `Schema` -> `Mongoose` -> `Model` -> `Schema`
**Examples**

Handle maps when applying defaults to nested paths

---

lib/helpers/cursor/eachAsync.js
test/helpers/cursor.eachAsync.test.js

Fix #12173
**Summary**
Node has support for AbortController and AbortSignal now: https://www.nearform.com/blog/using-abortsignal-in-node-js/ . So we can reasonably easily add support for AbortSignal in a few places, like `eachAsync()`.
The only potential problem with this implementation is that it doesn't actually kill the underlying MongoDB cursor (see https://www.mongodb.com/docs/manual/reference/command/killCursors/ ). However, MongoDB does recommend not killing cursors directly from applications, so this omission is justifiable.
**Examples**

Add support for AbortSignal on eachAsync()

---

lib/model.js

**Summary**
This PR adds a link to available options for `Model.create`, because the options are directly passed through to `.save`

style(model): add a link to available options for "Model.create"

---

test/schema.validation.test.js

**Summary**
This PR changes some tests in `schema.validation.test` to not potentially exit early.
fixes #5891 (at least partially but all example cases given)
Note: the approach used in this PR is also used already later in the file, so i had gone for that

test(schema.validation): fix tests to not exit early

---

lib/helpers/model/discriminator.js
test/model.discriminator.test.js

Fix #12246
**Summary**
We now support defining virtuals and methods using schema options, but that doesn't work well with discriminators unless the discriminator schema has the exact same virtuals and methods as the base schema.
With this PR, you can define additional virtuals on a discriminator schema using `new Schema(definition, { virtuals: { myVirtual: () => 42 } })`
**Examples**

fix(model): allow defining discriminator virtuals and methods using schema options

---

test/common.js

**Summary**
This PR changes the `test/common.js` import for `mongoose` to be a explicit file.
Before typescript's language server could not infer the types for mongoose, but now it has actual proper types, which should make writing (and following) tests easier by having intellisense / auto-completion available.
<details>
<summary>Screenshot showcasing problem</summary>
Before change:
After Change:
</details>
PS: weirdly this "typescript cannot infer the index file" only happens when trying to import the root `index.js`, from `index.js` itself importing `lib/` actually has proper intellisense

test(common): change mongoose require to be explicit "index" file

---

docs/compatibility.md
lib/cast.js
lib/types/array/methods/index.js
test/document.test.js

In the implementation of the other array methods that mutate the array,
the _markModified function is called, but in the splice method it
wasn't.
This leads to do not detect changes that happen in arrays when the splice method is used.

Call _markModified in splice array method

---

.github/workflows/test.yml
.mocharc.yml
test/common.js
test/connection.test.js
test/index.test.js
test/mocha.opts
test/model.populate.test.js
test/model.test.js
test/shard.test.js

**Summary**
This PR does:
- change from `mocha.opts` to `mocha.yml` because mocha stopped supporting the `.opts` format
- re-set the ANSI color for the SHARD warning (otherwise the next console log's / debug logs would also be in that color)
- change `common.js`'s uris to be consistent across both `uri` and `uri2` (before only `uri` would have the env applied)
- change `common.js` to have a extra value `databases` so that the databases for `uri` and `uri2` can also be used for things like `useDb` instead of just the full uri's
- change many tests from static uri's to use `common.js`'s `uri` and `uri2`
- change many tests from static database names to use `common.js`'s `databases` array
- change many tests to unify database naming to what is available in `common.js`'s `databases` array
- …

Update some tests and config to be more maintainable

---

.github/workflows/test.yml

**Summary**
This PR removes the "coverage" step and directly collects coverage from the requested configuration
the configuration where it will be collected from can be configured in the matrix `include` with the `coverage: true` property
current configuration to collect coverage (like in the removed `coverage` job) is:
- os: ubuntu-20.04
- mongodb: 5.0.2
- node: 16
This reduces test time (and also likelihood of the tests failing) by one mocha test run - also less duplicated script

Reduce CI time by directly collecting coverage from requested config

---

lib/connection.js

Below code throws `MissingSchemaError` in the `populate` statement:
```js
const { Schema } = mongoose;
try {
await mongoose.connect(process.env.MONGODB_URI);
mongoose.set("overwriteModels", true);
const personSchema = Schema({
name: String,
});
const storySchema = Schema({
author: { type: Schema.Types.ObjectId, ref: "Person" },
title: String,
});
const Story = mongoose.model("Story", storySchema);
const Person = mongoose.model("Person", personSchema);
const person = await Person.create({ name: "David" });
await Story.create({
title: "My Story",
author: person._id,
});
await Story.findOne({ title: "My Story" })
.populate("author")
.exec();
} catch (error) {
console.error(error);
}
}
run();
```
It will works if I do not set …

Fix regression for `overwriteModels` flag

---

lib/document.js
types/document.d.ts

Fix #12233
**Summary**
#12233 highlighted a gap in `$assertPopulated()`: there's no way to manually populate using `=`.
```ts
// TypeScript complains about incorrect type
newParent.nestedChild = new NestedChildModel({ name: 'NestedChild' })
newParent.$assertPopulated<{ nestedChild: NestedChildModel }>('nestedChild')
```
```ts
// Throws at runtime because `nestedChild` isn't populated yet
newParent.$assertPopulated<{ nestedChild: NestedChildModel }>('nestedChild')
newParent.nestedChild = new NestedChildModel({ name: 'NestedChild' })
```
This PR combines the two steps into 1 for TypeScript's benefit:
```ts
// Does `$assertPopulated()` and `$set()` in one operation
const doc = newParent.$assertPopulated<{nestedChild: NestedChild}>('nestedChild', {
nestedChild: new NestedChildModel({ name: …
```

fix(document): allow calling `$assertPopulated()` with values to better support manual population

---

docs/source/api.js
lib/schema/array.js
lib/schema/string.js
lib/types/DocumentArray/methods/index.js
lib/types/array/methods/index.js

**Summary**
This PR updates all invalid spread JSDOC syntaxes and updated the documentation code to properly handle the spread.
also includes some updates to the documentation script types.
Note: `{String} ...arg` is invalid, the proper definition is `{...String} arg`, and because this is not directly included from dox in the `name` property, it is "moneky"-patched in

Update JSDOC `...` (spread) definition

---

lib/aggregate.js
lib/connection.js
lib/cursor/AggregationCursor.js
lib/cursor/QueryCursor.js
lib/document.js
lib/index.js
lib/model.js
lib/query.js
lib/schema.js
types/connection.d.ts
types/cursor.d.ts
types/indexes.d.ts
types/query.d.ts

**Summary**
This PR updates old mongodb driver urls to be consistently referring to the `4.9` documentation at https://mongodb.github.io/node-mongodb-native/4.9/modules.html
also updated some (now redirecting) `https://www.mongodb.org/display/DOCS` to the pages they redirect to
One thing i was not sure on is where `http://mongodb.github.io/node-mongodb-native/2.1/api/Cursor.html` lead to, for now i have replace it to `https://mongodb.github.io/node-mongodb-native/4.9/classes/FindCursor.html`  and for `https://mongodb.github.io/node-mongodb-native/2.0/api/AggregationCursor.html` to `https://mongodb.github.io/node-mongodb-native/2.0/api/AggregationCursor.html`

style: update old mongodb nodejs driver documentation urls

---

test/types/schema.test.ts
types/indexes.d.ts

**Summary**
This PR adds string IndexDirections, according to https://github.com/Automattic/mongoose/issues/10629#issuecomment-908456806 these string versions exist at runtime
fixes #10629

fix(types): add string "ascending" and "descending" index-directions<

---

test/common.js
test/document.test.js
test/gh-1408.test.js
test/model.aggregate.test.js
test/model.populate.setting.test.js
test/model.querying.test.js
test/model.test.js

**Summary**
This PR updates some tests:
- removes usage of `process.env.TRAVIS`
- removes setting `global.CURRENT_TEST`
- converts a test to be async/await instead of callback-style in hopes that it fails less (see node results at https://github.com/Automattic/mongoose/pull/12397#issuecomment-1237912666)

Improve tests

---

lib/helpers/model/applyHooks.js
lib/helpers/model/applyMethods.js
test/document.test.js
test/model.test.js

Fix #12254
**Summary**
#12254 was a tricky issue, but comes down to the fact that `applyHooks()` will apply hooks twice if you have a custom method named `init`, which leads to infinite recursion. I added a workaround in `applyHooks()`.
I also made `applyMethods()` ignore methods that are strictly equal to the Mongoose implementation. That is, calling `schema.method('save', Model.prototype.save)` will be a no-op now. Which is better behavior IMO, that better supports the case of calling `loadClass()` with a class that extends Document, since in that case you don't want `save()` to be a custom method anyway.
**Examples**

fix(model): make `applyHooks()` and `applyMethods()` handle case where custom method is set to Mongoose implementation

---

lib/helpers/setDefaultsOnInsert.js
test/helpers/setDefaultsOnInsert.test.js

Fix #12279
**Summary**
#12279 pointed out that we need to make sure we don't apply `setDefaultsOnInsert` on a subdoc path when a path nested underneath that subdoc path is `$set`. That makes the MongoDB server throw a `Updating the path 'subscriptionsConfig.hasPaidSubscription' would create a conflict at 'subscriptionsConfig'` error.
**Examples**

fix(setDefaultsOnInsert): avoid applying defaults on insert if nested property set

---

lib/helpers/indexes/isIndexEqual.js
lib/model.js
test/model.indexes.test.js
test/model.test.js

This refactors `diffIndexes` to smaller functions. 
Also, refactors `cleanIndexes` and `createIndexes` to accept receiving optional parameters for the indexes to drop/create. This reduces the number of `listIndexes` required for `syncIndexes` to work.
I'd like to merge this since it's in a functional state, then I'll work on fixing #12250 once I can dedicate more time to it.

refactor(model): allow optionally passing indexes to createIndexes and cleanIndexes

---

scripts/website.js

**Summary**
This PR removes setting `pkg.latest38x` which is not used anywhere anymore
re #11725

docs(scripts/website): remove setting "latest38x" which is not used anywhere

---

lib/model.js
lib/query.js
test/query.test.js

Fix #12365
**Summary**
#12365 pointed out that we're not cloning hooks correctly. That's because `this.constructor` doesn't seem to pick up the correct Query class - it picks up the default `Query`, not the model-specific `Query`.
**Examples**

fix(query): use correct Query constructor when cloning query

---

lib/types/array/methods/index.js
test/types.array.test.js

**Summary**
The problem here is that `pull()` adds defaults to the query filter that is sent to MongoDB on `save()`, so it won't match documents that don't have the default set. This behavior is problematic because this may cause `save()` to start not pulling documents if the user adds a new property with a default to the schema.
We fix this by explicitly removing any fields that are set to `default` in the document.
```javascript
const catschema = new Schema({
name: String,
colors: [{
_id: false,
hex: { type: String, default: '#ffffff' },
name: String
}]
});
const Cat = db.model('Test', catschema);
const cat = new Cat({});
cat.init({
name: 'Garfield',
colors: [{ name: 'Orange' }]
});
cat.colors.pull({ name: 'Orange' });
// Sends `{ $pull: { colors: { $or: [{ name: 'Orange', hex: …
```

Improve handling of defaults when using `pull()`

---

test/model.test.js

**Summary**
This PR moves a test inside the suite of the file and changes where the model gets registered in
this resolves the following error
```txt
1) Check if static function that is supplied in schema option is available
should give a static function back rather than undefined:
OverwriteModelError: Cannot overwrite `TestModel` model once compiled.
at Mongoose.model (file:///mnt/projects/nodejs/mongoose/lib/index.js:554:13)
at Context.ModelJS (file:///mnt/projects/nodejs/mongoose/test/model.test.js:8851:32)
at https://deno.land/std@0.154.0/node/timers.ts:21:21
at Object.action (deno:ext/web/02_timers.js:148:13)
at handleTimerMacrotask (deno:ext/web/02_timers.js:65:12)
```
encountered in https://github.com/Automattic/mongoose/pull/12397#issuecomment-1243519912
Edit:
this PR also …

test(model.test): move test inside suite

---

lib/schema/SubdocumentPath.js
test/document.test.js

Fix #12328
**Summary**
#12328 pointed out that, when initializing a subdocument, we call default functions _before_ applying the initial property values. This is problematic for default functions.
Looks like easy fix: just skip applying defaults when creating the empty object, and let `init()` apply defaults.
Still one failing test case though that I need to fix, thought I had fixed it but guess not.
**Examples**

fix(document): correct context for default functions in subdocuments with init

---

lib/helpers/query/cast$expr.js

**Summary**
Version [6.2.0](https://github.com/Automattic/mongoose/releases/tag/6.2.0) introduced a feature which casts literals inside `$expr` queries to their respective types based on the models schema. This pull request fixes an issue with this feature where JS would throw a null-reference error when using `null` as a value inside `$ifNull` arrays in the expression. 
The implemented fix is non-intrusive an solely checks if the value which is to be cast is `null` and preserves the value if it is.
**Examples**
A common scenario is reproducing an `$exists` operator in an `$expr` using `$ifNull`. Let's say we want to fetch all books which don't have an `authorId` or where the `authorId` is `null`.
```.js
await bookModel.find({ $expr: { $eq: [ { $ifNull: [ "$authorId", null ] }, null ] } …
```

fix: allow null values inside $expr objects

---

lib/aggregate.js
lib/model.js
lib/query.js
lib/schematype.js
lib/types/array/methods/index.js

**Summary**
This PR changes all `#### Example.*:` to be a consistent `#### Example:`
re #12316

style: change to consistent "Example:" for jsdoc comments

---

lib/helpers/model/applyMethods.js
test/model.test.js

Fix #12423
**Summary**
In #12423 it looks like we now delete shared schema methods, which is definitely unintentional. We should only delete schema methods that exactly match methods on the Mongoose `Model` class prototype.
**Examples**

fix(model): avoid deleting shared schema methods in fix for #12254

---

lib/model.js

Add calrification for using the `overwrite` flag in model.findByIdAndUpdate and model.findOneAndUpdate
**Summary**
The way mongoose changes the update behaviour (adds `$set` to the update command) and how to prevent it is not intirely clear.
I believe this note could help save some time and effort for future users.

Add clarification about overwrite flag in model.js

---

test/types/schema.test.ts
types/inferschematype.d.ts

Fix #12242
**Summary**
#12242 shows that we can do a better job of inferring enum types for numbers, like how we infer enums from strings. You do need to use `as const` as @hasezoey pointed out, but otherwise this approach seems to work.
**Examples**

fix(types): infer number enum types from schema if using `enum: [0, 1] as const`

---

index.js
test/types/sanitizeFilter.test.ts
types/index.d.ts

**Summary**
Adding `sanitizeFilter` to the types as in the [index.js](https://github.com/Automattic/mongoose/blob/master/index.js#L55). 
**Note:** I know some things are already missing and not sure if they are meant to be "private" and exported for convenience (i.e. `skipMiddlewareFunction`).
**Examples**

chore: Add `sanitizeFilter` to types

---

docs/validation.md
test/docs/validation.test.js

Fix #12430
**Summary**
Some improvements to validation docs. First, add a section highlighting that you can use [global schematype configuration](https://thecodebarbarian.com/whats-new-in-mongoose-54-global-schematype-configuration.html) to set SchemaType-level validation logic, like adding validation for all number paths or all string paths. I also took some time to add a table of contents and prune some unnecessary details: the `context` option is no longer supported in Mongoose 6, and no need to specify which versions of Mongoose 4 support `$pull` validation because Mongoose 4 is no longer supported.
**Examples**

docs(validation): add section on global schematype validation, clean up other issues

---

lib/plugins/removeSubdocs.js
lib/plugins/saveSubdocs.js
lib/plugins/validateBeforeSave.js

**Summary**
This PR adds names to previously `anonymous` plugin functions, which could be logged with `schema.plugins`, this should make it easier to debug if there should ever be the need (and for users to actually see what it is doing instead of a unhelpful `anonymous`)

style: add names to previously anonymous plugin functions

---

.eslintrc.json
test/types/models.test.ts
types/index.d.ts

Fix #12319
**Summary**
#12319 correctly pointed out that it is clunky to pull the hydrated document type from an inferred schema. This PR adds a helper `HydratedDocumentFromSchema` that helps make that cleaner.
**Examples**

fix(types): add HydratedDocumentFromSchema to make it easier to pull inferred hydrated doc type

---

test/types/schema.test.ts
types/index.d.ts

**Summary**
This PR updates `DiscriminatorSchema` to:
- have better and more reasonable names
- also transfer & combine all statics from both schemas
also see #12457 (which could make this PR obsolete when resolved)

Update `DiscriminatorSchema` to have better names and combine statics

---

types/index.d.ts

**Summary**
Remove default from helper type `PluginFunction`, these default are unnecessary because all values are passed-through from where the helper type is used and so they go always unused
i already did a ts-benchmark, but nothing changed (`Instantiations` are the same as master and this branch, and time is within margin of error)

fix(types): remove unused defaults in "PluginFunction"

---

test/types/schema.test.ts
test/types/schemaTypeOptions.test.ts
types/schematypes.d.ts

**Summary**
This PR changes `SchemaTypeOption.index` to use the same definition as the `schema.index` function
also adds some tests for that field
fixes #12395
Edit:
also added some more tests for the `schema.index` function

fix(types): update SchemaTypeOptions.index to use "IndexDirection"

---

lib/query.js
test/types/queries.test.ts
types/query.d.ts

**Summary**
This PR adds a type for the "array of array with key-value pairs" as a possible type
also adds some more documentation about this way to the jsdoc
fixes #12434
was broken by #11852

fix(types): add "array of array key-value pairs" as a argument option for "query.sort()"

---

lib/query.js
test/helpers/update.castArrayFilters.test.js
test/query.test.js

Fix #12325
**Summary**
#12325 pointed out that, in Mongoose 5, `findOne(ObjectId)` worked the same as `findById(ObjectId)`. I don't see any reason why we shouldn't continue to support this behavior.
**Examples**

fix(query): treat `findOne(_id)` as equivalent to `findOne({ _id })`

---

package.json

**Summary**
This PR updates `mongodb-memory-server` to the latest patch version, because this fixes some CI errors that may occur for replsets
this change is also included in #12262, but i thought that this change should maybe land earlier

chore(devDeps): upgrade "mongodb-memory-server" to 8.9.3 to fix some CI errors

---

test/types/models.test.ts

**Summary**
This PR adds types-tests for `find` and `findOne` with a direct `ObjectId` argument, because it was missing in the original PR
re #12485

test(types): add types-test for find & findOne with ObjectId argument

---

lib/error/setOptionError.js
lib/error/validation.js
lib/helpers/error/combinePathErrors.js
lib/index.js
test/index.test.js
test/types/base.test.ts
types/index.d.ts

**Summary**
This PR adds the ability to set multiple options at once for `mongoose.set`
behavior is:
- if `key` is not a `object` and no `value` is given, return the option (like before)
- if `key` is not a `object` and `value` is given, convert them to a `{ key: value }` object
- if `key` is a `object`, ignore `value` and use that object
- if there is a error for a specific option, collect the error and evaluate all other options
- if there is only `1` error, throw that error (to keep backwards compat)
- if there are multiple errors, throw the whole array of errors
fixes #10438

feat(index): add ability to set multiple options at once in ".set"

---

lib/helpers/projection/isPathExcluded.js
lib/model.js
test/document.test.js

Fix #12414
**Summary**
If you load a document with an array deselected `const doc = await Model.findOne().select({ arr: 0 })` and then save with no changes, Mongoose will save an empty array. This looks like it applies to all deselected defaults.
This PR makes it so that Mongoose skips deselected defaults when calculating what changed in the document.
**Examples**

fix(model): avoid saving applied defaults if path is deselected

---

test/mocha-fixtures.js

**Summary**
This PR is a small follow-up of #12262, where i noticed some spelling mistakes and example comments left-overs, also using `MONGOOSE_REPLSET_URI` in the false case of `startMemoryReplset`

chore(mocha-fixtures): fix spelling and remove "example" comments

---

test/types/middleware.test.ts
types/middlewares.d.ts

**Summary**
This PR adds `estimatedDocumentCount` and `countDocuments` as possible hooks in the types, plus tests
fixes #12516

fix(types): add "estimatedDocumentCount" and "countDocuments" as possible hooks

---

test/types/schema.test.ts
types/index.d.ts

Fix #12457
**Summary**
#12457 pointed out that our types are slightly incorrect: `Schema.prototype.discriminator()` returns `this`, not the discriminated schema. Needed to change some tests which relied on the incorrect behavior. In cases like this where the TS types and runtime behavior disagree, we should assume the runtime behavior is more correct and fix the types, including any incorrect typing tests.
**Examples**

fix(types): indicate that Schema.prototype.discriminator() returns `this`

---

docs/models.md

**Summary**
This fixes the closing tag missed in the suggestions at https://github.com/Automattic/mongoose/pull/12526#discussion_r988039671

docs(models): fix non-matching closing tag

---

types/pipelinestage.d.ts

densify pipeline stage was not in the union type
for PipelineStage, this was causing ts error when
users were trying to call the aggregate method with
densify stage
**Summary**
After declaring a model and using its `.aggregation` method with a `$densify` stage, I received an error related to the fact that there was no method overload matching a pipeline with `$densify` as a stage.
Looking at the `PipelineStage` type, I saw that `PipelineStage.Densify` was missing in the union type.
So I just added it.
**Examples**
The following was causing an error, now it's allowed.
```typescript
MyModel.aggregate([
{
$densify: ...
}
])
```

Add missing densify type pipeline type

---

lib/document.js
lib/model.js
lib/schema.js
test/model.test.js
test/timestamps.test.js

Fix #12117
**Summary**
Quick feature for 6.7 to make working with timestamps and `bulkSave()` + `insertMany()` easier. Right now, there's no way to configure timestamps for individual documents when using `bulkSave()` and `insertMany()`. This PR adds a `$timestamps()` method that sets the timestamps option for all future `save()`, `bulkSave()`, and `insertMany()`.
**Examples**

feat(document): add `$timestamps()` method to set timestamps for `save()`, `bulkSave()`, and `insertMany()`

---

types/pipelinestage.d.ts

**Summary**
For how the `$replaceWith` pipeline stage type was written, it wasn't possible to replace the document by using expressions.
**Examples**
Things like the following were not possible, now they're.
```js
db.sales.insertMany([
{ "_id" : 1, "item" : "butter", "price" : 10, "quantity": 2, date: ISODate("2019-03-01T08:00:00Z"), status: "C" },
{ "_id" : 2, "item" : "cream", "price" : 20, "quantity": 1, date: ISODate("2019-03-01T09:00:00Z"), status: "A" },
{ "_id" : 3, "item" : "jam", "price" : 5, "quantity": 10, date: ISODate("2019-03-15T09:00:00Z"), status: "C" },
{ "_id" : 4, "item" : "muffins", "price" : 5, "quantity": 10, date: ISODate("2019-03-15T09:00:00Z"), status: "C" }
])
```
```js
SalesModel.aggregate([
{ $match: { status: "C" } },
{ 
$replaceWith: {
_id: "$_id",
item: …
```

Adjust replaceWith type pipeline stage

---

.github/ISSUE_TEMPLATE/bug.yml

**Summary**
This PR adds a optional field to the `bug` github issue template for the Typescript version
re https://github.com/Automattic/mongoose/issues/12512#issuecomment-1268898713

chore(template::bug): add field for typescript version

---

CHANGELOG.md
docs/change-streams.md
lib/aggregate.js
package.json
test/aggregate.test.js
test/types/PipelineStage.test.ts
types/aggregate.d.ts
types/expressions.d.ts
types/pipelinestage.d.ts

**Summary**
Fixes: https://github.com/Automattic/mongoose/issues/12536
Adds `$fill` aggregation pipeline stage.
https://docs.mongodb.com/manual/reference/operator/aggregation/fill/
Adds `$linearFill` and `$locf` WindowOperator's 
https://www.mongodb.com/docs/manual/reference/operator/aggregation/linearFill/
https://www.mongodb.com/docs/manual/reference/operator/aggregation/locf

feat(aggregation): add $fill pipeline stage

---

lib/helpers/model/discriminator.js
lib/model.js
test/model.discriminator.test.js
test/types/discriminator.test.ts
types/models.d.ts

Fix #12472
**Summary**
There isn't a good way for Mongoose to dedupe hooks other than checking if you have two functions that are `===`. Deduping based on `toString()` would prone to false positives with certain design patterns.
So for cases where deduping is not going to work, like #12472, we now have a `mergeHooks` option to `Model.discriminator()`. `Model.discriminator(name, discriminatorSchema, { mergeHooks: false })` makes Mongoose take the discriminator schema's hooks.
**Examples**

feat(model): add `mergeHooks` option to `Model.discriminator()` to avoid duplicate hooks

---

test/types/expressions.test.ts
types/expressions.d.ts

**Summary**
Adds `limit` to `$filter` expression. 
https://www.mongodb.com/docs/manual/release-notes/5.2/#operator-s-limit-field

fix(types): add limit to $filter expression

---

docs/populate.md

docs(populate): added transform option description

---

lib/helpers/aggregate/prepareDiscriminatorPipeline.js
test/helpers/aggregate.test.js

Fix #12478
**Summary**
#12478 points out that `prepareDiscriminatorPipeline()` unnecessarily adds a `$match` stage with the discriminator key if the user already explicitly set the correct discriminator key in the initial `$match`.
**Examples**

fix(aggregate): avoid adding extra `$match` stage if user manually set discriminator key to correct value in first pipeline stage

---

lib/types/DocumentArray/index.js
test/document.test.js

Fix #12480
**Summary**
Looks like we missed a spot when we allowed using `schema` as a top-level key: `DocumentArray/index.js` still uses `doc.schema` rather than `doc.$__schema`
**Examples**

fix(document): allow creating document with document array and top-level key named `schema`

---

lib/schema/documentarray.js
test/model.update.test.js

Fix #12518
**Summary**
`ArraySubdocument` gracefully handles the case when `parentArray` is a `Query`, but looks like the schematype-specific subclass `EmbeddedDocument` does not. This PR makes it so that `EmbeddedDocument` relies on the `__parentArray` property that `ArraySubdocument` sets.
**Examples**

fix(update): handle runValidators when using `$set` on a doc array in discriminator schema

---

lib/cast.js
test/cast.test.js

Fix #12508
**Summary**
Looks like schema-level `strict` overrides schema-level `strictQuery`, which is definitely not something we want given that we want to switch `strictQuery` back to `false` by default.
**Examples**

fix(cast): make schema-level strictQuery override schema-level strict for query filters

---

lib/helpers/isAsyncFunction.js
package.json

Re: #12576
**Summary**
A couple of related fixes:
1. Fix the issue that was causing browser build to fail
2. Remove `dist` to prevent accidentally publishing out-of-date browser build if `build-browser` fails
3. Use a different approach for `isAsyncFunction()` based on [this SO thread](https://stackoverflow.com/questions/38508420/how-to-know-if-a-function-is-async), because our current approach doesn't seem to work very well when compiled through Babel. I suspect the issue is that Babel converts `Object.getPrototypeOf(async function() {});` to `Object.getPrototypeOf(function() {});` under the hood.
**Examples**

fix: correct browser build and improve isAsyncFunction check for browser

---

lib/document.js
test/document.test.js

closes #11849 
Not sure if this is the best approach.
Anyway, open to feedback.

feat(document): add $clone method

---

types/models.d.ts

**Summary**
While looking into the constructor signature overrides of the Mongoose's model `create` function, I've noticed that one of its overrides is missing. 
This PR adds it.

feat(types/models): add missing create constructor signature override type

---

lib/helpers/populate/assignVals.js
lib/helpers/populate/getModelsMapForPopulate.js
lib/model.js
lib/types/map.js
test/document.test.js
test/types.map.test.js

**Summary**
#12494 shows that, in 5.x, you could use maps of arrays of refs. We don't currently have any test coverage for that case, so in 5.x it worked more by accident than by design. In 6.x we unexpectedly broke that. This PR gives us better support for populating maps of arrays of refs, including populating just one entry in the map.
**Examples**

Better support for populating maps of arrays of refs

---

lib/helpers/populate/getSchemaTypes.js
lib/schema.js
test/helpers/populate.getSchemaTypes.test.js
test/schema.test.js

**Summary**
Fix #12530 
Current handling for getting schema types underneath maps of mixed from #9298 and https://github.com/Automattic/mongoose/commit/63a34bec66f263c96a72d0ffb2f28a6c563a2a12 doesn't do a good job of handling `Mixed`. This PR fixes that.
**Examples**

Correctly find paths underneath single nested document with an array of mixed

---

types/validation.d.ts

**Summary**
As the documention mentions [it](https://mongoosejs.com/docs/api.html#schematype_SchemaType-validate), the `propsParameter` property does not exists on the `ValidateOpts<T>` type and cause TypeScript to generate an error.
**Examples**
I have created a validator to check if the ObjectId references existing mongoDB collection document.
```ts
export const refExists: ValidateOpts<string> = {
async validator(_id, props): Promise<boolean> {
const self = this.constructor as Model<any>;
const {ref} = self.schema.paths[props.path].options;
const model = models[ref];
return await model.exists({_id}).exec() !== null;
},
propsParameter: true,
};
```
This snippet generate two TypeScript errors:
> error TS2322: Type '{ validator(_id: string, props: (result: boolean) => void): …

Improve ValidateOpts type

---

lib/queryhelpers.js
test/query.test.js

fix #12603
**Summary**
Selecting a Map field with the flag `select` to `false` in the schema declaration using the `.select('+field')` syntax now correctly returns the field.

fix(query): select Map field with `select: false` when explicitly requested

---

docs/guides.md
docs/lodash.md
docs/source/index.js

Fix #12559
**Summary**
We do still occasionally get bug reports related to Lodash, so we should add some docs that highlight common pitfalls, and what we support vs what we doesn't when it comes to Lodash.
**Examples**

docs: add Lodash guide highlighting issues with cloneDeep()

---

lib/index.js

fix #12618
**Summary**
Canceled an example that was related to the old `createConnection` syntax and wasn't removed in #6766

Removed outdated example from `createConnection` method

---

docs/connections.md

fix #12624
**Summary**
The `Option Changes in v5.x` was referring to a link present only in v5 docs

Removed v5 link from v6 docs

---

.github/workflows/benchmark.yml
.github/workflows/codeql.yml
.github/workflows/documentation.yml
.github/workflows/test.yml
.github/workflows/tidelift-alignment.yml
.github/workflows/tsd.yml

**Summary**
This PR updates all `action/checkout` to version `3.1.0` and also consistenizes the definitions of versions.
Upgrade in hopes to remove `Warning: The 'save-state' command is deprecated and will be disabled soon. Please upgrade to using Environment Files.`

chore(workflows): update actions/checkout to 3.1.0

---

test/types/schema.test.ts
types/inferschematype.d.ts

Fix #12420
**Summary**
Our types should treat setting `default` to a function that always returns `undefined` in the same way we treat setting `default: undefined`.
**Examples**

fix(types): make array paths optional in inferred type of array default returns undefined

---

test/types/models.test.ts
types/index.d.ts

fix #12622
**Summary**
The problem was that the `pre` and `post` hook were resolving the method as `Document` instead of a `Query` for the conflicting types declared in https://github.com/Automattic/mongoose/blob/78ea4c754027dff02e1477f7aeb25f4435ac6910/types/middlewares.d.ts#L3-L4
By changing the type declaration the hook now resolves `this` as a query by default.

fix(type): pre hook with deleteOne should resolve this as Query

---

lib/helpers/model/discriminator.js
lib/model.js
test/model.discriminator.test.js
test/types/discriminator.test.ts
types/models.d.ts

feat(model): add `mergePlugins` option to `discriminator`

---

test/types/schema.test.ts
types/inferschematype.d.ts
types/schematypes.d.ts

Fix #12593
Re: #12268
Re: #3208
**Summary**
Missed adding TS definitions for #12268. This makes it possible to use UUIDs in TS schemas, including with `InferSchemaType`.
**Examples**

fix(types): add UUID to types

---

test/types/models.test.ts
types/index.d.ts
types/inferschematype.d.ts
types/utility.d.ts

Fix #12573
**Summary**
`model<any>()` currently returns a model with just an `_id` property, which is very strange. This PR fixes that.
**Examples**

fix(types): correct handling for model<any>

---

test/types/schema.test.ts
types/index.d.ts
types/schematypes.d.ts

Fix #12590
**Summary**
`SchemaType` should have a reference to the `DocType` so it knows that type to set `this` to in when the user does `schema.path('mypath').validate(function(v) { ... })`. With this PR, the following script compiles fine
```ts
import { Schema, SchemaType, InferSchemaType } from 'mongoose';
const UserSchema = new Schema({
_password: String
});
type User = InferSchemaType<typeof UserSchema>;
UserSchema.path('hashed_password').validate(function (v) {
if (this._password && this._password.length < 8) {
this.invalidate('password', 'Password must be at least 8 characters.');
}
});
```
**Examples**

fix(types): set `this` to doc type in `SchemaType.prototype.validate()`

---

lib/helpers/timestamps/setupTimestamps.js

With the current browser.umd it‘s no longer possible to create schemas in the browser with `timestamps: true`. The following error is thrown: `Cannot read properties of null (reading 'get')`
Example to reproduce:
```
const TestSchema = new mongoose.Schema(
{ a: String },
{ timestamps: true }
);
```

fix(schema): fix setupTimestamps for browser.umd

---

types/document.d.ts

fix(document): Set Document.modelName property in constructor

---

lib/document.js
test/document.test.js

Fix #12656
**Summary**
We added some tracking of what the "saved state" of a document is in #9396 and #10773, but #12656 pointed out that we're not actually storing this saved state correctly when the first operation is a `push()`. Thankfully, #11644 makes this a bit easier: we can copy the state in `markModified()`.
Hopefully this is all we need, but we may want to consider tracking `savedState` by just cloning the document when the document is saved or loaded. That is easier from an implementation perspective, but bad from a performance perspective. I would prefer to not have to do that.
**Examples**

fix(document): handle setting array to itself after saving and pushing a new value

---

lib/document.js

Fix #11990
**Summary**
Docs need to explain that `$isNew` is false in post('save') hooks, this question has come up a few times.
**Examples**

docs(document): explain that `$isNew` is `false` in post('save') hooks

---

lib/query.js

fix #12706
**Summary**
Updated documentation for the `updateOne` and `replaceOne` queries to match MongoDB Node driver v4.x return values

docs(query): updated examples for `updateOne` and `replaceOne`

---

docs/typescript/statics-and-methods.md

Changed line gave "'User' was used before it was defined" linting error. Will compile if you ignore the lint error but I think it's more informative to show that `this` can be used - as it is an instance of `UserModel` here.

Replace used before defined User with this.

---

CONTRIBUTING.md
docs/async-await.md
docs/connections.md
docs/documents.md
docs/faq.md
docs/guide.md
docs/jest.md
docs/lodash.md
docs/middleware.md
docs/models.md
docs/populate.md
docs/promises.md
docs/queries.md
docs/schematypes.md
docs/subdocs.md
docs/tutorials/custom-casting.md
docs/tutorials/getters-setters.md
docs/tutorials/query_casting.md
docs/validation.md

**Summary**
This PR is a follow-up to #12623 and adds style-guidelines as said in #12645
All Changes:
- change remaining static links in the documentation to relative ones
- change all remaining not-required prefix links to no-prefix links (`./guide.html` -> `guide.html`)
- add a documentation style guidelines section to CONTRIBUTING
- change slightly outdated information in the CONTRIBUTING (about file extensions)
- consistenize spacing in CONTRIBUING
fixes #12645

[DOCS] Update remaining relative and static links, also add style guidelines for documentation

---

lib/model.js
types/populate.d.ts

Fix #12599
**Summary**
In a couple of places our description of the `justOne` flag is flipped. This PR fixes that.
**Examples**

docs: fix inverted explanation of `justOne` option for populate

---

lib/cursor/QueryCursor.js
types/cursor.d.ts

**Summary**
Wraps the `mongodb.FindCursor.rewind` function to reset the cursor to its uninitialized state, effectively resetting the cursor to the beginning.
**Examples**
```ts
const options = {}
ModelClass.find(options) 
// - instance1
// - instance2
// - instance3
// ================================================
const cursor = ModelClass.findOne(options).cursor()
await cursor.next() // instance1
await cursor.next() // instance2
cursor.rewind()
await cursor.next() // instance1
```

add `rewind` function to `QueryCursor`

---

types/pipelinestage.d.ts

See doc: https://www.mongodb.com/docs/manual/reference/operator/aggregation/replaceWith/
Not sure if `ObjectExpressionOperator` should be modified instead?

fix(types): Update replaceWith pipeline stage

---

lib/helpers/cursor/eachAsync.js
test/helpers/cursor.eachAsync.test.js

Fix #12652
**Summary**
#12652 points out that there is a race condition in `eachAsync()` when `parallel > 1` and `batchSize` is set. Given that we run a bunch of parallel queues, `documentsBatch` can change while the `eachAsync` callback is running.
This fixes part of the issue: makes it so that at least every document gets processed, and each `eachAsync()` callback gets a consistent batch of documents that doesn't change.
However, there is still the potential issue that the individual documents in the batch can be in any order when `parallel > 1`. Because we run `next()` in parallel, you can end up with surprising behavior like document 9613 in the same batch as documents 9900-9999. Or an `eachAsync()` callback running with a batch of size 67 followed by a batch of 33 even though you …

fix(cursor): make `eachAsync()` avoid modifying batch when mixing `parallel` and `batchSize`

---

lib/cast.js
test/query.test.js

fix: setting global `strictQuery` after Schema creation wasn't working

---

types/query.d.ts

Fix #12688
Fix #12689
**Summary**
A more robust fix for #12689, which mostly does what we expect. It looks like we do lose the generics with `toConstructor()`, but I think this approach is better than Mongoose compilation crashing on TypeScript 4.6.
**Examples**

fix(types): avoid typeof Query with generics for TypeScript 4.6 support

---

test/types/schema.test.ts
types/inferschematype.d.ts

Fix #12611
**Summary**
Bitten yet again by the fact that ReadonlyArrays and Arrays are separate classes in TypeScript :sob: 
**Examples**

fix(types): correctly infer ReadonlyArray types in schema definitions

---

lib/cast.js

**Summary**
Simple code cleanup as suggested here https://github.com/Automattic/mongoose/pull/12717#discussion_r1030184662

fix: code cleanup in `getStrictQuery` function

---

docs/guide.md
lib/helpers/printStrictQueryWarning.js
lib/index.js
lib/query.js

fix #12666
**Summary**
`strictQuery` will be switched back to `false` by default in Mongoose 7 so a warning message is shown on the database connection and on query execution if the `strictQuery` option is undefined and forced to true by the user.
Let me know if I understood the suggested logic correctly for the query warning message.

added deprecation warning for default `strictQuery`

---

test/types/virtuals.test.ts
types/index.d.ts

Fix #12702
Re: #11908
@carlosingles can you also please take a look?
**Summary**
Looks like `model()` isn't pulling TVirtuals correctly, which is leading to virtuals not showing up in query results if you're using inferred schemas.
**Examples**

fix(types): infer virtuals in query results

---

lib/helpers/common.js
test/helpers/common.test.js

**Summary**
`helpers.common.modifiedPaths` is a recursion function.
when user call `db.updateOne({key: badValue})`, the `badValue` will cause a endless recursion call. but it is impossible to check user's input. so I think we can check the recursion level , it will be helpful for debugging.
**Examples**
```javascript
async function updateDoc(){
const count = collectionA.countDocuments({}); // miss an `await`, will cause a endless recursion call.
await collectionB.updateOne({key: count}, {upsert: true});
}
```

make `modifiedPaths` safer.

---

lib/helpers/schema/merge.js
test/schema.test.js

Fix #12654
**Summary**
Docs say that `Schema.prototype.add()` copies indexes if you call `add()` with a schema instance, but looks like that doesn't actually happen. I can see the case for putting this change in a minor release, but I think patch is fine since the docs indicate that this is the correct behavior.
**Examples**

fix(schema): copy indexes when calling `add()` with schema instance

---

types/index.d.ts

Fix #12595
Re: #11911
**Summary**
Not my favorite change, but unfortunately necessary if we want to support #12595 with `extends Document`. Once we drop support for `extends Document`, we can revisit this issue. See comments about why this change is necessary.
**Examples**
```ts
import mongoose, { UpdateQuery } from 'mongoose';
const { Schema, model } = mongoose;
interface IAnimal {
name?: string;
}
const animalSchema = new Schema<IAnimal>({
name: { type: String }
});
const Animal = model<IAnimal>('Animal', animalSchema);
const writeOperations = ['foo', 'bar', 'baz'].map(name => {
const changes: UpdateQuery<IAnimal> = { }
if (name === 'foo') {
changes.name = name.repeat(2);
} else {
changes.name = …
```

fix(types): support using `UpdateQuery` in `bulkWrite()`

---

lib/model.js
test/model.test.js

fix #12250
**Summary**
The `model.collection.createIndex` is now executed only if there are indexes in the `toCreate` array.
`getIndexesToCreate` now includes a check to evaluate if the index was dropped. In that case, it will proceed to recreate it.

fix(model): prevent index creation on syncIndexes if not necessary

---

test/types/schema.test.ts
types/inferschematype.d.ts

**Summary**
Fixes #12782
**Examples**
Added a test

InferSchemaType: consider { required: boolean } required if it isn't explicitly false

---

lib/query.js

fix #12474
**Summary**
Improved documentation for `slice()` and explained how indexes behave in edge cases.

docs(query): updated explanation for slice

---

lib/helpers/common.js
test/helpers/common.test.js

**Summary**
If the same object is referenced in multiple places, it was wrongfully detected as circular, even when it wasn't.
Amends commit 7974f004fae549ac11bbc247ac371fe6be4aa137.
Fixes #12775.
**Examples**
Demonstrated by the added test.

Fix wrong circular dependency detection

---

types/aggregate.d.ts

**Summary**
This PR renames the generic `Aggregate` uses to make it more clear what the generic does and match the definition of `Query`
**Examples**

style(types/aggregate): rename generic to match Query definition

---

lib/helpers/query/castUpdate.js
test/query.test.js

fix #12794
**Summary**
Update queries now remove a field set to `undefined` as by expected behavior (starting from Mongoose 6) specified [here](https://mongoosejs.com/docs/migrating_to_6.html#removed-omitundefined).

fix(query): update queries removes fields set to `undefined`

---

lib/helpers/populate/assignVals.js
test/model.populate.test.js

Fix #12739
**Summary**
Avoid calling populate transform on null values
**Examples**

fix(populate): avoid calling `transform` if there's no populate results and using lean

---

lib/document.js
types/document.d.ts

**Summary**
For @lpizzinidev . We intended to make `$clone()` public for 6.8 in #12549, but looks like we didn't add it to TypeScript or the docs :cry: 
**Examples**

docs: make `Document.prototype.$clone()` public

---

lib/index.js

fix #12808
**Summary**
Added missing options to `mongoose.set` documentation.

docs(mongoose): Added missing options to `set`

---

lib/helpers/update/castArrayFilters.js
test/helpers/update.castArrayFilters.test.js

Fix #12565
**Summary**
`castArrayFilters()` doesn't handle embedded discriminators. With this PR, you should be able to use embedded discriminators, as long as you explicitly specify the embedded discriminator key in the array filter.
**Examples**

fix(update): handle embedded discriminators when casting array filters

---

lib/helpers/populate/assignRawDocsToIdStructure.js
test/model.populate.test.js

Fix #12730
Re: #10552
**Summary**
Strange edge case related to our fix for #10552. Using `resultOrder` only works well if each element of `resultOrder` is a number. Which is if we're populating an array. But if we have arrays, which means we're populating a property under a document array, then `newOrder[_resultOrder] = doc` doesn't work. But unfortunately, `resultOrder`'s values will be a number if there's only 1 result for that particular document array element. This PR works around that by using the "element under document array" behavior whenever there is an array value in `resultOrder`.
**Examples**

fix(populate): handle virtual populate underneath document array withjustOne=true and sort set where 1 element has only 1 result

---

test/types/schemaTypeOptions.test.ts
types/schematypes.d.ts

**Summary**
This PR adds the property `defaultOptions` for `SchemaType` and its extending classes
for `SchemaType` itself, property `defaultOptions` is optional, see: (and also search through the file, there is no explicit assignment)
https://github.com/Automattic/mongoose/blob/5528a6428bb08091c03d868e249c2e5a30144a71/lib/schematype.js#L55
but all mongoose provided extending classes explicitly define it:
https://github.com/Automattic/mongoose/blob/5528a6428bb08091c03d868e249c2e5a30144a71/lib/schema/SubdocumentPath.js#L326

fix(schematypes): add property "defaultOptions"

---

test/types/schema.test.ts
types/schemaoptions.d.ts

**Summary**
This PR adds the schema option `overwriteModels` to the types
fixes #12816

fix(schemaoptions.d.ts): add option "overwriteModels" as a schema option

---

lib/helpers/query/castUpdate.js
test/query.test.js

Fix #12821
**Summary**
#12797 missed a small edge case where `val` can be nullish.
**Examples**

fix(query): fix unexpected validation error when doing findOneAndReplace() with a nullish value

---

test/model.test.js

Fix #12643
**Summary**
I haven't been able to repro the flakey test locally, but I have some guesses about why this test is flaking. 1) `autoIndex` isn't disabled, so that could somehow be causing an incorrect collection to be created, 2) not waiting for `init()` before dropping. Either way, these two changes should make the test more robust.
**Examples**

test(model): make timeseries test more durable by avoiding autoIndex and drop/init race

---

lib/schema.js
test/schema.documentarray.test.js

Fix #12796
**Summary**
The root cause of #12796 is that we don't propagate `strictQuery` to implicitly created schemas like we do `strict`. So if global `strictQuery` is false, but the implicitly created schema's `strictQuery` is true. That gets even more confusing because embedded discriminator schemas do pick up the global `strictQuery` default, so with global `strictQuery = false` you get an error every time you create an embedded discriminator.
**Examples**

fix(schema): propagate strictQuery to implicitly created schemas for embedded discriminators

---

docs/js/navbar-search.js

**Summary**
This PR is for fixing what c3384bcd1dc60fa15b57f41931bac9d9c99fc6e2 introduced (a missing variable), which makes the search via the navbar impossible (because the script never actually runs)
re #12830
fixes the following current error:
```txt
Uncaught ReferenceError: defaultVersion is not defined
<anonymous> https://mongoosejs.com/docs/js/navbar-search.js:3
<anonymous> https://mongoosejs.com/docs/js/navbar-search.js:18
[navbar-search.js:3:17](https://mongoosejs.com/docs/js/navbar-search.js)
<anonymous> https://mongoosejs.com/docs/js/navbar-search.js:3
<anonymous> https://mongoosejs.com/docs/js/navbar-search.js:18
```

docs(navbar-search): add missing variable

---

test/types/aggregate.test.ts
types/aggregate.d.ts

**Summary**
add missing type definition for `Aggregate.prototype.model` function that can be used for set or get Model from an Aggregate object.
According to mongoose documentation `Aggregate.prototype.model` can be used in two ways:
```js
const aggregate = MyModel.aggregate([{ $match: { answer: 42 } }]);
aggregate.model() === MyModel; // true
// Change the model. There's rarely any reason to do this.
aggregate.model(SomeOtherModel);
aggregate.model() === SomeOtherModel; // true
```
...to get the aggregation object model and to set it.
But `types/aggregate.d.ts` is missing type definition for the get case of `Aggregate.prototype.model` function
This PR aims to fix this.
**Examples**

add type def for Aggreaget#model without arguments

---

lib/helpers/populate/assignRawDocsToIdStructure.js

Resolves #12865 
**Summary**
**Examples**

improve performance of assignRawDocsToIdStructure

---

types/index.d.ts

**Summary**
I sometimes use virtuals in the definition of other virtuals in my Mongoose schemas. This change allows virtuals to invoke other virtuals in TypeScript.
**Examples**
I have this code:
```typescript
userSchema.virtual("tier").get(function() {
// ...
candidate = this.programModel?.tier_override;
// ...
});
```
In this code, `programModel` is a virtual. However, compiling this code gives me an error:
```
src/user_model.ts:208:19 - error TS2339: Property 'programModel' does not exist on type 'Document<unknown, any, IUser> & IUser & Required<{ _id: ObjectId; }> & IUserMethods'.
208  candidate = this.programModel?.tier_override;
~~~~~~~~~~~~
```
This PR fixes the error.
I have my virtuals defined in their own interface:
```typescript
interface IUserVirtuals {
// ...
tier: string; …
```

Allow virtuals to be invoked in the definition of other virtuals

---

docs/typescript/schemas.md
test/types/schema.test.ts
types/inferschematype.d.ts

Re: #12807
**Summary**
Really not my favorite PR. I haven't been able to figure out exactly why this issue happens, I suspect because there's some self-referential issues that pop up because methods, virtuals, and statics use the inferred document type, and the inferred document type relies on schema options. But this is at least sufficient to unblock anyone using timestamp type inference.
We should consider deprecating `timestamps` type inference for 7.0 if we don't come up with a better solution. I'm going to take some time to come up with a minimal repro script for the TypeScript team. I don't expect this to end up being a bug that TS is willing to fix. But might as well so we can at least be certain that we're trying to do something TypeScript doesn't support.
**Examples**

fix(types): avoid inferring timestamps if `methods`, `virtuals`, or `statics` set

---

test/types/schema.test.ts
types/inferschematype.d.ts

**Summary**
Fixes #12869
Not a TypeScript expert, but I followed the example in #12463 and added a test case demonstrating this change works. I think what is happening here is that a readonly array cannot extend a regular array, so our types here need to use ReadonlyArray to handle both const and regular arrays.
**Examples**

Correctly infer string enums on const arrays

---

lib/model.js
test/model.test.js

Re: #12791
**Summary**
#12791 points out a few issues with our error reporting with `create()` and `insertMany()`. We do have a workaround using `insertMany()`, but the workaround does have a potential flaw: currently, `res.mongoose.validationErrors` can report validation errors in any order.
Specifically, the validation errors are in the order that the errors occur, not in the order of the original documents passed in. So if `doc1` and `doc2` both fail validation, `const res = await Model.insertMany([doc1, doc2], { ordered: false, rawResult: true })` can end up with doc2's validation error before doc1's in `res.mongoose.validationErrors` if doc1's validation takes longer than doc2's.
With this change, `res.mongoose.validationErrors` will always be in the same order as the documents …

fix(model): ensure consistent ordering of validation errors in `insertMany()` with `ordered: false` and `rawResult: true`

---

docs/discriminators.md
test/docs/discriminators.test.js

Fix #6087
**Summary**
Add `overwriteDiscriminatorKey` to discriminator docs, because that option is a bit hard to find.
**Examples**

docs(discriminators): add section about changing discriminator key

---

docs/typescript/virtuals.md

Fix #12684
**Summary**
Documentation related to where virtuals show up with automatically inferred schema types, and why they show up where they do. Also how to get the hydrated doc type. Because we didn't have a good link to answer @Jokero 's questions in #12684 
**Examples**

docs(typescript): explain that virtuals inferred from schema only show up on Model, not raw document type

---

.github/workflows/test.yml

**Summary**
this should get rid of the "set-output is deprecated" warning, also brings the version of `setup-node` to be the same as in normal-tests and replica-tests

chore(workflows/test): update "setup-node" version for the deno tests

---

test/connection.test.js
test/errors.validation.test.js
test/index.test.js

**Summary**
This PR enables some tests to also run on deno again, they were originally disabled because deno did not support catching some errors, but they now work
also updates a message on why a test is disabled for deno currently

test: allow more tests for deno

---

test/model.findOneAndUpdate.test.js

**Summary**
This PR removes a NodeJS <4 check in the tests, because the minimal NodeJS version is now 12 and so "useless"

test(model.findOneAndUpdate): remove NodeJS <4 check

---

docs/incompatible_packages.md
docs/source/index.js

Fix #12671
**Summary**
#12671 is an issue with another npm package that adds some global properties which break an upstream dependency of Mongoose. It would be nice to have a list of known incompatible packages in our docs.
On a side note, it would be great to know which npm packages modify global state.
**Examples**

docs: add list of known incompatible npm packages

---

lib/document.js
lib/schema.js

**Summary**
I want to set `Document` as the base class of a `loadClass` class so I can inherit its typings on `this` conveniently. There is a [guard condition hack in the code](https://github.com/Automattic/mongoose/blob/c77dd1bfbec6b551f0ba602b318bdd98f68c4aeb/lib/schema.js#L2291) to allow this for `Model` already. This PR just extends to guard condition to account for possibility Document is the base class. If  that didn't already exist I wouldn't PR this, but since it exists may as well account for Document too, in case people do that, and for consistency.
**Examples**
Something like this:
```
export class MyResourceMethods extends Document
{
delete() {
return this.remove();
}
async ping() {
await this.updateOne({ $inc: { pingCount: 1 } });
return { modified: true };
}
...
}
```
If you …

Add guard to stop loadClass copying Document if Document is used as base of loaded class (same hack as implemented for Model already).

---

lib/helpers/populate/createPopulateQueryFilter.js
test/model.populate.test.js

Fix #12834
**Summary**
#12834 points out that `match` on `_id` overwrites rather than merges. Which is not a very good API design, because any custom `match` that specifies `_id` will overwrite the `_id` filter specified by `populate()`. This PR fixes that.
**Examples**

fix(populate): merge instead of overwrite when `match` is on `_id`

---

test/types/queries.test.ts
types/query.d.ts

This PR sets type safety `returnDocument` type as `'before' | 'after'` instead of accepting any `string`.

types(query):  `returnDocument` type safety

---

test/types/lean.test.ts
types/index.d.ts

types(lean): added omit for `ArraySubdocument` type in `LeanType` declaration

---

lib/cast.js
test/docs/cast.test.js

**Summary**
with `strictQuery true`, a query likes:
```js
{$or: [{notInSchema: 'any'}, {age: {$gt: 18}}]}
```
will become
```js
{$or: [{}, {age: {$gt: 18}}]}
```
and `{}` will match every documents
this pull will 
+ remove empty object `{}` from conditions
then 
+ if conditions is an empty array, remove it

fix(cast): remove empty conditions after strict applied

---

docs/schematypes.md

fix #12885
**Summary**
I removed the dead link to `openifyit-mongoose-types` repo (no longer existing/maintained) and applied a minor fix to formatting.

docs(schematypes): removed dead link and fixed formatting

---

docs/tutorials/lean.md

This PR fixes a broken link in the docs.
Expected: https://mongoosejs.com/docs/api.html#query_Query-lean
Actual: https://mongoosejs.com/docs/query.html#query_Query-lean

docs: fix link to lean api

---

test/collection.capped.test.js
test/collection.test.js
test/connection.test.js
test/docs/cast.test.js
test/docs/date.test.js
test/docs/debug.test.js
test/docs/findoneandupdate.test.js
test/docs/getters-setters.test.js
test/docs/lean.test.js
test/docs/virtuals.test.js
test/helpers/clone.test.js
test/helpers/indexes.getRelatedIndexes.test.js
test/helpers/indexes.isIndexEqual.test.js
test/helpers/isMongooseObject.test.js
test/helpers/isSimpleValidator.test.js
test/helpers/populate.getSchemaTypes.test.js
test/helpers/populate.getVirtual.test.js
test/helpers/projection.applyProjection.test.js
test/index.test.js
test/model.test.js
test/query.middleware.test.js

**Summary**
This PR updates some tests / test files to close all connections that were opened, also changes some test files to be working stand-alone
though i am not really proud of some of the connection caching done with `connectionsToClose`
some more detailed notes:
- all test files *except* `connection.test.js` and `index.test.js` have been updated with `connectionsToClose` or a simple `mongoose.disconnect` instead of not closing the connections
- some spaces have been added between some tests
- many `test/helpers` test files have been updated to work when tested stand-alone (only testing a single test file)
- change some import order in `test/helpers` to be consistent across `test/helpers` test files
- some tests have been updated to use the existing connection instead of creating a …

Close all connections in all tests, also change some tests to be working stand-alone

---

test/types/schema.test.ts
types/inferschematype.d.ts

**Summary**
Fix #12882.
The key insight here is that arrays of scalars and arrays of objects have different type inference logic. For example:
1. `type: [{type: String, required: true}]` is an array of strings.
2. `type: [{type: "String", required: true}]` is also an array of strings.
3. `type: [{type: {foo: {type: String}, required: true}]` is an array of objects that contains a field named `type`. Note here that `type` must be interpreted as a real key, not a type key. 
So if we have an array, we need to check if it's an array of scalars or objects. This is done as follows:
1. If the object has a type key that isn't callable and isn't a string, it's an object, so we need to call `ObtainDocumentType` to make sure that its keys are interpreted correctly. (i.e. if the object has a key …

Correctly infer types on document arrays

---

lib/drivers/node-mongodb-native/collection.js
test/connection.test.js

**Summary**
If you create a new model while Mongoose is disconnected, and `bufferCommands` is false, you'll get the following error:
```
MongooseError: Cannot call `tests.findOne()` before initial connection is complete if `bufferCommands = false`. Make sure you `await mongoose.connect()` if you have `bufferCommands = false`.
```
That is unexpected. You should never get that error after calling `mongoose.connect()`, even with `bufferCommands` disabled.
**Examples**

fix(collection): handle creating model when connection disconnected with bufferCommands = false

---

docs/migrating_to_7.md
lib/cast.js
lib/helpers/query/castFilterPath.js
lib/helpers/query/castUpdate.js
lib/helpers/update/castArrayFilters.js
lib/schema/SubdocumentPath.js
lib/schema/array.js
lib/schema/boolean.js
lib/schema/buffer.js
lib/schema/date.js
lib/schema/mixed.js
lib/schema/number.js
lib/schema/operators/geospatial.js
lib/schema/string.js
lib/schema/uuid.js
lib/schematype.js
test/model.query.casting.test.js
test/model.querying.test.js
test/types.number.test.js

Fix #12914
**Summary**
We created the `castForQueryWrapper` abstraction in https://github.com/Automattic/mongoose/commit/69e286a831d885533380e69e6fff3e93318c6cb9 to avoid potentially breaking custom schematype implementations by adding a 3rd param, because `castForQuery()` historically has relied on checking argument length to check if `$conditional` is set or not. But the castForQueryWrapper abstraction is a bit messy and makes it hard to write custom schematypes.
With this PR, `castForQuery()` now always takes 3 arguments, including the context. And, if you don't want to specify `$conditional`, you should pass null.
**Examples**

BREAKING CHANGE: remove castForQueryWrapper and _castForQuery on schematype, make castForQuery not rely on $conditional being optional

---

lib/cast.js
lib/schema/array.js
test/query.test.js
test/schema.test.js

Fix #12902
Re: #12909
**Summary**
A more complete fix for #12902 than #12909. I also added the suggestion from #12909, but better to also fix the underlying issue, which is that we aren't correctly passing the Query as context when casting a `$elemMatch`.
**Examples**

fix(query): correctly pass context when casting `$elemMatch`

---

test/aggregate.test.js

**Summary**
This PR increases the timeout for a `beforeEach` hook to 4 seconds (from a default of 2 seconds), in the hopes that test fail less with `Error: Timeout of 2000ms exceeded.`
see https://github.com/hasezoey/mongoose/actions/runs/3989840214/jobs/6842753284 as example

test(aggregate): increase timeout for a "beforeEach" hook

---

lib/cursor/ChangeStream.js
test/collection.capped.test.js
test/collection.test.js
test/connection.test.js
test/model.test.js
test/model.watch.test.js
test/query.middleware.test.js

**Summary**
Applied some suggestions from #12890. Mostly getting rid of unnecessary `connectionsToClose` - left it in one case where it makes sense. Also refactored out some `Model.watch()` cases, and fixed a potential bug due to the MongoDB node driver continuing to poll after change stream is closed.
**Examples**

test: some cleanup re: #12890

---

docs/migrating_to_7.md

**Summary**
This PR fixes some things for `migrate_to_7.md`:
- change `strictQuery` change to use code-tags instead of markdown-code symbols
- change `castForQueryWrapper` to use proper code start and end
- change `castForQueryWrapper` TOC entry to use the correct heading id

docs(migrate_to_7): fix some styles

---

test/types/models.test.ts
test/types/queries.test.ts
test/types/schema.test.ts
types/inferschematype.d.ts

**Summary**
Probably best to defer the change from #12781 until our 7.0 release. The change seemed easy enough, but then we got bit by test failures in master that we didn't notice until after we merged our PR for 6.9. This change may require users to update method return signatures and do other additional work, so it is likely a bit too big of a change for a minor release.
**Examples**

Revert "typescript: Allow null for optional document fields"

---

lib/document.js
test/document.test.js

fix(document): isModified should not be triggered when setting a nested boolean to the same value as previosly

---

lib/connection.js
lib/index.js
test/connection.test.js

fix #12966
**Summary**
Added `nextConnectionId` counter to keep track of auto-increment IDs for new connections.

fix(connection): handles unique autoincrement ID for connections

---

lib/aggregate.js
types/aggregate.d.ts
types/pipelinestage.d.ts

**Summary**
The current input parameter type for `near` aggregation operator does not reflect what MongoDB actually supports since version `4.0` (https://www.mongodb.com/docs/v4.0/reference/operator/aggregation/geoNear/). `4.0` is minimum supported version by Mongoose `^6.0.0` (https://mongoosejs.com/docs/compatibility.html).
I've switched to the correct (already existing) interface, removed `uniqueDocs` property (which has no effect since MongoDB `2.6`) and added `num` property supported in MongoDB `4.0.x` but removed in `4.2`.
**Examples**
Without these changes, I cannot, for example, use GeoJSON point:

Fix "near" aggregation operator input type

---

test/types/expressions.test.ts
types/expressions.d.ts

types(expressions): added missing Top operator to `AccumulatorOperator` type declaration

---

lib/query.js
test/model.update.test.js

**Summary**
Mongoose requires unique model names, so to avoid conflicts when using discriminators, you use 3 parameter syntax: `model.discriminator(modelName, schema, discriminatorKeyValue)`.
When updating a document using e.g. `updateOne`, you're allowed to change discriminator key value when you provide `overwriteDiscriminatorKey`.
But the code responsible for updating the discriminator type was relying on `modelName` being equal to `discriminatorKeyValue`, which may not be the case if you use custom model name for your discriminator.
`Schema.discriminators` are indexed by model name and the code was using update value for `discriminatorKey`.
**Examples**
I modified an existing test to make it fail, then fixed it.
I'm not sure if I should keep the original test as is and add a new one, …

Fix discriminator type field update for custom discriminator model name

---

docs/transactions.md
test/docs/transactions.test.js

fix #12934
**Summary**
Added an example substituting the broken link in the `Connection.transaction()` method documentation and removed an empty first line from the `withTransaction` method example.

docs(transactions): added example for `Connection.transaction()` method

---

lib/schema.js
test/schema.test.js

feat: added `Schema.prototype.omit()` function

---

test/types/models.test.ts
types/aggregate.d.ts
types/models.d.ts

**Summary**
This change adjusts the type of the `options` parameter of `Model.aggregate` to be the `AggregateOptions` type from mongoose, instead of the one from mongodb. The aggregate method just passes this parameter on to `Aggregate.option`, which is already typed to accept the `AggregateOptions` type from mongoose, so this seems like the correct choice.
The 2 types mostly seem to be compatible anyways, but there is a small inconsistency that makes them incompatible: `mongodb.AggregateOptions` specifies that the `session` property may be a `ClientSession`, or `undefined` (but not `null`), while the `AggregateOptions` type from mongoose also allows `null`. So maybe that also should simply be aligned.

types(model): fix type of options of Model.aggregate

---

lib/helpers/document/applyDefaults.js
test/document.test.js

Fix #12905
**Summary**
If `applyDefaults()` creates a default underneath a single nested subdocument when loading from MongoDB, a subsequent `save()` won't save that default. This is a quick fix that handles that particular case. It won't handle nested subdocuments, or subdocuments underneath arrays, because that's proven to be a bit trickier. However, this PR should be enough to unblock OP from #12905 with minimal risk, and we can improve change tracking in this case later.
**Examples**

fix(document): save newly set defaults underneath single nested subdocuments

---

lib/types/array/methods/index.js
test/document.test.js

**Summary**
Looks like in Mongoose 6.0.0, our switch to using proxies for arrays broke some internal behavior for `$shift()`. The TLDR; is that `$shift()` mistakenly always becomes a `$set`, as opposed to a `$pop`, since 6.0.0. Which may have performance implications for large arrays.
This issue was happening because 1) setting `_shifted` on the array proxy triggers a `$set`, and 2) calling `shift()` on an array proxy also triggers a `$set`.
**Examples**

fix(document): make array `$shift()` use `$pop` instead of overwriting array

---

lib/query.js
test/query.test.js
types/query.d.ts

**Summary**
This PR removes the query option `snapshot`, which i could not find any documentation about it anymore (even for mongodb (db) 3.6), i could only find things for `readconcern: "snapshot"`
Note: this PR does not touch the read-concern option

feat(query): remove all references to option "snapshot"

---

docs/api.pug
docs/includes/nav.pug
docs/js/redirect-old-api.js
docs/layout.pug
docs/source/api.js
docs/source/index.js

**Summary**
This PR addresses #12217, with the approach of using a script to redirect based on the anchor
fixes #12217
**Note: This description was changed later, so the earlier comments might reference older information**

docs(api.pug): change to redirect to mongoose API page

---

test/model.test.js

**Summary**
This PR tries to fix the lint errors that are currently present in the 7.0 branch.
i am not quite sure when changes regarding `connectionsToClose` were made, but it seems some spots had been forgotten

test(model.test): dont use undefined array

---

lib/index.js
test/connection.test.js
types/mongooseoptions.d.ts

closes #12965
**Summary**
If explicitly set to `false` the `createInitialConnection` option will disable the creation of the default initial connection.

feat(index): added createInitialConnection option to Mongoose constructor

---

lib/helpers/query/castUpdate.js
test/query.test.js

closes #12930
**Summary**
As a result of [this](https://github.com/Automattic/mongoose/issues/12930#issuecomment-1416503984) conversation, #12797 introduced breaking changes.
This PR revert them (as well as the fix of #12826) to the previous behavior.
Update queries now do not remove fields set to `undefined`.

fix(query): revert breaking changes introduced by #12797

---

lib/error/index.js
test/model.populate.test.js
types/error.d.ts

**Summary**
Add and export `StrictPopulateError` class so it can be used by ts/esm modules
**Examples**
```javascript
import { MongooseError } from 'mongoose';
const err = new MongooseError.StrictPopulateError('test')
if(err instanceof MongooseError.StrictPopulateError){
// do something
}
```

chore: add strict populate as exported error

---

lib/schema/uuid.js
test/schema.uuid.test.js

schematype(UUID): added null check to prevent error on binaryToString conversion

---

package.json

**Summary**
According to https://www.mongodb.com/docs/drivers/node/current/whats-new/#what-s-new-in-4.14, `mongodb@4.13` has a memoryleak which is fixed in `mongodb@4.14`. Naturally they recommend to upgrade to 4.14
Other than that, the 4.14 version seems to only have "Deprecated methods and options that reference the legacy Logger." so the upgrade should be a no-brainer

Mongodb v4.13 Memoryleak fix

---

lib/query.js
test/query.test.js

Fix #12944
**Summary**
`find({ $and: [{ foo: 'bar' }] }).find({ $and: [{ foo: 'baz' }] })` currently overwrites instead of merges `$and`. This PR changes that, so chaining concatenates `$and`.
**Examples**

BREAKING CHANGE: merge `$and`, `$or` conditions in query filters

---

lib/model.js
test/docs/debug.test.js

fix(model): avoid sending null session option with document operations

---

docs/search.js
package.json
scripts/generateSearch.js

**Summary**
This PR aims to improve the search generation script, by doing:
- move the script from `/docs` to `/scripts` (because it is not a browser script)
- disconnect on error (had it hanging for me)
- add useful error when no config is found
- change to use `/docs/api/file.html` over `/docs/api.html` (re https://github.com/Automattic/mongoose/pull/12223#issuecomment-1428470684 & https://github.com/Automattic/mongoose/issues/13033)
- use `Object.entries` over creating a one-time use array
- disable `strictQuery` warning

Improve search generation script

---

.github/workflows/test.yml
lib/cursor/AggregationCursor.js
lib/cursor/QueryCursor.js
lib/utils.js
test/browser.test.js

**Summary**
This PR (commit: 9396dbbd5962532eeebc7aa18840f1f4a5af66bf) fixes gh-11943 in 5.x branch. It makes access to `process.versions` lazy (in a function, not at module level) and thus does not crash mongoose loaded in a browser.
This PR (commit: f9146a304339283bbb45aca63ad82baf1ad5c5f5) also contains an *attempt* to implement a test for this issue. Unfortunately it does not achieve the main goal. I haven't been able to mock/replace value of `process.versions` to mimic what is available in the browser. Whatever is written to it (or its properties) is lost and the original values are always returned.
I am open for any suggestion on how to achieve that and can work on the PR until it is good enough. I have checked that the main change fixes the issue in our project.
Also it includes a …

fix: (5.x) make access to `process.versions` lazy

---

lib/model.js
test/connection.test.js

fix #12940
**Summary**
Avoid usage of cached `createCollection` callback if `autoCreate` option value has changed.

fix(connection): disable createConnection buffering if autoCreate option is changed

---

lib/query.js

Fix #13050
**Summary**
Right now we always send `projection` option to the MongoDB server, even if `projection` is an empty object. This is a bit clunky for numerous reasons: perf, messy logs, etc. With this change, we won't send `projection` if it is an empty object.
**Examples**
No projections in below script:
```javascript
'use strict';
run().catch(err => console.log(err));
const schema = new mongoose.Schema({ name: String });
const Test = mongoose.model('Test', schema);
await Test.findOne();
await Test.find();
await Test.findOneAndUpdate({}, { name: 'bar' });
}
```

fix(query): avoid sending unnecessary empty projection to MongoDB server

---

docs/tutorials/getters-setters.md
test/docs/getters-setters.test.js

Fix #13049
**Summary**
Quick docs fix for #13049 
**Examples**

docs(getters-setters): explain that getters do not run by default on `toJSON()`

---

test/deno.js
test/docs/debug.test.js
test/model.test.js
test/types.subdocument.test.js

**Summary**
Fix #13061. Turns out there was some stale data in the 'tests' collection that this test was picking up, below is the doc:
```
Found <ref *1> model {
"$__": InternalCache {
activePaths: StateMachine { paths: { __v: "init" }, states: { init: [Object] } },
skipId: true,
getters: { _id: Document { first_name: [Getter/Setter], age: [Getter/Setter] } },
nestedPath: "_id",
[Symbol("mongoose#Document#scope")]: [Circular *1]
},
"$isNew": false,
_doc: {
_id: ObjectId {
[Symbol(id)]: Buffer(12) [
99, 244, 221, 196,  76,
238,  72, 239,  52, 185,
255, 124
]
},
doc_embed: {},
subArray: [ { testString: "Test 2", _id: [Object] } ],
createdAt: 2023-02-21T15:05:40.101Z,
updatedAt: 2023-02-21T15:05:40.115Z,
__v: 0
}
}
```
Looks like this is due to `types.subdocument.test.js` not properly …

Fix Deno tests

---

docs/middleware.md

Re: #12680
**Summary**
#12680 pointed out that we don't list 'validate' as a potential query middleware. This fixes the docs. Below is an example of using query middleware for `validate()`
```javascript
'use strict';
const schema = new mongoose.Schema({ name: String });
schema.pre('validate', () => {
console.log('Regular pre validate');
});
schema.pre('validate', { query: true, document: false }, () => {
console.log('Pre query validate');
});
const Test = mongoose.model('Test', schema);
run().catch(err => console.log(err));
const doc = new Test();
await doc.validate();
console.log('----');
await Test.updateOne({}, { name: 'bar' }).setOptions({ runValidators: true });
} …
```

docs(middleware): list `validate` as a potential query middleware

---

docs/migrating_to_5.md

**Summary**
This PR fixes usage of code in headers and removes a extra curly bracket in a code example

Fix code in headers for `migrating_to_5`

---

docs/migrating_to_6.md

docs(migrating_to_6): added info about removal of reconnectTries and reconnectInterval options

---

docs/populate.md

**Summary**
This PR fixes some things for the `populate` documentation:
- Add missing TOC entry
- fix usage of markdown inline code-blocks inside html tags
- add code-blocks around `limit-vs-perDocumentLimit` header

docs: fix populate docs

---

docs/migrating_to_6.md
docs/populate.md
lib/schematype.js

**Summary**
This PR backports some (mainly) documentation changes for 6.x that are already in master (7.0), includes changes from:
- #13090
- #13084 
- #13083

Backport some documentation changes into 6.x

---

test/types/mongo.test.ts
types/index.d.ts

**Summary**
Mongoose exposes its underlying `mongodb` import via the `mongo` export. However, if you use `import * as mongoose from 'mongoose'` syntax then `mongoose.mongo.X` becomes untyped. By using an alias export instead, the types are preserved, even when importing like that.
**Examples**
See the test I added.

fix: export mongodb types more robustly

---

lib/schema/uuid.js
test/schema.validation.test.js

closes #12991
**Summary**
Added conversion of buffered `UUID` values to pass the `checkRequired` test.

fix(schematype): fixed validation for required UUID field

---

lib/model.js

The official documentation was not updated, it shows that Model.findOne() uses callback, which is not accepted now.
The Change updates the document with updated method for Model.findOne().
fixes #13095

Doc: Updated callback method for Model.findOne()

---

test/types/populate.test.ts
types/models.d.ts

It wasn't yelling at me.
Also, while working on this issue I noticed the populate section is more focused on query population than calling `Model.populate()`. Maybe we should include a small section about that function since we have a section titled `Populate` in the docs.

Add Path generic

---

types/query.d.ts

**Summary**
This PR removes the function `update` from the query types, because it has been removed for 7.0 in runtime
re #12955
re #13039

fix(types/query): remove "update" function

---

.eslintrc.json
.npmignore
test/types/document.test.ts
types/index.d.ts

Fix #13094
**Summary**
I applied @hasezoey 's suggested fix for #13094. We can avoid `Record<string, never>` as a special case, because the only value that matches that is empty object `{}`. But avoiding `Record<string, any>` or `Record<string, unknown>` is hard because it seems like _any_ object extends from `Record<string, any>`, and there's no good way to check if a type is a record type, or at least if a type is an object with known keys.
I'm open to suggestions for better ways to fix this. But this should be enough to unblock.
**Examples**

fix(types): handle `Record<string, never>` as value for HydratedDocument TOverrides parameter

---

package.json

@vkarpov15 I think the bump to node 14 minimum was accidental, this reverts mongoose 6.x to still be supported on node 12.
**Examples**

6.x should still support node 12

---

lib/schema/documentarray.js
test/types.documentarray.test.js

Fix #12997
**Summary**
We made some changes in https://github.com/Automattic/mongoose/issues/9811 to support modified paths when you have a map of subdocuments, but looks like those changes weren't correctly applied to maps of document arrays. This PR fixes that.
**Examples**

fix(documentarray): set correct document array path if making map of document arrays

---

.github/workflows/test.yml

**Summary**
This PR updates the github actions to not use `ubuntu-18.04` anymore, because github will remove support for this
this change may need to be backported if lower versions are still meant to be supported (like 6.x or 5.x)

Update github actions to not use `ubuntu-18.04` anymore

---

lib/helpers/document/applyDefaults.js
test/docs/debug.test.js
test/document.test.js

Fix #13003
**Summary**
Without this fix, `applyDefaults()` thinks it needs to apply defaults to all sibling properties of `properties.foo` when the projection is `{ 'properties.foo': 1 }`
**Examples**

fix(document): avoid setting array default if document array projected out by sibling projection

---

docs/layout.pug

**Summary**
This PR provides a quick fix for using the correct version path in the sidebar, a similar fix as was applied to 5.x.
Also adds a new 7.x version entry (like was done on 5.x with 6.x)
Downside is that this makes it not display correctly when running locally (via `docs:view`).
fixes #13144

[6.x] docs: quick fix to work with new subpath

---

test/types/querycursor.test.ts
types/cursor.d.ts

**Summary**
Fix for https://github.com/Automattic/mongoose/issues/13152
**Examples**

fix(document): add index param to eachAsync fn

---

test/types/queries.test.ts
types/query.d.ts

Changed the `lean` attribute of `QueryOptions` to `boolean | Record<string, any>` to allow correct inference on a query return type.
closes #13142

type(query): changed `QueryOptions` lean type to `Record<string, any>`

---

lib/connection.js

Fix #12971
**Summary**
Quick detail that shouldn't affect any prod code. But #12971 does point out that our base connection class doesn't have a `doClose()` method, but calls `this.doClose()`. The built-in MongoDB driver layer does have a `doClose()`, but there's no indication to anyone building a new driver that they need to implement that, and if you instantiate a new connection directly (which you shouldn't do) you'll get an error about `doClose()` not being a function.
**Examples**

fix(connection): add stub implementation of `doClose` to base connection class

---

test/types/querycursor.test.ts
types/cursor.d.ts

**Summary**
This PR is a backport of #13153 for 6.x
fixes #13152

[6.x] add `cursor.eachAsync` index parameter

---

scripts/generateSearch.js

This PR moves the Error message that was added in 0b7bbbbc23a2b79fb05defaef27f91efc54398bb to the require, where the actual error gets thrown if the config does not exist.
also adds a message on how much content was added.

chore(generateSearch): move config missing error to require

---

scripts/generateSearch.js

**Summary**
This PR fixes the search generation not including API documentation for 7.x, it was broken because of #12223 and the search script only using the `api.html` entry
Note version 5 and 6 are not affected

fix(generateSearch): fix search generation for API

---

test/types/docArray.test.ts
types/types.d.ts

Changed `DocumentArray` constructor parameter type from `any[]` to `(T & AnyObject)[]`.
closes #13087

types(documentarray): typed DocumentArray constructor parameter

---

lib/document.js
test/document.test.js

Fix #13158
**Summary**
Document.prototype.$inc() doesn't call setters right now, which is a little strange given that `findOneAndUpdate()` with `$inc` does call setters.
The biggest wrinkle here is that we're calling setters on the _resulting value_, not the value passed in to `$inc`. So `$inc('balance', 4)` will call setters with `balance = 6 + 4` if `balance` was originally 6. I think this is slightly better because setters are often used for rounding, and we want to make sure devs that are using `$inc()` instead of `+=` don't run into unexpected binary floating point precision issues.
**Examples**

fix(document): apply setters on resulting value when calling Document.prototype.$inc()

---

lib/model.js
test/model.test.js
test/types/models.test.ts
types/models.d.ts

Fix #12791
**Summary**
#12791 pointed out that it is still very tricky to figure out exactly which documents were inserted if you're using `insertMany()` with `ordered: false`. That's because the document can either 1) fail Mongoose validation, 2) fail because of a MongoDB server error, 3) succeed. And the results for (1), (2), and (3) are all in separate properties, which means you need to do some stitching to figure out exactly what happened with a particular document.
With this PR, if there were any errors, there will be a `results` property on the error (or `res.mongoose.results` if you're using `rawResult: true`) that contains an array which has either 1) the document if the document was successfully inserted, 2) the MongoDB write error if the write failed, 3) the Mongoose validation …

fix(model): add `results` property to unordered `insertMany()` to make it easy to identify exactly which documents were inserted

---

test/types/docArray.test.ts
types/types.d.ts

**Summary**
As a result of [this feedback](https://github.com/Automattic/mongoose/issues/13087#issuecomment-1470729163), fixes the bug introduced by #13089 changing the type of `DocumentArray` constructor's parameter to `AnyObject[]`.
Closes #13087

types(documentarray): fixed type of DocumentArray constructor parameter

---

.github/workflows/stale.yml

**Summary**
This PR updates the stale close message, because it is not actually "19 days since stale label" but "19 days since no activity"
Example: https://github.com/Automattic/mongoose/issues/13017#issuecomment-1475044901

chore(workflows/stale): update close message

---

lib/helpers/timestamps/setupTimestamps.js
test/timestamps.test.js

Re: #9951
Re: #13170
**Summary**
I noticed when working on #13170 that the fix for #9951 only applies to `findOneAndReplace()`, not `replaceOne()`.
**Examples**

fix(timestamps): set timestamps on empty `replaceOne()`

---

lib/schema.js
test/model.populate.test.js

Fix #13189
Re: #8210
Re: #8198
**Summary**
Apply the fix for #8198 to single nested subdocuments, as opposed to just arrays. That looks like it fixes #13189, which highlights the same underlying issue as #8210.
**Examples**

fix(schema): make creating top-level virtual underneath subdocument equivalent to creating virtual on the subdocument

---

test/types/models.test.ts
types/models.d.ts

**Summary**
You can now specify the custom type for the top-level document returned in a `change` event.
This aligns with the changes introduced in [MongoDB 4.6.0](https://github.com/mongodb/node-mongodb-native/releases/tag/v4.6.0).
**Example**
```
TestModel.watch<ITest, ChangeStreamInsertDocument<ITest>>([]).on('change', (change) => {
console.log(change.fullDocument); // TS won't complain
});
```
Closes #13206

types(model): aligned `watch()` type for mongodb 4.6.0

---

benchmarks/get.js
lib/document.js
lib/helpers/document/compile.js
lib/schema.js
test/deno.js
test/virtualtype.test.js

**Summary**
`doc.myProp` does a lot of unnecessary string manipulation and comparisons. This PR trims off a bunch of the unnecessary work.
Before:
```
$ node ./benchmarks/get.js 
{
"Model loop ms": 2011,
"POJO loop ms": 7
}
```
After:
```
$ node ./benchmarks/get.js 
{
"Model loop ms": 206,
"POJO loop ms": 8
}
```
Not really sure how much faster we can make this, Mongoose will always be slower than a plain old property access because we need to support getters, etc. 
**Examples**

Speed up get on top-level properties by 10x

---

lib/schema.js
test/model.populate.test.js
test/schema.test.js

Fix #13085
**Summary**
`removeVirtual()` still leaves a dangling reference to the virtual type, this PR fixes that. With this fix, #13085 can correctly redeclare virtuals.
**Examples**

fix(schema): fix dangling reference to virtual in `tree` after `removeVirtual()`

---

lib/model.js
test/model.test.js
types/models.d.ts

Fix #13176
**Summary**
Make the `bulkWrite()` API more consistent with `insertMany()`:
If `ordered: false`, validate all write operations, and strip out any invalid ones. Execute the valid operations.
1. If remaining operations succeed, add `mongoose.validationErrors` to result to indicate which operations failed validation.
2. If remaining operations failed, add `mongoose.validationErrors` to the error to indicate which operations failed validation.
I'm not thrilled with the fact that `bulkWrite()` doesn't throw an error if some operations failed validation, but that is consistent with how `insertMany()` works. And I'd prefer to maintain consistency, and consider changing the API for the next major release. What do you think @hasezoey ?
**Examples**

fix(model): execute valid write operations if calling `bulkWrite()` with ordered: false

---

.github/workflows/test.yml
test/deno.js

**Summary**
This PR updates the used deno version to 1.32, because 1.32.2 got a port of `node:zlib` implemented in rust (rather than a polyfill?), because it often resulted in `Error during unzip for /binary/mongodb-linux-x86_64-ubuntu2004-6.0.0.tgz: Error: incorrect header check`
hopefully this fixes this problem for deno
[Example run](https://github.com/hasezoey/mongoose/actions/runs/4631765108/jobs/8195024293)

chore(workflows/test): update deno version to 1.32

---

scripts/generateSearch.js

**Summary**
Re: [this comment](https://github.com/mongoosejs/backend/commit/378f7e27a2ae2379260047febddd699fe479c67a#r108335721), looks like our search backend isn't using Atlas search correctly. Unfortunately with the current `version` property being a string, we get the following error: `MongoServerError: "compound.must[0].equals.value" must be a boolean, objectId, number, or date` . Looks like there's no way for `$search` with `equals` to compare strings. So I added a `versionNumber` property.
We'll get rid of the `Content` model/s `version` property once we've merged the search changes and confirmed no issues.
**Examples**

chore: add `versionNumber` property to docs content for search

---

test/types/schema.test.ts
types/index.d.ts
types/inferschematype.d.ts

Fix #13129
**Summary**
Looks like the `Omit<>` trick we did to avoid TS complaining about circular constraints doesn't work if you set the `incremental` option in TypeScript 4.9+. With this change `TSchemaOptions` no longer references itself, so no more circular constraints. We just wrap `TSchemaOptions` in `ResolveSchemaOptions` whenever we use it in the schema class.
I wish there was some reasonable way to test this, but the issue doesn't seem to show up in tsd, so our only option would be to manually run a particular version of tsc with `--incremental` on a script. And I don't think that's necessary, seems easy enough to eyeball that this particular change removes the circular constraint.
**Examples**

types(schema): avoid circular constraint in TSchemaOptions with --incremental by deferring `ResolveSchemaOptions<>`

---

lib/model.js
test/document.test.js
test/model.test.js

Use `collection.findOne()` for saving docs with no changes

---

docs/migrating_to_7.md
lib/schema.js

Island rhythms/add promise docs

---

lib/model.js
test/model.test.js

**Summary**
This allows specifying that a schema's collection should be created as a [clustered collection](https://www.mongodb.com/docs/manual/core/clustered-collections/).
**Examples**
```js
const schema = Schema(
{ 
name: String 
},
{ 
clusteredIndex: { 
key: { _id: 1 }
}
}
);
```

add clusteredIndex to schema options

---

docs/subdocs.md

**Summary**
This PR updates the section `Removing Subdocs` in `subdocs.md` to use `deleteOne` instead of `remove`, because for 7.0 the `remove` function was renamed `deleteOne`
fix #13297

docs(subdocs): fix mention of subdocument ".remove" function

---

lib/connection.js
lib/error/createCollectionsError.js
lib/model.js
test/connection.test.js

feat: implement `createCollections()`

---

docs/css/mongoose5.css
docs/layout.pug

**Summary**
This PR (mainly) updates the documentation side-bar to be better use-able, things include:
- replace `span` hamburger menu-hack with a svg
- change the container element for `#menu > .pure-menu` to be a `nav` instead of implicit `div`
- change sub-lists to be their own lists (plus css changes necessary)
- show indications of what element in the side-bar is currently hovered over (and use the same effect for the current page)
- change the mobile-menu (logo) header and sidebar to be sticky / fixed, so it can be accessed at any scroll level
re #13314
<details>
<summary>Screenshots</summary>
old active & hover:
new active & hover:
old mobile + scroll:
new mobile + scroll:
</details>
PS: these changes should make it easier to change the lists (secondary & tertiary lists) to be made …

Update website sidebar to be better use-able

---

docs/source/api.js
docs/source/index.js
docs/source/utils.js
scripts/website.js

**Summary**
This PR changes the documentation to be able to re-load the api js file to reflect any changes, previously api would be reload-able, but the reload would not reflect any changes from the original js file, only if the pug files were changed
in more detail:
- changes the `parse` function in `docs/source/api` to be in 3 different functions:
- process the properties `processFile`
- load a file with dox and process file `parseFile`
- load and process all defined files `parseAllFiles`
- removes the global storage of the raw js parsed js files in `docs/source/api` (because it only needs to be loaded once and on reload would need to reload the anyway)
- update `scripts/website` to be able to use the reload function
- fix a accidental wrong type import in `docs/source/utils.js` from a …

[Docs] reload api js files on change

---

benchmarks/mapOfSubdocs.js
lib/document.js
lib/types/map.js
test/types.map.test.js

**Summary**
Re: #13191, #13271.
Benchmark from #13191 with 2000 documents, before this change:
```
Starting the process of mapping all minis and timing it
Iterating through all minis: 5.661ms
Sorting all minis: 1.368ms
Creating and populating Map of Minis: 0.4ms
Saving Map of Minis to MongoDB using Mongoose: 1.684s
Map Process: 1.692s
Saved Minis Map successfully!
```
After:
```
Starting the process of mapping all minis and timing it
Iterating through all minis: 6.554ms
Sorting all minis: 1.872ms
Creating and populating Map of Minis: 0.555ms
Saving Map of Minis to MongoDB using Mongoose: 315.028ms
Map Process: 324.444ms
Saved Minis Map successfully!
```
I would love to make this faster and will work on it some more, as well as adding a benchmark for this, but figured I'd add a PR first. …

perf: speed up creating maps of subdocuments

---

lib/error/objectParameter.js
lib/query.js
test/model.findOneAndUpdate.test.js

Fix #13264
**Summary**
As #13264 pointed out, most of our query methods, like `find()`, `deleteOne()`, etc. error out if the `filter` isn't an object. But `findOneAndUpdate()`, `findOneAndReplace()`, and `findOneAndDelete()` do not. This PR fixes that issue.
**Examples**

fix(query): set ObjectParameterError if calling `findOneAndX()` with filter as non-object

---

.github/workflows/test.yml
test/deno.js
test/mocha-fixtures.js

**Summary**
@hasezoey FYI, I'm temporarily removing mongodb memory server from deno tests on 6.x branch because we've been experiencing some weird test failures, see:
1. Error 1: https://github.com/Automattic/mongoose/actions/runs/4853799889/jobs/8650382091
2. Error 2: https://github.com/Automattic/mongoose/actions/runs/4853740990/jobs/8650256294
I'd like to bring mongodb memory server back as soon as we can, but right now these test failures are blocking releasing 6.11.
**Examples**

Temporarily remove mongodb memory server from deno tests on 6.x

---

test/types/lean.test.ts
types/index.d.ts

Closes https://github.com/Automattic/mongoose/issues/13345
**Summary**
Since 7.1.0, `lean()` replaces `Map` in documents with their `Record<string, V>` equivalent by using `FlattenMaps`. Currently, `FlattenMaps` returns a type incompatible with `InferSchemaType` type when there is a property of `DocumentArray` type. This PR fixes it.
**Examples**
This won't produce compilation error:
```ts
import { model, Schema, InferSchemaType } from 'mongoose';
import { expectType } from 'tsd';
async function test() {
const imageSchema = new Schema({
url: { required: true, type: String }
});
const placeSchema = new Schema({
images: { required: true, type: [imageSchema] },
});
type Place = InferSchemaType<typeof placeSchema>;
const PlaceModel = model('Place', placeSchema);
const place = await …
```

Handle `DocumentArray` in `FlattenMaps`

---

docs/layout.pug

**Summary**
This PR fixes `Schemas` entry in the documentation sidebar not being highlighted while being on the page
re #13314

docs(layout): fix "Schemas" not being highlighted when currently on page

---

test/types/lean.test.ts
types/index.d.ts

**Summary**
Complements PR https://github.com/Automattic/mongoose/pull/13346 (issue https://github.com/Automattic/mongoose/issues/13345) by proper handling of union types (for example, `Types.DocumentArray | undefined` when property is optional).

Handle union types in `FlattenMaps`

---

.github/workflows/test.yml
test/.eslintrc.yml
test/deno.js
test/deno_mocha.js
test/mocha-fixtures.js

**Summary**
This PR changes the deno test to start the fixtures before mocha and to start mocha in a child-process, to workaround the issue about connections still being open at the end of the test suite
only downsides are that deno permissions will have to be set via the `args` array in the code now, because i dont know of a way to start a child deno process with the same permissions
re https://github.com/Automattic/mongoose/pull/13349#issuecomment-1531194531
also reverts #13349
PS: this is basically just a workaround, not fixing the actual issue

chore(deno): change to start mocha fixtures before mocha

---

test/types/document.test.ts
types/document.d.ts

Fix #13223
**Summary**
As implemented, `doc.deleteOne()` returns a promise, not a query. We could either update the `deleteOne()` implementation to match `updateOne()`, which _does_ return a query; or we update the TypeScript types. I think changing the TS types is the way to go, because it is less backwards breaking. But we should consider changing `doc.deleteOne()` to return a query in the next major release.
**Examples**

types(document): correct return type for `Model.prototype.deleteOne()`: promise, not query

---

package.json

**Summary**
This PR updates the engine-node version to match what mongodb has defined, because otherwise mongoose says to support a lower version than a library it uses
https://github.com/mongodb/node-mongodb-native/blob/ce8e69b6db0eb4c0b9271ce43e334d70b967d227/package.json#L102

chore: update node engine version to match mongodb's minimal

---

lib/query.js
test/model.findOneAndReplace.test.js
test/query.test.js

Fix #13340
**Summary**
Looks like this issue was introduced in https://github.com/Automattic/mongoose/pull/13059 . In order to correctly apply schema level projection, you need to call `this._applyPaths()`, and it looks like with #13059 `findOneAndReplace()` no longer calls `this._applyPaths()`.
With this change, we _only_ handle creating projection logic in `optionsForExec()`. Individual thunks are no longer responsible for calling `applyPaths()`, etc.
**Examples**

fix(query): apply schema-level paths before calculating projection for findOneAndUpdate()

---

test/types/models.test.ts
types/models.d.ts

**Summary**
This PR modifies `Model.bulkWrite` to be overwrite-able and not be strict by default (i am not quite sure if it is wanted)
this changes `bulkWrite` to be more in-line with functions like `create` & `insertMany`

fix(types): change "bulkWrite" to not be strict by default and allow overwriting

---

lib/connection.js
lib/helpers/processConnectionOptions.js
test/connection.test.js

fix: don't modify passed options object

---

lib/helpers/timestamps/setupTimestamps.js
lib/query.js
test/model.findOneAndReplace.test.js

**Summary**
`overwrite` and `timestamps` aren't supported options on the MongoDB server, they're internal to Mongoose, so they should be stored under `_mongooseOptions`. Removing these options makes debug output cleaner and improves perf slightly.
**Examples**

fix(query+timestamps): avoid sending `overwrite` and `timestamps` options to MongoDB

---

docs/jest.md
lib/helpers/printJestWarning.js

**Summary**
Give people a way to hide Jest warnings without disabling the potentially problematic Jest features. Unfortunately I don't see a better way to do this than environment variables, but I'm open to a better alternative.
Fix #13373 
**Examples**

Add SUPPRESS_JEST_WARNINGS environment variable to hide jest warnings

---

lib/document.js
test/document.test.js

Re: #13327
**Summary**
Part 2 of #13327 points out that `doc.set('c.x.y', 1)` doesn't work if `c` is a map of mixed. Turns out that 1) Mongoose doesn't pick up map of mixed, and 2) Mongoose doesn't handle creating objects correctly when doing a deep set underneath a map. This PR fixes both of those.
**Examples**

fix(document): handle set() from top-level underneath a map of mixed

---

lib/document.js
lib/helpers/clone.js
test/document.test.js
types/index.d.ts

Fix #13341
Re: #2790
**Summary**
See discussion from #13341. TLDR; `toObject({ flattenObjectIds: true })` will return an object with all ObjectIds converted to strings. There are a couple of ways to do this with Mongoose, but the other alternatives aren't sufficiently fine-grained: `JSON.parse(JSON.stringify(doc))` will JSON-ify everything, `mongoose.ObjectId.set('transform', v => v.toString())` will apply this behavior to every `toObject()` call, etc.
**Examples**

feat(document): add flattenObjectIds option to toObject() and toJSON()

---

types/document.d.ts

```js
/**
* Alias for `set()`, used internally to avoid conflicts *
* @param {String|Object} path path or object of key/vals to set
* @param {Any} val the value to set
* @param {Schema|String|Number|Buffer|*} [type] optionally specify a type for "on-the-fly" attributes
* @param {Object} [options] optionally specify options that modify the behavior of the set
* @param {Boolean} [options.merge=false] if true, setting a [nested path](/docs/subdocs.html#subdocuments-versus-nested-paths) will merge existing values rather than overwrite the whole object. So `doc.set('nested', { a: 1, b: 2 })` becomes `doc.set('nested.a', 1); doc.set('nested.b', 2);`
* @return {Document} this
* @method $set
* @memberOf Document
* @instance
* @api public */
```
**Summary**
**Examples**

Update document.d.ts set function params

---

test/types/lean.test.ts
types/models.d.ts
types/query.d.ts

Fix #13382
**Summary**
Doing `Model.updateOne().lean()` returns an incorrect type: has `_id`, etc. With this change, queries now have a `QueryOp` generic that they can use to check the current query op. With this change, `Model.deleteOne().lean()`, etc. all reflect their runtime behavior: `lean()` is a no-op.
**Examples**

types: make `lean()` not clobber result type for `updateOne()`, etc.

---

lib/model.js
lib/query.js
lib/validoptions.js
test/document.test.js
test/query.test.js
types/mongooseoptions.d.ts
types/query.d.ts

Fix #7511
Fix #8678
**Summary**
Add `translateAliases` option on query, schema, and global level to apply `Model.translateAliases()` on all query fields automatically: `filter`, `projection`, `update`, and `distinct`.
**Examples**

feat(query): add `translateAliases` option to automatically call translate aliases on query fields

---

docs/guide.md

Passing {virtuals: true} to toObject does not have the same effect as toJSON{ vrituals: true} Tested on Ubuntu 22.04 and Windows 10 using version "^6.9.2"
Can be replicated with the following model file:
```
const postSchema = new Schema(
{
text: String,
username: String,
comments: [{ type: Schema.Types.ObjectId, ref: 'comment' }],
},
{
// replace with toJSON to revert to correct behavior
toObject: {
virtuals: true,
},
}
);
postSchema.virtual('commentCount').get(function () {
return this.comments.length;
});
// Initialize our Post model
const Post = model('post', postSchema);
```
Please correct if I'm using this code erroneously
**Summary**
Documentation directly states including virtuals can be achieved via the same process for both toJSON and toObject but `{ virtuals: true }` has no …

Remove direction to include virutals in toObject

---

index.js
lib/index.js
types/error.d.ts

**Summary**
Exports the class `MongooseError` so it can be tested using `err instanceof MongooseError`
**Examples**
```ts
import mongoose from 'mongoose';
const Model = mongoose.model('model', new mongoose.Schema({ answer: Number }));
async function main() {
const doc = new Model({ answer: 'not a number' });
const err = doc.validateSync();
console.log(err instanceof mongoose.Error); // true
console.log(err instanceof mongoose.MongooseError); // true
console.log(err instanceof mongoose.Error.ValidationError); // true
}
main();
```
Closes #13387

feat(ts): Export MongooseError class

---

test/mocha-fixtures.js

**Summary**
This PR enables md5 checks on the archives downloaded by MMS, this is in hopes to narrow down deno zlib errors as corrupt downloads or zlib not working correctly on deno.
i could not get the error to reproduce locally and in the CI runs i did i could also not explicitly reproduce it, so i hope that this will help find a run over time

test(fixtures): check md5 of archive downloaded

---

lib/helpers/populate/getModelsMapForPopulate.js
test/helpers/getModelsMapForPopulate.test.js

**Summary**
This PR adds the model name to a error, it is probably not the best method for debugging which model the problem is, but better than not mentioning it.
also adds a test-file for the the helper because i was unsure where to add the test
fixes #13406

fix(getModelMapForPopulate): mention model name in error

---

lib/drivers/node-mongodb-native/collection.js
test/docs/debug.test.js
test/index.test.js
test/query.test.js

closes #13364 
Had to fix a couple of tests because of the changes. Let me know if that is not the correct approach.

fix: custom debug function not processing all args

---

lib/helpers/model/castBulkWrite.js
test/model.test.js

**Summary**
Right now, the current error message on an invalid bulk write op "Invalid op passed to `bulkWrite()`" doesn't provide any insight as to what the invalid op was. `inspect()` output provides a little extra info to make this issue easier to debug.
**Examples**

fix(model): include inspect output in `castBulkWrite()` error

---

docs/connections.md

Re: #13391
**Summary**
Quick note about keepAlive deprecation in the most recent release of the MongoDB Node driver. Related reading: https://www.mongodb.com/docs/v7.0/faq/diagnostics/#does-tcp-keepalive-time-affect-mongodb-deployments-, https://jira.mongodb.org/browse/NODE-5190
**Examples**

docs(connections): add details about `keepAlive` deprecation

---

lib/cursor/QueryCursor.js
lib/query.js
test/query.cursor.test.js

Cannot remove the options assignment in query.js as it causes test failures.
closes #13417

fix query cursor and middleware interaction

---

lib/cursor/QueryCursor.js
test/query.cursor.test.js

Fix #13411
**Summary**
Currently, `skipMiddlewareFunction()` in `pre('find')` middleware causes an error if you're using cursors. With this change, it is now fine to call `skipMiddlewareFunction()` in pre('find') middleware with cursors with no parameters; or with `null`, `undefined`, or empty array `[]`.
The reason why we don't support passing an array of documents is that it would be tricky to rewrite current cursor logic to use arrays. We may consider this for the future if there's demand.
**Examples**

fix(cursor): handle calling `skipMiddlewareFunction()` in pre('find') middleware with cursors

---

lib/query.js
test/model.findOneAndUpdate.test.js

Fix #13413
**Summary**
Looks like we double applied paths in `findOneAndUpdate()`. Likely due to merge conflict issues with 6.x. Cleaned that up and added a test, so shouldn't happen again.
**Examples**

fix(query): handle plus path in projection with findOneAndUpdate()

---

lib/helpers/schema/merge.js
lib/schema.js

Fix #13275
**Summary**
Right now, you can call `new Schema()` on a schema from a different copy of the Mongoose module to "copy" the schema over to use the local Mongoose module's schema class. But that doesn't apply to child schemas. This PR makes it so that child schemas also merge correctly.
**Examples**

fix(schema): recursively copy schemas from different modules when calling `new Schema()`

---

lib/schema/SubdocumentPath.js
lib/schema/array.js
lib/schema/bigint.js
lib/schema/boolean.js
lib/schema/buffer.js
lib/schema/date.js
lib/schema/decimal128.js
lib/schema/documentarray.js
lib/schema/uuid.js
test/schematype.test.js

Re: #7156
**Summary**
Looks like some schematypes are missing the `get()` function to register a getter for all instances of the schematype. Only numbers, strings, and ObjectIds currently have that function. This came up in #7156 in the context of dates.
Not urgent because there is an easy workaround, but something we should ship for 7.3.
**Examples**

feat(schema): consistently add `.get()` function to all SchemaType classes

---

lib/helpers/schema/merge.js
test/model.test.js

Fix #13409
**Summary**
`castBulkWrite()` relies on `schema.$timestamps`, which is only set if you explicitly go through `.set()` rather than setting `.options.timestamps`.
**Examples**

fix(schema): make bulkWrite updateOne() and updateMany() respect timestamps option when set by merging schemas

---

types/index.d.ts
types/schemaoptions.d.ts
types/types.d.ts

Fix #13421
**Summary**
So the parameters aren't all `any`
**Examples**

types: improve function parameter types for `ToObjectOptions` transform option

---

.github/workflows/tsd.yml
package.json
test/types/schema.test.ts

Fix #13235
**Summary**
Some tests started failing when we upgraded tsd. Doesn't look to be a major issue, just some odd patterns in our tests. When we made the tests more closely reflect how the code is used, the tests now pass :man_shrugging: 
**Examples**

test: fix tests with tsd@0.28.1

---

docs/connections.md
lib/connection.js

Fix #11187
**Summary**
We get lots of questions about multi tenant, so would be nice to have a section of the docs to point people to.
**Examples**

docs(connections): add section on multi tenant

---

docs/tutorials/ssl.md

docs: add additional notes for Atlas X.509 authentication

---

docs/populate.md

**Summary**
This PR fixes the `/docs/populate.html` guide that was accidentally broken by #13090

docs(populate): fix accidental removal of text

---

test/types/queries.test.ts
types/query.d.ts

Fix #13224
**Summary**
Quick improvement for TypeScript users using `select()`
**Examples**

types: allow overwriting `Paths` in `select()` to tell TypeScript which fields are projected

---

lib/cursor/QueryCursor.js
test/query.cursor.test.js

Fix #13453
Backports #13435
**Summary**
Backporting #13435 to 6.x to fix #13453 
**Examples**

fix(cursor): allow find middleware to modify query cursor options

---

test/types/aggregate.test.ts
types/expressions.d.ts

Fix #13060
**Summary**
More info here: https://www.mongodb.com/docs/manual/reference/operator/aggregation/mergeObjects/#syntax . Technically you can only use `$mergeObjects: Record<string, string>` if using `$mergeObjects` in a [$bucket](https://www.mongodb.com/docs/manual/reference/operator/aggregation/bucket/#mongodb-pipeline-pipe.-bucket), [$bucketAuto](https://www.mongodb.com/docs/manual/reference/operator/aggregation/bucketAuto/#mongodb-pipeline-pipe.-bucketAuto), or [$group](https://www.mongodb.com/docs/manual/reference/operator/aggregation/group/#mongodb-pipeline-pipe.-group) stage accumulator, but implementing that is complex and likely not worth the effort.
**Examples**

types(aggregate): allow object syntax for `$mergeObjects`

---

docs/populate.md

Fix #13400
**Summary**
Re: #13400, populate docs don't really explain why we recommend using ObjectId for `_id` and `ref`. Added a note about that, and moved the note to the "Saving Refs" section.
**Examples**

docs(populate): add a little more info on why we recommend using ObjectId for `_id`

---

docs/populate.md
lib/helpers/populate/getModelsMapForPopulate.js
lib/schema.js
test/model.populate.test.js
types/index.d.ts

Fix #12443
**Summary**
#12443 asks for a way to merge `match` options when populated rather than overwriting. Instead of adding yet another new option, I added a new parameter to `match()` function: the virtual definition. That makes it easy to append the virtual `match` to any custom match you want to add.
**Examples**

feat(populate): pass virtual to `match` function to allow merging match options

---

lib/model.js
test/model.create.test.js

Fix #13487
Re: #5061
**Summary**
Mongoose 6 used to ignore falsy last arguments to `Model.create()`, Mongoose 7 removed support for that behavior because we removed support for callbacks. In the interest of backwards compat, we should make `await Model.create(doc, undefined)` work like how it did in Mongoose 6.
**Examples**

fix(model): ignore falsy last argument to create() for backwards compatibility

---

docs/further_reading.md

**Summary**
This PR removes the extra style for `img`, which causes the "jobs" sidebar to break by having one really large image take all space

docs(further_reading): remove style for "img"

---

lib/aggregate.js
types/aggregate.d.ts

**Summary**
Ran into this issue earlier: using `Model.aggregate()` in a place where a promise is expected, like `assert.rejects()`, TypeScript reports an error because Aggregate doesn't have `finally()` or `[toStringTag]`.
```
Argument of type 'Aggregate<any[]>' is not assignable to parameter of type 'Promise<unknown> | (() => Promise<unknown>)'.
Type 'Aggregate<any[]>' is missing the following properties from type 'Promise<unknown>': finally, [Symbol.toStringTag]
```
We already have `[toStringTag]` and `finally()` on Query, so would be nice to have them on Aggregate as well.
**Examples**

feat(aggregate): add `Aggregate.prototype.finally()` to be consistent with Promise API for TypeScript

---

test/types/mongo.test.ts
types/augmentations.d.ts
types/index.d.ts
types/types.d.ts

fixes #12537
**Summary**
This PR changes the `Types.ObjectId` to not have its own `_id` declaration anymore but augment `bson.ObjectId` directly

types: augment bson.ObjectId instead of adding on own type

---

lib/query.js
test/model.findOneAndReplace.test.js

Fix #13507
**Summary**
`findOneAndReplace()` isn't respecting query `strict` option right now. This change fixes that.
**Examples**

fix(query): respect query-level `strict` option on `findOneAndReplace()`

---

docs/guide.md
lib/model.js
lib/schema.js
test/model.test.js
types/schemaoptions.d.ts

**Summary**
MongoDB has added [many options to `createCollection()`](https://www.mongodb.com/docs/manual/reference/method/db.createCollection/) and schemas don't quite support all of them. In the interest of making sure developers can use schemas to configure their collections, this PR adds a `collectionOptions` option to schemas; this means you can specify options like `storageEngine` and `validator` in your schema.
**Examples**

feat(schema): add collectionOptions option to schemas

---

docs/connections.md
docs/faq.md

Fix #13483
**Summary**
Finish up our switch from recommending localhost to recommending 127.0.0.1. Especially important now that Node v16 is nearing EOL, so no more versions of Node that aren't affected by this issue.
**Examples**

docs(connections+faq): add info on localhost vs 127.0.0.1

---

lib/cast.js
lib/query.js
lib/schema/SubdocumentPath.js
test/query.test.js

Fix #13512
**Summary**
This change has a bit wider of a surface area than I'd like, but it should be good for performance and developer experience. The problem in #13512 is that Mongoose converts any query filters to POJOs first, and then recasts subdocument path POJOs back into subdocuments, before converting them to POJOs again; and loses the original settings so there's no way to execute a query on a subdocument path without applying defaults.
With this change, Mongoose will only convert documents in query filters to POJOs once, using the `toBSON()` function. Besides fixing #13512, this should make Mongoose faster in cases where you have subdocuments in query filters.
The only potential risk is that we're copying documents as POJOs somewhere. That's why I had to add `source = …

feat(query): delay converting documents into POJOs until query execution, allow querying subdocuments with defaults disabled

---

lib/cursor/QueryCursor.js
lib/model.js
test/query.toconstructor.test.js

**Summary**
There are a couple of places where we still use internal callback calls, which caused some trouble when implementing the in-memory-driver. This doesn't seem to cause any bugs, but we shouldn't rely on callbacks at all given that the MongoDB driver no longer supports them.
**Examples**

refactor: avoid using callbacks for internal `deleteOne()` and `find()` calls

---

test/types/schema.test.ts
types/index.d.ts

Fix #13534
**Summary**
Works fine at runtime, just TypeScript types don't support it. Causes some confusion, see #13534 
**Examples**

types: support `mongoose.Schema.ObjectId` as alias for `mongoose.Schema.Types.ObjectId`

---

lib/query.js
test/query.test.js

Fix #13550
**Summary**
In Mongoose 6, `findOneAndUpdate()` with `overwrite: true` was converted into `findOneAndReplace()`. Looks like that behavior got lost in some of our callback refactoring work for Mongoose 7. This PR adds that behavior back.
What do you think about deprecating the `overwrite` option? It is no longer necessary with `findOneAndReplace()`, and is a potential source of confusion.
**Examples**

fix(query): convert findOneAndUpdate to findOneAndReplace when overwrite set for backwards compat with Mongoose 6

---

lib/connection.js
lib/drivers/node-mongodb-native/connection.js
test/timestamps.test.js

**Summary**
Pulling in some work we started on with #4292 work (see [vkarpov15/gh-4292 branch](https://github.com/Automattic/mongoose/tree/vkarpov15/gh-4292)). One of the annoying pain points in building the in-memory driver was that we couldn't import Mongoose's `Connection` class without importing all of MongoDB. The driver layer is supposed to abstract that out, but connections have a bunch of MongoDB references that should really be in the driver layer.
**Examples**

Move all MongoDB-specific connection logic into driver layer, add `createClient()` method to handle creating MongoClient

---

lib/model.js

Fix #13531
**Summary**
This issue is a bit tricky to test, but the idea is that, in the `insertMany()` error handler, the `error` may not necessarily have a `writeErrors` property. I was able to repro with the following script by shutting down my MongoDB server in the 10 seconds between "Sleep" and "Executing".
```javascript
'use strict';
run().catch(err => console.log(err));
await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test', { serverSelectionTimeoutMS: 5000 });
const Test = mongoose.model('Test', mongoose.Schema({ name: String }));
await Test.init();
console.log('Sleep');
await new Promise(resolve => setTimeout(resolve, 10000));
console.log('Executing');
await Test.insertMany([{ name: 'foo' }]); …
```

fix(model): avoid TypeError if insertMany() fails with error that does not have `writeErrors` property

---

lib/helpers/populate/getModelsMapForPopulate.js
lib/model.js
lib/types/array/methods/index.js
test/model.populate.test.js

Fix #13575
**Summary**
A bit of a nasty issue: `populate()` relies on `getModelsMapForPopulate()` to set `populatedModelSymbol` on the passed in options to set the model being populated, so future calls know what model this path was populated with. But shallow cloning in `Model.populate()` breaks that.
I'd love to do some refactoring here, but will hold off for now because that can take a long time.
**Examples**

fix(populate): correctly set `populatedModelSymbol` on documents populated using `Model.populate()`

---

lib/document.js
lib/helpers/populate/getModelsMapForPopulate.js
lib/helpers/populate/getSchemaTypes.js
lib/schema.js
test/document.test.js

Fix #13582
**Summary**
#13582 points out that we didn't correctly clear `modifiedPaths()` on array subdocuments, other than the first subdocument in the array. This PR fixes that, but it looks like the fix for #6818 succeeded because of the buggy behavior. So we added some new logic to explicitly validate the parent array if making changes underneath a document array.
**Examples**

fix(document): clean up all array subdocument modified paths on save()

---

test/types/models.test.ts
test/types/virtuals.test.ts
types/index.d.ts
types/models.d.ts
types/schemaoptions.d.ts
types/utility.d.ts

**Summary**
#13529 points out some issues with `MergeType`, this PR makes it so that we avoid using `MergeType` in `HydratedDocument<>` where possible.
However, for a future release, we should remove HydratedDocument, and instead rely on inferring the hydrated document type from the schema. Inferring HydratedDocument type from the raw document type isn't possible in general, and relies on `Omit<>`, which is super brittle in TypeScript - breaks on private/protected fields, unions with generics, and other cases.
**Examples**

types: avoid unnecessary MergeType<> if TOverrides not set, clean up statics and insertMany() type issues

---

lib/connection.js
lib/drivers/node-mongodb-native/connection.js
test/connection.test.js

Fix #11821
**Summary**
Right now there's no clean way to close a `useDb()` connection, you have to reach into internals and remove the db from `relatedDbs`, etc. With this PR, `removeDb()` lets you permanently close a `useDb()` connection so it can be garbage collected: removes it from `relatedDbs`, `otherDbs`, and marks the db as force closed and destroyed, so any collection operations immediately error out.
**Examples**

feat(connection): add `Connection.prototype.removeDb()` for removing a related connection

---

docs/deprecations.md
lib/query.js
package.json
test/model.findOneAndDelete.test.js
test/model.findOneAndReplace.test.js
test/model.findOneAndUpdate.test.js

**Summary**
Includes `includeResultMetadata` support now that the MongoDB node driver supports it re: #13584. Also deprecates `rawResult` option, and adds the deprecation warning details to the deprecation warnings guide re: #13567 .
**Examples**

feat: upgrade to MongoDB Node.js driver 5.7.0

---

lib/model.js
test/model.create.test.js
test/types/create.test.ts
types/models.d.ts

**Summary**
This PR adds option `immediateError` to `create`, to not throw on the first error encountered and instead add the error to the result list (only applicable if the input is a array)
Default: `true` for backwards compatibility (current master behavior)
works with both `ordered: false` and `ordered: true`
Result of `immediateError: false`:
```ts
const result = await Model.create([{ test: "yes" }, {}, { test: "no" }], { immediateError: false });
// index 0 is the "test: yes" document
// index 1 is a error instance
// index 2 is the "test: no" document
```
is this implementation OK or should it maybe be split into returning a object of values and errors or some other way?
also moves option `ordered` from "SaveOptions" (on .save) to "CreateOptions" (to .create) because from what i …

feat(model): add create option "immediateError"

---

docs/validation.md
lib/error/cast.js
lib/error/messages.js
lib/schematype.js
test/docs/validation.test.js
test/model.test.js
test/schema.test.js
types/schematypes.d.ts

Fix #3162
**Summary**
We do already have support for custom error messages, but that is using strings with template variables, like `cast: '{VALUE} is not a number'`.
With this PR, we'll also support "cast: [null, value => `${value} is not a number`]" as a supported syntax to create a custom error message. 
**Examples**

feat: support generating custom cast error message with a function

---

lib/document.js
lib/helpers/schema/getPath.js
lib/schema.js
lib/schema/SubdocumentPath.js

**Summary**
Flame graph helped identify that most of the time was spent in the following loop. With a faster implementation that doesn't loop through all modified paths for every subdocument, Mongoose is now 3-4x faster on the mapOfSubdocs benchmark.
```
for (const subdoc of subdocs) {
for (const p of paths) {
if (p == null || p.startsWith(fullPathToSubdoc + '.')) {
paths.delete(p);
}
}
}
```
Before this change:
```
{
"Average save time ms": 439.4
}
```
After this change:
```
{
"Average save time ms": 145.8
}
```
Flamegraph now looks a bunch more reasonable too:
I think we can now mark #13191 and #13271 as fixed, because `$__reset()` is no longer a bottleneck and between this PR and #13280 Mongoose is now more than 10x faster on this particular benchmark.
**Examples**

perf: speed up mapOfSubdocs benchmark by 4x by avoiding unnecessary O(n^2) loop in getPathsToValidate()

---

lib/model.js
test/model.create.test.js

throw error after all saves are done

---

docs/async-await.md
docs/faq.md
docs/middleware.md
docs/queries.md
lib/model.js
test/model.insertMany.test.js

Fix #13616
**Summary**
#13616 pointed out one example in our docs that still uses callbacks. That's a problem now that 7.x dropped support for callbacks. I also found a few other spots where we still use callbacks in the docs, this PR fixes those.
**Examples**

docs: rework several code examples that still use callbacks

---

lib/schema.js
test/document.test.js

Fix #13599
**Summary**
#13599 pointed out that we introduced a potentially breaking change in #13396: `transform()` option propagates to implicitly created schemas, which means existing `transform` functions need to account that they'll run on subdocuments. This PR undoes that backwards breaking change by explicitly omitting `transform` from the `toJSON` and `toObject` options propagated down to implicitly created schemas.
**Examples**

fix(schema): avoid propagating `toObject.transform` and `toJSON.transform` option to implicitly created schemas

---

test/types/middleware.test.ts
types/index.d.ts

Fix #13601
**Summary**
`pre('deleteOne', { document: true })` fails to compile currently, which is a bit problematic. Looks like the current TS types require `{ document: true, query: false }`, which isn't correct.
**Examples**

types: correctly handle `pre('deleteOne', { document: true })`

---

test/types/schema.test.ts
types/inferschematype.d.ts

**Summary**
Ran into a small issue where `InferSchemaType` ends up interpretting `myMap: { type: Schema.Types.Map, of: Number, required: true }` as a boolean. This fixes that.
**Examples**

types(schema): handle `type: Schema.Types.Map` in TypeScript

---

types/query.d.ts

**Summary**
I ran into a small issue when using a function like `findOneAndUpdate` or `updateMany`, the `runValidator` flag in the `queryOptions` interface is optional but has no information about the default value.

Types: Add inline comment to to tell the default value of the runValidator flag in the queryOptions types

---

lib/document.js
lib/types/ArraySubdocument.js
lib/types/DocumentArray/methods/index.js
lib/types/array/methods/index.js
lib/types/subdocument.js
test/document.test.js

**Summary**
Fix #13609. This issue was pretty tricky at first glance, and I spent a lot of time trying to figure out how to make it so that `pull()` would mark paths in default state as modified. But then I realized the simple solution was to just always call `$__reset()` on every subdoc :smile: Given that `$__reset()` is no longer a bottleneck, this is a better solution because we can now consistently ensure that every individual subdocs' state is reset on `save()`.
**Examples**

Correctly clean up nested subdocs modified state on save()

---

lib/query.js

Island rhythms/deprecate overwrite

---

lib/helpers/model/castBulkWrite.js
test/model.test.js

fix: timestamps:false on bulkWrite works

---

lib/document.js
test/document.modified.test.js

**Summary**
This pull request should fix the  issue [#13667](https://github.com/Automattic/mongoose/issues/13667). 
The error was caused in a recent change of the Document.isModified method, to resolve it I returned the paths variable declaration as it was before that change.  
**Examples**
These pictures show the repro script provided in the original issue running with and without the changes

fix: Document.prototype.isModified support for a string of keys as first parameter

---

lib/schema.js
test/schema.test.js

Re: #13626
**Summary**
#13626 is one of those issues where doing the "5 whys" exercise takes you down a very deep rabbit hole. There are a few issues that came together to form the issue reported in #13626. The one addressed in this PR is that `Schema.prototype.clone()` unintentionally creates duplicate constructors for subdocuments and document arrays that are nested underneath a subdocument path.
```javascript
new Schema({
docArr1: [{ name: String }] // unaffected
subdoc1: new Schema({
docArr2: [{ name: String }], // affected
subdoc2: new Schema({ name: String }) // affected
});
}).clone();
```
The issue is that `Schema.prototype.clone()` first uses `utils.clone()` to clone the schema's paths, and then clone the single nested paths:
```javascript
s.paths = utils.clone(this.paths); …
```

fix(schema): make `Schema.prototype.clone()` avoid creating different copies of subdocuments and single nested paths underneath single nested paths

---

docs/middleware.md
test/document.modified.test.js

Fix #13518
**Summary**
#13518 points out that we still had some examples in the middleware docs that used remove, even though remove is no longer supported in Mongoose 7. This PR changes those examples to use `deleteOne()` instead.
**Examples**

docs(middleware): fix old example using `post('remove')`

---

lib/document.js
test/schema.validation.test.js

**Summary**
Another related issue to #13626. The reason why #13626 was leading to an uncaught error was that the `if (value && !(value instanceof Constructor)) {}` check in `schema/DocumentArrayElement.js` was not getting the correct scope or index set, so the subdocument threw an uncaught validation error because the subdocument didn't know what array it was part of. `scope` was the top level document, not the document array. With this PR, we'll always pass `options.index` and also set `scope` to the document array.
**Examples**

fix(document): correctly set index when casting subdocs for validation re: #13626
