- docs/deprecations.md
Fix #13661
**Summary**
Quick fix, #13661 points out that the deprecation docs flip `includeResultMetadata`
**Examples**
> docs(deprecations): quick fix for includeResultMetadata docs

- lib/model.js
- test/model.test.js
Fix #13664
**Summary**
Looks like if `bulkWrite()` is empty and `ordered: false`, we never hit the `if (--remaining <= 0)` check, so `bulkWrite()` hangs forever. Fixed in this PR, but likely worth doing some refactoring to switch to using async functions rather than callbacks internally within `bulkWrite()` to avoid this sort of issue.
**Examples**
> fix(model): avoid hanging on empty `bulkWrite()` with ordered: false

- docs/layout.pug
- docs/typescript/statics.md
Fix #12942
**Summary**
Make statics and methods TypeScript section highlight the auto type inference approach first, and also add info on how to use generics for methods.
**Examples**
> docs(typescript): highlight auto type inference for methods and statics, add info on using methods with generics

- test/types/schema.test.ts
- types/inferschematype.d.ts
Re: #13514
**Summary**
One potential workaround for #13514 is using object syntax for defining `required`, because the following works fine:
```javascript
new Schema({
email: {
type: String,
required: { isRequired: true, message: 'Email is required' }
}
});
```
But we don't currently support that in TypeScript. This PR adds support for the `required: { isRequired: true }` syntax. Unfortunately doesn't help very much with #13514.
**Examples**
> types(schema): support `required: { isRequired: true }` syntax in schema definition

- lib/utils.js
- test/schema.uuid.test.js
Fix #13657
**Summary**
Right now, `save()` will actually apply getters on map paths when updating an existing doc. That's why the test case from #13657 shows maps of uuids getting saved as strings. This PR fixes that by making it so that `getValue()`, Mongoose's internal way to "get dotted path without Mongoose internals", always passes `getters: false` to `map.get()`.
**Examples**
> fix: avoid applying map property getters when saving

- docs/middleware.md
Fix #13669
**Summary**
Middleware docs don't make it clear that `doc.deleteOne()` currently doesn't run query middleware. We're fixing this in #13660. Can't fix this in 7.x because we have tests that assert on this behavior. So add a section to the docs, and make sure to make a note of the breaking change in 8.x.
**Examples**
> docs(middleware): clarify that `doc.deleteOne()` doesn't run query middleware currently

- test/types/schema.test.ts
- types/index.d.ts
- types/middlewares.d.ts
Fix #13633
**Summary**
TypeScript types don't support `options` param for document and model middleware currently. This PR adds that.
**Examples**
> types: allow accessing `options` from pre middleware

- test/types/schema.test.ts
- types/index.d.ts
Fix #13702
**Summary**
Just a quick types fix. Current return value doesn't accurately reflect runtime behavior.
**Examples**
> types(schema): correct return type for `Schema.prototype.indexes()`

- lib/queryhelpers.js
- test/query.test.js
Fix #13679
**Summary**
The flipped sign is because "excude === true" means a projection that explicitly excludes fields, like `{ name: 0, age: 0 }`. The case on L308 is looking to capture the case where the user does something like `{ name: 1, __t: 0 }` as a way to explicitly exclude `__t`, which is included by default. So `if (!exclude)` is correct, and happens to fix the bug in #13679 as well
**Examples**
> fix(query): allow deselecting discriminator key

- package.json
- test/types/mongo.test.ts
- types/augmentations.d.ts
- types/index.d.ts
- types/types.d.ts
> backport pull 13515

- test/types/models.test.ts
- types/models.d.ts
- types/query.d.ts
Fix #13705
**Summary**
Make `Model.findOne({}, null, { lean: true })` equivalent to `Model.findOne({}).lean()` in terms of TypeScript return value.
**Examples**
> types(models+query): return `lean` type when passing QueryOptions with `lean: true` to relevant model functions like `find()` and `findOne()`

- docs/discriminators.md
- test/docs/discriminators.test.js
Re: #10435
**Summary**
Added back embedded discriminator docs, with a couple of comments on `path()` generic requirement for TypeScript.
I'll take another look and see if we can maybe remove the need to do `schema.path<Schema.Types.Subdocument>` and just have Mongoose infer the type correctly.
**Examples**
> docs: add brief note on TypeScript generic usage for embedded discriminator `path()` calls

- lib/connection.js
- test/docs/transactions.test.js
Fix #13698
**Summary**
#13698 pointed out that, although we do reset `$isNew` if the transaction fails, we do not reset `$isNew` in between transaction retries. So if you `save()` a document within a transaction that was created outside of a transaction, retrying a transient error will always fail with `DocumentNotFoundError`.
~Some followup work: we should be running transaction tests in CI. I'll look into that.~ I got transaction tests running in CI
**Examples**
> fix(connection): reset document state in between transaction retries

- docs/middleware.md
Fix #13713
**Summary**
We don't explain that `validate` hooks apply to document middleware by default anywhere, this PR fixes that.
**Examples**
> docs(middleware): clarify that query middleware applies to document by default

- types/inferschematype.d.ts
**Summary**
TypeScript doesn't seem to care whether we do `export InferSchemaType` or not, but apparently some IDEs do. Do you know if there's any potential harm in doing this @hasezoey ?
**Examples**
> types: export InferSchemaType

- lib/helpers/schema/getIndexes.js
- lib/schema.js
- test/schema.test.js
- test/types/mongo.test.ts
- types/augmentations.d.ts
- types/inferschematype.d.ts
Fix #13725
**Summary**
Our TypeScript types say Mongoose supports 'ascending' and 'descending' as `IndexDirection`, but runtime behavior doesn't support that. I figure it is easy enough to add support to runtime behavior rather than removing the TypeScript types.
**Examples**
> fix(schema): support 'ascending', 'asc', 'descending', 'desc' for index direction

- lib/helpers/query/selectPopulatedFields.js
- test/helpers/query.selectPopulatedFields.test.js
Fix mongodb-js/mongoose-autopopulate#96
**Summary**
In order to `populate()` correctly, we need the field referenced by `refPath`. We already project in populated fields by default, so adding `refPath` unless explicitly excluded is reasonable.
**Examples**
> fix(query+populate): add `refPath` to projection by default, unless explicitly excluded

- lib/cursor/ChangeStream.js
**Summary**
ChangeStream doesn't work with fromEvent function from rxjs because this function uses addListener function which doesn't have _bindEvents
https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/fromEvent.ts#L291
**Examples**
```js
const productsObservable = fromEvent(
this.productsModel.watch(),
'change',
).pipe(map((change) => change.fullDocument));
```
In current implementation nothing happens
> fix(ChangeStream): add _bindEvents to addListener function

- test/types/models.test.ts
- types/models.d.ts
Fixes https://github.com/Automattic/mongoose/issues/13746
**Summary**
Typescript was complaining of missing types when I was using `includeResultMetadata`. So in this PR, I fixed that issue by adding the missing types for it.
> fix: missing typings for option includeResultMetadata

- test/types/document.test.ts
- types/document.d.ts
- types/utility.d.ts
ref: #13738 
**Summary**
Improved various Document's methods
> types: enhanced Document's methods

- lib/model.js
- test/model.test.js
Fix #13664
**Summary**
@JavaScriptBach is right that the fact that `bulkWrite([], { ordered: false })` throwing an error is a bit of a rough patch in the API. Especially since `bulkWrite([])` (no `ordered: false`) does not throw an error.
**Examples**
> fix(model): make Model.bulkWrite() with empty array and ordered false not throw an error

- lib/query.js
- test/query.test.js
- test/query.toconstructor.test.js
Re: #13617
**Summary**
Unfortunately there's a lot of functionality duplicated between mongoose and mquery, so with #13617 we're moving towards moving this logic into mongoose for easier maintenance. The big change in this PR is `sort()`: we've moved sort handling into Mongoose, and we're making `options.sort` always an object. We're now converting `.sort([['a', 1]])` into `.sort({ a: 1 })`, rather than leaving it as `[['a', 1]]` under the hood. Keeping entries-style syntax internally is not necessary post ES2015, key order is still maintained, and that removes the need for us to handle edge cases like `.sort([['a', 1]]).sort({ b: 1 })`.
**Examples**
> BREAKING CHANGE: stop using mquery for `updateX()`, `deleteX()`, `sort()`, always convert sort args to objects

- lib/document.js
- lib/schema/array.js
- lib/types/array/index.js
- test/document.test.js
**Summary**
#13748 points out that accessing `user.hobbies` actually modifies the `hobbies` array if there's a getter on elements of the `hobbies` array. That is a problem. To fix that, I moved the logic for applying getters from `SchemaArray.prototype.applyGetters()`, which is also called when you access `user.hobbies`, and into the top-level `applyGetters()` function, which is only called by `toObject()` and `toJSON()`.
As a side effect, in order to avoid breaking Schema UUID tests, we instead need to apply getters on index access. So `user.hobbies[0]` will fire getters on `hobbies.0`, but not modify `hobbies`. That's what the changes to `types/array/index.js` are for.
Still to investigate: it looks like `oneUser.get('hobbies.0')` double calls getters with this PR. Worth checking before …
> fix(document): make array getters avoid unintentionally modifying array, defer getters until index access instead

- types/pipelinestage.d.ts
Add search meta
**Summary:**
This pull request extends the Mongoose module typings by incorporating the SearchMeta interface. This addition offers better type definitions for developers leveraging MongoDB Atlas Search, ensuring that their implementations are more type-safe and adhere to the expected structure.
**Motivation:**
With MongoDB Atlas Search gaining traction, many developers are harnessing its full-text search capabilities within their Mongoose-based applications. By providing detailed type definitions, we can simplify their development process, prevent type-related errors, and encourage best practices.
**Key Features:**
Introduced the SearchMeta interface that encapsulates the $searchMeta aggregation pipeline stage.
Included annotations for the possible properties within this …
> Enhance Mongoose Typings with SearchMeta Interface for Atlas Search

- test/types/schema.test.ts
- types/inferschematype.d.ts
- types/schematypes.d.ts
Fix #13780
**Summary**
#13780 points out that accessing `mongoose.Schema.Types.BigInt` throws a compiler error in TypeScript. This PR fixes that.
**Examples**
> types(schematypes): add missing BigInt SchemaType

- lib/helpers/query/castUpdate.js
- test/model.updateOne.test.js
**Summary**
Right now, MongoDB allows storing top-level keys that start with $, but our `castUpdate()` function doesn't allow top-level dollar keys.
```javascript
'use strict';
void async function main() {
await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');
//await mongoose.connection.dropDatabase();
await mongoose.connection.collection('test').insertOne({ $set: [1,2, 3, 4] });
console.log(await mongoose.connection.collection('test').find().toArray());
console.log('Done');
}();
```
**Examples**
> feat: allow top level dollar keys with findOneAndUpdate(), update()

- lib/query.js
- test/model.findOneAndUpdate.test.js
**Summary**
Fixes #13783
When calling `findOneAndUpdate` with no update query the `_decorateUpdateWithVersionKey` function adds `'$setOnInsert': { __v: 0 }` to the update doc so it passes the `_mergeUpdate` first check which then sets the `_update` to `{}` but with `versionKey` set to `false` the update doc length is 0 so the `_mergeUpdate` function returns early
this PR set a value of empty object to the `_update` property even when `Object.keys(doc).length === 0` so it's defined
> set default value for _update when no update object is provided and versionKey is set to false

- lib/document.js
Found this commit [0] while I was looking for a way to omit specific virtuals using toObject/toJSON, then noticed it wasn't in the api docs. Added an extra sentence to the doc to make it clear that this is an option.
First time contributing, let me know if there's anything else I can add.
[0] [760fa73](https://github.com/Automattic/mongoose/commit/760fa73b1f6fdb6ed5c7d1c8641a56803ffd530a)
> update docs to reflect change from commit 760fa73

- CHANGELOG.md
**Summary**
This PR adds a missing entry of noting that the mongodb driver had been updated for that version, because 2aa453cba40308307f6ce90fb7ee51aa45dbeac4 was not included in the changelog.
i have already updated the [github release](https://github.com/Automattic/mongoose/releases/tag/7.5.0) to include this notice
> chore(CHANGELOG): add missing entry for mongodb 5.18.1 upgrade for 7.5.0

- types/models.d.ts
**Summary**
This PR removes a duplicated method signature for `exists` in the `Model` interface within the `types/models.d.ts` file. The duplication does not add any functional value and could potentially lead to confusion. This change aims to clean up the code for better readability and maintenance.
> fix: remove duplicated 'exists' method in Model interface in models.d.ts

- .github/workflows/test.yml
**Summary**
This PR forces color for CI test output, which should make it easier to parse if there are problems (especially for something like debugging #13764)
Color is not enabled by default in github CI because (from what i can tell) it is detected as "not a tty"
> chore(workflows/test): force color

- lib/helpers/populate/markArraySubdocsPopulated.js
**Summary**
An exception handling mechanism has been introduced to prevent Mongoose from attempting to populate null objects within an array. This fix prevents application crashes that occur when null elements are present within an array in a document.
Prior to this fix, when encountering a null object within an array, the code would attempt to populate the null object and consequently crash. Null objects in arrays can be present in various scenarios, such as incomplete or inconsistent data.
With this fix in place, if a null object is found within an array, it will not attempt to be populated, ensuring the application's stability in such cases.
**Examples**
Consider a MongoDB document with a `founders` field designed to be an array of objects:
```javascript
founders: [
{
legal_form: { …
```
> Handle null objects in arrays during populate operations

- test/types/queries.test.ts
- types/models.d.ts
- types/query.d.ts
**Summary**
W.r.t issue https://github.com/Automattic/mongoose/issues/11306
This PR improves the type safety for the return type of `Model#distinct` and `Query#distinct`. It should behave more like Mongodb does, i.e., if you give something that isn't a key on the document, you would still get an empty array or maybe something `unknown[]`. If you _do_ give the correct key from the schema, you'll get a type safe result.
**Note:** This is not a backwards compatible change, as pointed out here: https://github.com/Automattic/mongoose/issues/11306#issuecomment-1705526596
**Examples**
The changes to the tests should be good enough examples. Can add more here if required.
> BREAKING CHANGE: Safer types for `Model.distinct` and `Query.distinct`.

- lib/model.js
- test/model.validate.test.js
Fix #12668
**Summary**
`Model.validate()` currently modifies the passed in object for casting purposes, which is inconsistent with how `Model.castObject()` works and can leave the passed-in object in a half-casted state if there's a cast error. This PR makes `Model.validate()` use `Model.castObject()` to create a casted copy of `obj`, and run validation on all paths that successfully casted.
**Examples**
> BREAKING CHANGE: make `Model.validate()` use `Model.castObject()` to cast, and return casted copy of object instead of modifying in place

- test/types/schema.test.ts
- types/index.d.ts
Fixes this issue: https://github.com/Automattic/mongoose/issues/13800
> types(schematypes): use DocType for instance method this

- lib/helpers/query/getEmbeddedDiscriminatorPath.js
- test/helpers/query.castUpdate.test.js
- test/model.findByIdAndUpdate.test.js
**Summary**
while trying to use findByIdAndUpdate on a document where its schema uses discriminator. I faced the same error here, https://github.com/Automattic/mongoose/issues/8837
looking at this PR, https://github.com/Automattic/mongoose/pull/8878. Trying to simulate the same fix for this case.
The error (Cannot read properties of null (reading 'schema') stack that I received was, 
```
'TypeError: Cannot read properties of null (reading 'schema')  
at getEmbeddedDiscriminatorPath (/node_modules/mongoose/lib/helpers/query/getEmbeddedDiscriminatorPath.js:78:110)   
at walkUpdatePath (/node_modules/mongoose/lib/helpers/query/castUpdate.js:328:22)   
at castUpdate (/node_modules/mongoose/lib/query.js:4419:28)   
at processTicksAndRejections (node:internal/process/task_queues:95:5)   
``` …
> fix: accessing discriminator schema with null

- lib/helpers/populate/markArraySubdocsPopulated.js
- test/model.populate.test.js
**Summary**
#13839 , plus lint fixes and test case
**Examples**
> Edits to Handle null objects in arrays during populate operations 

- test/types/schema.test.ts
- types/index.d.ts
- types/schematypes.d.ts
This PR tries to fix [#13797](https://github.com/Automattic/mongoose/issues/13797).
To fix it, I pass down `EnforcedDocType` down and assign it to `this` in the required function.
I have also changed this type of `default` function in schema, since it had the same issue.
> fix: Pass correct document type to required and default function

- lib/index.js
- lib/schema.js
- test/schema.test.js
Fix #13788
**Summary**
#13788 pointed out that we have an issue where `Schema.prototype.discriminator()` doesn't handle number discriminator keys correctly. Mostly because that function uses a [POJO](https://masteringjs.io/tutorials/fundamentals/pojo) to store the future discriminator keys, which means numeric keys get converted to strings. This PR makes `Schema.prototype._applyDiscriminators` use a map instead to retain numbers.
**Examples**
> fix(schema): handle number discriminator keys when using `Schema.prototype.discriminator()`

- lib/cast/bigint.js
- test/document.test.js
Fix #13791
**Summary**
By default, MongoDB Node driver returns BigInts as a BSON Long, but Mongoose doesn't know how to cast BigInts to Longs. This PR fixes that
**Examples**
> fix(document): handle MongoDB Long when casting BigInts

- types/index.d.ts
Fix #13775
**Summary**
In #13577, we removed `FlatRecord` from Schema definition because we didn't think it was necessary. And it doesn't look like `FlatRecord` is necessary in TypeScript 5, but for some reason is necessary in certain cases with TypeScript 4.
Will add `FlatRecord` back since it doesn't seem to break anything, and fixes #13577. But we will undo this change for 8.0, and we should make a note that we no longer support TypeScript 4.x or older.
**Examples**
> types: avoid "interface can only extend object types with statically known members" error in TypeScript 4

- lib/helpers/model/castBulkWrite.js
- test/model.test.js
Fix #13823
**Summary**
`mongoose.set('setDefaultsOnInsert', false)` doesn't disable setDefaultsOnInsert for `bulkWrite()`, this PR fixes that
**Examples**
> fix(model): make bulkWrite casting respect global setDefaultsOnInsert

- lib/drivers/node-mongodb-native/connection.js
**Summary**
Minor tweak: currently we access MongoDB Node driver internals to get the current database name, this PR uses `databaseName`, which is part of the MongoDB Node driver's public API
**Examples**
> refactor(connection): get database name without using mongodb node driver internals

- lib/document.js
- test/document.test.js
> fix: account for null values when assigning `isNew` property

- docs/deprecations.md
Fix #13844
**Summary**
Quick typo fix that #13844 pointed out
**Examples**
> docs(deprecations): fix typo in includeResultMetadata deprecation docs

- lib/helpers/discriminator/getConstructor.js
- lib/schema/SubdocumentPath.js
- test/document.test.js
Fix #13835
**Summary**
Currently, Mongoose doesn't pick up default values for the discriminator key when creating a new subdocument. The default value doesn't get set until after Mongoose decides which constructor to use. So this PR makes Mongoose check for default values on the discriminator key when initializing a subdocument.
**Examples**
> fix(document): handle default values for discriminator key with embedded discriminators

- docs/css/style.css
**Summary**
When browsing through the docs of mongoose, I opened it's home page and noticed a horizontal overflow, caused by the `pre` element in the first code snippet, hence I thought of fixing it.
**Examples**
Previously (having overflow issue): 
Now (fixed overflow issue):
> docs: fix `pre` element overflow in home page

- lib/model.js
- test/document.test.js
Fix #13799
**Summary**
#13799 points out that property changes in `pre('save')` hooks don't get saved if you're using `bulkSave()`. That is inconsistent with plain old `save()`.
**Examples**
> fix(model): make `bulkSave()` persist changes that happen in pre('save') middleware

- .eslintrc.js
- lib/cast.js
- test/model.query.casting.test.js
Fix #13880
**Summary**
A simpler solution than #13888, went for a different branch name and different PR because branch names that end in `.js` can make our current eslint config screw up your git state.
**Examples**
> fix: handle casting `$elemMatch` underneath `$not` underneath another `$elemMatch`

- lib/index.js
- test/index.test.js
Fix #13887
**Summary**
Typo in global `applyPluginsToChildSchemas` option handling pointed out by #13887 
**Examples**
> fix(mongoose): correctly handle global applyPluginsToChildSchemas option

- lib/document.js
- test/document.test.js
- test/query.middleware.test.js
Fix #13876
**Summary**
Re: #13339. A couple related issues:
1. If setting a path underneath a single nested subdoc, need to be careful to set on both `doc` and `doc._doc` if there isn't a setter for the path (for example, with `strict: false`).
2. When running `_getPathsToValidate()` underneath a single nested subdoc, need to get paths relative to parent.
**Examples**
> fix(document): call pre('validate') hooks when modifying a path underneath triply nested subdoc

- lib/queryhelpers.js
- test/query.test.js
Fix #13760
**Summary**
The issue is that, if using only `-` paths, `applyPaths()` doesn't set the correct value for `exclude` because all minus paths are stripped out until we sort through the schema to tell if this is deselecting a default selected path from the schema or not.
**Examples**
> fix(query): allow deselecting discriminator key using `-` syntax

- lib/cursor/QueryCursor.js
- lib/query.js
- test/query.cursor.test.js
Fix #13773
**Summary**
Bug fix, double applying `this._optionsForExec()` means projections lose `+age` projections that override `age: { select: false }` in schema. This double-applying only happens with `.cursor()` right now.
**Examples**
> fix(QueryCursor): avoid double-applying schema paths so you can include `select: false` fields with `+` projection using cursors

- test/types/models.test.ts
- types/models.d.ts
**Summary**
This solves a typescript problem we are having with using options and insertMany, issue https://github.com/Automattic/mongoose/issues/13930. In this PR I have added an additional overload when inserting an array with options.
**Examples**
See the test case and bug report for examples
> fix(types): add insertMany array overload with options

- lib/helpers/query/cast$expr.js
- test/helpers/query.cast$expr.test.js
Fix #13881
**Summary**
[`$round` syntax takes an array, not a number](https://www.mongodb.com/docs/manual/reference/operator/aggregation/round/). This PR fixes that.
**Examples**
> fix(query): handle `$round` in `$expr` as array

- docs/populate.md
See https://mongoosejs.com/docs/6.x/docs/populate.html#dynamic-ref
Line restored from master, https://github.com/Automattic/mongoose/blob/d5964cdeeb278bf55b656fcf0217233b41e1e9ef/docs/populate.md?plain=1#L472-L474
> 6.x/populate.md: fix edit whoopsie scrapping a line, and setting half of this doc in unclosed code tag

- lib/index.js
- test/index.test.js
Fix #13887 for 6.x
**Summary**
This PR backports #13911 for 6.x
> Backport to 6.x: correctly handle global applyPluginsToChildSchemas option

- .npmignore
**Summary**
This PR updates the `.npmignore` to include some files which were added since the last touch to npmignore, mainly:
- transition from `eslintrc.json` to `.eslintrc.js`
- addition of markdownlint-cli
- addition of lgtm
- move of scripts to `scripts`
- addition of `.mocharc.yml`
also excluded `tools/`, because to my knowledge these are not meant to be shipped, another exclude is `tsconfig.json`
see https://unpkg.com/browse/mongoose@7.6.0/ for context
> chore(npmignore): ignore newer files

- package.json
**Summary**
This PR bumps the `bson` dependency to match the installed `mongodb`'s one, because otherwise some package managers (example yarn-v1) will install *the old* bson for mongoose and *the new* bson for mongodb driver, causing confusing test failures.
i noticed this while trying to install mongoose@7.6.0 for typegoose
context: https://unpkg.com/browse/mongodb@5.9.0/package.json#L28
<details>
<summary>Some test failure examples from typegoose</summary>
```txt
FAIL  test/tests/ref.test.ts (5.488 s)
● check reference with buffer _id
Expected "refFieldBuffer" to be "mongoose.Types.Buffer | Buffer"
171 |   const { _id: refBufferId } = await RefTestModel.create({ refFieldBuffer: _id1 });
172 |   const { refFieldBuffer } = await RefTestModel.findById(refBufferId).orFail().exec();
> 173 | …
```
> chore: bump bson to match mongodb@5.9.0 exactly

- .mocharc.yml
- package.json
**Summary**
This PR moves the mocha config options in `package.json` to `.mocharc.yml`, this way mocha config is defined in one place only and we also dont need to ship that config (re #13946)
> chore: move mocha config from package.json to mocharc

- lib/query.js
according to https://mongoosejs.com/docs/deprecations.html#rawresult it mus tbe true, not false. it would also make more sense tbh
> fix: raw result deprecation message

- types/models.d.ts
- types/query.d.ts
adds types for includeResultMetadata (see  https://mongoosejs.com/docs/deprecations.html#rawresult) and sets rawResult as deprecated.
related to #13954
> type: add types for includeResultMetadata

- lib/model.js
- test/model.test.js
Fix #13907
**Summary**
Calling `bulkSave()` with the base model means `bulkSave()` only casts against the base model, ignoring discriminators. This PR fixes that by setting the discriminator key on the corresponding update for every document that has a discriminator key.
**Examples**
> fix(model): make bulkSave() save changes in discriminator paths if calling bulkSave() on base model

- lib/schema.js
- lib/schema/SubdocumentPath.js
- lib/schema/documentarray.js
- test/document.test.js
Fix #13898
**Summary**
Using `schema.path('docArr').discriminator(...)` works fine, but not `docArrSchema.discriminator(...); const schema = new Schema({ docArr: [docArrSchema] })`. This PR makes it so that both syntaxes work.
**Examples**
> fix(schema): handle embedded discriminators defined using `Schema.prototype.discriminator()`

- lib/schema.js
- test/document.test.js
**Summary**
In fix for #3265, we made it so that we store an entry in `subpaths` for every element in an array, presumably to help make it easier to look up array paths. With a little bit of changes, it turns out this is unnecessary; and, as #13874 pointed out, adding an entry to `subpaths` for every element in an array can be considered a memory leak.
**Examples**
> Avoid storing a separate entry in schema `subpaths` for every element in an array

- test/types/models.test.ts
- types/models.d.ts
Fix #13957
**Summary**
Something in the way `insertMany()` generics are structured causes the errors in #13957. Adding `insertMany()` overrides that have no generics fixes that, which seems like a reasonable approach.
**Examples**
> types(models): add cleaner type definitions for `insertMany()` with no generics to prevent errors when using `insertMany()` in generic classes

- test/types/models.test.ts
- types/models.d.ts
Fix #13904
**Summary**
Looks like just an inconsistency in typedefs, result of `insertMany()` should be assignable to Mongoose's `InsertManyResult`, but currently isn't.
**Examples**
> types(model): make InsertManyResult consistent with return type of insertMany

- lib/model.js
- test/document.test.js
- test/types/document.test.ts
- types/document.d.ts
Fix #13878
**Summary**
TypeScript doesn't allow specifying a type for the `constructor` property, so right now there's no ergonomic way to get the model associated with a document in TypeScript. Need to use `as`. This PR makes it so that you can do `doc.$model()`. Requires a small runtime change, Mongoose doesn't currently support calling `doc.$model()` without args.
**Examples**
> fix(document): allow calling `$model()` with no args for TypeScript

- lib/model.js
- test/document.test.js
Fix #13956
**Summary**
Right now get the following error when you try to use `collection` as a schema path name:
```
$ node gh-13956.js 
TypeError: Cannot read properties of undefined (reading 'Symbol(mongoose#Document#scope)')
at Model.set [as collection] (/home/val/Workspace/MongoDB/mongoose/lib/helpers/document/compile.js:205:32)
at Function.compile (/home/val/Workspace/MongoDB/mongoose/lib/model.js:4776:30)
at Mongoose._model (/home/val/Workspace/MongoDB/mongoose/lib/index.js:620:27)
at Mongoose.model (/home/val/Workspace/MongoDB/mongoose/lib/index.js:579:27)
at run (/home/val/Workspace/MongoDB/troubleshoot-mongoose/gh-13956.js:11:25)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
This PR fixes that, you can now use `collection` as a schema name, …
> fix(document): avoid triggering setter when initializing `Model.prototype.collection` to allow defining `collection` as a schema path name

- docs/timestamps.md
**Summary**
This PR fixes a typo in the timestamps documentation [here](https://mongoosejs.com/docs/timestamps.html#under-the-hood). It simply changes `if` to `of`.
**Examples**
> Fix Typo In Timestamps Docs

- types/index.d.ts
**Summary**
Schema.discriminator accepts only strings, even though other discriminator functions (e.g Schema.Types.Array) accept number | string
**Examples**
```javascript
baseSchema.discriminator(1, derivedSchema);
```
would give compile error, even though numbers as discriminators do work.
> Fix Typescript definition of schema.discriminator to allow strings.

- lib/helpers/query/castUpdate.js
- test/model.findOneAndUpdate.test.js
Fix #13962
**Summary**
#13962 points out an issue: we pass `filter` by reference when adding a `$setOnInsert` to prevent MongoDB from complaining about empty updates, but then `setDefaultsOnInsert` can modify that filter. This PR fixes that bug by making sure we shallow clone `filter`.
**Examples**
> fix(update): avoid applying defaults on query filter when upserting with empty update

- lib/utils.js
- test/model.populate.test.js
Fix #13951
**Summary**
Right now, `populate('user  fans')` will fail with a StrictPopulateError because of the extra space. I think it is sufficiently reasonable to split by multiple spaces, so `populate('user  fans')` is equivalent to `populate('user fans')`. This may cause issues in cases where path names have whitespace characters, but given that it isn't currently possible to populate a space-delimited path anyway, I don't think that is concerning.
**Examples**
> fix(populate): handle multiple spaces when specifying paths to populate using space-delimited paths

- docs/typescript/query-helpers.md
**Summary**
- I found some errors in the sample code of "Manually Typed Query Helpers"
- https://mongoosejs.com/docs/typescript/query-helpers.html#manually-typed-query-helpers
**Examples**
```
lib/models/project2.ts:9:25 - error TS2304: Cannot find name 'QueryWithHelpers'.
9   byName(name: string): QueryWithHelpers<
~~~~~~~~~~~~~~~~
lib/models/project2.ts:29:9 - error TS2304: Cannot find name 'QueryWithHelpers'.
29   this: QueryWithHelpers<any, HydratedDocument<Project>, ProjectQueryHelpers>,
~~~~~~~~~~~~~~~~
lib/models/project2.ts:36:66 - error TS2552: Cannot find name 'schema'. Did you mean 'Schema'?
36 const ProjectModel = model<Project, ProjectModelType>('Project', schema);
~~~~~~
lib/models/project2.ts:41:9 - error TS2304: Cannot find name 'connect'.
41   await …
```
> fix(document): fix missing import and change wrong variable name

- docs/migrating_to_8.md
- lib/helpers/model/castBulkWrite.js
- lib/helpers/query/castUpdate.js
- lib/helpers/timestamps/setupTimestamps.js
- lib/helpers/update/applyTimestampsToUpdate.js
- lib/model.js
- lib/query.js
- test/document.test.js
- test/model.updateOne.test.js
- test/query.test.js
- test/types/maps.test.ts
- test/types/models.test.ts
- types/inferschematype.d.ts
**Summary**
Re: #13578, remove the `overwrite` option for 8.0. In 7.x, `Model.findOneAndUpdate(filter, update, { overwrite: true })` becomes a `findOneAndReplace()`, which is a vestigial quirk of back when `update()` with no atomic operators would overwrite the document. Given that's no longer the case, we don't really need an `overwrite` option anymore.
Removed a few tests that relied on `overwrite: true`.
**Examples**
> Remove `overwrite` option for `updateOne()`, `findOneAndUpdate()`, etc.

- scripts/website.js
**Summary**
This PR fixes the website script to correctly build for `rc`-like versions by just not reading past the last digit. (also fixed legacy `alpha` releases)
Also includes some extra fixes:
- print string that failed to parse
- trim childprocess output (remove last empty-newline)
- ignore git tag `test`
example of a failed run: https://github.com/Automattic/mongoose/actions/runs/6632207139/job/18017384534 (c28cffea0a47ce07a4b154d4435eacfbc72c56d7)
> chore(scripts/website): fix script to correctly parse "-rc" like versions

- lib/schematype.js
- types/validation.d.ts
When using a custom validator function in sub-schemas it's currently impossible to retrieve corresponding field in the schema and thus, access info like `ref` or `refPath`.
I just add a new field to `ValidatorOptions` called `fullPath` retrieved from `this.$fullPath` before the call of the validator function.
```js
const { Schema, models, model } = require("mongoose");
const User = model("User", {email:  String});
const metaSchema = new Schema({
user: {
type: Schema.Types.ObjectId,
ref: "User",
validate: {
async validator(_id, props) {
// here context is lost if we don't have the fullPath field
// because retrieving current nested field options is impossible using path
// as depth related information is no longer available
const ref = this.schema.path(props.fullPath)?.options?.ref;
const …
```
> Add fullPath to ValidatorProps

- lib/schema.js
- lib/schema/SubdocumentPath.js
- test/schema.test.js
Fix #13978
**Summary**
Deep cloning schema `paths` property causes issues when discriminator schema contains the main schema as a subdocument. This PR makes it so that we don't deep clone unnecessarily, just clone each `path` and avoid re-applying discriminators unnecessarily (discriminators are already copied in `SubdocumentPath.prototype.clone`)
**Examples**
> fix(schema): handle recursive schemas in discriminator definitions

- lib/connection.js
- lib/document.js
- test/docs/transactions.test.js
Fix #13973
**Summary**
#13973 points out that, due to the fact that we store the document's initial `savedState` during the first transaction operation, this can lead to us calling `unmarkModified()` unintentionally. Right now `$__set()` calls `unmarkModified()` if the document's `savedState` says that the value hasn't changed from the initial value. However, we also need to check if this is a transaction retry and the transaction says the document was already modified before the transaction started.
**Examples**
> fix(connection): retain modified status for documents created outside a transaction during transaction retries

- test/types/models.test.ts
- types/models.d.ts
- types/query.d.ts
Fix #14026
**Summary**
`Unpack<T>` returns the array element type if `T` is an array, or `T` otherwise. We already use `Unpacked<>` in some similar cases, like async iterators for `aggregate()`. 
**Examples**
> types(model+query): unpack arrays in distinct return type

- lib/cursor/ChangeStream.js
- test/model.populate.test.js
- test/model.test.js
Fix #14049
**Summary**
Missed a spot when handling the `hydrate` option for change streams: works fine when you use change streams as an iterator with `next()`, but doesn't work with `on()`.
**Examples**
> fix(ChangeStream): correctly handle `hydrate` option when using change stream as stream instead of iterator

- types/middlewares.d.ts
- types/models.d.ts
- types/query.d.ts
**Summary**
After https://github.com/Automattic/mongoose/pull/13618 was merged, the now missing `count()` function was not removed from the types.
cc @IslandRhythms
> fix: Remove count() from TypeScript definitions

- test/types/queries.test.ts
- types/models.d.ts
- types/query.d.ts
Fix #14062
**Summary**
Looks like we didn't fully remove `count()` from TS types when removing runtime support, this PR fixes that
**Examples**
> types(model+query): correctly remove count from TypeScript types to reflect removal of runtime support

- lib/schema.js
- test/model.updateOne.test.js
Fix #13977
**Summary**
Quick fix: looks like `schema._getPath()` just returns the array path when called with `arr.$`, which seems incorrect, and causes update validators to try to pass a string value to `SingleNested.prototype.doValidate()` in #13977. Tests pass with this change, so I think this fix is reasonable.
**Examples**
> fix: handle update validators and single nested doc with numberic paths

- lib/schema.js
- lib/utils.js
**Summary**
This pr fixes an issue index object order when it has aliases, it rename the key from the alias to the original field and maintain it's position in the object as entered by user.
**Examples**
```
const UserSchema = new Schema(
{
n: {
type: String,
alias: 'name',
},
age: {
type: Number,
}
}
)
UserSchema.index({ name: 1, age: -1 });
// The current behavior will generate index object like this 
// original fields { name: 1, age: -1 }
// after replacing the name alias with original field  { age: -1, n: 1 } ❌ 
The fix in this PR will make it work as intended and preserve the object key order
{ n: 1, age: -1 } ✅ 
```
This issue exist in version 7 and version 8 and would great to merge this PR in both versions.
Thank you!
> Index: Fix index alias object key position

- lib/helpers/populate/assignVals.js
- test/model.populate.test.js
**Summary**
Fixes this issue: https://github.com/Automattic/mongoose/issues/14098
**Examples**
> fix(populate): fix curPath to update appropriately 

- test/query.test.js
Fix #13970
**Summary**
The test failure in #13970 is because [read preference 'nearest' doesn't distinguish between primaries and secondaries](https://www.mongodb.com/docs/manual/core/read-preference/#mongodb-readmode-nearest), so in theory the query can fetch data from a secondary before data has replicated to it.
Either way, the test code is unnecessary now, this logic dates back to 2012 in https://github.com/Automattic/mongoose/commit/205a709c4e69c759709e3113f7de4f0859f1ddd4. It doesn't actually test whether the read preference is sent, and would be less flakey if read preference wasn't sent to the server. And the behavior it tries to cover is covered in other tests.
**Examples**
> test(query): remove unnecessary query test code

- test/types/document.test.ts
- types/document.d.ts
Fix #14081
**Summary**
TypeScript types for `doc.deleteOne()` still return `Promise<this>`. This PR makes `doc.deleteOne()` correctly return a `QueryWithHelpers` with correct types.
**Examples**
> types(document): correct return type for `doc.deleteOne()` re: Mongoose 8 breaking change

- test/types/models.test.ts
- types/models.d.ts
Fix #14072
**Summary**
You can set options like `timestamps` and `strict` on individual bulkWrite operations, that's handled in `castBulkWrite()`. This PR lets you set those options in TypeScript
**Examples**
> types(models): allow specifying `timestamps` as inline option for bulkWrite() operations

- test/types/queries.test.ts
- test/types/schema.test.ts
- types/index.d.ts
- types/query.d.ts
**Summary**
Fixes this issue: https://github.com/Automattic/mongoose/issues/13840
**Examples**
> fix: Strict Projection Object Typing

- lib/helpers/populate/assignRawDocsToIdStructure.js
- lib/helpers/populate/assignVals.js
- test/model.populate.test.js
Fix #14018
**Summary**
The issue is that Mongoose uses the `sort` order when assigning populated documents, which is incorrect in the case where you have virtual populate with `justOne`. In the `justOne` case, the `sort` just determines the documents you get back; the order in which the documents are assigned should be matched up by document id, not just using the sort order.
**Examples**
> fix(populate): set populated docs in correct order when populating virtual underneath doc array with justOne

- types/query.d.ts
Fix #14077
Re: #14059 
**Summary**
Based on @hasezoey 's suggestions, make query filter types based off of `RawDocType` rather than `DocType`. Tests still pass, although I haven't quite figured out how to write an automated test for this. Suggestions welcome on that front.
**Examples**
> types(query): base filters and projections off of RawDocType instead of DocType so autocomplete doesn't show populate

- types/index.d.ts
Fix #14090
**Summary**
I took a look, and with this changes it looks like intellisense picks up property names as well as update operators 
**Examples**
> types: make property names show up in intellisense for UpdateQuery

- lib/statemachine.js
- lib/types/array/methods/index.js
- test/types.array.test.js
**Summary**
Re: #11380, #13546. This one quick improvement of using `push()` instead of `concat()` already helps shave off maybe 10% off of #11380.
Before:
```
l100.avg=1140.53, total.avg=3175.7342
```
After:
```
l100.avg=1249.86, total.avg=2870.4085
```
Gonna work to see what other performance wins we can turn up.
**Examples**
> Perf improvements when creating arrays of primitives

- package.json
- scripts/website.js
**Summary**
The `docs:prepare:publish:XYZ` scripts are becoming hard to maintain and test. This cleans things up a bit so at least the logic from `docs:clean:stable` and `mv ./docs/7.x ./tmp` are moved to the `website.js` script. So the actions that don't change the branch are in one script.
**Examples**
> Island rhythms/cleanup

- docs/source/api.js
**Summary**
This PR fixes the documentation filemap, which was not done in 3ec26a0fa30e98736b859202832c5121a9ffb1c5 and so broke the website by having a empty api page
> docs(source/api): fix "index.js" -> "mongoose.js" rename

- lib/schemaType.js
- test/schematype.test.js
Fix #14070
**Summary**
#14070 makes a fair point that `validate` overwriting default schematype validators is a point of friction, and merging validators would make the default validator API much more useful. I figure it is reasonable to ship this with 8.1, what do you think @AbdelrahmanHafez @hasezoey ?
**Examples**
> feat(schematype): merge rather than overwrite default schematype validators

- lib/helpers/discriminator/applyEmbeddedDiscriminators.js
- lib/index.js
- lib/schema/SubdocumentPath.js
- lib/schema/documentarray.js
- test/document.test.js
Fix #14109
**Summary**
For #14109, re: #13898. Delay applying discriminators added using `Schema.prototype.discriminator()` on embedded schemas (document arrays and single nested paths) until you compile the top-level model. This allows adding discriminators to document arrays using `Schema.prototype.discriminator()` _after_ defining a document array with the schema, which is the primary issue in #14109.
**Examples**
> fix: allow adding discriminators using `Schema.prototype.discriminator()` to subdocuments after defining parent schema

- lib/schema.js
- test/types.documentarray.test.js
Fix #14101
**Summary**
The underlying issue in #14101 is that we have two different schema types for `options` and `options.$`, even though they should be the same. Which leads to issues when validating a subdoc of `options.$`'s caster using `options` schematype. Specifically triggering [this `if` statement](https://github.com/Automattic/mongoose/blob/12c58921bb683acfa9c78a497a6f8e684ea5c368/lib/schema/documentArrayElement.js#L71-L73), which leads to issues with nested arrays because `scope` can be an array.
The fix is to avoid cloning, so `options` and `options.$` are largely interchangeable as far as casting and validation are concerned.
**Examples**
> fix(schema): avoid creating unnecessary clone of schematype in nested array so nested document arrays use correct constructor

- types/models.d.ts
Fix #14132
**Summary**
This was mistakenly removed when we cherry-picked https://github.com/Automattic/mongoose/pull/14078 to 7.x. We fixed some of the issues in https://github.com/Automattic/mongoose/commit/e6d2fbe5fa246d6b6e527b79809a2f9130887ed3, but looks like we missed a spot.
**Examples**
> types: add back mistakenly removed findByIdAndRemove() function signature

- lib/helpers/populate/assignVals.js
- test/model.populate.test.js
**Summary**
Fix #14073 
A bit of a weird fix, but it works. The idea is that, if you call populate on `items.brand`, where `items` is a doc array and `brand` is an ObjectId ref, the `transform` option will get an array of ids as 2nd arg, not a single id. To work around this, we need to track what position in the array is being assigned, and get the original id by that index.
**Examples**
> Call transform object with single id instead of array when populating a justOne path under an array

- lib/helpers/clone.js
- lib/schema/SubdocumentPath.js
- test/document.test.js
Fix #14058
**Summary**
#14058 pointed out an unfortunate issue with the fix for #11247: `required` subdocuments without defaults end up getting minimized out, which leads to errors on subsequent saves by default unless you use the `validateBeforeSave: false` option for `save()`. This behavior is very unintuitive. With this PR, we'll skip minimizing subdocuments that have `required` set to a truthy value, including functions. So still works as expected if not `required`.
**Examples**
> fix: avoid minimizing single nested subdocs if they are required

- test/types/models.test.ts
- types/models.d.ts
Fix #14130
**Summary**
#14130 points out that, right now, calling `Model.findOneAndDelete(filter)` will return `Query<ModifyResult<THydratedDocType>>` rather than `Query<THydratedDocType>` because of the `?:` in the `& { includeResultMetadata: true }` type definition.
**Examples**
> types: make findOneAndDelete() without options return result doc, not ModifyResult

- lib/helpers/projection/isExclusive.js
- lib/model.js
- lib/query.js
- lib/queryhelpers.js
- lib/utils.js
- test/model.populate.test.js
Fix #3230
Re: #13760
Re: #13679
**Summary**
Right now, populating with `__t: 0` in projection throws a "Cannot do inclusion on field prop in exclusion projection", whereas deselecting projection works fine outside of `populate()`. The issue looks to be an ordering issue: Mongoose isn't correctly handling `__t: 0` as the first property in the `select` object, and with `populate()` Mongoose was reversing key order, so `{ name: 1, __t: 0 }` was ending up as `{ __t: 0, name: 1 }` because of `utils.object.shallowCopy`.
Both issues are fixed: Mongoose now handles `__t: 0` as first property in select object (`utils.object.shallowCopy()` was removed, no longer necessary with spread operator), and `populate()` with `{ __t: 0 }` now works as expected :+1:
**Examples**
> fix(populate): allow deselecting discriminator key when populating

- lib/document.js
- lib/model.js
- lib/schema.js
- lib/schema/bigint.js
- lib/schema/boolean.js
- lib/schema/buffer.js
- lib/schema/date.js
- lib/schema/decimal128.js
- lib/schema/number.js
- lib/schema/objectid.js
- lib/schema/string.js
- lib/schema/uuid.js
- lib/utils.js
- test/utils.test.js
**Summary**
This PR removes function `utils.options` (`lib/utils.js`) which shallow-copies objects, which is now solved with JS-native spread-operator.
i got this idea because of #14155.
my only concern would be the removal of `clone`'s that was done previously (with 6820605d5082f94bba5a5b7ccae2dfe8c5d0a0c8), no tests fail and the comments mentioned it was because `utils.options` directly assigned to the second parameter.
as for performance, i have not measured, but i would assume it is about the same, if not better thanks to the removal of `clone`s
> refactor: remove `utils.options` / `utils.object.shallowCopy`

- types/models.d.ts
**Summary**
The Typescript types definition file is missing a definition for `applyDefaults()` in `Model` Interface.
**Examples**
Error was
```
TS2339: Property 'applyDefaults' does not exist on type 'Model<Item, {}, {}, {}, any>'.
```
> add missing Type for applyDefaults

- lib/document.js
**Summary**
null check is missing in $__set method which is causing `TypeError: Cannot set properties of null (setting 'isNew')`
**Repro script**
```
var mongoose = require('mongoose')
console.log(mongoose.version)
let Schema = mongoose.Schema
var eventSchema = new Schema({
name: { type: String },
field3: { type: Schema.Types.Mixed },
__stateBeforeSuspension: {
field1: { type: String },
field2: { type: String },
jsonField: {
name: { type: String },
ex: { type: String }
}
}
})
eventSchema.add({
test: { 
val1: { type: String },
val2: { type: String }
}
})
eventSchema.add({
subSchema4: [{ field1: { type: String } }, { field2: { type: String } }]
})
eventObj.save(function (err, eventObj) {
var newObject = eventObj.toObject()
newObject.subSchema4[0] = null
eventObj.set(newObject) …
```
> null check

- lib/helpers/document/applyDefaults.js
- lib/helpers/projection/hasIncludedChildren.js
- lib/helpers/projection/isNestedProjection.js
- test/query.test.js
Fix #14115
**Summary**
Right now nested projections, like `{ prop: { subprop: 1 } }`, throw off the logic that checks for projections when applying defaults. So `{ prop: { subprop: 1 } }` will still apply defaults on all properties underneath `prop` that have defaults _other than_ `subprop`.
With this PR, we won't treat `{ prop: { subprop: 1 } }` as `{ prop: 1}` for applying defaults, which is what our `applyDefaults()` function does now.
**Examples**
> fix(document): avoid treating nested projection as inclusive when applying defaults

- lib/helpers/indexes/getRelatedIndexes.js
- test/helpers/indexes.getRelatedIndexes.test.js
**Summary**
We would like to define an index on a base model, with a partial filter so that it only applies to discriminators. It's not a discriminator index (as described in #11424), because it's not specific to any one child. 
We were surprised that these indexes were being silently ignored during syncing, and wondered if you are open to changing the behavior. Alternatively, please let me know if this key is just not necessary in the filter. I'm new to both Mongoose and MongoDB. Thanks!
**Examples**
I've added a test, where you can see that getRelatedIndexes no longer skips indexes on base models with the discriminator key, if it's just checking existence:
```
__t: { $exists: true }
```
> Allow defining index on base model that applies to all discriminators

- lib/schema/array.js
- test/model.query.casting.test.js
**Summary**
- after this PR is merged
- https://github.com/Automattic/mongoose/pull/13938
- Error in cast because options.discriminatorKey is obtained before checking if the schema is null
- here:
- https://github.com/Automattic/mongoose/pull/13938/files#diff-5078cdf8af89c694947cdcb5e60fcd3e29dda608e62642ecf5fc3eeb97e43ce1R71
- Changed to refer to context.schema as well as this PR
- https://github.com/Automattic/mongoose/commit/266804b995ae715cd4746d0e5b687e7fb96441fc
**Examples**
query:
```
{
users: {
$elemMatch: {
$and: [
{ name: "test" },
$or: [
{ is_deleted: true },
{ is_deleted: null } 
]
]
}
}
}
```
> fix: cast error when there is an elemMatch in the and clause

- docs/guides.md
- docs/layout.pug
- docs/migrating_to_8.md
- docs/tutorials/ssl.md
**Summary**
The current SSL documentation is invalid for Mongoose v8 as the MongoDB Node.js driver v6.0.0 removed the [deprecated SSL option](https://github.com/mongodb/node-mongodb-native/releases/tag/v6.0.0).
Fixes #14166 
**Examples**
The documentation has been updated to use the new equivalents:
- `sslValidate: false` -> `tlsAllowInvalidCertificates: true` & `tlsAllowInvalidHostnames: true`
- `sslCA` -> `tlsCAFile`
- `sslCRL` -> `tlsCRLFile`
- `sslCert` -> `tlsCertificateKeyFile`
- `sslKey` -> `tlsCertificateKeyFile`
- `sslPass` -> `tlsCertificateKeyFilePassword`
- `sslValidate` -> `tlsAllowInvalidCertificates`
- `tlsCertificateFile` -> `tlsCertificateKeyFile`
> docs - update TLS/SSL guide for Mongoose v8 - MongoDB v6 driver deprecations

- lib/schema/bigint.js
- lib/schema/boolean.js
- lib/schema/buffer.js
- lib/schema/date.js
- lib/schema/number.js
- lib/schema/string.js
- lib/schema/uuid.js
- lib/schemaType.js
- test/model.findOneAndUpdate.test.js
- test/schema.select.test.js
Fix #14114
**Summary**
Currently, CastError only shows the path relative to parent, which is less than ideal in the case where casting update throws an error; in that case, Mongoose just throws the CastError, rather than wrapping the CastError in a `ValidationError` like how `save()` does. This PR makes CastError use `$fullPath` instead when casting updates
**Examples**
> fix(update): set CastError path to full path if casting update fails

- test/types/queries.test.ts
- types/models.d.ts
- types/query.d.ts
**Summary**
Fix #14190; findByIdAndDelete() is currently returning `ModifyResult` even if options isn't set
**Examples**
> Fix return types for findByIdAndDelete overrides

- docs/guide.md
- docs/migrating_to_8.md
- lib/schema.js
Fix #14194
**Summary**
Some docs improvements to clarify that `_id: false` schema option is primarily for subdocuments, not top-level documents
**Examples**
> docs: clarify disabling `_id` on subdocs

- lib/cursor/ChangeStream.js
- test/model.test.js
Fix #14177
**Summary**
It looks like the potential bug we mentioned in #12890 was actually correct behavior; MongoDB change streams can emit 'error' events after 'close'. The original reason for this change was to avoid a flakey test, so I think we should just remove the `if (ev === 'error' && this.closed)` check.
**Examples**
> fix(ChangeStream): avoid suppressing errors in closed change stream

- lib/helpers/discriminator/applyEmbeddedDiscriminators.js
- test/document.test.js
Fix #14162
**Summary**
#14162 points out that if you reuse a schema that has embedded discriminators defined using `Schema.prototype.discriminator()`, you'll get an OverwriteModelError because Mongoose already applied discriminators to the schema type. This PR makes it so that applying discriminators to the same SchemaType twice is a no-op.
**Examples**
> fix(discriminator): handle reusing schema with embedded discriminators defined using Schema.prototype.discriminator

- docs/tutorials/findoneandupdate.md
- test/model.findOneAndUpdate.test.js
**Summary**
`findOneAndUpdate` docs still use `rawResult`, and it looks like we had a broken reference to an old test name as well. This PR fixes that.
Fix #14207
**Examples**
> docs: update findOneAndUpdate tutorial to use includeResultMetadata

- lib/document.js
- test/document.test.js
Fix #14205
**Summary**
Still debugging the need for the `valForKey === null` check, but otherwise this works. Without the `=== null` check, the `with conflicted data in db` test in `model.test.js` fails; it looks like because we don't store validation errors on nested paths. Will take another look tomorrow.
**Examples**
> fix(document): allow setting nested path to `null`

- types/models.d.ts
- types/query.d.ts
Fix #14204
**Summary**
While Mongoose's current options typings are technically correct because of chaining, using stricter types in the Model functions that return a query lines up better with how developers use it. Plus with `[other: string]: any`, devs can still use other options.
I only made these changes for `deleteX()`, `replaceOne()`, and `updateX()` because Mongoose's `QueryOptions` has a `projection` property that doesn't line up exactly with the MongoDB Node driver's: the MongoDB Node driver's `projection` type is just `Record<string, any>`, doesn't take into account schema definitions.
**Examples**
> types(model+query): use stricter typings for updateX(), replaceOne(),deleteX() Model functions

- lib/document.js
- lib/types/subdocument.js
- test/document.modified.test.js
- types/document.d.ts
Re: #14024
**Summary**
Some of the work we did to make `isModified()` more consistent with what paths Mongoose validates and sends to MongoDB caused some trouble for users, so this PR adds a `ignoreAtomics` option to `isModified()` that can help smooth out the issues. Basically, with this `ignoreAtomics` option, `isModified()` will return `false` if passed an array path where the top-level array has a non-`$set` atomic operator. So if `post.comments` has a `$push` and no `$set`, then `post.isModified('comments.0.title', { ignoreAtomics: true })` will return `false`.
**Examples**
> fix: add ignoreAtomics option to isModified() for better backwards compatibility with Mongoose 5

- test/types/schema.test.ts
- types/index.d.ts
**Summary**
Adding the missing `omit()` method to the `Schema` class type definition
**Examples**
> types(schema): add missing `omit()` method

- types/models.d.ts
Fix #14234
Re: #8782
Re: #8778
**Summary**
#14234 points out that the `strict` option we added to `bulkWrite()` top level options in #8778 isn't reflected in `types`. This PR adds that.
**Examples**
> types(model): add missing `strict` property to `bulkWrite()` top level options

- lib/query.js
- test/query.test.js
**Summary**
It looks like with `findOne()`, `findOneAndDelete()`, and `findOneAndUpdate()` Mongoose double calls query `transform()` functions. This PR removes the obsolete `_wrapThunkCallback()` function that causes this issue.
**Examples**
> avoid double-calling query transform() with findOne()

- lib/model.js
- test/model.populate.test.js
Fix #14231
**Summary**
We handle deselecting `_id` in `populate()` using the following syntax: `await U.findOne({ name: 'u1' }).populate('comments', '-_id');` but putting `-_id` in an array `await U.findOne({ name: 'u1' }).populate('comments', ['-_id']);` leads to a malformed result document where `comments` is `[ { '0': '-_id' } ]` due to how we shallow copy select conditions before removing `_id`. So we need an additional case to avoid using `{ ... }` to shallow copy an array.
**Examples**
> fix(populate): handle deselecting `_id` with array of fields in `populate()`

- lib/model.js
Fix #14238
**Summary**
Fixed an out of date example that still uses callbacks; we dropped support for callbacks in Mongoose 7.
**Examples**
> docs(model): remove callback example for `ensureIndexes()`

- lib/helpers/discriminator/applyEmbeddedDiscriminators.js
- test/document.test.js
Fix #14245
**Summary**
#14245 points out that we don't correctly call `applyEmbeddedDiscriminators()` on the discriminator schema, which leads to missing discriminators on self-referential discriminator schemas. This PR fixes that.
**Examples**
> fix(document): handle embedded recursive discriminators on nested path defined using Schema.prototype.discriminator

- lib/connection.js
- test/connection.test.js
- test/types/connection.test.ts
- types/connection.d.ts
**Summary**
We have `dropCollection()` and `dropDatabase()` helpers on connections, but not `listCollections()`, so there's no way to list all connections in MongoDB without bypassing Mongoose. This PR adds a new `Connection.prototype.listCollections()` helper that wraps MongoDB's `listCollections()`, including handling the fact that `listCollections()` returns a cursor.
**Examples**
> feat(connection): add listCollections() helper to connections

- docs/guide.md
- lib/connection.js
- lib/drivers/node-mongodb-native/connection.js
- lib/model.js
- lib/mongoose.js
- lib/schema.js
- lib/validOptions.js
- types/connection.d.ts
- types/inferschematype.d.ts
- types/models.d.ts
**Summary**
cc @alexbevi 
Atlas search indexes are special indexes for Atlas text search. There's distinct functionality to create Atlas search indexes in the MongoDB Node driver, so I added the following functionality:
1. Model helpers: `Model.createSearchIndex()`, `Model.updateSearchIndex()`, `Model.dropSearchIndex()` to wrap the MongoDB Node driver's `Collection.prototype.createSearchIndex()`, etc. functions
2. Schema helper to define search indexes `Schema.prototype.searchIndex()`
3. An `autoSearchIndex` option analogous to `autoIndex` that opts in to automatically creating search indexes. Unlike `autoIndex`, `autoSearchIndex` is false by default.
Here's an example of this code in action:
```
mongoose.set('autoSearchIndex', true);
const schema = new mongoose.Schema({ name: String }, { …
```
> Add Atlas search index helpers to Models and Schemas

- lib/types/array/methods/index.js
- test/document.test.js
Fix #14244
Re: #4322
**Summary**
When we originally implemented `push()` with `$position` in #4322, we made it so that calling `push()` with different `$position` arguments would throw a sync error. This decision is not completely unreasonable because the MongoDB server doesn't support `$push` with different `$position` arguments. However, this decision is inconsistent with the rest of the array API: as a general rule, Mongoose arrays revert to just making the operation a `$set` on the entire array when Mongoose can't represent the user's desired update using atomic operators. With this PR, we will convert from atomic update to `$set` on the whole array if the user calls `push()` with multiple different `$position` arguments. 
With this change, a modified version of the repro script from …
> fix(document): allow calling `push()` with different `$position` arguments

- lib/drivers/node-mongodb-native/collection.js
- test/collection.test.js
Fix #14184
**Summary**
#14184 points out that buffer timeouts with `find()` silently time out in 6.x. This PR makes it so that the [`removeQueue()` call in the buffer timeout callback](https://github.com/Automattic/mongoose/blob/4b6d208ead94152643f95d2503b235e2c264ef64/lib/drivers/node-mongodb-native/collection.js#L171) can actually find the `find()` call. `removeQueue()` searches by name and args, and the `this.addQueue(() => {})` pushes an anonymous function onto the queue.
**Examples**
> fix(collection): correctly handle buffer timeouts with `find()`

- test/types/queries.test.ts
- types/query.d.ts
Fix #14275
**Summary**
8.1 accidentally removed a few Mongoose-specific query options, including `runValidators`. This PR adds those options back, and adds test to protect against future regression.
**Examples**
> types(query): add missing `runValidators` back to MongooseQueryOptions

- test/types/queries.test.ts
- types/query.d.ts
Fix #14282
**Summary**
Missed a couple of options in #14278
**Examples**
> types(query): add back `context` and `setDefaultsOnInsert` as Mongoose-specific query options

- lib/document.js
- test/document.test.js
Fix #14269
**Summary**
Quick improvement for handling spread docs in `$set()`. `true` means we retain existing properties, so `{ ...doc, foo: true }` will still have `foo: true`.
Worth noting that we don't currently have a good way of handling key order - I'm looking into that. But `{ foo: true, ...doc }` currently will still have `foo: true`, even if `doc` has `foo: false`.
**Examples**
> fix(document): handle setting nested path to spread doc with extra properties

- lib/model.js
- test/model.test.js
Fix #14281
**Summary**
Quick improvement to error message, related work #2005.
**Examples**
> fix(model): throw readable error when calling `Model()` with a string instead of `model()`

- test/types/connection.test.ts
- types/connection.d.ts
> add type for createCollections

- docs/migrating_to_7.md
- lib/cursor/aggregationCursor.js
- lib/cursor/queryCursor.js
**Summary**
Currently, [documentation](https://mongoosejs.com/docs/api/querycursor.html#QueryCursor.prototype.eachAsync()) for QueryCursor.prototype.eachAsync write that it takes a callback as a parameter.
However, with the update to version 7, eachAsync no longer supports callbacks. - [Show commits](https://github.com/Automattic/mongoose/commit/b911bef9e41ed622ec3961b03d130edc5c2e4c09#diff-b9b6c3043d3ed32b9229dc3abc6d06af6f84d23106dc129cdefe46db4f89de54)
So, I fix parameters of eachAsync and the migrating guide to 7.
it has two more changes.
1. Add `AggregationCursor.prototype.next`, which was missing the guide.
2. fix conditional statements conditional in `QueryCursor.prototype.next`
> fix(QueryCursor): eachAsync parameter of AggregationCursor and QueryCursor

- lib/helpers/pluralize.js
**Summary**
Adds pluralization for woman, cactus, focus, fungus, nucleus, and fixes the pluralization of virus from `viri` to [`viruses`](https://simple.wiktionary.org/wiki/viruses)
**Examples**
woman -> women
virus -> viruses
cactus -> cacti
focus -> foci
fungus -> fungi
nucleus -> nuclei
> Adding missing pluralizations, fixing pluralization: virus -> viruses

- docs/compatibility.md
Per @vkarpov15's change in #14230, note in the 5.13 docs that Mongoose 5.13 is compatible with MongoDB Server 5.0.
> Update 5.13 compatibility docs

- lib/helpers/populate/setPopulatedVirtualValue.js
- lib/schema.js
- test/model.populate.test.js
Fix #14285
**Summary**
Looks like the virtual populate setter doesn't correctly return the populated doc, this PR fixes that. Also did a quick bit of refactor to make it so that we have less populate logic in `lib/schema.js`.
**Examples**
> fix(populate): call setter on virtual populated path with populated doc instead of undefined

- lib/model.js
- test/model.test.js
- types/models.d.ts
Fix #14296
**Summary**
Making changes to schemas after compiling a model is a common feature request. We can support that by adding an extra model function `recompileSchema()` that applies schema changes after model compilation.
**Examples**
> feat(model): add `recompileSchema()` function to models to allow applying schema changes after compiling

- test/types/models.test.ts
- types/models.d.ts
Fix #14303
**Summary**
Quick fix for correct return type when calling `findOneAndUpdate()` with `includeResultMetadata: true` and `lean: true`: return a `ModifyResult` with the lean doc type.
**Examples**
> types(model): correct return type for findOneAndUpdate with `includeResultMetadata` and `lean` set

- docs/timestamps.md
Fix #14309
**Summary**
Our docs could be a bit more explicit about how `findOneAndReplace()` and `replaceOne()` update timestamps. Unfortunately there's no way for Mongoose to prevent overwriting timestamps in with `replaceOne()` and `findOneAndReplace()`, so we should document this and avoid implying that Mongoose prevents updating `createdAt` on all query methods.
**Examples**
> docs(timestamps): clarify that `replaceOne()` and `findOneAndReplace()` overwrite timestamps

- lib/document.js
- lib/schema.js
- lib/types/documentArray/methods/index.js
- lib/types/subdocument.js
- test/document.test.js
- types/models.d.ts
Fix #14315
**Summary**
Right now document arrays' `toString()` function never includes virtuals in output, even if `toObject.virtuals` is set. This PR makes it so that we 1) bubble `toObject` and `toJSON`, minus `transform`, to implicitly created schemas, 2) don't hard-code `virtuals: false` when calling `inspect()` on subdocuments.
**Examples**
> fix: include virtuals in document array `toString()` output if `toObject.virtuals` set

- types/query.d.ts
Fixes - #14341 
**Summary**
Fixed the issue of unable to add arbitrary fields in the `options` object for Model functions whose `options` parameter had the type of `MongooseQueryOptions`, such as `deleteMany`, `deleteOne`, `replaceOne`, `updateMany`, `updateOne`, etc.
> Added typescript support for arbitrary fields for the options parameter of Model functions which are of type MongooseQueryOptions

- lib/helpers/populate/getModelsMapForPopulate.js
- test/model.populate.test.js
Fix #14249
**Summary**
#14249 turns out to be an easy fix: it looks like we don't correctly handle `ref()` functions that return a model instance. `available[modelName]` then indexes based on the source code of the `model` constructor :disappointed: . This PR fixes that. 
**Examples**
> fix(populate): handle ref() functions that return a model instance

- lib/document.js
- lib/model.js
- test/model.hydrate.test.js
- test/types/models.test.ts
- types/models.d.ts
> Island rhythms/deeply hydrate doc

- lib/cursor/aggregationCursor.js
- test/aggregate.test.js
Fix #14331
**Summary**
Aggregation cursor doesn't support `transform` option currently, which is inconsistent with query cursor API. This PR makes it so that calling `Model.aggregate(pipeline).cursor({ transform })` adds a transform to the aggregation cursor's `_transforms`.
**Examples**
> fix(cursor): make aggregation cursor support `transform` option to match query cursor

- lib/plugins/trackTransaction.js
- test/docs/transactions.test.js
**Summary**
When we `$set` an array, it looks like Mongoose converts the array to an object. This PR makes sure we handle array atomics correctly when we reset the document after a transient transaction error.
Fix #14340
**Examples**
> Avoid corrupting $set-ed arrays when transaction error occurs

- docs/middleware.md
- lib/model.js
- test/model.middleware.test.js
- test/types/middleware.test.ts
- types/index.d.ts
Fix #7893
Fix #14263
**Summary**
Add support for `schema.pre('bulkWrite', function(next, ops) { ... })` and `schema.pre('createCollection', function() { ... })`. Support for 2 new model middleware functions :+1:
**Examples**
> feat: add middleware for bulkWrite() and createCollection()

- docs/connections.md
Fix #14266
**Summary**
We don't currently mention `asPromise()` in connection docs, but `asPromise()` is necessary for error handling when using `createConnection()`.
**Examples**
> docs(connections): add note about using `asPromise()` with `createConnection()` for error handling

- lib/cursor/ChangeStream.js
- test/model.test.js
**Summary**
Hi. I've implemented receiving resumeTokenChanged logic on 6.x.
https://github.com/Automattic/mongoose/issues/14349
This code is picked from this PR https://github.com/Automattic/mongoose/pull/13736 and I've changed a bit for 6.x
**Examples**
> Receive resumeTokenChanged changeStream event also in 6.x

- types/query.d.ts
**Summary**
A `Record<string, string>` is a valid argument to `Query.select`, but Typescript currently rejects it since it doesn't overlap with `string | string[] | Record<string, number | boolean | object>`.
**Examples**
```ts
export const selectTypeTest = async (): Promise<void> => {
type Test = {
_id: mongoose.Types.ObjectId;
testProp: string;
createdAt: number;
updatedAt: number;
};
const schema = new mongoose.Schema<Test>(
{
testProp: { type: String },
createdAt: { type: Number },
updatedAt: { type: Number },
},
{
timestamps: { currentTime: () => new Date().valueOf() },
}
);
const M = mongoose.model<Test>("Test", schema);
await M.create({ testProp: "hello" });
const myDoc = await M.findOne({}).select({ _id: 0, renamed: "$testProp" }).lean().exec();
/* …
```
> Record<string, string> as valid query `select` argument

- types/models.d.ts
- types/query.d.ts
**Summary**
Addresses #14378. `MongooseQueryOptions` type was recently edited to include `& { [other: string]: any }` in order to support arbitrary options. This implementation broke Typescript support for all of the official Mongoose option properties, in the sense that there's no more auto-completion when you start typing something like "runValidators", and there's no in-line JSDoc displayed.
This is caused by the use of the `Omit` Typescript utility in the type for `options` in `updateOne`, `updateMany`, and a few others. Resolution is to redo the implementation with a build-up approach instead of using `Omit`.
**Examples**
See example and screenshots in #14378
> [fix] Add back Typescript help for true Mongoose-specific `options` for updateOne, updateMany, etc. 

- types/models.d.ts
- types/utility.d.ts
Fixes #14378
**Summary**
Fixes the missing typescript details from the `options` parameter of functions like `updateMany()`, `updateOne()`, etc. The issue happened because the `Omit` in `Omit<MongooseQueryOptions<TRawDocType>, 'lean'>` was making the type of the keys vague because `MongooseQueryOptions` contains `[other: string]: any`. To fix this, introdduced a new TS Util function called `ExcludeKeys` which fixes this logic without weakening the type
**Examples**
The property `timestamps` and other such params are now visible
Its still supporting arbitrary options like `fallback` without any type issues
> fix: missing typescript details on options params of updateMany, updateOne, etc.

- lib/query.js
- test/query.test.js
- types/query.d.ts
Fix #14365
**Summary**
Right now, `sort(null)` is a no-op. There's no good way to unset the current sort option other than `delete query.getOptions().sort`, which works but looks a bit janky. This PR adds `q.sort(null, { override: true })`, the `override` option lets you explicitly override the current sort.
**Examples**
> feat(query): add `options` parameter to `Query.prototype.sort()`

- test/types/querycursor.test.ts
- types/query.d.ts
Fix #14374
**Summary**
Right now, using `for await` with a cursor doesn't quite work in TypeScript: you get `DocType[]` rather than `ResultType`. Similarly, that means `populate<Paths>()` doesn't work right with `cursor()`.
**Examples**
> types(querycursor): correct cursor async iterator type with `populate()` support

- lib/model.js
- test/connection.test.js
Fix #14372
**Summary**
Initial implementation of `lean` for `insertMany` in #8507 made `lean` just skip validation, not hydrating docs, which makes `insertMany` with `lean` still significantly slower. I'm inclined to change it so that `insertMany` with `lean` also skips hydrating Mongoose docs, because the name `lean` implies that we skip all hydration and other Mongoose-specific stuff similar to [query lean](https://mongoosejs.com/docs/tutorials/lean.html).
**Examples**
> perf(model): make `insertMany()` `lean` option skip hydrating Mongoose docs

- lib/helpers/schema/applyWriteConcern.js
- test/docs/transactions.test.js
Fix #11382
**Summary**
You aren't supposed to set write concern on operations in a transaction, rather set writeConcern on the transaction as a whole:
This PR makes it so that Mongoose doesn't apply schema-level write concern to operations that are within a transaction
**Examples**
> fix(schema): avoid applying default write concern to operations that are in a transaction

- lib/document.js
- lib/schema.js
Re: #14113
**Summary**
Without this change:
```
$ node gh-14113.js 
6.12.6
mongoose spendTime: 24358 average: 48.716
$ node gh-14113.js 
6.12.6
mongoose spendTime: 24956 average: 49.912
$ node gh-14113.js 
6.12.6
mongoose spendTime: 25182 average: 50.364
```
With this change:
```
$ node gh-14113.js 
6.12.6
mongoose spendTime: 24003 average: 48.006
$ node gh-14113.js 
6.12.6
mongoose spendTime: 24222 average: 48.444
$ node gh-14113.js 
6.12.6
mongoose spendTime: 24247 average: 48.494
```
Seems like a small difference, but if you remove `init` entirely the average goes down to about 47.5, so this is actually a fairly significant speedup of `init()`. I'm assuming that the rest of the relatively small performance degradation in Mongoose 5 and 6 is due to bson slowdowns discussed in #13456. …
> perf(document+schema): small optimizations to make `init()` faster

- lib/connection.js
- test/connection.test.js
Fix #14377
**Summary**
`connection.on('error', fn)` should mean that `openUri()` errors shouldn't count as unhandled exceptions.
**Examples**
> fix(connection): avoid unhandled error on createConnection() if on('error') handler registered

- docs/version-support.md
**Summary**
This PR updates `version-support` to:
- indicate `Mongoose 5` is completely EOL, no requestion backporting of anything
- indicate `Mongoose 6` does not accept requesting backporting of features anymore
> Update version support documentation for mongoose 5 & 6

- lib/model.js
- lib/query.js
- test/types/models.test.ts
- types/models.d.ts
Re: #14400
**Summary**
Bringing MongoDB's `AnyBulkWriteOperation` type into Mongoose, and overriding `update` with Mongoose's `UpdateQuery` type to account for query casting. Currently, the issue is that `bulkWrite([{ updateOne: { $set: { date: '2023-06-01' } } }])` fails type checks because `date` needs to be of type date. And passing in `AnyKeys<>` is a no-go because that messes up MongoDB's `$addToSet` type checking and makes the `bulkWriteAddToSet` test in `models.test.ts` fail
**Examples**
> types(model): make `bulkWrite()` types more flexible to account for casting

- test/types/PipelineStage.test.ts
- types/pipelinestage.d.ts
**Summary**
With MongoDB releasing the new vector search index & pipeline stage, Mongoose is missing this PiplineStage, which creates a compilation error in TypeScript. The proposal is to add support for this new PipelineStage - VecrorSearch
The motivation is to maintain & support the typesafe aggregation pipeline in Mongoose.
This PR is aiming to solve [this issue](https://github.com/Automattic/mongoose/issues/14428)
**Examples**
```
const contentsSchema = new mongoose.Schema({
embedding: {
type: [Number],
},
title: String,
});
export const Contents = mongoose.model(
"Contents",
contentsSchema,
"contents",
);
const result = await Contents.aggregate([
{
$vectorSearch: {
index: "title_vector_index",
path: "embedding",
filter: {someField: "value",} …
```
> Add TypeScript interface for the new PipelineStage - Vector Search - solving issue #14428

- test/types/docArray.test.ts
- test/types/schema.test.ts
- types/inferschematype.d.ts
Fix #14367
**Summary**
The root cause of #14367 looks to be a minor inconsistency in type inference: on L232 we had `ObtainDocumentType<Item, any, { typeKey: TypeKey }>[]`, and on L238 we have `Types.DocumentArray<ObtainDocumentType<Item, any, { typeKey: TypeKey }>>`. If these 2 are consistent, the code from #14367 compiles. Not 100% sure why, but we have tests proving this does the right thing.
**Examples**
> types: consistently infer array of objects in schema as a DocumentArray

- lib/document.js
**Summary**
In the process of creating a new document, I encountered a TypeError. Upon investigating the error stack, it revealed that the issue was related to an undefined property 'ref' during the execution of model.$set in the Mongoose library.
Upon further examination, I noticed that there was a missing null check for schema.options[typeKey][0], where typeKey is a crucial part of the schema. In my case, schema.options[typeKey][0] was undefined, leading to a subsequent error when trying to access the 'ref' property. To address this issue, I have proposed a pull request to the Mongoose repository that includes the necessary null check for schema.options[typeKey][0]. This modification ensures a smoother handling of cases where the referenced type is absent.
> Added Null check in case schema.options['type'][0] is undefined

- lib/model.js
- test/document.test.js
Fix #14420
Re: #13782
**Summary**
The issue in #14420 is that the update to `save()` is `{ $set: { sub: {} } }`, which gets minimized away by #13782. With this PR, we'll only minimize top-level properties of update operators in the `save()` update. So in the #14420 case, we'll just minimize `sub` to `null`, but leave the rest of the update. I think this is the most consistent way to handle #14420 without undoing the changes we made in #13782.
**Examples**
> fix(model): improve update minimizing to only minimize top-level properties in the update

- lib/schemaType.js
- test/schematype.test.js
- types/schematypes.d.ts
> Add function `SchemaType.prototype.validateAll`

- scripts/tsc-diagnostics-check.js
- test/types/queries.test.ts
- types/query.d.ts
Re: #14398
Fix #14397
@FaizBShah WDYT?
**Summary**
#14398 but with a couple of changes:
1. Avoided changing `FilterQuery<RawDocType>` back to `FilterQuery<DocType>` for everything but `getFilter()` and `getQuery()`. For some reason, tests fail without that
2. Fixes for the #11964 test. The fact that we had to change that test was concerning, but after diving down the rabbit hole I'm convinced the #11964 test is just incorrect and will never work unless `FilterQuery` types to `any`. [Here's a couple of TypeScript playground examples demonstrating the issue](https://www.typescriptlang.org/play?#code/PTAEGUAsHsHcGdQBdIEMkBpQFMBu2A7UASwDNQBPaAV1FQBN7QADAMlAG8T6AuUeJACdiBAOagAvsywpsoQdnjUANkhHikFAA5z60RQQDkSUAWwBjRfFTDlFAFAhQafHSLNivfkPXNQWwWgdQU17TR1QABVQAF5Obj4zfEFJUHYuTz4BYTFJAG57c2gCAVAADz5 …
> types: improve the typing of FilterQuery<T> type to prevent it from only getting typed to any

- lib/schema.js
- test/schema.test.js
> fix: array schema definitions with `of` keyword

- types/index.d.ts
- types/schemaoptions.d.ts
**Summary**
Support for MongoDB Atlas search indexes was added in [#14251](https://github.com/Automattic/mongoose/pull/14251) but the types for `Schema.searchIndex` and the `autoSearchIndex` option were missed.
Add these types so that the typescript definitions match the capabilities of the JavaScript version of `mongoose`.
**Examples**
Not applicable. Just adding type definitions for existing functionality.
> types(schema): add missing search index types

- lib/document.js
- lib/model.js
- lib/schema/documentarray.js
- lib/schematype.js
- test/document.test.js
**Summary**
#14418 is a tricky issue, there's a couple of causes:
1. [This `toObject()` call](https://github.com/Automattic/mongoose/blob/d516f50f2073f69c62cabd6bf0e765e08abb0208/lib/schema/documentArray.js#L456) swallows up the fact that you're setting the doc array element to a document that potentially includes populated values
2. [This check fails](https://github.com/Automattic/mongoose/blob/d516f50f2073f69c62cabd6bf0e765e08abb0208/lib/document.js#L1381) because `$__.wasPopulated` was `true` rather than an object with `value`
**Examples**
> Avoid depopulating populated subdocs underneath document arrays when copying to another document

- types/query.d.ts
- types/schemaoptions.d.ts
**Summary**
This PR changes `Query.getFilter` and `Query.getQuery` to use `RawDocType` again, as this is the same argument as in `.find`'s `filter` parameter.
In addition also pass-through the `QueryHelpers` and `DocType` in `SchemaOptions`'s `query`'s object (otherwise there is a test failure).
This change from e3f320515297240f6bca4ec6be7b14c442a97a46 somehow made it so that `PopulatedDoc<Document, RefType>` could not be narrowed down to the used `RefType` anymore, and i dont know why, but this change fixed it again for typegoose.
> fix(types/query): bring "getFilter" and "getQuery" in-line with "find" and other types

- docs/middleware.md
The update method was removed in v7.2 along with the middleware/hook it comes with. However the current v8 docs still shows that udpate hook is supported, which is invalid.
I had an issue after upgrading from v6 - v8 with the update hook. The docs misled me and it took me about 5hours before I got to know that update is no longer supported in v8.
> Removed unused hook from docs

- lib/document.js
- lib/schema/documentArray.js
- test/document.test.js
Fix #14414
**Summary**
Setting `validateAllPaths` makes Mongoose run validation on all paths in the schema, regardless of change tracking. This is useful because sometimes change tracking makes Mongoose skip running validators that users expect to run, so handy to have a mechanism to run all validators if the end user prefers that approach.
**Examples**
> feat(document): add `validateAllPaths` option to `validate()` and `validateSync()`

- lib/document.js
- test/document.test.js
Fix #14446
**Summary**
#14446 points out that we continue to loop through and try to create properties when getting nested paths underneath a virtual even if the virtual returned a non-object. Since this will always throw an error, we should just avoid that and assume this is just the virtual returning a non-object by design.
**Examples**
> fix(document): handle virtuals that are stored as objects but getter returns string with toJSON

- lib/schema.js
- test/schema.test.js
Fix #14457
**Summary**
Need to be careful to avoid adding multiple id getters when reusing the same schema multiple times
**Examples**
> fix(schema): deduplicate idGetter so creating multiple models with same schema doesn't result in multiple id getters

- lib/helpers/discriminator/applyEmbeddedDiscriminators.js
- lib/index.js
- lib/schema.js
- test/schema.test.js
Fix #14448
**Summary**
Quick fix to allow calling `Schema.prototype.discriminator()` with discriminator options, right now no way to set a custom discriminator value with `Schema.prototype.discriminator()`.
**Examples**
> fix(schema): support setting discriminator options in Schema.prototype.discriminator()

- lib/model.js
- test/document.test.js
Fix #14445
**Summary**
Right now the Mongoose 8 functionality that minimizes empty documents when updating sets empty subdocuments to `null`, which is problematic because defaults don't kick in on null values. With this PR, we'll instead $unset empty subdocuments.
**Examples**
> fix(document): make update minimization unset property rather than setting to null

- test/types/schema.test.ts
- types/schematypes.d.ts
- types/validation.d.ts
Fix #14496
**Summary**
The [SchemaType.prototyp.validate API docs](https://mongoosejs.com/docs/api/schematype.html#SchemaType.prototype.validate()) include an example of returning the original error message that the validator threw instead of Mongoose's automatic message formatting:
```javascript
schema.path('name').validate({
validator: function() { throw new Error('Oops!'); },
// `errors['name']` will be "Oops!"
message: function(props) { return props.reason.message; }
});
```
The TypeScript types disallow this currently.
**Examples**
> types(validation): support function for validator `message` property,  and add support for accessing validator `reason`

- lib/model.js
- lib/mongoose.js
**Summary**
Right now calling `setDriver()` after `mongoose.model()` leaves models in an inconsistent state where they point to the old default connection and collections derived from the old default connection.
**Examples**
> fix(mongoose): make setDriver() update mongoose.model() connections and collections

- lib/helpers/discriminator/applyEmbeddedDiscriminators.js
- lib/helpers/model/discriminator.js
- lib/model.js
- lib/schema/subdocument.js
- lib/schemaType.js
- test/model.test.js
Fix #14444
**Summary**
Right now `recompileSchema()` applies most schema changes, but not additional `Schema.prototype.discriminator()` or `SchemaType.prototype.discriminator()` calls. This PR makes `recompileSchema()` go through and reapply every discriminator that was added to the schema.
**Examples**
> fix(model): make `Model.recompileSchema()` also re-apply discriminators

- docs/connections.md
**Summary**
It's just a simple typo. The "errors" string was repeated twice.
> chore: remove typo

- lib/connection.js
- test/connection.test.js
- test/types/connection.test.ts
- types/connection.d.ts
> feat: `listDatabases()` function

- docs/middleware.md
- test/types/middleware.test.ts
**Summary**
Docs and test case re: #14305. The clearest issue reported in #14305 is that our middleware docs has no examples of using async functions for post hooks.
**Examples**
> Add documentation for calling `schema.post()` with async function

- test/types/queries.test.ts
- types/query.d.ts
Fix #14473
Re: #14459
Tagging @FaizBShah @sderrow  re: #14436, #14397
**Summary**
It looks like the major reason for `FilterQuery<T>` setting all props to `any` is because TypeScript disallows setting an object with a concrete type to an abstract type. This includes generic function parameters, like calling a function with `FilterQuery<>` as a parameter where `FilterQuery<>` depends on the generic. For example:
```ts
function findById<ModelType extends {_id: Types.ObjectId | string}>(model: Model<ModelType>, _id: Types.ObjectId | string){
// Will not compile without `as FilterQuery<ModelType>`, even if `FilterQuery<T> = T` because `FilterQuery`
// depends on generic type `ModelType`
return model.find({_id: _id});
}
```
From [this SO …
> types(query): make `FilterQuery` props resolve to `any` for generics support

- lib/connection.js
- lib/drivers/node-mongodb-native/connection.js
- test/connection.test.js
Re: #14506
Re: #9048
**Summary**
As a general rule we should move any connection helper that isn't just transparently calling `this.db.functionName()` to node-mongodb-native driver. `listDatabases()` is close, but the extra `admin()` call makes it violate this rule.
Also refactored out the `this.readyState === STATES.connecting` check into a helper so we aren't copy/pasting that in every helper.
**Examples**
> refactor(connection): move listDatabases implementation to node-mongodb-native driver

- lib/helpers/populate/assignVals.js
- test/model.populate.test.js
Fix #14494
**Summary**
If there's a `match` function, `sift` will always filter out `null` results, so we may populate docs in incorrect order.
**Examples**
> fix(populate): avoid match function filtering out `null` values in populate result

- test/types/middleware.test.ts
- test/types/models.test.ts
- types/index.d.ts
- types/models.d.ts
**Summary**
The `bulkWrite` options are incorrectly typed. `timestamp` does not exists as an option on `updateOne`/`updateMany` (there was a test but it didn't work, I fixed this as well). And the type incorrectly showed a timestamp as options to `bulkWrite`, which doesn't work. 
Also extended the mongodb `BulkWriteOptions` making it easier to use the `MongooseBulkWriteOption` without the need to also always extend mongodb.
**Examples**
See fixed test
> types(models): fix incorrect bulk write options

- test/types/docArray.test.ts
- types/types.d.ts
Fix #14469
**Summary**
Due to missing generic, `toObject()` and `toJSON()` on array subdocs currently returns `any`.
**Examples**
> types(DocumentArray): pass DocType generic to Document for correct toJSON() and toObject() return types

- lib/model.js
- types/models.d.ts
**Summary**
Fix #14450 . Looks like we missed a spot when implementing the search indexes API
**Examples**
> Add `Model.listSearchIndexes()`

- lib/helpers/populate/getModelsMapForPopulate.js
- lib/model.js
- lib/schema.js
- lib/virtualType.js
- test/model.hydrate.test.js
**Summary**
In #14503, the issue is that `hydrate()` sets the populated docs in the populated virtual, but doesn't hydrate them. The docs are still lean. This PR makes `hydrate()` hydrate those populated docs if `hydratedPopulatedDocs` is set.
**Examples**
> Make `hydrate()` recursively hydrate virtual populate docs if `hydratedPopulatedDocs` is set

- test/types/populate.test.ts
- test/types/queries.test.ts
- types/query.d.ts
Fix #14441
**Summary**
When you pass a generic to `populate()`, like `populate<{ child: Child }>('child')`, to override the result type, calling `toObject()` loses the `{ child: Child }` type override by default.
Future work: if passing `depopulate: true` to `toObject()`, that removes the populated paths.
**Examples**
> types(query+populate): apply populate overrides to doc `toObject()` result

- lib/schema/documentArray.js
- test/model.test.js
- types/document.d.ts
- types/types.d.ts
Fix #14520
**Summary**
I don't see any reason why `IdType` can't default to `unknown`, tests pass and `unknown` seems more correct. @hasezoey can you please check if this causes any problems for typegoose?
**Examples**
> types(document): make document _id type default to unknown instead of any

- lib/document.js
- lib/types/array/methods/index.js
- test/document.test.js
- test/types.array.test.js
Re: #14502
**Summary**
Part of #14502 is that `pull()` uses the Mongoose array, rather than the internal raw array, for making updates, which mixes up change tracking.
**Examples**
> fix(array): avoid converting to `$set` when calling `pull()` on an element in the middle of the array

- test/types/schema.test.ts
- types/inferschematype.d.ts
Re: #14367
**Summary**
Part of the issue in [this comment](https://github.com/Automattic/mongoose/issues/14367#issuecomment-2002045122) is that we don't infer correct type in TypeScript when user uses `path: [Schema.Types.String]` to define an array of strings.
**Examples**
> types(schema): correctly infer Array<Schema.Types.*>

- lib/document.js
Re: #14394
**Summary**
#14394 points out that `toObject()` gets slow when there's a lot of virtuals. Part of that is we always take the "slow path" when applying virtuals by assuming the virtual is nested.
Consider the following script, 200 documents with 800 virtuals each. The below example uses replica set, but not strictly necessary for this example.
```javascript
'use strict';
void async function main() {
await mongoose.connect('mongodb://127.0.0.1:27017,127.0.0.1:27018/mongoose_test');
const ChildSchema = new mongoose.Schema({ name: String, parentId: 'ObjectId' });
const ChildModel = mongoose.model('Child', ChildSchema);
const ParentSchema = new mongoose.Schema({
name: String
});
ParentSchema.virtual('child1', { ref: 'Child', localField: '_id', …
```
> perf(document): add fast path for applying non-nested virtuals to JSON

- lib/helpers/model/castBulkWrite.js
- lib/model.js
- types/models.d.ts
Fixes #14536
There's a fairly inconsistent experience with the `timestamps` option in `bulkWrite` right now:
- The only way to influence `insertOne` operations is by specifying `timestamps` in the the top-level `bulkWrite` options
- `updateOne` and `updateMany` have their `timestamps` option set purely at the operation level
- There's no way to set the `timestamps` option for `replaceOne` operations
Let's debate desired behavior here, but this PR introduces a hierarchy in order to (mostly) prevent breaking changes:
1. If `timestamps` is specified within a given operation (e.g., `op.updateOne.timestamps`), then use it
2. Next look at the `timestamps` setting in the top-level `bulkWrite` options and use it if it exists
3. Finally, default is `true`
-  Consistency!
- Doesn't represent a …
> Improved timestamps option handling in bulkWrite

- docs/typescript/schemas.md
- docs/typescript/subdocuments.md
- docs/typescript/virtuals.md
- types/index.d.ts
Re: #14286
**Summary**
Did a bunch of work on the TypeScript docs to make it more clear that using `InferSchemaType<>` is usually not necessary. Because `InferSchemaType<>` returns a mostly raw document interface but with DocumentArrays and Subdocs, it typically isn't useful for end users because you end up with a mostly-lean document. `InferSchemaType<>` is still useful internally because it helps automatic type inference internally, but it unfortunately tries to satisfy both the lean document type and the hydrated document type, which leads to confusion.
For user-facing API, we should instead encourage `inferRawDocType` from #13900, which will infer the raw doc type from the schema, and `inferHydratedDocumentType`, which will infer the fully hydrated document type but is not yet …
> docs: de-emphasize `InferSchemaType<>` in TypeScript docs in favor of automatic inference

- types/query.d.ts
**Summary**
Normally, a `findOne` or `findById` returns `DocType | null`. When using `Query.prototype.select`, we can provide a `RawDocTypeOverride` in order to define the true return type of the projected document. Currently, this makes `findOne` and `find` queries return `RawDocTypeOverride` directly, but in order to be consistent, it should return `RawDocTypeOverride | null`.
This is consistent with how you don't currently have to specify the array version for `find`; that method automatically returns the array version of `RawDocTypeOverride`. Therefore, `select` on `findOne` should return the nullable version of `RawDocTypeOverride` automatically.
**Examples**
```ts
export const selectReturnType = async (): Promise<void> => {
type Test = {
_id: …
```
> Add `null` to `select` override return type for `findOne`

- lib/query.js
- test/query.test.js
Fix #14521
**Summary**
The following code errors out with a "n" is not in the schema error because of `upsert`. The issue is that we first cast the query filter, then run `translateAliases`, which is a 2-fold bug: 1) alias isn't in schema so Mongoose throws strict mode error with "upsert", 2) Mongoose doesn't apply casting to fields where the user specifies the path's alias rather than the path itself.
```javascript
const doc = await Test.findOneAndUpdate(
{ n: '14521' },
{ age: 7511 },
{ translateAliases: true, upsert: true, returnDocument: 'after' }
);
```
With this PR, translateAliases runs before query casting.
**Examples**
> fix(query): apply translateAliases before casting to avoid strictMode error when using aliases

- docs/connections.md
Fix #14528
**Summary**
#14528 points out that we have an example which uses `fast.js` and `slow.js` as connection file names without clarifying why one connection is "fast" and the other is "slow". Admittedly the fast/slow distinction is a bit of a red herring in this case, so I'm updating the docs to use a different example of separate connections for web vs mobile.
**Examples**
> docs(connections): improve description of connection creation patterns

- lib/document.js
- test/document.test.js
- test/model.populate.test.js
Re: #14394
**Summary**
3x perf improvement on benchmark with this one weird trick. Without this PR:
```
$ node gh-14394.js 
Num docs 200 200
toObject ms: 1141
{
_id: new ObjectId('66365214acdcbc00eacbd721'),
name: 'test child 0_0',
parentId: new ObjectId('66365214acdcbc00eacbd71f'),
__v: 0
}
Done
```
With this PR:
```
$ node gh-14394.js 
Num docs 200 200
toObject ms: 492
{
_id: new ObjectId('66365214acdcbc00eacbd721'),
name: 'test child 0_0',
parentId: new ObjectId('66365214acdcbc00eacbd71f'),
__v: 0
}
Done
```
Not sure why this is so much faster, but still works and makes `$toObject()` that much faster :man_shrugging: 
**Examples**
> perf(document): avoid cloning options using spread operator for perf reasons

- test/types/create.test.ts
- types/models.d.ts
Fix #14548
**Summary**
Right now the generic param to `create()` makes `create()`'s type checking slightly looser. This was introduced in https://github.com/Automattic/mongoose/commit/e75d4b6b530868cd14233d3a2ae0a6628e536bc2 (#11563) but doesn't look to be strictly necessary. With this PR, `create()` generic param can be used to make `create()` type checking strict.
**Examples**
> types(model): allow passing strict type checking override to create()

- lib/error/browserMissingSchema.js
- lib/error/divergentArray.js
- lib/error/eachAsyncMultiError.js
- lib/error/invalidSchemaOption.js
- lib/error/missingSchema.js
- lib/error/notFound.js
- lib/error/objectExpected.js
- lib/error/objectParameter.js
- lib/error/overwriteModel.js
- lib/error/parallelSave.js
- lib/error/strict.js
- lib/error/strictPopulate.js
- lib/error/validator.js
- lib/error/version.js
- lib/index.js
- lib/mongoose.js
Fix #12335
**Summary**
`lib/index.js` and `lib/mongoose.js` contain the significant changes here. The issue is that, because of how Rollup hoists imports when you don't set `strictRequires: true`, the `setDriver()` call in `lib/mongoose.js` will always run _after_ the Mongoose singleton is initialized in `lib/index.js`. So the Mongoose constructor needs to handle null driver case, and `lib/mongoose.js` needs to call `setDriver()` to make sure the driver change propagates to the newly created Mongoose singleton.
In regular Node.js, that second `setDriver()` call is a no-op because `setDriver()` checks to see if new driver is `===` old driver.
On a related note, I also cleaned up some circular imports in `lib/error/*.js`. `lib/error/index.js` imports `lib/error/cast.js` and …
> handle initially null driver when instantiating Mongoose for Rollup support

- docs/guide.md
- lib/helpers/schema/applyReadConcern.js
- lib/model.js
- lib/query.js
- lib/schema.js
- test/schema.test.js
- types/schemaoptions.d.ts
Fix #14511
**Summary**
Ability to set `readConcern` on schema-level, similar API as existing `read` and `writeConcern` options
**Examples**
> feat(schema): add schema-level readConcern option to apply default readConcern for all queries

- test/types/populate.test.ts
- types/models.d.ts
- types/query.d.ts
Fix #14574
Re: #14441
**Summary**
Fix for #14441 made it so that, if you chain `populate()` onto a query, the resulting doc doesn't have instance methods. To fix, we need to make QueryWithHelpers and Query aware of `TInstanceMethods`; this PR makes sure we pass along `TInstanceMethods` to queries everywhere
**Examples**
> types(model+query): pass TInstanceMethods to QueryWithHelpers so populated docs have methods

- lib/helpers/omitUndefined.js
- lib/helpers/query/cast$expr.js
- lib/mongoose.js
- test/types/base.test.ts
- types/index.d.ts
Fix #14569
**Summary**
Export `omitUndefined()` helper for #14569 re: discussion from #14547
**Examples**
> feat(mongoose): export omitUndefined() helper

- lib/query.js
- lib/utils.js
- test/query.test.js
Fix #14567
**Summary**
Currently, when you call `TestModel.find({ $and })`, Mongoose doesn't clone the `$and`. Then `Query.prototype.and()` uses `push()` to add onto the `$and` array, which modifies the existing `$and` array.
We already have some logic in place from #12944 that shallow clones $and, $or if they're set, but that only currently kicks in if there's an existing `$and` / `$or`. With this PR, we'll do a shallow clone on `$and`, `$or` if they exist on the user's provided query filter.
**Examples**
> fix(query): shallow clone $or, $and if merging onto empty query filter

- lib/cast.js
- lib/schema/operators/text.js
- test/cast.test.js
Fix #14576
**Summary**
Cast `$comment` to string, unless there's a schema path called `$comment`. See [MongoDB docs](https://www.mongodb.com/docs/manual/reference/operator/query/comment/) for more info on $comment.
**Examples**
> fix(cast): cast $comment to string in query filters

- docs/transactions.md
- lib/aggregate.js
- lib/connection.js
- lib/model.js
- lib/mongoose.js
- lib/query.js
- lib/validOptions.js
- test/docs/transactions.test.js
- test/model.findByIdAndUpdate.test.js
- types/mongooseoptions.d.ts
Fix #13889
**Summary**
Having to pass `session` option to every operation in a transaction is cumbersome and error prone. Node 16+ has a stable AsyncLocalStorage class as part of the async_hooks API; we can use AsyncLocalStorage to set `session` option by default on all operations in a function as long as the user uses `Connection.prototype.transaction()` wrapper. See `docs/transactions.md` changes for an example.
**Examples**
> feat: add `transactionAsyncLocalStorage` option to opt in to automatically setting `session` on all transactions

- .github/workflows/test.yml
- package.json
- test/schema.select.test.js
**Summary**
This PR upgrades `mongodb-memory-server` to `9.0.0`(`-beta.2`), but also does:
- upgrade all used mongodb version's patch version
- add mongodb `7.0.0` as a test (because mms more probably supports it with 9.0.0)
- upgrade deno to 1.36 (because with the new mms version, 1.34 just gets stuck before even starting the server)
Currently known problems:
deno really does not like the new MMS (mongodb?) version, constant `Server selection timed out` and locally many test fail too.
also in a debug run in CI it seems like the server somehow has a lot of failed hearbeats, and i dont understand why
even when testing locally against a mongodb docker container (via `MONGOOSE_TEST_URI`), those same tests fail and the final error logged also is `Server selection timed out after 30000 ms`
> upgrade to mongodb-memory-server 9.0.0

- lib/model.js
- test/model.test.js
Fix #14572
**Summary**
Right now we have a `throwOnValidationError` that means `bulkWrite()` and `insertMany()` will throw if any operations fail validation... except if all operations fail validation. This PR makes it so that we still throw a `MongooseBulkWriteError` if all operations fail validation.
**Examples**
> fix(model): make `bulkWrite()` and `insertMany()` throw if `throwOnValidationError` set and all ops invalid

- lib/schema.js
- test/helpers/update.castArrayFilters.test.js
Fix #14595
**Summary**
`Schema.prototype._getSchema()` doesn't quite handle the case where you have `docArr.$.primitiveArr.$`, that last `$` gets dropped off because `primitiveArr.schema == null`.
**Examples**
> fix(update): cast array of strings underneath doc array with array filters

- lib/document.js
- lib/types/subdocument.js
- test/document.test.js
Fix #14591
**Summary**
Tricky issue: if you `save()` a doc, then `set()` a more than 3 level nested single nested path using dot notation, pre('validate') hooks don't fire because the subdoc paths aren't marked as modified beyond the 1st level.
This PR provides a reasonable fix for this particular case, but I will look more closely at how our change tracking handles subdocs as a followup to this work.
**Examples**
> fix(document): fire pre validate hooks on 5 level deep single nested subdoc when modifying after save()

- lib/document.js
**Summary**
A bug introduced in v8.3.3 by #14543 caused `toJSON` to not be executed for virtual sub documents. The issue is caused by the `options` being incorrectly passed into the `get` function instead of the `clone` function.
**Examples**
I don't have an easy examples sorry, but I think the fix should be fairly evident. The intentions of #14543 was to pass `noDottedPath: true` to the `get` function but it mistakenly included the clone options which should have been passed to `clone` instead, as on line 4139 below it.
> Pass options to `clone` instead of `get` in applyVirtuals.

- lib/model.js
- test/model.test.js
Fixes #14622
**Summary**
When having a sharded collection and having set _shardKey_ on  the schema,  using buildBulkWriteOperations does not take the _shardKey_ into account. 
The documention for _shardKey_ states (https://mongoosejs.com/docs/guide.html#shardKey):
> Each sharded collection is given a shard key which must be present in all insert/update operations
This PR enabled support for the _shardKey_ option when using the _buildBulkWriteOperations_ method. 
**Examples**
Given this schema 
```js
const measurementSchema = new Schema({
temperature: { type: Number },
sensorId: { type: String },
}, { shardKey: { sensorId: 1 } });
const Measurement = db.model('Measurement',measurementSchema )
```
and assuming an saved document _m_, this _bulkSave_ action will correctly include _sensorId_ …
> fix: ensure buildBulkWriteOperations target shard if shardKey is set

- test/types/subdocuments.test.ts
- types/index.d.ts
- types/types.d.ts
Fix #14601
**Summary**
Right now `toObject()` on subdocs will return `any` if you use `HydratedArraySubdocument` or `HydratedSingleSubdocument`.
I made this PR against master, but when merged I will also cherry-pick to 7.x.
**Examples**
> types: pass DocType down to subdocuments so `HydratedSingleSubdocument` and `HydratedArraySubdocument` `toObject()` returns correct type

- lib/query.js
- lib/utils.js
- test/query.test.js
Fix #14610
**Summary**
Follow up on #14580, #14567: also shallow clone `$and` and `$or` conditions to make casting avoid mutating $or/$and elements in place. We already use `utils.merge()` to avoid mutating for top-level keys in query filter.
**Examples**
> fix(query): shallow clone $or and $and array elements to avoid mutating query filter arguments

- docs/migrating_to_7.md
**Summary**
Fix #13762, specifically [this comment](https://github.com/Automattic/mongoose/issues/13762#issuecomment-2108700170). The `id` setter has caused enough confusion that we should mention it in the migration guide.
**Examples**
> docs(migrating_to_7): add id setter to Mongoose 7 migration guide

- docs/transactions.md
Analog to mongodb driver docs update: https://github.com/mongodb/node-mongodb-native/pull/4122
https://github.com/Automattic/mongoose/issues/14603
> docs: add note about parallelism in transations

- lib/model.js
**Summary**
When we call the discriminator function of a model we can pass options with overwriteModels Boolean field. 
But that field isn't considered in the logic. 
**Examples**
model.discriminator(discriminatorName, schema, { overwriteModels: true });
> check the value of overwriteModels in options

- test/types/models.test.ts
- types/models.d.ts
- types/query.d.ts
- types/utility.d.ts
Fix #14615
Re: #13836
Re: #12064
**Summary**
Fixes #14615 by inferring the type of 1-level deep schema paths to help with query filters. Consider the following schema:
```
const FooSchema = new Schema({
one: { type: String }
});
const MyRecordSchema = new Schema({
_id: { type: String },
foo: { type: FooSchema }
});
```
Currently, Mongoose can infer `await MyRecord.distinct('foo').exec()` return type because `foo` is a top-level path. But not `await MyRecord.distinct('foo.one').exec()` because `foo.one` is nested.
As per discussion in #12064, we don't want to infer arbitrarily deep nested paths: too risky because we don't want to run into the dreaded `Type instantiation is excessively deep and possibly infinite` error in an unforeseen case, and we don't want to cause performance issues. …
> types(models+query): infer return type from schema for 1-level deep nested paths

- lib/helpers/populate/getModelsMapForPopulate.js
- test/model.populate.test.js
Fix #12363
Fix #12440
**Summary**
The primary issue from #12363 and #12440 is that right now we call `ref()` functions on virtuals with the top-level document rather than the subdocument, even if the virtual is defined on the subdocument. For example, in Mongoose 8, with the following setup, `ref()` would see `this` as an instance of `ParentSchema`, not the `b` subdocument.
```javascript
const ASchema = new Schema({
name: String
});
const BSchema = new Schema({
referencedModel: String,
aId: ObjectId
});
BSchema.virtual('a', {
ref: function() {
return this.referencedModel;
},
localField: 'aId',
foreignField: '_id',
justOne: true
});
const ParentSchema = new Schema({
b: BSchema
});
const A1 = db.model('Test1', ASchema);
const A2 = db.model('Test2', ASchema);
const Parent = …
```
> BREAKING CHANGE: call virtual `ref` function with subdoc, not top-level doc

- lib/types/map.js
**Summary**
I had a bug when deleting an entry from a populated Map.
**Examples**
```js
import mongoose, { Schema } from 'mongoose';
import connectToDatabase from '@/server/libs/database/mongoose';
await connectToDatabase();
const playerSchema = new mongoose.Schema({
name: String,
});
const PlayerModel = mongoose.model('PlayerTest', playerSchema);
const characterSchema = new mongoose.Schema({
name: String,
items: [{
type: Schema.Types.ObjectId,
ref: 'ItemTest',
}],
});
const CharacterModel = mongoose.model('CharacterTest', characterSchema);
const itemSchema = new mongoose.Schema({
name: String,
});
const ItemModel = mongoose.model('ItemTest', itemSchema);
const gameSchema = new mongoose.Schema({
characters: {
type: Map,
of: {
type: Schema.Types.ObjectId,
ref: 'CharacterTest',
},
required: …
```
> Fix problem when deleting an entry on a populated Map

- lib/connection.js
- lib/drivers/node-mongodb-native/collection.js
- test/connection.test.js
Fix #14648
**Summary**
The operation-start and operation-end events are currently not documented, and operation-end wasn't being emitted consistently. This PR adds these events to the connection docs, and fixed the issues with operation-end.
**Examples**
> fix(connection): fix up some inconsistencies in operation-end event and add to docs

- types/index.d.ts
Fix #14630
**Summary**
#14630 pointed out that, under certain circumstances that I'm unable to quantify exactly, `Boolean`, `mongoose.Schema.Types.ObjectId`, and several other schema types get inferred as dates. This doesn't happen in tsd, or if Mongoose is symlinked into node_modules, so we can't write tests for this issue with our current testing setup.
I tracked the issue down to somehow `typeof NativeDate` catching `Boolean` and other data class types. This PR appears to fix the issue, and doesn't break any existing code that we're currently aware of.
**Examples**
> types: avoid inferring Boolean, Buffer, ObjectId as Date in schema definitions under certain circumstances

- lib/document.js
- lib/helpers/schema/idGetter.js
- test/document.unit.test.js
Re: #14394
**Summary**
Turns out `.toString()` is significantly faster than `String()` for converting values to strings:
This PR gives us maybe 12% speedup on `recursiveToObject` benchmark with no breaking changes :sunglasses: 
**Examples**
> perf: avoid unnecesary get() call and use faster approach for converting to string

- lib/document.js
- lib/model.js
- lib/schema.js
- test/document.test.js
- test/document.unit.test.js
- test/index.test.js
- test/model.test.js
**Summary**
Re: #14394, we can get a maybe 2.5% speedup by not combining Mongoose global options and schema base options every time we call `$toObject()`. Not a huge speedup, but every little bit helps given that `$toObject()` is called on some heavily used code paths, like `save()` and `JSON.stringify()`.
I'll put this change in 8.5, just to de-risk because it may cause some issues for people who modify `toJSON` and `toObject` options after compiling their schemas.
**Examples**
> perf: memoize toJSON / toObject default options

- types/pipelinestage.d.ts
**Summary**
Adding types for the [$documents](https://www.mongodb.com/docs/manual/reference/operator/aggregation/documents/) pipeline stage and fixing an issue with the type for the [$unionWith](https://www.mongodb.com/docs/manual/reference/operator/aggregation/unionWith/) type (the `coll` field is optional if the `pipeline` field is present)
**Examples**
> Add $documents pipeline stage and fix $unionWith type

- docs/nextjs.md
Both of the links at the end of the first paragraph pointed to the same Vercel page.  I believe that the last link in the first paragraph should instead point to the appropriate Mongoose AWS page.
> Fix AWS Lambda docs link

- lib/helpers/query/castUpdate.js
- test/model.updateOne.test.js
Fix #14675
**Summary**
For other update operators, we correctly handle casting embedded discriminator paths when we can infer the embedded discriminator type from the filter. But looks like not for `$pull`. This PR fixes that.
We should really clean up the duplicated `_getSchema()` followed by `getEmbeddedDiscriminatorPath()` calls. Looks like the only reason why we need to call `_getSchema()` is because of `$fullPath`, but we need to investigate some more to figure that out.
**Examples**
> fix(query): cast $pull using embedded discriminator schema when discriminator key is set in filter

- lib/drivers/node-mongodb-native/connection.js
- test/connection.test.js
Fix #14611
**Summary**
MongoDB driver introduced a handy set of `commandStarted`, `commandFailed`, `commandSucceeded` events that are great for monitoring performance. With this PR, we'll bubble those events up to the Mongoose connection if the `monitorCommands` option is set.
We shouldn't need to add `monitorCommands` to Mongoose's `ConnectOptions` because `monitorCommands` is already an option in MongoDB driver's connection options: https://github.com/mongodb/node-mongodb-native/blob/8fb43f86b22f98e488a3a98c0b562ca240ffdaa1/src/cmap/connection.ts#L118
**Examples**
> feat(connection): bubble up monitorCommands events to Mongoose connection if `monitorCommands` option set

- lib/mongoose.js
- lib/validOptions.js
- test/index.test.js
**Summary**
Right now there's always a default `mongoose.connection`. We added a `createInitialConnection` option that prevents new `Mongoose` instances from creating a default connection, but that doesn't apply to existing `Mongoose` instances, including the default one. So there's no way to really "delete" the default connection in the API.
With this PR, `mongoose.set('createInitialConnection', false)` will also remove the default connection, presuming it isn't connected and there are no models already on it.
**Examples**
> Remove default connection if setting createInitialConnection to false after Mongoose instance created

- lib/mongoose.js
- test/driver.test.js
**Summary**
One thing that's unfortunately missing from the driver API is the ability to set global plugins. Drivers can always do `mongoose.plugin(myPlugin)`, but the problem is that assumes you only have one Mongoose instance. If a user were to do `const mongoose = new Mongoose(); mongoose.setDriver(myDriver);`, then there's no way for that driver to apply plugins to the new Mongoose instance.
With this PR, drivers can export a `plugins` array that `setDriver()` will look for, and apply plugins to the Mongoose instance.
**Examples**
> feat(mongoose): allow drivers to set global plugins

- lib/document.js
- test/document.test.js
Fix #14677
**Summary**
Right now we propagate `validateModifiedOnly` to subdocument `validate()`, which causes problems when a subdocument is directly modified. If you overwrite the full subdocument, we should validate the whole subdocument, not just the subdocs modified paths.
**Examples**
> fix(document): avoid passing validateModifiedOnly to subdocs so subdocs get fully validating if they're directly modified

- lib/helpers/projection/applyProjection.js
- test/helpers/projection.applyProjection.test.js
Fix #14680
**Summary**
Our `applyProjection()` helper doesn't currently handle projections underneath arrays. This PR should fix that.
**Examples**
> fix(projection): handle projections on arrays in `Model.hydrate()` projection option

- lib/schema/array.js
- lib/schema/documentArray.js
- test/model.query.casting.test.js
- test/model.test.js
Fix #14678
**Summary**
Right now, casting `$elemMatch` on a primitive array in `bulkWrite()` throws an error. That's because we have some logic for casting `$elemMatch` in the primitive array schematype that really belongs in the document array schematype, but in the past we've just thrown all conditional handling logic for arrays onto the primitive array schematype.
With this PR, we now have separate `$conditionalHandlers` for document array schematype vs primitive array schematype. And the offending logic that caused #14678 is only on the documentarray schematype.
**Examples**
> fix: handle casting primitive array with $elemMatch in bulkWrite()

- test/types/connection.test.ts
- types/connection.d.ts
**Summary**
This fixes `Connection.withSession()`'s type definition, which currently doesn't seem to match the implementation [[here](https://github.com/Automattic/mongoose/blob/3ad5b4f932180609ed7e68926fd7ca4abc6228b1/lib/connection.js#L458)].
**Examples**
(a test is added instead)
> types(connection): fix return type of withSession()

- lib/query.js
- lib/queryHelpers.js
- test/query.test.js
- test/schema.select.test.js
- types/query.d.ts
**Summary**
[sanitizeProjection option](https://thecodebarbarian.com/whats-new-in-mongoose-5-13-sanitizeprojection.html) currently exists to prevent cases like `select({ name: '$password' })`, which would cause the `name` property to contain the value of the `password` property in newer versions of MongoDB.
While that is helpful, `sanitizeProjection` can do a bit more to prevent inclusion of sensitive data when the projection is potentially untrusted. With this PR, if `sanitizeProjection` is enabled, there is no way to project in a field that's deselected with `select: false` in the schema definition. If `password` has `{ type: String, select: false }` and `sanitizeProjection` is set, then `select('+password')`, `select('password')`, etc. will be ignored.
@hasezoey what do you think about …
> feat(query): make sanitizeProjection prevent projecting in paths deselected in the schema

- lib/document.js
- lib/model.js
- lib/modifiedPathsSnapshot.js
- lib/stateMachine.js
- test/docs/transactions.test.js
- test/document.test.js
- types/document.d.ts
Fix #14268
**Summary**
`$createModifiedPathsSnapshot()` takes a snapshot of the document's current change tracking state, without modifying the document's properties. `$restoreModifiedPathsSnapshot()` restores the document's change tracking state to a given snapshot.
Primarily useful for custom transaction wrappers like #14268. When you modify a document in a transaction and that document was created outside of the transaction, you may need to restore the document's change tracking state if the transaction was aborted.
As part of making this work, I also moved `Model.prototype.$__delta` and supporting code to `Document.prototype.$__delta`. Otherwise, `getChanges()` crashes on subdocuments because subdocuments don't have a `$__delta` function.
**Examples**
> feat(document): add `$createModifiedPathsSnapshot()`, `$restoreModifiedPathsSnapshot()`, `$clearModifiedPaths()`

- test/types/schema.test.ts
- types/schematypes.d.ts
- types/validation.d.ts
Fix #14696
**Summary**
Ensure `this` has the correct type in `validate.validator` below.
```ts
isActive: {
type: Boolean,
default: false,
validate: {
validator(v: any) {
expectAssignable<User>(this);
return !v || this.name === 'super admin';
}
}
}
```
I made 2 changes to support this:
1) passing `EnforcedDocType` down to `ValidateFn` via `ValidateOpts` and `SchemaValidator` 
2) Removing `LegacyAsyncValidateFn`. For some reason, `LegacyAsyncValidateFn` breaks these tests, and I have no idea why. It has something to do with the `done` function. Either way, `LegacyAsyncValidateFn` is no longer necessary because we removed support for validators that receive a callback in [Mongoose 6](https://mongoosejs.com/docs/migrating_to_6.html#removed-validator-isasync), so I think it is safe to remove. …
> types: correct `this` for `validate.validator` schematype option

- lib/model.js
Fix #14698
**Summary**
Add an additional example, and indicate that `insertMany()` with `lean: true` doesn't apply defaults. 
Re: #14372
**Examples**
> docs(model): note that `insertMany()` with `lean` skips applying defaults

- docs/faq.md
- lib/schema/array.js
- test/document.test.js
Fix #6691
**Summary**
I took another look at #6691 and I can't see any reason for us continuing to disallow `default: null` on array paths. We already allow `default: undefined` and `default: () => null`, the latter of which is practically identical. Silently ignoring `default: null` for arrays feels more like a bug than anything, and changing it doesn't break any tests. 8.5 release is a good opportunity to make this change.
**Examples**
> feat: allow setting array default value to `null`

- lib/plugins/saveSubdocs.js
- lib/types/subdocument.js
- test/document.test.js
Fix #9885
**Summary**
It looks like when we removed `remove()`, we didn't make it so that `post('deleteOne')` hooks fire when you `save()` a deleted doc. This PR makes Mongoose consistently trigger post('deleteOne') middleware on subdocs when you call `subdoc.deleteOne(); await topLevelDoc.save();`, which is what used to happen when you did `subdoc.remove(); await topLevelDoc.save();`
**Examples**
> fix(document): ensure post('deleteOne') hooks are called when calling `save()` after `subdoc.deleteOne()`

- test/types/document.test.ts
- test/types/plugin.test.ts
- test/types/queries.test.ts
- types/query.d.ts
Fix #14697
**Summary**
With the way that `lean()` is currently implemented, the following code unexpectedly compiles
```ts
export interface IUser {
name: string;
createdAt: Date;
updatedAt: Date;
}
export interface IUserVirtuals {
id: string;
}
type UserModelType = Model<IUser, {}, {}, IUserVirtuals>;
export type UserInstance = InstanceType<UserModelType>;
let user: UserInstance | null = null;
// Compiles even though `lean()` but `user` is hydrated doc
user = await UserModel.findOne().lean();
```
That's because TypeScript automatically infers the generic param to `lean()` if `user` has an explicit type.
In order to support this, I needed to change the default value of `RawDocType` param to `Query<>` to `unknown`. When `RawDocType` was set to `DocType` by default, that would break when …
> types: avoid automatically inferring lean result type when assigning to explicitly typed variable

- test/types/docArray.test.ts
- test/types/schema.test.ts
- types/document.d.ts
Fix #14660
**Summary**
`_id: T` is more correct because `_id` should always exist on a hydrated document by default. And this doesn't break any tests other than ones that assert on the behavior from #14660. @hasezoey what do you think, does this work fine with Typegoose?
**Examples**
> types: make `_id` required on Document type

- types/query.d.ts
**Summary**
This PR fixes `find` and `fineOne` overload returns where `DocType` should be used over `RawDocType`, at least to my understanding, this had already been done partially in fa0bc8d656cccd3081800026fa75d7b6990f51cd, but not for `findOne` so this could be forward-ported.
The generics for context (as of 7.7.0):
https://github.com/Automattic/mongoose/blob/061bb828c706512d79c79f5d42774316bf167357/types/query.d.ts#L191
Without this change using and expecting assignability would result in a error like in typegoose:
```txt
Type 'QueryHelperThis<typeof QueryMethodsClass, FindHelpers, DocumentType<QueryMethodsClass, FindHelpers>>' is not assignable to type 'QueryWithHelpers<DocumentType<QueryMethodsClass, FindHelpers> | null, DocumentType<QueryMethodsClass, FindHelpers>, FindHelpers, …
```
> types(query): fix usage of "RawDocType" where "DocType" should be passed

- lib/cursor/changeStream.js
**Summary**
Client code that calls `stream.close().then(...)` fails with TypeError, since mongoose `close()` returns undefined.
> Fix ChangeStream.close to return a Promise<void> like the driver

- lib/model.js
- test/docs/transactions.test.js
Fix #14738
**Summary**
Looks like we missed a spot when implementing `transactionAsyncLocalStorage`, we're not adding `session` option to `insertMany()`. I reviewed and don't see any other places in `Model` where we aren't setting `session`
**Examples**
> fix(model): handle `transactionAsyncLocalStorage` option with `insertMany()`

- lib/cursor/queryCursor.js
- test/query.cursor.test.js
**Summary**
Minor pain point in working with QueryCursor: sometimes you want to access the raw `cursor` property, but that property isn't set when the cursor is initially created. You need to wait for a `cursor` event.
This PR adds a new `getDriverCursor()` function which waits for the `cursor` event if necessary
**Examples**
> feat(QueryCursor): add getDriverCursor() function that returns the raw driver cursor

- .github/workflows/test.yml
- .github/workflows/tsd.yml
- package.json
**Summary**
This PR updates the dev-dependency `mongodb-memory-server` to major version 10.
Additionally also updates all mongodb server versions to their latest patch again.
~~This PR is a DRAFT for now as version 10.0.0 is not yet released and this PR currently makes use of `-beta` releases~~
> Upgrade `mongodb-memory-server` to 10.x

- lib/model.js
- test/model.test.js
fixes #14753 
**Summary**
buildBulkWriteOperations adds the shard key to the filter condition, but it sets it to the schema's value, not the document's value. 
This PR also updates a problematic test, which passed because the update value it uses was the same schema's shard key value.
Also, not sure about the backport policy, but we might need to get this ported to the minor version. It was broken in 8.4.1
> Correct shardkey access in buildBulkWriteOps

- docs/transactions.md
- lib/aggregate.js
- lib/connection.js
- lib/index.js
- lib/model.js
- lib/query.js
- lib/validoptions.js
- test/docs/transactions.test.js
- types/mongooseoptions.d.ts
Backport #14583 to 7.x
Re: #13889
**Summary**
Add `transactionAsyncLocalStorage` option to 7.x. Should work fine because Node v14.x has "experimental" support for the same AsyncLocalStorage API that became stable in 16.x.
**Examples**
> feat: add transactionAsyncLocalStorage option to opt in to automatically setting session on all transactions

- lib/cast.js
- test/docs/cast.test.js
due to update on [6.10.1](https://github.com/Automattic/mongoose/blob/master/CHANGELOG.md#6101--2023-03-03) was reverted #12898 because of #13086
I believe that my commit has actually fixed a bug where `{}` was unintentionally created through the strict process, which was not the developer's intention. I am updating this pull request to address the issue I just mentioned.
Now, only allows empty condition when the developer directly provides it. Additionally, if an empty condition appears due to the casting process, it will be removed.
> Improve fix cast empty query

- lib/helpers/query/cast$expr.js
- test/helpers/query.cast$expr.test.js
Fix #14751
**Summary**
Incorrect handling for `$switch` in `cast$expr()`
**Examples**
> fix(query): handle casting $switch in $expr

- docs/migrating_to_6.md
**Summary**
fixes a wrong example with `typePojoToMixed` behavior in mongoose 5
**Examples**
> docs: fix a wrong example in v6 migration guide

- lib/document.js
- lib/model.js
- lib/schemaType.js
- lib/types/map.js
- test/model.populate.test.js
Fix #14759
**Summary**
When depopulating, it looks like Mongoose applies `_id` getters, which is problematic if you add a default getter to convert all ObjectIds to strings like here: https://thecodebarbarian.com/whats-new-in-mongoose-54-global-schematype-configuration.html#schematype-getters. Fixed by replacing `doc._id` with `doc._doc._id` to get the raw id and bypass any getters.
We should backport this to 7.x and 6.x. Same issue impacts those versions.
**Examples**
> fix(model+document): avoid depopulating manually populated doc as getter value

- lib/helpers/clone.js
**Summary**
Looking more closely at #14394, we actually call `clone()` on primitive values a **lot** in Mongoose. `cloneObject()`, for instance, calls `clone()` on every key.
This PR is looking like another maybe 10% speedup on `recursiveToObject` benchmark, 308ms average vs 345ms average.
**Examples**
> perf(clone): avoid further unnecessary checks if cloning a primitive value

- lib/schema/documentArray.js
- test/document.test.js
Fix #6691
Re: #14717
**Summary**
Looks like #14717 missed a spot, we still need a change to support `default: null` for document arrays
**Examples**
> fix: allow setting document array default to `null`

- lib/document.js
- test/document.test.js
Fix #14771
Re: #14394
Re: #14623
**Summary**
Fixing #14771, which is a bug that was likely introduced by #14623. The issue is that older versions of Mongoose make parent `virtuals` option apply to subdocs presuming that the subdocs don't explicitly set `virtuals`.
```javascript
const userLabSchema = new mongoose.Schema({
capacityLevel: Number
});
userLabSchema.virtual('capacityLevelCeil').get(function() {
return Math.ceil(this.capacityLevel);
});
const labPlotSchema = new mongoose.Schema({
plotId: Number,
lab: userLabSchema
});
username: String,
labPlots: [labPlotSchema]
}, { toObject: { virtuals: true } });
const User = mongoose.model('User', userSchema);
const doc = new User({
username: 'test',
labPlots: [{
plotId: 1,
lab: { capacityLevel: 3.14 } …
```
> fix(document): apply virtuals to subdocuments if parent schema has `virtuals: true` for backwards compatibility

- lib/types/map.js
**Summary**
Updates SchemaType `Map.set`'s documentation to note which extra constraints are on the key names.
> style(map): document key name constraints

- docs/typescript/schemas.md
While using Mongoose with TypeScript, @ShunnShine and I discovered the dangers of defining the schema in a separate variable when we realized all of our fields with `required: false` were being treated as `required: true`.
We eventually figured out how to fix the type definitions by using `as const`.
We looked at the [Schemas in TypeScript](https://mongoosejs.com/docs/typescript/schemas.html) documentation and saw a warning about assigning a schema to a temporary variable (fair enough), but did not see any information about using `as const`, even though it is used in the example code right below - without explanation.
This PR adds a little section about type widening and `as const` to help users understand why this was done.
> docs: add schema type widening advice

- test/types/schema.test.ts
- types/inferrawdoctype.d.ts
- types/inferschematype.d.ts
support schema type inference based on schema options timestamps as well
Fix #13215
**Summary**
Currently, `InferSchemaType` and `InferRawDocType` does not infer type based on timestamps fields provided in the schema options, which can lead to some difficulties while developing process (you'll have to add fields into your schema types manually to avoid the issue or extend returned typescript type).
> fix: support schema type inference based on schema options timestamps as well

- lib/model.js
- lib/query.js
- test/docs/transactions.test.js
- test/query.test.js
- test/types/queries.test.ts
- types/models.d.ts
- types/query.d.ts
Fix #8006
**Summary**
Make it easier to use `distinct()` with transactions, so you don't need to chain `setOptions()`. `distinct()` looks to be the only query function where you can't pass in `options`.
**Examples**
> feat(model+query): support `options` parameter for distinct()

- test/types/connect.test.ts
- test/types/connection.test.ts
- types/connection.d.ts
> allow `mongoose.connection.db` to be undefined

- test/types/querycursor.test.ts
- types/cursor.d.ts
Fix #14787
**Summary**
`await cursor.next()` will be `null` if there's no more docs
**Examples**
> types(cursor): indicate that cursor.next() can return null

- lib/model.js
- test/model.populate.test.js
**Summary**
in #14794 due to being called with `lean()` there's no `_doc` object so that throws an error
another issue here is documents with duplicate foreignField so the `rawDocs[key]` already exists and its value is being overwritten.
this change shouldn't affect (gh-14759) and its test case still runs successfully.
another solution would be to check for `rawDocs[key]._id`  and `val._doc` first using the following statement instead
```js
(rawDocs[key]._doc && String(rawDocs[key]._doc._id)) !== (val._doc && String(val._doc._id)))
> fix populate called with lean (gh-14794)

- test/types/models.test.ts
- test/types/queryhelpers.test.ts
- types/models.d.ts
- types/query.d.ts
**Summary**
Previously, there was a catch-all case in RootQuerySelector which would accept any key with type "any". This still allows nice IDE typehints, but can lead to bugs where the incorrect key is used for a filter with no warning that the key is clearly wrong.
With this PR, only keys that contain a "." are unsafely typed as any, which should reduce the blast radius of the hacky types dramatically.
**Examples**
Previously, the following would be a valid type:
```ts
const testDoc: FilterQuery<{ testKey: string }> = {
invalidKey: 'test',
};
```
Now, the above case gives a type error for "invalidKey".
Note that a case such as this will still be accepted (since its hard to properly type any nested queries):
```ts
const testDoc: FilterQuery<{ testKey: string }> = {
"invalidKey.test": …
```
> Refine query selector to highlight unexpected query keys

- lib/document.js
- test/document.test.js
Fix #14788
**Summary**
When we add all paths underneath a nested path to list of paths to validate, we actually need to avoid adding paths underneath single nested subdocuments. That's because validating a single nested subdoc triggers validation on all paths underneath that subdoc.
**Examples**
> fix(document): call required functions on subdocuments underneath nested paths with correct context

- types/index.d.ts
Fix #14793
**Summary**
As #14793 points out, HydratedSingleSubdocument and HydratedArraySubdocument need to use `MergeTypes`, otherwise we end up with hard to diagnose compiler errors stemming back to having `RawType & HydratedType`.
**Examples**
> types: make HydratedSingleSubdocument and HydratedArraySubdocument merge types instead of using &

- lib/document.js
- lib/types/array/methods/index.js
- test/document.populate.test.js
- test/document.test.js
**Summary**
One issue that popped up while I was working on #1635 is that `depopulate()` converts Mongoose arrays to vanilla JavaScript arrays. So `band.depopulate('members'); band.members.addToSet(id);` will error out because `band.members` is no longer a Mongoose array.
The approach I came up with is to use `getValue()`: if `getValue()` returns a Mongoose array, then we just modify the array in-place to avoid triggering setters. If not a Mongoose array, then we have a case where mpath is returning an array of values underneath a document array, like in the #10592 test case `doc.depopulate('docArr.members')`, so we fall back to `setValue()`. 
I left `assert.ok(!band.embeddedMembers[0].$populated('member'));` commented out because that assertion fails, but I want to look at it some more …
> fix(document): make sure depopulate does not convert hydrated arrays to vanilla arrays

- lib/utils.js
- test/utils.test.js
@vkarpov15, I was unable to add reviewers directly and would appreciate your feedback on this PR. Please let me know if there are any additional steps I should follow or if you have any suggestions.
Feel free to reach out if you have any questions or need further information.
**Summary**
The motivation for me to make this pull request is that while we were working on our serverless project we used Mongoose but we got an error that said Cannot read properties of undefined (reading 'toLowerCase') we were not able to fix as on our local we could run and it worked fine so we scratched a lot of our head thinking we didn't use toString function anywhere where is the issue code, so we put consoles and then check on deployment logs and realized the issue was that the secret manager was not …
> Add empty string check for collection name passed

- lib/model.js
Fix #14804
**Summary**
Quick docs improvements re: #14804 
**Examples**
> docs(model): add 'throw' as valid strict value for bulkWrite() and add some more clarification on `throwOnValidationError`

- lib/index.js
Fix #14810
**Summary**
Fixed an out-of-date example and improved it to make better use of `await`
**Examples**
> docs(mongoose): remove out-of-date callback-based example for `mongoose.connect()`

- test/types/schema.test.ts
- types/document.d.ts
- types/inferrawdoctype.d.ts
Fix #12883
**Summary**
Making document methods generic by default makes TypeScript do some strange type widening where it automatically infers the generic parameter if the variable being assigned has an explicit type. This PR makes `toJSON()` and `toObject()` not generic by default.
In the interest of caution, I'm targeting merging this in v8.6 because it may cause some issues for users that rely on the broken behavior.
**Examples**
> types: make toObject() and toJSON() not generic by default to avoid type widening

- lib/cursor/changeStream.js
- lib/cursor/queryCursor.js
- package.json
- scripts/tsc-diagnostics-check.js
- test/connection.test.js
- test/model.test.js
- test/model.watch.test.js
- test/query.cursor.test.js
**Summary**
We haven't upgraded to MongoDB Node driver 6.8 because we have a test failure due to a minor breaking change in the driver: `cursor.next()` no longer errors out after calling `cursor.close()`. We reported an issue in the MongoDB Node driver JIRA here: https://jira.mongodb.org/browse/NODE-6255 and the issue is in progress, but I'm thinking that 1) better for Mongoose to enforce this behavior if our tests rely on it, 2) we've already been blocked from upgrading to `mongodb@6.8` for 6 weeks.
**Examples**
> feat: upgrade mongodb -> 6.8.0, handle throwing error on closed cursor in Mongoose

- lib/document.js
- lib/error/parallelSave.js
- lib/error/parallelValidate.js
- lib/error/version.js
- lib/helpers/model/discriminator.js
- lib/helpers/populate/getModelsMapForPopulate.js
- lib/helpers/populate/markArraySubdocsPopulated.js
- lib/model.js
- lib/query.js
- test/model.discriminator.test.js
- test/model.populate.test.js
Fix #14827
Re: #14759
**Summary**
There are a few spots we missed in #14760 where `populate()` logic gets `doc._id` (which applies getters) instead of `doc._doc._id` (which skips getters)
**Examples**
> fix(populate): fix a couple of other places where we get the document's _id with getters

- test/types/queries.test.ts
- types/query.d.ts
Fix #14841
Re: #14764
**Summary**
Quick fix for a missing root query selector
**Examples**
> types(query): add $expr to RootQuerySelector

- lib/document.js
- lib/helpers/clone.js
- test/document.test.js
Fix #14840
Fix #14835
Re: #14724
**Summary**
We finally managed to fix the root cause of #7442 etc.: `applyGetters()` was re-triggering getters on single nested subdocs by using `get()` to get the value, even though that isn't necessary because `applyGetters()` is only called on already cloned values. This PR fixes that, and means we can get rid of the `_skipSingleNestedGetters` option as well
**Examples**
> fix(document): avoid unnecessary clone() in `applyGetters()` that was triggering additional getters

- lib/cursor/changeStream.js
**Summary**
An unintended consequence of #14813 using promises rather than event emitters is that sync errors in `changeStreamThunk()` aren't possible to handle. `Model.watch().on('error')` doesn't work because the constructor throws an error before the `on('error')` call happens.
This PR makes `ChangeStream()` constructor throw an error if `changeStreamThunk()` throws a synchronous error. The code is a little clunky, but at least avoids silently ignoring sync errors in `changeStreamThunk()`. This code is hard to test because `changeStreamThunk()` doesn't throw in Mongoose in general. 
**Examples**
> fix(cursor): throw error in ChangeStream constructor if `changeStreamThunk()` throws a sync error

- lib/connection.js
- lib/cursor/queryCursor.js
- lib/drivers/node-mongodb-native/connection.js
Fix #14859
Fix #14860
@Mouri-P can you please take a look at this one as well?
**Summary**
An alternative fix for #14859: I don't like using `setMaxListeners()` because that may hide memory leaks in user code, and there's no way to `setMaxListeners()` for just one event or one type of handler. Either way, connections have their own queueing mechanism with `_queue`, so we can just use that.
**Examples**
With this PR, no MaxListeners warning on the following script:
```js
const { Schema } = mongoose;
const iterations = 11;
const mongoConn = async () => {
const dbs = ["admin", "config", "local", "temp"];
const collections = {};
for (let i = 0; i < iterations; i++) {
const db = mongoose.connection.useDb(dbs[parseInt(Math.random() * 4)]);
const collection …
```
> fix(connection): avoid MaxListenersExceededWarning on multiple useDb() calls by avoiding using event emitters

- types/cursor.d.ts
Hi, this is a very small contribution to add the `signal` option to `eachAsync` typing. Thanks!
> Added the signal option to eachAsync typings

- test/types/models.test.ts
- types/query.d.ts
Revert #14764
Fix #14863
Fix #14862
**Summary**
#14764 introduced issues for quite a few devs, see #14863. We should revert for now, and consider adding #14764 in 9.0.
cc @alex-statsig 
**Examples**
> types: allow arbitrary keys in query filters again

- lib/plugins/trackTransaction.js
- test/docs/transactions.test.js
- test/document.test.js
**Summary**
Updating initial state on every save seems like incorrect behavior, since the idea of "initial state" is that is the state we should restore the document to if transaction fails.
Fix #14848
**Examples**
> fix(transaction): avoid unnecessarily updating initial state in between transactions

- test/types/inferrawdoctype.test.ts
- types/inferrawdoctype.d.ts
- types/inferschematype.d.ts
Fix #14839
**Summary**
For some reason, it looks like `inferRawDocType<>` is inferring dates as Mongoose Date SchemaType rather than JavaScript dates. If I change to `NativeDate`, that works as expected. I made the same change in InferRawDocType, which doesn't look to be affected by this issue, but should fix that just in case TypeScript decides to change its mind.
**Examples**
> type(inferrawdoctype): infer Date types as JS dates rather than Mongoose SchemaType Date

- test/types/schema.test.ts
- types/schematypes.d.ts
Fix #14879
**Summary**
There are places in the docs where we recommend pushing default setters to schematypes like `mongoose.Schema.String.setters.push(fn)`, but TypeScript types currently don't support that.
**Examples**
> types: make SchemaType static `setters` property accessible in TypeScript

- docs/populate.md
- lib/types/array/methods/index.js
- test/model.populate.setting.test.js
- test/model.populate.test.js
Fix #1635
**Summary**
Calling `push()` on a populated array with an ObjectId currently casts the ObjectId to a document, which seems like dubious behavior. This PR changes that behavior. Putting this in the 8.7 milestone for caution.
**Examples**
> fix: depopulate if `push()` or `addToSet()` with an ObjectId on a populated array

- index.js
**Summary**
While using Sentry (with OpenTelemetry as the underlying system) to instrument Mongoose in my project, I encountered the following error:
```
2024-09-12 11:26:31.183 TypeError: Cannot read properties of undefined (reading ‘prototype’)
2024-09-12 11:26:31.183     at MongooseInstrumentation.patch (/usr/src/app/node_modules/.pnpm/@opentelemetry+instrumentation-mongoose@0.42.0_@opentelemetry+api@1.9.0/node_modules/@opentelemetry/instrumentation-mongoose/build/src/mongoose.js:94:44)
2024-09-12 11:26:31.183     at MongooseInstrumentation._onRequire (/usr/src/app/node_modules/.pnpm/@opentelemetry+instrumentation@0.53.0_@opentelemetry+api@1.9.0/node_modules/@opentelemetry/instrumentation/build/src/platform/node/instrumentation.js:164:39)
2024-09-12 11:26:31.183     at hookFn …
```
> Fix missing `Aggregate` re-exports

- test/types/document.test.ts
- types/document.d.ts
Fix #14876
**Summary**
Right now `doc.depopulate()` just returns `this`, which may be incorrect if paths are depopulated. This PR adds generic parameter, similar to how `doc.populate<{ user: UserType }>('user')` returns document with `user` property updated, `doc.depopulate<{ user: ObjectId }>('user')` also updates the `user` property type.
**Examples**
> types(document): add generic param to depopulate() to allow updating properties

- lib/schema/uuid.js
- test/model.populate.test.js
Fix #14869
**Summary**
As #14869 pointed out, calling `toObject()` on a document with uuids with `getters: true` ends up with `"[object -Obje-ct]--"` strings :cry: This PR should fix that
**Examples**
> fix: make getters convert uuid to string when calling toObject() and toJSON()

- lib/helpers/query/castUpdate.js
- test/model.updateOne.test.js
Fix #3027
**Summary**
Cast `$rename` in updates to a string
**Examples**
> feat(query): cast $rename

- lib/connection.js
- lib/drivers/node-mongodb-native/connection.js
Fix #14727
cc @alexbevi 
**Summary**
The problem here is that `readyState` can return `connected` immediately after an AWS Lambda container thaws after some time. `readyState` only looks at the last heartbeat, but not how long ago the last heartbeat occurred - with this PR, if the last heartbeat is stale (more than 2 heartbeat intervals) then we assume we're disconnected.
This PR still needs significant testing, but I wanted to put it out for review to solicit early feedback.
**Examples**
> fix(connection): avoid returning `readyState = connected` if connection state is stale

- lib/error/bulkSaveIncompleteError.js
- lib/model.js
- test/model.test.js
Fix #14763
**Summary**
Make it so that `bulkSave()` throws an error if not all documents were successfully updated due to version errors or optimistic concurrency. I thought more about #14763 and this seems like the way to go: if not all documents were updated, we don't know which documents we can run post save hooks on, or which documents to update `$isNew` on.
**Examples**
> fix(model): throw MongooseBulkSaveIncompleteError if bulkSave() didn't completely succeed

- lib/constants.js
- lib/helpers/model/applyStaticHooks.js
- test/model.test.js
Fix https://github.com/Automattic/mongoose/issues/14903
**Summary**
Make it so that if the custom static overwrites an existing aggregate middleware, don't apply middleware to it by default. This should be achieved by filtering custom static-named aggregates in `applyStaticHooks.js`. 
Furthermore, aside from this PR, I believe we should extend this filtering not only to query and aggregation middleware but also to other [Mongoose middlewares](https://mongoosejs.com/docs/middleware.html), including Document and Model middleware. Does that make sense? If so, I would like to create another PR for this work.
**Examples**
```
schema.statics.aggregate = function(pipeline) {
let match = { $match: { deleted: { '$ne': false } } };
if (pipeline.length && pipeline[0].$match) { …
```
> fix(model): skip applying static hooks by default if static name conflicts with aggregate middleware

- lib/helpers/projection/isExclusive.js
- lib/helpers/projection/isInclusive.js
- test/helpers/projection.isExclusive.test.js
- test/helpers/projection.isInclusive.test.js
Fix #14893
**Summary**
https://github.com/Automattic/mongoose/commit/2b197b21dff7fb53333a623426d564442f78552e#diff-af7545780ae0b49c587fcbe08b131ce99659ccac5786983702610b6c7a3b8a24 made it so that `isExclusive()` would return `null` if the projection had a `$elemMatch` where the first property was an ObjectId, Date, Buffer, or other value object.
**Examples**
> fix(projection): avoid setting projection to unknown exclusive/inclusive if elemMatch on a Date, ObjectId, etc.

- lib/constants.js
- lib/helpers/model/applyStaticHooks.js
- test/model.test.js
Additional Fix for PR: https://github.com/Automattic/mongoose/pull/14904
**Summary**
Ensure that if a custom static method overwrites an existing mongoose middleware, the middleware is not applied by default, similar to how it works with query and aggregate middleware.
```js
const middlewareFunctions = [
...[
...queryMiddlewareFunctions,
...aggregateMiddlewareFunctions,
...modelMiddlewareFunctions,
...documentMiddlewareFunctions
].reduce((s, hook) => s.add(hook), new Set())
];
```
I used a `Set()` to eliminate duplicates in the following three function names: updateOne, deleteOne, and validate.
1) Document middleware's **updateOne** and Query middleware's **updateOne**
2) Document middleware's **deleteOne** and Query middleware's **deleteOne**
3) Document middleware's **validate** and …
> fix(model): filter applying static hooks by default if static name conflicts with mongoose middleware

- benchmarks/createDeepNestedDocArray.js
- lib/document.js
- test/document.test.js
Fix #14897
**Summary**
Saving a new doc with many very deep subdocs is extremely expensive: the test case in this PR fails after 35 seconds on my local without the change I made to `lib/document.js`. Saving a new doc 10 levels deep is still more expensive than I'd like, this test now takes maybe 300ms, I'll investigate why this is so slow and add a benchmark.
**Examples**
> fix(document): avoid massive perf degradation when saving new doc with 10 level deep subdocs

- lib/helpers/document/applyVirtuals.js
- lib/model.js
- test/model.test.js
- types/models.d.ts
Fix #14818
**Summary**
Logic largely copied from https://github.com/mongoosejs/mongoose-lean-virtuals/blob/master/index.js to apply a Model's virtuals to a POJO.
**Examples**
> feat(model): add `Model.applyVirtuals()` to apply virtuals to a POJO

- docs/migrating_to_6.md
It was removed by this commit that first appeared in the 6.x series:
6865fea216220a88d2e7128d3a8eb8228f29155e
My codebase only used this property for deleting models in a few places. Please peer-review the note
in case there are other uses of this property worth mentioning.
> Update migrating_to_6.md about mongoose.modelSchemas

- .github/workflows/test.yml
- docs/compatibility.md
**Summary**
Re: #14934
**Examples**
> fix: add mongodb 8 to test matrix

- lib/model.js
- lib/options.js
- test/document.test.js
Fix #14935
**Summary**
`insertMany()` currently respects schema-level flattenObjectIds option settings, which means if schema sets `flattenObjectIds: true` then Mongoose will store ObjectIds as strings. 
This does not affect `save()` because `save()` was fixed in #13648, but that issue still affects `insertMany()`.
In general, `internalToObjectOptions` should always set `flattenObjectIds` to `true` because we rely on those options when trying to get the MongoDB server representation of an object for queries, `insertMany()`, etc.
We should also backport this fix to 6.x and 7.x.
**Examples**
> fix: set flattenObjectIds to false when calling toObject() for internal purposes

- lib/helpers/document/applyTimestamps.js
- lib/model.js
- test/model.test.js
- types/models.d.ts
Fix #14698
**Summary**
While we won't automatically apply timestamps to `Model.insertMany(docs, { lean: true })` anymore re: https://github.com/Automattic/mongoose/issues/14698#issuecomment-2380251651, we can at least make it easy to do `await MyModel.insertMany(docs.map(doc => MyModel.applyTimestamps(doc)), { lean: true })`
**Examples**
> feat(model): add applyTimestamps() function to apply all schema timestamps, including subdocuments, to a given POJO

- lib/model.js
Fix #14951
**Summary**
Help clarify why #14951 is happening
**Examples**
> docs(model): add more info on acknowledged: false, specifically that Mongoose may return that if the update was empty

- test/types/schema.test.ts
- types/inferschematype.d.ts
Fix #14950
**Summary**
#14950 points out that it is tricky to handle GeoJSON with TypeScript schema definitions because `inferschematype` doesn't handle `type: { type: String }` correctly.
**Examples**
> types: correct schema type inference when using nested typeKey like `type: { type: String }`

- lib/schema.js
- lib/schema/array.js
- lib/schema/documentArray.js
- lib/types/array/index.js
- lib/types/documentArray/index.js
- test/document.test.js
- types/index.d.ts
**Summary**
Neat little feature that allows defining virtuals on arrays, so you can define a `last` virtual on an array that gets you the last element in the array:
```js
schema.virtual('nums.last', { applyToArray: true }).get(function() {
return this[this.length - 1];
});
// Later
doc.nums.last; // last element in the array
```
Fix #2326
**Examples**
> feat: allow defining virtuals on arrays, not just array elements

- test/types/schema.test.ts
- types/index.d.ts
- types/query.d.ts
Fix #14902
**Summary**
#14902 points out correctly that `lean()` returns buffers as instances of `mongodb.Binary` at runtime, but our types say buffers are of type `Buffer`. This PR changes Mongoose's TypeScript types to match the runtime behavior.
**Examples**
> types: make Buffers into mongodb.Binary in lean result type to match runtime behavior

- lib/helpers/populate/getModelsMapForPopulate.js
- lib/helpers/populate/modelNamesFromRefPath.js
- test/model.populate.test.js
Re: #10983
Also related to #6870, that issue addresses a slightly different case where the `refPath` is within the same doc array as the id.
**Summary**
There was a bug in our fix for #10983 where we mishandle `refPath` in an array of ObjectIds where the `refPath` refers to a parent of the array.
```javascript
const Parent = db.model(
'Parent',
new mongoose.Schema({
docArray: [
{
type: {
type: String,
enum: ['Child', 'OtherModel']
},
ids: [
{
type: mongoose.Schema.ObjectId,
refPath: 'docArray.type' // <-- note that `docArray.type` is not within the `ids` array
}
]
}
]
})
);
```
In `getModelsMapForPopulate()`, we end up with a case where we have a flat array of all ids and a flat array of all model names, but no way to match the two. In `flat.filter((val, i) => modelNamesForRefPath[i] === …
> fix(populate): handle array of ids with parent refPath

- lib/helpers/document/cleanModifiedSubpaths.js
- test/document.test.js
Fix #14952
**Summary**
Right now `cleanModifiedSubpaths()` cleans the modified paths from the affected subdoc and the top-level doc, but not any intermediate subdocs, which can cause false validation errors like in #14952.
**Examples**
> fix(document): recursively clear modified subpaths when setting deeply nested subdoc to null

- docs/documents.md
- package.json
Fix #14944
**Summary**
Add section in the docs about setting deeply nested paths. Clarify that `?.` and `??` are fine, we also support `.get()` and `.set()`, but `??=` comes with caveats.
**Examples**
> docs(documents): add section on setting deeply nested properties, including warning about nullish coalescing assignment

- types/inferschematype.d.ts
**Summary**
Improve Go to Definition for inferred schema definitions
**Examples**
In [schema.test.ts](https://github.com/Automattic/mongoose/blob/c187fd84d197e2f29759a157c798538661d36079/test/types/schema.test.ts#L471), add a type alias such as
```ts
type InferredSchemaDecimal2 = InferredTestSchemaType['decimal2'];
```
Without this change, using "Go to Definition" does not work, and the typescript language service reports "No definition found". With this change, "Go to Definition" navigates directly to the definition in the schema.
[Screencast](https://github.com/user-attachments/assets/9d59082d-b592-48a7-9021-264ac46a2331)
I don't think there's a way to test for this with `tsd`, you just need to know the pattern to make it work nicely.
> types: improve goto definition for inferred schema definitions

- types/connection.d.ts
**Summary**
Quick fix for a missing option
**Examples**
> types(connection): add missing sanitizeFilter option

- docs/migrating_to_7.md
**Summary**
Currently link to the section "Id Setter" is not working due to a missing id & the auto-generated one is not the correct one!
> docs(migration-guide-v7): correct link to the section "Id Setter"

- lib/cursor/aggregationCursor.js
- lib/cursor/queryCursor.js
- test/query.cursor.test.js
- types/cursor.d.ts
**Summary**
Implemented using `_destroy()` like recommended in Node docs here: https://nodejs.org/api/stream.html#writable_destroyerr-callback because that's the preferred way to handle async cleanup in destroy(), because destroy() itself needs to be sync.
**Examples**
> fix(cursor): close underlying query cursor when calling destroy()

- test/types/check-types-filename.js
- test/types/schema.test.ts
- types/index.d.ts
Fix #14451
**Summary**
Right now it is hard to get the type of the JSON serialized document from a Mongoose document and schema. This PR adds a JSONSerialized<T> type helper which transforms Mongoose subdocs into POJOs, ObjectIds into strings, Dates into strings, and Maps into POJOs. That should cover most cases.
**Examples**
> types: add JSONSerialized helper that can convert HydratedDocument to JSON output type

- lib/model.js
- test/model.test.js
- types/indexes.d.ts
Fix #14868
**Summary**
Add an option to make `syncIndexes()` mark indexes as hidden (see [MongoDB hidden indexes docs](https://www.mongodb.com/docs/v5.1/core/index-hidden/)) as opposed to dropping them. Hidden indexes are useful because rebuilding an index can be expensive, so if you accidentally drop a index that you shouldn't it can take a while to recover. With hidden indexes, you can test whether removing this index will cause performance issues without actually dropping the index. `syncIndexes({ hideIndex: true })` will hide all non-schema indexes rather than dropping them.
Hidden index support was added in MongoDB 4.4 so we should make a quick note about version compatibility, since Mongoose 8 technically supports all the way back to MongoDB 3.6.
**Examples**
> feat(model): add hideIndexes option to syncIndexes() and cleanIndexes()

- lib/query.js
- test/query.test.js
- types/query.d.ts
Fix #11474
**Summary**
Schema-level `select: false` is very useful, but there are cases where you want to disable `select: false` for all fields, like building an admin panel. This option will be very useful for mongoose studio.
**Examples**
> feat(query): add schemaLevelProjections option to query to disable schema-level select: false

- lib/cast.js
- lib/query.js
- test/query.test.js
Re: #14657
**Summary**
By default, Mongoose adds `$in` when you query a non-array field with an array value. So `Test.find({ name: ['foobar'] })` becomes `Test.find({ name: { $in: ['foobar'] } })` by default. #14657 pointed out that this behavior seems contradictory with `sanitizeFilter`, which is supposed to disallow any query selectors.  This PR makes `sanitizeFilter` disable the implicit `$in` behavior.
**Examples**
> fix(query): make sanitizeFilter disable implicit $in

- types/index.d.ts
Fix: #14988 
**Summary**
The global is defined in the @types/node package, which is not in the dependencies. Without the package, NativeDate would be interpreted as any by typescript, and resolves the types in the Schema incorrectly.
**Examples**
```
import { Schema, Types } from "mongoose";
interface IUser {
organization: Types.ObjectId;
}
const userSchema = new Schema<IUser>({
// typescript error: Type 'typeof ObjectId' is not assignable to type 'DateSchemaDefinition | typeof Mixed | undefined'.
organization: { type: Schema.Types.ObjectId, ref: "Organization" },
});
```
> types: use globalThis instead of global for NativeDate

- package.json
Fix #14877
**Summary**
Most notably, this PR loosens our longstanding policy of pinning exact versions of the MongoDB Node driver: Mongoose 8.8 will now be compatible with MongoDB Node driver 6.10.x.
Re: issues like #14877, we may consider further loosening Mongoose's supported MongoDB Node driver semver range in the future, but `~6.10` should be a good first step.
**Examples**
> feat: upgrade mongodb -> ~6.10

- test/types/document.test.ts
- test/types/models.test.ts
- test/types/populate.test.ts
- test/types/schema.test.ts
- types/index.d.ts
- types/models.d.ts
- types/query.d.ts
Re: #12959
**Summary**
Technically `__v` always exists on hydrated documents, unless `versionKey` option is set to `false` in the schema. Admittedly most developers don't use `__v` directly, but #12959 pointed it out.
**Examples**
> types: add __v to lean() result type and ModifyResult

- types/document.d.ts
**Summary**
- There is type support for `flattenMaps`, but there wasn't any for `flattenObjectIds`, and I wanted to add type support for that. I hope there are no errors; if there are, please provide this support. Thank you.
**Examples**
> types: added toJSON:flattenObjectIds effect

- lib/model.js
**Summary**
If `bulkWrite()` throws any error that doesn't have a `writeErrors` property, `bulkSave()` fails with `TypeError: Cannot read properties of undefined (reading 'find')`
**Examples**
> fix(model): avoid throwing TypeError if bulkSave()'s bulkWrite() fails with a non-BulkWriteError

- lib/model.js
**Summary**
If `collection.createIndex()` happens to throw a sync error (as opposed to returning a promise that rejects), we end up with an unhandled error. Long term, I think what we should do is refactor to use async/await, but this fix should be enough for now.
**Examples**
> fix(model): avoid unhandled error if `createIndex()` throws a sync error

- package.json
**Summary**
This PR updates 7.x `mongodb-memory-server` to `9.5.0` as it has some fixes regarding ubuntu 2404 and rhel 8 handling (backported from 10.x)
> 7.x: deps(mongodb-memory-server): upgrade to 9.5.0

- docs/migrating_to_6.md
I spent many hours migrating a large code base from 5.x to 6.x. By a large margin, more hours were lost as a result of the change to `strictQuery: true`. Parts of my queries had been discarded and it wasn't clear why.
Although I had read the migration guide multiple times, perhaps I glossed over this section believing that since I wasn't using the strictQuery option before, this change didn't apply to me.
To limit my scope of work, I always wasn't reading ahead to the changes in 7.x, where the default flipped back to what it was in 5.x.
So only at the very end during peer-review did someone point out that we should set `strictQuery:false`-- the default in both 5.x and >=7.x. Then I re-read that section of the migration guide and all my problems with parts of queries being discarded made …
> docs(migration-guide-6x): document that strictQuery default will flip-back

- lib/mongoose.js
- test/document.test.js
Fix #14961
**Summary** 
We found in #14961 that subdocument discriminators created using `Schema.prototype.discriminator()` don't get 'validate' hooks applied correctly. That's because are calling `applyEmbeddedDiscriminators()` _after_ `Model.compile()`. And Mongoose generally assumes that all middleware is registered before model compilation. This PR moves `applyEmbeddedDiscriminators()` up.
**Examples**
> fix: apply embedded discriminators to subdoc schemas before compiling top level model so middleware applies correctly

- lib/helpers/isBsonType.js
- lib/helpers/schema/applyReadConcern.js
- lib/helpers/schema/applyWriteConcern.js
- lib/query.js
Re: #14906
**Summary**
Some small improvements that maybe give us an extra 1-2% on performance. Not huge, but a step in the right direction. I'm still debugging to see where we can find some extra perf.
**Examples**
> perf: make a few micro-optimizations to help speed up findOne()

- lib/error/objectParameter.js
- lib/model.js
- lib/query.js
- test/query.test.js
Re: #14948
**Summary**
As we found out in #14948, `findOne(null)` throws an error with the MongoDB Node driver, but Mongoose treats it as `findOne({})`. I do think that making `findOne(null)` and `findOne(undefined)` throw an error is more correct (while still allowing `findOne({})` and `findOne()` to return the first doc), and I think this change is a step in the right direction, but I'm wondering if we should put this in a minor release 8.10, or hold off until 9.0?
**Examples**
> fix(model+query): make `findOne(null)`, `find(null)`, etc. throw an error instead of returning first doc

- .github/workflows/benchmark.yml
- .github/workflows/documentation.yml
- .github/workflows/test.yml
- .github/workflows/tidelift-alignment.yml
- .github/workflows/tsd.yml
**Summary**
Node 22 is the current Node.js version and LTS version. It was missing from CI test matrix.
I've already been running Mongoose on Node 22 for a while without issues, but it should be included in the official CI too. Therefore:
- Add 22 to test matrix, in addition to existing ones.
- Replace older single-version actions with 22. Some were run in Node 16, which is end-of-life. Some in 18, which will be end-of-life in six months. If an action is only run in one version, might as well be the latest.
For successful CI run, see the [PR in this fork](https://github.com/stscoundrel/mongoose/pull/1)
> CI: add Node 22

- lib/helpers/indexes/isTimeseriesIndex.js
- lib/model.js
- test/model.test.js
Fix #14984
**Summary**
Starting in MongoDB 6.3, MongoDB server creates a default index on timeseries collections, see [docs here](https://www.mongodb.com/docs/manual/core/timeseries/timeseries-index/#compound-indexes). We shouldn't try to drop that index if the schema has `timeseries` option.
**Examples**
> fix(model): make diffIndexes() avoid trying to drop default timeseries collection index

- lib/helpers/model/castBulkWrite.js
- test/model.test.js
Fix #14978
**Summary**
Right now we don't handle array filters when casting bulkWrite, this PR fixes that
**Examples**
> fix(model): handle array filters when casting bulkWrite

- lib/query.js
**Summary**
While debugging some unexpected memory usage in a production cluster, we noticed that mongoose's `Query` object was constructing a new `Error` instance in order to be able to preserve the original stack when throwing an error after attempting to execute the query more than once. This is problematic in that until the stack is converted to a string, the error retains references to every object in the call site info. This PR changes the execution stack object to the actual stack string to avoid this problem. Since this variable appears intended to not be part of the public API it seems reasonable to change.
**Examples**
> fix: save execution stack in query as string

- types/cursor.d.ts
Fix #14976
**Summary**
Add `Symbol.asyncDispose()` to querycursors and correct the return type of `Symbol.asyncIterator` to indicate that it returns a cursor with different return type. I had to add a new generic `NextResultType` to work around the issue where `next()` always returns `DocType | null`.
No need for any runtime changes AFAIK because [Node.js streams already support AsyncDispose](https://nodejs.org/api/stream.html#readablesymbolasyncdispose)
**Examples**
> types(cursor): correct `asyncIterator` and `asyncDispose` for TypeScript with lib: 'esnext'

- lib/helpers/populate/getModelsMapForPopulate.js
- lib/model.js
- lib/validOptions.js
- test/model.populate.test.js
- types/populate.d.ts
Fix #14979
**Summary**
It is a little strange that `doc.populate('child')` will populate 'child' even if 'child' is already populated. This PR adds an option to disable that behavior, either for an individual populate call using `doc.populate({ path: 'child', forceRepopulate: false })` or globally with `mongoose.set('forceRepopulate', false)`.
We should consider making `forceRepopulate` default to false for Mongoose 9.
**Examples**
> feat: add forceRepopulate option for populate() to allow avoiding repopulating already populated docs

- lib/helpers/model/castBulkWrite.js
- lib/helpers/query/castUpdate.js
- lib/query.js
- test/model.test.js
Fix #15040
**Summary**
#15040 points out there's no way to set `overwriteDiscriminatorKey` for `bulkWrite()`. Also had a good suggestion for inferring the discriminator key from the update if `overwriteDiscriminatorKey` is set, I added that.
**Examples**
> fix(model+query): support overwriteDiscriminatorKey for bulkWrite updateOne and updateMany, allow inferring discriminator key from update

- benchmarks/saveSimple.js
- lib/document.js
- lib/model.js
- lib/options/saveOptions.js
- lib/plugins/saveSubdocs.js
- lib/schema.js
Fix #15029
**Summary**
#15029 points out that we spend a lot of unnecessary CPU cycles in `save()` in `$getAllSubdocs()`, even for schemas that have no subdocs. That's because currently `save()` calls `$getAllSubdocs()` 5 times, and `$getAllSubdocs()` loops through every path in the document searching for subdocs.
With this PR, we will only call `$getAllSubdocs()` 1x if calling `save()` with no subdocs, and also `$getAllSubdocs()` will only loop through paths we know can have subdocs based on the schema. So if the schema doesn't have any subdocuments, document arrays, or maps of subdocs, then `$getAllSubdocs()` will have an empty `for` loop.
In my quick experiment with the `saveSimple` benchmark, I'm seeing a 2.7% improvement in performance, which isn't huge, but that's 2.7% on every save …
> perf: cache results from getAllSubdocs() on saveOptions, only loop through known subdoc properties

- lib/helpers/schema/getIndexes.js
- lib/model.js
- lib/query.js
- lib/schema.js
- lib/schemaType.js
- test/document.test.js
- test/types/schema.test.ts
- types/index.d.ts
- types/indexes.d.ts
- types/schematypes.d.ts
**Summary**
Allow overriding MongoDB's default "duplicate key error" message in your schemas:
```javascript
new Schema({
email: { type: String, unique: [true, 'Email must be unique'] }
});
```
This works for `save()` and query methods, but does **not** work for `bulkWrite()` and `insertMany()` because the duplicate key error in that case does not return `keyPattern`, which means we would either have to guess the duplicate key by the index name (brittle) or parse the index key from the error message (we would have to pull in Acorn or something like that, because duplicate key error message is not formatted as JSON).
**Examples**
> feat: allow specifying error message override for duplicate key errors `unique: true`

- lib/helpers/query/getEmbeddedDiscriminatorPath.js
- test/model.updateOne.test.js
Fix #15051
**Summary**
If user updates the embedded discriminator key via array filter, use the overwritten discriminator key when casting the update.
**Examples**
> fix: cast using overwritten embedded discriminator key when set

- docs/guide.md
- docs/schematypes.md
- index.js
- lib/cast/double.js
- lib/helpers/clone.js
- lib/mongoose.js
- lib/schema.js
- lib/schema/double.js
- lib/schema/index.js
- test/double.test.js
- test/helpers/isBsonType.test.js
- test/types/schemaTypeOptions.test.ts
- types/inferschematype.d.ts
- types/schematypes.d.ts
**Motivation**
Support a IEEE 754-2008 floating point type in mongoose for compatibility with CSFLE/QE. The current `Number` schema type can result in either Int32, Int64, or Doubles that are inserted into the database using type inference but CSFLE and QE require exact BSON types in schemas.
The reason the Double constructor returns a BSON.Double is so even when an integer is inserted, the field is still queryable as a `$double`:
```
await Test.create({ myDouble: '42' });
const doc = await Test.findOne({ myDouble: { $type: 'double' } });
assert.deepEqual(doc.myDouble, new BSON.Double(42));
```
**Summary of Changes**
- Same changes as NODE-6503 but for Double.
- Add `SchemaType` `Double`, which has the following behavior:
- its default `cast` method throws when provided a 
- a non-numeric …
> feat(NODE-6504): Add Double as a SchemaType

- lib/document.js
- lib/schemaType.js
- test/model.hydrate.test.js
Fix #15048
**Summary**
#15048 points out that `hydratedPopulatedDocs` option for `hydrate()` doesn't mark the paths as `populated()`. Also turns out that `hydrate()` doesn't actually hydrate the nested populated docs.
**Examples**
> fix: mark documents that are populated using hydratedPopulatedDocs option as populated in top-level doc

- test/types/docArray.test.ts
- types/types.d.ts
Fix #15041
**Summary**
We need `splice()` in the DocumentArray type definition, because `splice(1, 0, { name: 'foo' })` should work.
**Examples**
> types: add splice() to DocumentArray to allow adding partial objects with splice()

- lib/connection.js
- lib/drivers/node-mongodb-native/connection.js
cc @alexbevi 
Fix #15042
Revert #14812
**Summary**
We've gotten a few bug reports that indicate connectivity issues with Mongoose 8.7, including #14971 etc. Most notably, we've confirmed that #15042 is caused by the heartbeat check we added in #14812: we should not use that heartbeat check if the topology is `LoadBalanced` because the MongoDB Node driver doesn't send heartbeats in that case, so for LoadBalanced topology Mongoose currently loses connectivity after 20 seconds. Given this and all the issues we've gotten specifically referencing connectivity issues in Mongoose 8.7.0, I think it is prudent to remove this check for now.
**Examples**
> fix(connection): remove heartbeat check in load balanced mode

- test/types/PipelineStage.test.ts
- test/types/expressions.test.ts
- types/expressions.d.ts
Fixes #15086
**Summary**
Adds TypeScript support for the $firstN, $lastN, $bottom, $bottomN, $minN and $maxN operators
**Examples**
```typescript
GameEntry.aggregate([
{
$sort: { score: -1 }
},
{
$group: {
_id: '$gameId',
maxScores: {
$firstN: { input: '$score', n: 3 }
}  
}
]);
```
> types(aggregate): add $firstN, $lastN, $bottom, $bottomN, $minN and $maxN operators

- index.js
- lib/connection.js
- lib/cursor/aggregationCursor.js
- lib/document.js
- lib/drivers/node-mongodb-native/collection.js
- lib/model.js
- lib/mongoose.js
- lib/query.js
- lib/schema/string.js
- package.json
**Summary**
This PR does a bunch of small maintenance things, mainly removing more `callback` documentation references, some other changes include:
- remove `Double` from being assigned in `index.js` because it does not exist in `mongoose`
- import & export `MongooseError` *once*
- use consistent error constructors for `mongoose::model`
- assign more function names (to not have them be `anonymous` anymore)
- remove "always true" path in `model::aggregate`
- expose `Connection::on` and `Connection::once` to the documentation
- update `@typescript-eslint/*` to fix warning in `npm lint`
> Remove more `callback` doc references & some small other changes

- lib/schema.js
- test/schema.test.js
Fix #15056
**Summary**
Defining an index using `unique` in schema path and later calling `schema.index()` causes 2 indexes to be added, which is likely a user error.
**Examples**
> fix(schema): throw error if duplicate index definition using `unique` in schema path and subsequent `.index()` call

- lib/model.js
- test/model.test.js
**Summary**
`Model.validate()` handles discriminators property, but `Model.castObject()` does not, which causes problems when calling `Model.validate()` on a schema that has embedded discriminators, as well as when calling `castObject()` with a discriminator key.
**Examples**
> fix(model): handle discriminators in castObject()

- test/types/document.test.ts
- types/document.d.ts
Fix #15077
**Summary**
#15077 points out that `lean()` and `toObject()` should return compatible types, but currently do not due to __v
**Examples**
> types(document): make sure `toObject()` and `toJSON()` apply versionKey __v

- lib/model.js
- test/docs/transactions.test.js
Fix #15091
**Summary**
MongoDB does not allow multiple operations on a single transaction in parallel. Since Mongoose `create()` uses `save()` under the hood, Mongoose cannot reliably `create()` multiple docs in a transaction unless `ordered: true` is set.
**Examples**
> fix(model): throw error if calling `create()` with multiple docs in a transaction unless `ordered: true`

- lib/aggregate.js
- lib/cursor/aggregationCursor.js
**Summary**
Aggregate cursors didn't automatically add session if it was present in AsyncLocalStorage. Also the options weren't the same for exec and cursor so I added a function to make them the same just like in QueryCursor.
**Examples**
```js
mongoose.set("transactionAsyncLocalStorage", true);
mongoose.connect("mongodb://127.0.0.1:27017/cursortest");
const test = async () => {
await mongoose.connection.transaction(async (session) => {
const TestModel = mongoose.model(
"Test",
new mongoose.Schema({ name: String })
);
mongoose.set("debug", true);
await TestModel.aggregate([{ $match: {} }]);
const cursor1 = TestModel.aggregate([{ $match: {} }]).cursor();
const cursor2 = TestModel.aggregate([{ $match: {} }])
.session(session)
.cursor();
await …
```
> Fix aggregate cursor als

- lib/helpers/indexes/isIndexSpecEqual.js
- lib/schema.js
- test/helpers/indexes.isIndexSpecEqual.js
- test/schema.test.js
Fix #15109
**Summary**
#15109 points out that if index spec has keys in different order, that is still valid. So `schema.index({ a: 1, b: 1 }); schema.index({ b: 1, a: 1 })` should work. Also, if there is a custom index `name`, then that is fine too, because MongoDB enforces index uniqueness based on `name`. It's just that two indexes with the same spec will have the same `name` unless an explicit `name` option is specified in the index options.
**Examples**
> fix(schema): avoid throwing duplicate index error if index spec keys have different order or index has a custom name

- lib/connection.js
- lib/document.js
- lib/model.js
Fix #15107
**Summary**
Fix a couple of docs issues mentioned in #15107.
**Examples**
> docs(connection+document+model): remove remaining references to remove(), clarify that deleteOne() does not execute until then() or exec()

- lib/helpers/populate/getModelsMapForPopulate.js
Fix #15078
**Summary**
Although 5.x is technically EOL, I think it is reasonable to make an exception and backport the security fix for CVE-2024-53900 to 5.x. It is not a difficult fix, and would help out developers that are still on 5.x.
After this though, we will mark Mongoose 5.x as deprecated in npm.
**Examples**
> fix(populate): backport security fix for $where in populate

- lib/types/map.js
- test/types.map.test.js
Fix #15108
**Summary**
#15108 is due to Mongoose change tracking not cleaning up modified paths underneath maps of subdocs when overwriting the entire subdoc. So `doc.map.delete('subdoc')` will still leave any subpaths of `map.subdoc` modified. This PR cleans up those paths.
**Examples**
> fix(map): clean modified subpaths when overwriting values in map of subdocs

- test/types/lean.test.ts
- types/index.d.ts
Fix #15057
Replacement for #15072
**Summary**
This looks to be a more correct approach than #15072, which had some unexpected issues that @hasezoey pointed out. @hasezoey can you please double check whether this causes issues for Typegoose? 
**Examples**
> types: correctly handle union types in BufferToBinary and related helpers

- docs/typescript/populate.md
- types/index.d.ts
Fix #15101
**Summary**
Mongoose does support using `ref` on UUID paths, so we should also support it in the RefType and PopulatedDoc<> helpers.
**Examples**
> types: add UUID to RefType

- docs/js/search.js
**Summary**
I refactored https://github.com/mongoosejs/backend to run on Netlify functions because I was having a lot of trouble with deploying to Azure Functions. Netlify's automatic CI/CD should make it much easier to maintain the backend going forward.
I will have to make this change in other branches. However not urgent - the Azure Functions endpoint is still running and up to date, I just had to make some changes to our GitHub webhook re: #15117 so that's the only code that's out of date.
**Examples**
> move search endpoint to netlify

- test/types/lean.test.ts
- types/index.d.ts
Fix #15122
**Summary**
The problem in #15122 is that BufferToBinary is drilling into Document instances, and when a user does `Document & IChild` we can't reliably infer the raw document type, so we need to skip that case.
**Examples**
> types: make BufferToBinary avoid Document instances

- lib/model.js
- test/model.test.js
Fix #15075
**Summary**
#15075 pointed out that `Model.castObject()` silently ignores document arrays that are set to primitive non-null values. This PR fixes that, including accounting for `castNonArrays` schema object.
**Examples**
> fix(model): handle document array paths set to non-array values in Model.castObject()

- lib/model.js
**Summary**
Although `updateOne()` should never return a nullish value under normal circumstances, we can be more defensive in this code
**Examples**
> fix(model): avoid throwing unnecessary error if `updateOne()` returns `null` in `save()`

- lib/cursor/queryCursor.js
Fix #10449
**Summary**
I wasn't able to repro #10449 locally, but there shouldn't be any issues with clearing the stack on every call. Minor performance impact, but better parallelization and less risk of stack overflows.
**Examples**
> perf(cursor): clear the stack every time if using populate with batchSize to avoid stack overflows with large docs

- lib/document.js
- lib/utils.js
Fix #15071
**Summary**
#15071 is a tricky situation where the user has a shared connection package that uses Mongoose 8.8, and a client npm package which defines schemas using Mongoose 8.5 but then defines models using the Mongoose 8.8 connection. And we added a new `childSchemas.path` property in 8.8.3 with #15029 that Mongoose 8.8.3 expects, but schemas from Mongoose 8.5 do not have.
The "right" solution is to tell the user to ensure a consistent version of Mongoose, because we cannot realistically test that schemas from every version of Mongoose work with models from every other version of Mongoose. However, in the interest of not breaking code that previously worked, we can use this PR's more backwards-compatible approach.
**Examples**
> fix(document): avoid using childSchemas.path for compatibility with pre-Mongoose-8.8 schemas

- test/types/populate.test.ts
- types/models.d.ts
- types/query.d.ts
Fix #15111
**Summary**
`.populate<Paths>` returns a hydrated document with no virtuals, because we're not passing `TVirtuals` into queries. This PR fixes that by replacing `TInstanceMethods` with `TDocOverrides` similar to what we do for `HydratedDocument` - globbing together instance methods and virtuals into one "overrides" type that we `&` on to get the fully hydrated document.
**Examples**
> types(model+query): avoid stripping out virtuals when calling populate with paths generic

- lib/schema.js
- test/schema.test.js
Fix #15109
Re: #15112
**Summary**
The new duplicate index error has caused some headache for a lot of users, so in the interest of not blocking anyone from upgrading, I changed the error to a warning. That way there is an indication that duplicate indexes are a problem, and it should be only slightly more difficult to trace down the duplicate index because Node.js warnings can get stack traces with the `--trace-warnings` command line flag.
**Examples**
> fix(schema): make duplicate index error a warning for now to prevent blocking upgrading

- lib/document.js
- lib/model.js
- lib/schema.js
- lib/schema/array.js
- lib/schema/buffer.js
- lib/schema/decimal128.js
- lib/schema/number.js
- lib/schema/objectId.js
- lib/schema/string.js
- lib/schema/uuid.js
- lib/schemaType.js
- test/model.hydrate.test.js
**Summary**
Right now `hydratedPopulatedDocs` only goes one level deep, with both virtuals and conventional populate. This PR makes hydratedPopulatedDocs recursive.
**Examples**
> Handle hydrating deeply nested populated docs with hydratedPopulatedDocs

- lib/schema/documentArray.js
- lib/schema/subdocument.js
- test/model.test.js
Fix #15120
**Summary**
#15120 is caused by us reapplying embedded discriminators unnecessarily to cloned schematypes - when a schematype is `clone()`-ed, we also copy over the discriminator settings. So no need to reapply discriminators later. When cloning a schematype with discriminators, also copy the `_appliedDiscriminators` flag.
**Examples**
> fix(schema): allow multiple self-referencing discriminator schemas using Schema.prototype.discriminator

- lib/aggregate.js
- lib/connection.js
- lib/cursor/aggregationCursor.js
- lib/drivers/node-mongodb-native/connection.js
- test/connection.test.js
- types/connection.d.ts
Fix #15118
**Summary**
MongoDB 7 and up supports `aggregate()` on databases. The `$documents` stage only works on db.aggregate(), more info on db.aggregate() here: https://www.mongodb.com/docs/manual/reference/method/db.aggregate/.
**Examples**
> feat(connection): support Connection.prototype.aggregate() for db-level aggregations

- lib/document.js
**Summary**
Schema.options.ref works with functions but it doesn't mark the path as populated if done manually when creating a new document or assigning to a property.
**Examples**
```
mongoose.connect("mongodb://localhost:27017");
const test = async () => {
username: { type: String },
phone: { type: mongoose.Schema.Types.ObjectId, ref: "phones" },
});
const userSchemaWithFunc = new mongoose.Schema({
username: { type: String },
phone: {
type: mongoose.Schema.Types.ObjectId,
ref: function () {
return "phones";
},
},
});
const phoneSchema = new mongoose.Schema({
phoneNumber: { type: String },
extension: { type: String },
});
const User = mongoose.model("users", userSchema);
const UserWithFunc = …
```
> Fix document not applying manual populate when using a function in schema.options.ref

- CHANGELOG.md
- lib/model.js
- package.json
- test/model.test.js
**Summary**
`autoCreate` is supposed to skip implicit `createCollection()` calls, but `syncIndexes()` still sends a `createCollection()` even if `autoCreate` is disabled.
The potential issue with automatic `createCollection()` is calling `createCollection()` unnecessarily on every server restart (presuming the user calls `syncIndexes()` on every server restart) is wasteful and may cause slight performance degradation. 
Will put this in 8.10 in the interest of being cautious.
**Examples**
> fix(model): skip createCollection() in syncIndexes() if autoCreate: false

- scripts/website.js
**Summary**
For example, "Using `populatedDoc`" currently becomes `using-code>populateddoc</code>` because 1) `replace(/[^a-z0-9-_\s]/, '')` is missing a global flag, 2) need to strip out `<code>` and `</code>`
Here's the live example: https://mongoosejs.com/docs/typescript/populate.html#using-code%3Epopulateddoc%3C/code%3E
**Examples**
> docs: fix <code> in header ids

- test/types/lean.test.ts
- types/index.d.ts
- types/query.d.ts
Fix #15158
**Summary**
I am not entirely certain why this fix works, mostly done by trial and error. Likely https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types.
This PR is more reason why I would like to get rid of the various `BufferToBinary` etc. helper types in favor of calculating various types in the schema: raw doc type, hydrated doc type, and JSON serialized doc type.
**Examples**
> types: avoid BufferToBinary<> wiping lean types when passed to generic functions

- lib/model.js
- test/document.test.js
- types/models.d.ts
Fix #15156
**Summary**
Support `validateBeforeSave` option for `bulkSave()`, equivalent to the same option for `save()`. Also fixed an issue where `bulkSave()` currently validates document twice when inserting new doc.
**Examples**
> fix(model): allow passing validateBeforeSave option to bulkSave() to skip validation

- lib/model.js
- test/model.test.js
- test/types/models.test.ts
- types/models.d.ts
**Summary**
Fix #14843 
`insertOne()` is similar to `create()`, but only supports creating a single document. `insertOne()` is useful for 2 reasons:
1. Consistency with the [MongoDB CRUD API](https://www.mongodb.com/resources/products/fundamentals/crud). Mongoose models currently support all of the MongoDB CRUD API methods _except_ `insertOne()`, which is a bit of a gotcha.
2. `create()` with `options` has proven to be confusing for users, because `create(doc, { session })` attempts to create 2 documents, the 2nd with a `session` property. I don't want to drop support for `create(doc1, doc2)` (spread args) because that would just create the opposite hard-to-diagnose issue where `doc2` gets treated as options. `insertOne()` offers a neat alternative for users who just want to create 1 doc …
> feat(model): add insertOne() function to insert a single doc 

- lib/document.js
- package.json
- test/document.test.js
Fix #15084
**Summary**
With a little bit of work, we can support `transform` on a per-schematype basis, which can enable us to control how types end up being serialized to JSON. This is useful for custom schema types, as specified in #15084, also useful for controlling how buffers get serialized.
**Examples**
> feat(document): support schematype-level transform option

- .eslintrc.js
**Summary**
This PR sets ESLint's parser's ECMAScript version to `2022`, which is a version the targeted nodejs (16.20) supports, and could cause problems like in #15163
> Set ESLint ECMAScript version to `2022`

- package.json
**Summary**
This PR updates some lint dev-dependencies to their latest version. ESLint 8.x is EOL, so we might as well use the latest version.
Should we upgrade ESLint to 9.x within mongoose 8.x (which requires node 18+), as we only run lint in higher node environments and also already have other things that require higher node versions?
> Update lint dev-dependencies

- lib/model.js
- test/model.test.js
Fix #15164
**Summary**
#15075 fix unintentionally made it so that `Model.validate()` skips document arrays if the value being casted is an array. This PR fixes that.
**Examples**
> fix(model): make Model.validate() static correctly cast document arrays

- lib/schema/bigint.js
- lib/schema/boolean.js
- lib/schema/int32.js
- test/cast.test.js
Fix #15170
**Summary**
Added bitwise operator support to int32. Also fixed a couple of invalid `applySetters()` calls: `this.applySetters(null, val, context);` is incorrect args, first param to applySetters is value and 2nd is context. This makes it so that any operators that we don't have an explicit definition for are casted to the given schematype. For example, if `x` is a boolean, then `{ x: { $someConditional: 'true' } }` will get casted to `$someConditional: true`.
**Examples**
> fix(schema): handle bitwise operators on Int32

- lib/helpers/createJSONSchemaTypeDefinition.js
- lib/schema.js
- lib/schema/array.js
- lib/schema/bigint.js
- lib/schema/boolean.js
- lib/schema/buffer.js
- lib/schema/date.js
- lib/schema/decimal128.js
- lib/schema/documentArray.js
- lib/schema/double.js
- lib/schema/int32.js
- lib/schema/map.js
- lib/schema/number.js
- lib/schema/objectId.js
- lib/schema/string.js
- lib/schema/subdocument.js
- lib/schema/uuid.js
- lib/schemaType.js
- package.json
- test/schema.test.js
- types/index.d.ts
- types/schematypes.d.ts
**Summary**
Re: #11162, add a `jsonSchema()` method to schemas that allows creating a JSON schema for use with MongoDB server's `$jsonSchema` data validation. Alternatively, it can also produce a JSON schema for validation with normal JSON schema validators, like ajv - MongoDB's JSON schema syntax is slightly different and supports different types.
**Examples**
> Schema.prototype.jsonSchema(): convert Mongoose Schema to JSON schema

- lib/collection.js
**Summary**
Should be a fix for #14971.
In Mongoose 7+8, buffering should only happen before `mongoose.connect()` has been called. The reason why Mongoose still has buffering is that the MongoDB node driver will error out if you try to send a database operation on a MongoClient instance that you haven't called `connect()` on yet. But once the MongoDB Node driver has connected successfully to MongoDB at least once, database operations like `find()` etc. handle retries and disconnection via an internal server selection process, so Mongoose buffering is unnecessary.
When investigating #14971, I found that Mongoose may still buffer if the collection is created during a connection interruption. For example, in the following script, `console.log('Buffer', TestModel.collection.buffer);` will …
> fix(collection): avoid buffering if creating a collection during a connection interruption

- lib/model.js
- lib/query.js
- test/model.middleware.preposttypes.test.js
- test/model.test.js
- test/query.test.js
- types/models.d.ts
- types/query.d.ts
Fix #15190
**Summary**
#15190 points out that `Model.updateMany(obj)` updates all documents using `obj`, which is risky, especially given that our TypeScript types as written imply that `update` parameter is optional, meaning `updateMany(obj)` treats `obj` as `filter` rather than `update`, but the runtime behavior is different.
This PR specifically blocks `Model.updateMany(obj, null)`, while allowing `Model.updateOne(obj)` and `Query.prototype.updateMany(obj, null)`.
**Examples**
> fix(model): disallow `updateMany(update)` and fix TypeScript types re: `updateMany()`

- lib/document.js
- test/document.test.js
Fix #15192
**Summary**
I'm not certain why this `!== void 0` check is there, but that behavior doesn't break any of our tests and goes back to at least 2013: https://github.com/Automattic/mongoose/commit/be7d9784cfe3c902aeca414ef87913eb04ff3b6b. Likely just a bug that was introduced when adding strict mode that was never fixed.
**Examples**
> fix(document): allow setting values to undefined with set(obj) syntax with strict: false

- lib/aggregate.js
- test/aggregate.test.js
**Summary**
#15188 points out a not-helpful error message from the MongoDB server. We can improve this message in the case where the user calls `near()`.
**Examples**
> fix(aggregate): improve error when calling `near()` with invalid coordinates

- scripts/configure-cluster-with-encryption.sh
**Summary**
The encryption tests are failing due to some failures on drivers-evergreen-tools. For now, we can pin the last stable commit.
**Examples**
> fix: pin drivers-evergreen-tools version

- lib/cast/uuid.js
- lib/schema/uuid.js
- test/schema.uuid.test.js
Fix #15202
**Summary**
#15202 points out that `SchemaUUID._cast()` unexpectedly throws a TypeError because `_cast()` uses `this` as if it were a method, not a static function. For consistency, this PR moves that logic to a `castUUID` function, and that `castUUID` function throws a more helpful error if casting fails due to incorrectly formatted string.
**Examples**
> fix(schema): improve reason for UUID cast error, currently a TypeError

- lib/helpers/document/applyDefaults.js
- test/types.map.test.js
Fix #15196
**Summary**
Because arrays implicitly have a default value of `[]`, maps of arrays currently have incorrect change tracking when loaded from the db because `map.$*` is marked as state `default`
**Examples**
> fix: avoid applying defaults on map embedded paths

- lib/cast/bigint.js
- test/bigint.test.js
Fix #15200
**Summary**
MongoDB stores BigInts as Longs under the hood, so you may lose precision if storing a BigInt that's too large in MongoDB. This PR makes Mongoose throw an error in that case, to avoid accidentally overwriting valid data.
Without `useBigInt64`, MongoDB can only store the range of a signed 64 bit integer, which is what this check uses. With `useBigInt64`, you can actually store up to the max _unsigned_ 64 bit integer (18446744073709551615), but that leads to some unexpected quirks with querying. For example, the following `$gt` query doesn't return any docs even though `18446744073709551615n > 9223372036854775807n`.
```javascript
'use strict';
(async function() {
await …
```
> fix(bigint): throw error when casting BigInt that's outside of the bounds of what MongoDB can safely store

- test/schema.number.test.js
- test/types/schema.test.ts
- types/schematypes.d.ts
Fix #15236
**Summary**
Quick TypeScript parameter inconsistency
**Examples**
> types(schema): allow calling Schema.prototype.number() with no message arg

- docs/typescript/subdocuments.md
Fix #15211
**Summary**
Our TypeScript subdocs documentation uses `Types.Subdocument<>` for defining hydrated subdoc type override, which is incorrect, doesn't include any schema properties.
**Examples**
> docs(typescript): recommend using HydratedSingleSubdocument over Types.Subdocument

- CHANGELOG.md
- lib/helpers/query/castUpdate.js
- test/model.test.js
Re: #15218
**Summary**
From #15040, we infer discriminator key when casting the update if we have `TestModel.updateOne({}, { discriminatorKey })` but not `TestModel.updateOne({}, { $set: { discriminatorKey } })`. This PR checks the `$set` case. I ran into this issue while testing potential workarounds for #15218.
**Examples**
> fix: infer discriminator key if set in `$set` with overwriteDiscriminatorKey

- lib/model.js
- test/connection.test.js
Re: #15241
**Summary**
Re: discussiong from #15241, make it so that `autoCreate: false` prevents buffering in `init()`.
**Examples**
> fix: avoid connection buffering on init if autoCreate: false

- test/types/middleware.test.ts
- types/index.d.ts
- types/schematypes.d.ts
- types/validation.d.ts
**Summary**
#15242 pointed out that #14720 actually passes down the raw doc type as `this` for document middleware, not the hydrated doc type. This PR ensures we pass `THydratedDocumentType` down to `SchemaValidator`.
Weirdly enough, adding `THydratedDocumentType` to `.obj` and `.add()` breaks tests. Not sure why, but that doesn't seem to break anything here.
**Examples**
> types(middleware): make this in document middleware the hydrated doc type, not raw doc type

- test/types/schema.test.ts
- types/index.d.ts
Fix #15244
**Summary**
**Examples**
> types(schema): support `options` parameter to `Schema.prototype.discriminator()`

- lib/document.js
- lib/query.js
**Summary**
Avoid some string concatenation and other small issues. No massive improvements, but hard to find any massive improvements other than removing `_executionStack`
**Examples**
>  perf: some more micro optimizations for find() and findOne() re: #14906 

- lib/connection.js
**Summary**
The recent change in #15229 has added a timeout, which can lead to having the node process around for longer than expected (ie until the timeout has fired), which can cause jest to detect open handles.
(I had also encountered this while upgrading typegoose)
Also the check of `unref` existing is made for alternative engines like deno and bun, where i had previously encountered that `unref` may not always be implemented.
fixes #15241
> fix(connection): unref the "_waitForConnect"

- lib/connection.js
- lib/model.js
Fix #15241
**Summary**
Make `Model.init()` skip buffering timeouts introduced in #15229
Based on discussion from #15241, I think this is a reasonable approach which gives us the benefits of #15229 without the implicit dangling handles. The following Jest test won't complain about open handles:
```js
// Define a User schema and model
name: String,
email: String,
age: Number
});
const User = mongoose.model('User', userSchema);
describe('Database connection', () => {
it('test', function () {
});
});
```
However, the following script will still error out with buffering timeout, as opposed to silently exiting with no error.
```js
'use strict';
(async function() {
await …
```
> fix(model): avoid adding timeout on `Model.init()` buffering to avoid unintentional dangling open handles

- lib/schema.js
- test/schema.test.js
Fix #15253
**Summary**
Currently, overwriting an existing recursive path using `Schema.prototype.path()` leads to an exponential performance blowup because we're adding a separate recursive path to `childSchemas` on every `path()` call. For example, in the test case added, the document has 1092 subdocuments, but with 2 duplicate `childSchemas` entry Mongoose thinks there's over 56k subdocuments. With 3, Mongoose thinks there's about 560k subdocuments. I haven't been able to figure out a more complete explanation of the exact mathematical model of this growth, but suffice to say cleaning up duplicate childSchemas fixes the issue.
**Examples**
> perf(schema): clear childSchemas when overwriting existing path to avoid performance degradations

- lib/document.js
- test/document.test.js
Fix #15255
**Summary**
Right now we call `$__undoReset()` for every subdoc multiple times, because each `$__undoReset()` call recursively calls `$__undoReset()` on all of its subdocuments. So skip the recursive call for subdocuments.
**Examples**
> perf(document): only call `undoReset()` 1x/document

- lib/document.js
- test/document.test.js
- types/index.d.ts
Fix #15218
**Summary**
`toObject()` and `toJSON()` currently return an object with all fields from the document in the database, which may include fields that aren't in the schema. To work around that, we added a `schemaFieldsOnly` option to `toObject()` and `toJSON()`, which will loop over schema paths when getting values vs just cloning the entirety of `_doc`.
**Examples**
> feat(document): add schemaFieldsOnly option to toObject() and toJSON()

- types/index.d.ts
- types/inferschematype.d.ts
Fix #15121
**Summary**
#15121  points out an unpleasant edge case where our lean type inference breaks completely if `@types/node` isn't installed, because `Buffer === any`. Not something we can write tests for unfortunately. But this PR should make Mongoose more resilient to that case, I replaced all `extends Buffer` checks and we don't have any `: Buffer` or `?: Buffer` params or properties.
**Examples**
> types: make type inference logic resilient to no Buffer type due to missing `@types/node`

- lib/drivers/node-mongodb-native/collection.js
- lib/helpers/clone.js
Re: #15263
**Summary**
Right now `trustedSymbol` shows up in debug output, which can be extra confusing when debugging populate issues because populate adds trusted symbol by default:
```
Mongoose: groups.find({ key: { '$in': [ ObjectId("67b887650fca90b537952220"), ObjectId("67b887650fca90b537952224") ], [Symbol(mongoose#trustedSymbol)]: true }}, { skip: undefined, limit: undefined, perDocumentLimit: undefined })
```
This PR removes `trustedSymbol` from debug output.
**Examples**
> fix(debug): avoid printing trusted symbol in debug output

- lib/connection.js
- lib/drivers/browser/index.js
- lib/drivers/node-mongodb-native/bulkWriteResult.js
- lib/drivers/node-mongodb-native/index.js
- lib/helpers/getDefaultBulkwriteResult.js
- lib/helpers/model/decorateBulkWriteResult.js
- lib/model.js
- test/model.test.js
- types/models.d.ts
**Summary**
MongoDB's `BulkWriteResult` is a class, not just an interface, so we need to ensure we return an instance of that class in the "no valid ops" case.
**Examples**
> fix(model+connection): return MongoDB BulkWriteResult instance even if no valid ops

- lib/model.js
- test/model.test.js
- types/models.d.ts
Fix #15265
**Summary**
When we return `mongoose.results` property from `bulkWrite()`, the results property doesn't currently include any MongoDB write errors that occurred. That makes it a multi-step process to determine whether a given bulk write operation succeeded or failed.
This is more consistent with how `insertMany()` handles errors: `insertMany()` already adds write errors to `results`. However, `insertMany()` has some logic where it modifies the WriteError's index, which we should consider removing because that makes the result not an instance of MongoDB's `WriteError` class.
**Examples**
> feat(model): make bulkWrite `results` include MongoDB bulk write errors as well as validation errors

- lib/browser.js
**Summary**
This PR exposes `SchemaTypeOptions` on the browser build, like it is on the non-browser build.
As a workaround, it is already accessible via `mongoose.Schema.Types.Mixed.prototype.OptionsConstructor` (or similar) without this PR.
Btw, is the browser build still something that is supported?
> fix(browser): expose "SchemaTypeOptions"

- lib/browser.js
- lib/browserDocument.js
- lib/document.js
- lib/error/validation.js
- lib/helpers/model/applyHooks.js
- lib/query.js
- lib/schema/documentArray.js
- lib/schemaType.js
- test/document.test.js
- test/query.test.js
- test/types.document.test.js
**Summary**
Partially a fix for #14906, but also includes some related followup work because, in addition to removing `_executionStack`, we should do the same for parallel validation error. However, I took the time to refactor `validate()` to be an async function, to take advantage of async stack traces. With this PR, you get async stack traces when calling document.validate():
```javascript
Error.stackTraceLimit = 20;
mongoose.connect("mongodb://localhost:27017/mongoose_test");
name: { type: String, required: true, validate: v => v.length > 3 },
age: Number,
});
userSchema.pre('validate', function() {
if (this.name === 'secret') {
throw new Error('name cannot be secret');
}
});
const User = …
```
> BREAKING CHANGE: remove _executionStack, make validate() async function and call Kareem hooks directly vs through wrappers

- lib/helpers/populate/getSchemaTypes.js
- test/document.populate.test.js
Fix #9359
**Summary**
`doc.$__.populated[fullPath]` can be nullish in this context if `fullPath` includes `$*`, that is, if deep populating a path underneath a map. `topLevelDoc.$populated(fullPath, true)` is equivalent (the `true` makes $populated() return the full populated state rather than just the populated values) accounts for this case.
**Examples**
> fix(populate): correctly get schematypes when deep populating under a map

- .eslintrc.js
- .gitignore
- docs/field-level-encryption.md
- lib/schema.js
- lib/schema/array.js
- lib/schema/bigint.js
- lib/schema/boolean.js
- lib/schema/buffer.js
- lib/schema/date.js
- lib/schema/decimal128.js
- lib/schema/double.js
- lib/schema/int32.js
- lib/schema/objectId.js
- lib/schema/string.js
- lib/schemaType.js
- test/encryptedSchema.test.js
- test/schema.test.js
- test/types/schema.test.ts
- test/types/schemaTypeOptions.test.ts
- types/schemaoptions.d.ts
- types/schematypes.d.ts
**Summary**
This PR is an exact copy of https://github.com/mongodb-js/mongoose/pull/5, opened here for ease of review.  @vkarpov15 
This PR adds support for declaring encrypted schemas, as the first step in adding first class support for CSFLE to mongoose.  Functionally:
1. A new schema option, `encryptionType`, has been added.  This is required for schemas that are declaring encrypted fields, and it determines whether the schema will be configured for 'csfle' or 'qe'.
2. Keys in schemas can now be configured with an additional `encrypt` option.  This option contains metadata for libmongocrypt to encrypt the field (which will be automatically included in a schemaMap or encryptedFieldsMap).  The contents of this document are exactly the same as the fields used to configure a field for …
> feat(NODE-6506): Add support for encrypted schemas

- lib/document.js
- test/document.test.js
Fix #15308
**Summary**
When we refactored a `forEach()` into a `for` in `init()`, we left a `return` that should've become a `continue`
**Examples**
> fix(document): avoid stripping out fields in discriminator schema after select: false field

- lib/model.js
Re: #15314
**Summary**
Potential edge case that can lead `bulkSave()` to return `null`. Not likely because AFAIK `MongoBulkWriteError` should always have `writeErrors` property, but I don't think the `writeErrors` check adds anything here.
**Examples**
> fix(model): avoid returning `null` from bulkSave() if error doesn't have writeErrors property

- lib/mongoose.js
- test/driver.test.js
Fix #15321
**Summary**
In addition to drivers exporting `Connection`, `Collection`, and `plugins`, this PR allows drivers to export `Types`, and Mongoose will assign driver types automatically to `mongoose.Schema.Types` for use in schemas.
**Examples**
> feat: support custom types exported from driver

- test/types/schema.test.ts
- types/schematypes.d.ts
**Summary**
See test case: if defining `new Schema<DocType>`, TypeScript disallows `default: () => void 0`, which is a problem because we recommend using `default: () => void 0` to override Mongoose setting array paths to empty arrays by default.
**Examples**
> types: allow default function returning undefined with DocType override

- lib/helpers/populate/assignRawDocsToIdStructure.js
- test/model.populate.test.js
Fix #15315
**Summary**
A bit of a hack to unblock #15315 and allow virtual populate on array of UUIDs. `String()` on a `Binary` value returns a unicode string that isn't properly indexable when doing `doc = resultDocs[sid];`.
Future improvement: make Mongoose UUID types use BSON UUID class
**Examples**
> fix(populate): handle virtual populate on array of UUIDs

- docs/migrating_to_9.md
- lib/aggregate.js
- lib/browserDocument.js
- lib/cursor/aggregationCursor.js
- lib/cursor/queryCursor.js
- lib/document.js
- lib/helpers/model/applyHooks.js
- lib/helpers/model/applyStaticHooks.js
- lib/model.js
- lib/plugins/saveSubdocs.js
- lib/plugins/sharding.js
- lib/query.js
- package.json
- test/document.test.js
- test/model.middleware.test.js
- test/query.cursor.test.js
**Summary**
Re: https://github.com/mongoosejs/kareem/pull/39. With this change, we get async stack traces for validation errors in 9.0 branch :+1:
```javascript
Error.stackTraceLimit = 20;
mongoose.connect("mongodb://localhost:27017/mongoose_test");
name: { type: String, required: true, validate: v => v.length > 3 },
age: Number,
});
userSchema.pre('validate', function() {
if (this.name === 'secret') {
throw new Error('name cannot be secret');
}
});
const User = mongoose.model("User", userSchema);
async function runDemo() {
const doc = new User({ name: 'A' });
// await doc.validate().catch(err => console.log('Validate', err));
await doc.save().catch(err => console.log('Save', err));
}
runDemo().catch(err => …
```
> BREAKING CHANGE: use kareem@v3 promise-based execPre() for document hooks

- lib/document.js
- test/document.test.js
**Summary**
#15335 points out that we double-run validation on document array elements if the document array is underneath a subdocument. This is because of some logic we added to run validation on intermediate subdocuments in cases where a nested subdocument is modified but the top-level subdocument is not.
This PR ensures that we only consider top-level subdocuments, not nested subdocuments, when adding documents to `pathsToValidate`. 
**Examples**
> Avoid double calling validators on paths in document arrays underneath subdocuments

- lib/document.js
- lib/helpers/clone.js
- lib/options/schemaSubdocumentOptions.js
- lib/schema/subdocument.js
- lib/types/subdocument.js
- test/types.subdocument.test.js
- types/schematypes.d.ts
Fix #15313
**Summary**
In #11247, we made it so that Mongoose would minimize empty subdocuments by default. However, there isn't a great way to configure that behavior right now: #14151 disabled that behavior for required subdocs, but you might not want to make the field required.
This PR lets you set a `minimize` option on the schematype itself, like `subdoc: { type: Schema, minimize: false }` to disable minimize on the full subdocument. Setting `minimize: false` on the schematype will also override the child schema's `minimize`.
**Examples**
> feat(subdocument): support schematype-level minimize option to disable minimizing empty subdocuments

- lib/document.js
- lib/query.js
- lib/validOptions.js
- test/index.test.js
- types/mongooseoptions.d.ts
Re: #15194
**Summary**
Pulling in some work from 9.0 to hopefully address #15194. Given that users have bisected the issue to Mongoose 8.8.2, the most likely culprit is #15039. We plan on removing `_executionStack` in 9.0 because we don't think `_executionStack` provides enough value now that callback support is gone. This PR adds a `skipOriginalStackTraces` option that opts into skipping `_executionStack`, which should hopefully address the performance issues from #15194.
**Examples**
> feat: add skipOriginalStackTraces option to avoid stack trace performance overhead

- lib/query.js
- test/query.test.js
**Summary**
Even though [query.d.ts says otherwise](https://github.com/Automattic/mongoose/blob/5325a8544bce24a6994576e7b6d5ee4500469652/types/query.d.ts#L474-L517), `Query` does NOT in fact have the following methods:
- `findById`
- `findByIdAndUpdate`
- `findByIdAndDelete`
You can see as much if you try to call them. Here's a reproducible example:
```ts
type Person = {
_id: mongoose.Types.ObjectId;
name: string;
email: string;
archived: boolean;
createdAt: number;
updatedAt: number;
};
const personSchema = new mongoose.Schema<Person>({
name: { type: String, required: true },
email: { type: String, required: true, index: true },
archived: { type: Boolean, default: false },
createdAt: { type: Number },
updatedAt: { type: Number },
});
const Person = …
```
> Implement Query findById methods

- test/types/document.test.ts
- types/document.d.ts
- types/index.d.ts
- types/models.d.ts
Fix #15316
**Summary**
In TypeScript `toJSON({ virtuals: true })` and `toObject({ virtuals: true })` don't include virtuals even if virtuals are easy to infer.
To support this, I added a separate `TVirtuals` parameter to `HydratedDocument` in addition to `TOverrides`. Unfortunately this is somewhat redundant because virtuals are passed in to `HydratedDocument` twice. We can consider changing that for 9.0 so `TOverrides` becomes `TMethods`.
I'm putting this in 8.14 release because it seems to qualify as a new feature.
**Examples**
> types: include virtuals in toJSON and toObject output if `virtuals: true` set

- docs/migrating_to_7.md
**Summary**
I'm working on migrating from Mongoose v6 to Mongoose v7. Part of this includes dropping all callbacks in favor of Promises.
I noticed that `Model#count` and `Query#count` is not in the list though, which according to the types, had a callback param in v6, which was removed in v7. This should be in the list of functions as well that the `callback` param was removed from too.
_(Also fixes a petty typo as well, since I was modifying this file anyway.)_
**Examples**
N/A
> docs: adds Model#count to list of fns callback removed from

- lib/query.js
**Summary**
The returned object of `deleteOne` & `deleteMany` comes directly from mongodb driver. 
The API definition was not updated.
> docs: update deleteOne & deleteMany API def

- docs/migrating_to_7.md
**Summary**
The migration guide from Mongoose v6 to Mongoose v7 does not clarify that it uses MongoDB v5 instead of MongoDB v4.
Looking at your migration guides historically, it looks like an upgrade in the MongoDB Node Driver is expected, so this tripped me up in this instance. To ensure the migration guide relays an accurate scope of the work to migrate, could it include clarification on this?
This is a breaking change as we can set the MongoDB client using `Connection#setClient`.
Reference: https://mongoosejs.com/docs/7.x/docs/api/connection.html#Connection.prototype.setClient()
If the versions don't align, we can get:
```
Error {
error: [
'MongooseError: Must call `setClient()` with an instance of MongoClient',
'    at NativeConnection.setClient …
```
> docs: add version requirements to v7 migration docs

- types/inferrawdoctype.d.ts
**Summary**
Correctly recurse in InferRawDocType. When inferring the types of object arrays and objects, it should call itself, not ObtainDocumentType. The latter has been repurposed to obtain the type of full documents, not lean documents, and will infer DocumentArray instead of raw arrays.
**Examples**
Fixes #14954
> Correctly recurse in InferRawDocType

- benchmarks/findOneWithCast.js
- lib/utils.js
- test/model.query.casting.test.js
Fix #15364
**Summary**
#15364 points out that Mongoose casting mistakenly mutates objects passed in to `$elemMatch`. The core of this issue is that we only shallow clone using `{ ... }` in `utils.merge()`, which makes Mongoose casting mutate query filters that are at least 2 levels deep.
However, we unfortunately can't use `clone()` because `clone()` also clones Dates and ObjectIds, and we have tests which assert that Dates and ObjectIds are reference equal after being passed in to `findOneAndUpdate()`.
I wrote a quick benchmark which shows that the performance impact is negligible.
**Examples**
> fix: clone POJOs and arrays when casting query filter to avoid mutating objects

- test/connection.test.js
- test/types/connection.test.ts
- types/connection.d.ts
Fix #15359
Re: #15058
**Summary**
Missed a spot when adding `Connection.prototype.bulkWrite()` support in #15058: need TypeScript types as well.
**Examples**
> types(connection): add Connection.prototype.bulkWrite() to types

- lib/schema/map.js
- lib/types/map.js
- test/types.map.test.js
Fix #15350
**Summary**
In some perf improvements for #13191 (see https://github.com/Automattic/mongoose/commit/7bec5064d0a39032192be93df53e832f948207d8) we missed a spot where we need to calculate the full path for maps of maps and maps of primitive arrays. Otherwise, Mongoose will track changes to the map pseudo-path `myMap.$*`.
**Examples**
> fix: correct change tracking with maps of arrays of primitives and maps of maps

- docs/layout.pug
- docs/typescript/queries.md
Fix #15311
**Summary**
Add some recommendations on how to use `lean()` and `transform()` together based on discussion from #15311. Also good to have a "Queries" page for more info on how to use queries in TypeScript.
**Examples**
> docs: add TypeScript Query guide with info on `lean()` + `transform()`

- docs/migrating_to_9.md
- lib/cast/uuid.js
- lib/schema/uuid.js
- test/model.populate.test.js
- test/schema.uuid.test.js
- test/types/schema.test.ts
- types/index.d.ts
- types/inferschematype.d.ts
**Summary**
Currently, `type: 'UUID'` makes Mongoose internally store Mongoose Buffers, which get converted to strings via a built-in getter. This is inconsistent for a few reasons:
1. We have a separate `mongoose.Types.UUID` type, but `mongoose.Schema.Types.UUID` paths don't cast into `mongoose.Types.UUID` instances
2. Because UUID paths are stored as buffers and converted to string via getters, `lean()` means UUIDs are returned as instances of `mongodb.Binary` by default (unless mongoose-lean-getters plugin is enabled), so you end up having to handle 3 different types when working with UUIDs (Binary if lean, Buffer if toObject() with getters false or bypassing getters, string otherwise). Also adds some confusion for TypeScript. 
3. TypeScript types convert 'UUID' -> 'Buffer', which …
> BREAKING CHANGE: make UUID schema type return bson UUIDs

- package.json
**Summary**
This PR changes the git kareem dependency to be properly [marked `git`](https://docs.npmjs.com/cli/v11/configuring-npm/package-json#git-urls-as-dependencies) which is necessary for example yarn v1.
Also changes from a SSH link to HTTPS so developers who dont have SSH setup can still install and run mongoose.
> deps(kareem): change dependency notation to be HTTPS and properly "git"

- scripts/generateSearch.js
- scripts/website.js
**Summary**
This PR changes:
- `website.js` to print less per-line by changing the timestamp format and fixing double spaces
- `generateSearch.js` to be able be called from other scripts and not always run as a side-effect, which also fixes potentially exiting the process early due to `process.exit(-1 | 0)`
- `generateSearch.js` [to spam](https://github.com/Automattic/mongoose/actions/runs/14714708408/job/41295315309?pr=15377) less (only print on first, last and after 2 seconds)
- `generateSearch.js` to be able to save in parallel
Example lines of what is output now:
```txt
Processing ~98 files
Delete index.html
Delete docs/api/virtualtype.html
2025-04-29T09:08:01.666Z : rendered /mnt/ssd/projects/nodejs/mongoose/docs/tutorials/custom-casting.html
2025-04-29T09:08:01.669Z : rendered …
```
> Reduce print length in `website.js` and dont exit early in `generateSearch`

- .github/workflows/test.yml
- test/document.test.js
- test/query.test.js
Add Node 24 to version matrix, as it is the "current" and upcoming LTS version.
Required small change to two test cases:
The prevValue tests used "nulls" in expected values. This comparison fails in Node 24, as the actual value is "undefined".
However, the original value seems to be "undefined" in previous Node versions too. Therefore it does not seem like a change in behaviour, but only a change in how strict the assert is. Changing the expected value to "undefined" works in both Node 24 and previous Node versions.
> C: add Node 24

- docs/field-level-encryption.md
- test/encryption/encryption.test.js
- types/models.d.ts
**Summary**
This PR address a few more comments on the CSFLE feature branch: https://github.com/Automattic/mongoose/pull/15390
Additionally, I did a final review of the documentation and made a few small changes.  Additionally, I added Typescript support for the new `clientEncryption()` method on Mongoose's Model class.
**Examples**
> chore: comments on CSFLE feature branch PR#2

- lib/schema.js
- types/schemaoptions.d.ts
Re: #10591
**Summary**
Comments in #10591 mentioned that our docs and typescript types don't mention the `string[]` or `{ exclude: string[] }` syntaxes for `optimisticConcurrency`.
**Examples**
> docs+types(schema): add alternative optimisticConcurrency syntaxes to docs + types

- test/types/schema.test.ts
- types/index.d.ts
Fix #15412
Re: #15333
**Summary**
#15333 unintentionally removed support for post('init') hooks from TypeScript. Add that back.
**Examples**
> types(schema): allow post('init')

- types/types.d.ts
My main issue with this was that 'undefined' was a valid argument. Now it matches <https://mongoosejs.com/docs/api/documentarray.html#MongooseDocumentArray.prototype.id()>.
> types: fix signature of DocumentArray.id

- lib/error/serverSelection.js
Fix #15416
**Summary**
A reasonable request: propagate the original server selection error's `reason` property. [`cause` is JavaScript's official property for storing the original cause of an error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause).
**Examples**
> feat(error): set `cause` to MongoDB error `reason` on ServerSelection errors

- lib/model.js
- test/model.test.js
Fix #15410
**Summary**
@AbdelrahmanHafez please take a look at this one
The issue in #15410 is similar to the issue in #13907: `bulkSave()` currently relies on `bulkWrite()`'s `castBulkWrite()` logic to handle casting, which is inconsistent with `save()`. Further, it causes problems with discriminators (like in #13907  for top-level discriminators and #15410 for embedded discriminators) because you need to set the discriminator key on discriminator paths to tell `castBulkWrite()` which discriminator schema to use when casting.
We worked around the discriminator issue for top-level discriminators in #13907, but for embedded discriminators it is infeasible - needing to find every embedded discriminator in the doc will be complex and error prone. In the interest of simplifying things, we can …
> fix(model): make bulkSave() rely on document.validate() to validate docs and skip bulkWrite casting

- lib/helpers/query/cast$expr.js
Support queries of the form `{ $expr: true }` or `{ $expr: false }`, as boolean literals are valid expressions.
**Summary**
When trying to execute a query containing a `{ $expr: true }` or `{ $expr: false }` clause, I get an error `` `$expr` must be an object ``. Since `true` is a valid expression in the mongo query language, this seems like a mistake.
**Examples**
The following query will now work correctly:
```
model.findOne({ $and: [{ foo: bar }, { $expr: true }] })
```
> fix: Support $expr clauses with a boolean literal as an expression

- test/types/models.test.ts
- test/types/queries.test.ts
- types/index.d.ts
- types/query.d.ts
- types/types.d.ts
- types/utility.d.ts
Re: #15327
**Summary**
@pshaddel please take a look as well.
Simplified alternative to #15327 that seems to compile with Typegoose. The one major tradeoff is that it only considers 1 level deep nested paths, as opposed to 3 in #15327. However, that should be sufficient for most use cases. There's also the added benefit that this PR reuses the existing `With1LevelDeepNestedPaths` type, with some fixes to handle arrays, which should reduce risk.
**Examples**
> types: stricter projection typing with 1-level deep nesting

- test/types/queries.test.ts
- types/index.d.ts
**Summary**
Quick fix for #15418: looks like we need to explicitly `Omit<T, '_id'>` to avoid TypeScript getting tripped up by `_id` in `InclusionProjection` and `ExclusionProjection`.
**Examples**
> types: correct handling of `_id` in ProjectionType

- types/pipelinestage.d.ts
**Summary**
The `exact` field was missing from the interface, and the `numCandidates` field was typed as required. Neither of these match [the docs](https://www.mongodb.com/docs/atlas/atlas-vector-search/vector-search-stage/).
**Examples**
Previously, any use of the interface that directly used an object literal with `exact: true`, or any version that omitted `numCandidates` would fail.
> types: fix definition of VectorSearch.$vectorSearch

- docs/migrating_to_7.md
**Summary**
_(This PR is very similar to my previous PR regarding `Model#count`, so I've largely copy and pasted the description over._)
I'm working on migrating from Mongoose v6 to Mongoose v7. Part of this includes dropping all callbacks in favor of Promises.
I noticed that `Document#save` is not in the list though, which according to the types, had a callback param in v6, which was removed in v7. This should be in the list of functions as well that the `callback` param was removed from too.
**Examples**
N/A
**Notes for Reviewers**
The failed test case seems to be unrelated to this PR.
> docs: add Document#save to list of function with callbacks removed

- lib/cursor/queryCursor.js
- lib/query.js
- test/query.test.js
Fix mongoosejs/mongoose-lean-getters#44
**Summary**
https://github.com/mongoosejs/mongoose-lean-getters/issues/44#issuecomment-2874010333 pointed out an issue which is caused by how we handle async iterators in queryCursor.js. Query cursors use a `_transformForAsyncIterator` transform which converts `doc` to `{ value: doc, done: false }` or `{ done: true }` depending on whether the cursor returned null. Because transforms pass the transformed value to the next transform, `_transformForAsyncIterator` breaks user-specified transforms if it gets added first.
This PR makes it so that user-specified transforms are applied before `_transformForAsyncIterator`, which means user-specified transforms won't see the `{ value: doc, done: false }` doc.
However, I want to do some further work to check …
> fix(queryCursor): add _transformForAsyncIterator transform after user-defined transforms

- .github/workflows/benchmark.yml
- .github/workflows/documentation.yml
- .github/workflows/test.yml
- docs/compatibility.md
Fix #15427
**Summary**
**Examples**
> docs(compatibility): add note that Mongoose ^6.5 works with MongoDB server 7.x

- lib/aggregate.js
- lib/query.js
**Summary**
Good point by @hasezoey in #15430: `if (Symbol.asyncIterator != null)` checks are no longer necessary because `Symbol.asyncIterator` was introduced in node 10.x, and Mongoose 9 requires Node `>= 18` currently (may change before we formally release Mongoose 9).
**Examples**
> refactor: remove unnecessary async iterator checks

- test/types/models.test.ts
- types/models.d.ts
Fix #15437
**Summary**
**Examples**
> types(model): use ProjectionType for Model.hydrate()

- lib/document.js
- test/types.map.test.js
This PR fixes #15447 
The issue was that mongoose was double validating nested maps of subdocuments, once as the correct path, but then trying to validate `.$*` which represents the map schema rather than the actual value of a path.
The bug was in the `_getPathsToValidate` function in `lib/document.js`. We were incorrectly treating map schema paths (paths ending with `.$*`) as actual document paths for validation. These `$*` paths represent the schema for Maps but are not actual document paths that should be validated.
This PR ignores the `.$*` "path" when getting paths to validate.
> fix: fix validation for deeply nested maps of subdocuments

- test/types.map.test.js
Add test case re #15469 to assert that validation still throws an error when the path fails the validation.
> test: assert failing validation still throws an error in nested maps

- .github/workflows/test.yml
- lib/document.js
- lib/types/array/index.js
- lib/types/documentArray/index.js
- package.json
- test/multiple-require-instance.test.js
**Summary**
#15466 points out that Mongoose throws an unreadable error if creating a document array that was defined with `Schema()` from a different Mongoose instance.
I added tests to cover this case automatically - historically we haven't tested the multiple `require()` instance setup, but we should since it is so common.
**Examples**
> fix(DocumentArray): correctly set parent if instantiated with schema from another Mongoose instance

- lib/helpers/populate/assignVals.js
- lib/helpers/populate/getVirtual.js
- lib/schema.js
- test/helpers/populate.getVirtual.test.js
- test/model.populate.test.js
**Summary**
There are a few issues that pop up when you try to populate a deeply nested virtual like `rubric.parameters.$*.evaluationPrompt`: getting the virtual, setting with `.$*`, etc.
**Examples**
> fix(populate): handle populating deeply nested map paths 

- lib/document.js
- lib/schema.js
- test/document.test.js
- test/schema.path.test.js
- test/schema.pathType.test.js
Fix #15461
**Summary**
Primary issue comes down to:
1. Need to pass the path being set into `applySetters()` because that is the most reliable way to get the actual path being set, with no `.$*`.
2. `Schema.prototype.path()` and `Schema.prototype.pathType()` not being able to get paths underneath maps correctly.
Fixed both of those, along with adding specialized testing for `path()` and `pathType()`.
**Examples**
> fix(document+schema): improve handling for setting paths underneath maps, including maps of maps

- lib/model.js
- test/model.middleware.test.js
Fix #15480
**Summary**
Quick fix - apparently need `callback(err, this)`, `callback(err)` means a `null` result gets passed to error handling middleware.
**Examples**
> fix(model): make sure post save error handler gets doc as param on VersionError

- .github/workflows/encryption-tests.yml
**Summary**
Basically just the tile, only run the `encryption-tests` when necessary, similar to how `test.yml` only gets run at specific changes.
For example the encryption tests dont need to run if the PR only modifies documentation, like #15487.
Btw, i also noticed that `encryption-tests.yml` has more permissions than it actually seems to need, are they really required?
https://github.com/Automattic/mongoose/blob/62d13499dcc6e2e805b04e0759a4fb423a07a4da/.github/workflows/encryption-tests.yml#L10-L13
> chore(workflows/encryption-tests): only run if tests related files changed

- docs/index.md
The ```--save``` flag is no longer needed for ```npm install``` as of npm v5, because saving to ```package.json``` is the default behavior. This PR updates the Getting Started guide to reflect that.
> Remove unnecessary --save flag from npm install instruction

- lib/model.js
- test/model.test.js
Fix #15495
**Summary**
As implemented, `bulkWrite()` will filter out all ops if `ordered: false` and `_skipBulkWriteCasting: true`. This PR fixes that, and also makes `validOps` vs `validOpsIndexes` more consistent
**Examples**
> fix(model): avoid stripping out operations in bulkWrite() when ordered: false and _skipCastBulkWrite: true

- lib/cursor/queryCursor.js
- test/model.populate.test.js
Fix #15494
**Summary**
Query hydrates document first then populates, but query cursor populates then hydrates. That leads to `$__.parent` not getting set in `assignVals()`.
**Examples**
> fix(cursor): populate after hydrating in queryCursor so populated docs get parent()

- test/types/schema.test.ts
- types/index.d.ts
Fix #15516
**Summary**
Quick fix: should use user-specified THydratedDocumentType
**Examples**
> types(schema): use user-provided THydratedDocumentType as context for virtual get() and set()

- lib/document.js
- test/types.map.test.js
Fix #15519
**Summary**
If setting a map to null/undefined, need to clean modified subpaths. Otherwise we have dangling modified paths which cause issues like #15519.
**Examples**
> fix(document): clean modified subpaths if unsetting map

- types/index.d.ts
**Summary**
Add `options` property to schema types. I couldn't add the full set of generics because that caused a lot of hard-to-debug errors, but this should hopefully be enough to help plugin authors be able to access schema options.
**Examples**
> types: add options property to schemas

- test/types/queries.test.ts
- types/query.d.ts
Fixes #15526 
**Summary**
Support readonly array in `Query.select` as it allows passing in const arrays as well as mutable arrays.
> types: support readonly array in query.select

- test/types/schema.test.ts
- types/inferschematype.d.ts
**Summary**
We are using InferSchemaType to derive types from the models from the schema definition.
For fields with Typescript enum, the types are currently `string` which creates unnecessary casting.
I had to use `expectAssignable` for the required case and it is not completely clear why, but it will solve my problem which is around assignment.
> types(inferschematype):  Infer Typescript string enums

- test/types/schemaTypeOptions.test.ts
- types/schematypes.d.ts
**Summary**
Some followup work for #15524: `defaultOptions` is actually a static property on SchemaTypes, not an instance property. Also, add `schemaOptions`. 
**Examples**
> types(schematype): make defaultOptions static and add schemaOptions to DocumentArray

- lib/document.js
- test/types.map.test.js
**Summary**
If you create a map path using `type: { Map, of: String }`, you can store `null` values in that map. However, currently, if you try to set `required: true` on a map value path you get a validation error on `map.$*` whenever you try to validate a document.
**Examples**
> fix(map): avoid throwing required error if saving map of primitives with required: true

- types/connection.d.ts
**Summary**
Quick little issue I noticed - connections have a `base` property at runtime that points back to the Mongoose instance, but TypeScript types don't have that
**Examples**
> types(connection): add `base` to connection type

- lib/mongoose.js
- test/types/base.test.ts
- types/collection.d.ts
- types/connection.d.ts
**Summary**
Right now the Mongoose global doesn't export the base `Connection` and `Collection` classes, which makes things tricky for drivers looking to integrate against the base Connection and Collection classes without the node-mongodb-native driver. That's because `import { Connection } from 'mongoose';` triggers `lib/index.js`'s `setDriver()` call, and `Connection` is just a getter around the current driver's `Connection`, so there's no way to get the base Connection class without importing `mongoose/lib/connection`.
**Examples**
> feat(mongoose): export base Connection and Collection classes

- test/types/queries.test.ts
- types/index.d.ts
Fix #15557
Re: #13840
Re: #15327
**Summary**
#13840 made it so that Mongoose requires `as const` for projections defined using `const projection = { /* fields here */ }`. That can cause some problems like in #15557. I'm not 100% convinced we want to make the change in this PR, I'd like to hear @hasezoey and @AbdelrahmanHafez 's thoughts
**Examples**
> types: allow passing in projections without `as const`

- lib/model.js
Fix #15551
**Summary**
The `findById()` documentation indicates that `findOne({ _id: undefined })` will return an arbitrary document, which is no longer accurate. I also removed the `undefined` check in `findById()`, which is no longer necessary because `findOne({ _id: undefined })` no longer returns an arbitrary document.
**Examples**
> fix(model): remove unnecessary conversion of undefined -> null in findById

- lib/helpers/model/discriminator.js
- test/model.discriminator.test.js
Fix #15556
**Summary**
We allow discriminator schemas to set `methods` and `virtuals` options with #12246, I think `statics` should also be allowed.
**Examples**
> fix(model): allow setting `statics` option on discriminator schema

- lib/model.js
Fix #15565
**Summary**
Sloppy mistake from https://github.com/Automattic/mongoose/commit/dd41187a3afd81b13d05fa465afe6a9632365576: I missed a spot when renaming ensureSearchIndexes -> createSearchIndexes internally.
**Examples**
> fix(model): call correct function in autoSearchIndex

- lib/schema/string.js
- types/schematypes.d.ts
**Summary**
Support camelcase names in SchemaTypeOptions, and also make the docs consistently use the camelcase names in examples.
**Examples**
> types: support maxLength and minLength in SchemaTypeOptions

- lib/model.js
- test/model.validate.test.js
`Model.validate()` hangs indefinitely when all specified validation paths fail type casting. The Promise never resolves or rejects, causing timeouts.
1. `castObject()` throws a ValidationError and removes failed paths from the validation queue
2. The main validation loop becomes empty (`remaining = 0`)
3. `_checkDone()` is never called because the loop doesn't execute
4. The Promise hangs indefinitely
Refactored the Promise handling logic to properly handle the case when all validation paths are removed due to casting errors. The key changes:
Early settlement check: Added `if (remaining === 0) { return settle(); }` immediately after creating the Promise to handle the case where no paths need validation
Extracted settlement logic: Created a `settle()` helper function to centralize Promise …
> Bugfix: `Model.validate()` hangs when all paths fail casting

- docs/source/api.js
- lib/schema/array.js
- lib/schema/bigint.js
- lib/schema/boolean.js
- lib/schema/buffer.js
- lib/schema/date.js
- lib/schema/decimal128.js
- lib/schema/documentArray.js
- lib/schema/double.js
- lib/schema/int32.js
- lib/schema/number.js
- lib/schema/objectId.js
- lib/schema/string.js
- lib/schema/subdocument.js
- lib/schema/uuid.js
- lib/schemaType.js
**Summary**
This PR fixes some issues i came across in the docs once again:
- functions `cast` were labeled as `get`
- property `$conditionalHandlers` did not have the proper jsdoc tags, so at parse time it did not know where it belonged to (resulting in `function Object() { [native code] }.prototype.$conditionalHandlers`)
Additionally, i added `Types.UUID` and `Schema.Types.UUID` to be listed in the sidebar.
> Fix docs jsdoc tags and add UUID to be listed.

- test/document.test.js
- test/types/document.test.ts
- test/types/schema.test.ts
- types/document.d.ts
- types/index.d.ts
Fix #15578
**Summary**
`toJSON()` converts ObjectIds to strings using `ObjectIdToString` helper, but `toObject()` currently does not.
**Examples**
> types(document): better support for `flattenObjectIds` and `versionKey` options for toObject() and toJSON()

- test/types/discriminator.test.ts
- types/models.d.ts
Fix #15600
**Summary**
Finally found a use for the `TSchema` parameter to `Model<>`! When using auto inferred schemas, we can infer the base model's `TStaticMethods` and attach it to the discriminator model. All without changing `Model` generics.
**Examples**
> types(model): copy base model statics onto discriminator model

- types/index.d.ts
- types/inferrawdoctype.d.ts
- types/inferschematype.d.ts
**Summary**
Various performance improvements related to #15588 to make it so that top-line instantiations and memory usage for #15588 are roughly equivalent to master.
1. Consolidate array and readonly array paths
2. Minimize use of `IfEquals`: `IfEquals<>` is only necessary for `String` because of TypeScript's implicit boxing/unboxing (see below screenshot), there's no risk of TypeScript inferring container types for ObjectIds or Decimal128. There is a chance with `Boolean` and `Number`, but only if someone does `type: true` or `type: 42`, I don't think it is worth checking for that case though.
3. Consolidate `UnionToType`
@ssalbdivad can you also please take a look?
**Examples**
> types: improve performance on inferSchemaType re: #15588

- types/schematypes.d.ts
**Summary**
Currently, the `SchemaType` property of `schema` is required in the type definition and its JSDoc describes the property as "The schema this SchemaType instance is part of".
Instead, based on how mongoose actually works, it should be optional and the JSDoc should be changed, since it's not actually the `Schema` that the `SchemaType` is part of. Instead, the `schema` property only exists when the `SchemaType` is for a subdocument or document array and it refers to the actual subdocument schema itself.
**Examples**
Here's an example showing how the `schema` property isn't present on every SchemaType, just to prove that the Typescript definition should be changed to optional and its JSDoc should be modified accordingly.
```ts
type Person = {
_id: …
```
> Fix `schema` property type definition in SchemaType

- lib/helpers/clone.js
- lib/types/array/methods/index.js
- lib/types/documentArray/methods/index.js
- test/document.test.js
Fix #15625
**Summary**
`clone()` with `retainDocuments: true` needs to create new MongooseArray and DocumentArray instances, otherwise `$clone()` converts document arrays into vanilla arrays.
**Examples**
> fix(document): prevent $clone() from converting mongoose arrays into vanilla arrays

- test/types/models.test.ts
- types/models.d.ts
Fix #15626
**Summary**
Move more specific overrides for `insertMany()` up
**Examples**
> types(models): correct type overload for insertMany() with lean and rawResult

- lib/document.js
- lib/model.js
- lib/schema/documentArray.js
- lib/schema/map.js
- lib/schema/subdocument.js
- test/model.test.js
- types/models.d.ts
Fix #15627
**Summary**
In #15627, OP was looking to hydrate documents with some virtual properties that were computed using the aggregation framework. This PR adds a `virtuals: true` option to `Model.hydrate()` which sets any virtuals that are present in the data being hydrated.
**Examples**
> feat(model): add `virtuals` option to `Model.hydrate()` to set virtuals

- lib/drivers/node-mongodb-native/connection.js
- test/connection.test.js
Fix #15635
**Summary**
`useDb()` child connections have their own `_lastHeartbeatAt` property, but that property is not updated when the client receives a `serverHeartbeatSucceeded` event. The Connection class only updates the top-level connection's `_lastHeartbeatAt`. That means `useDb()` child connections' helpers that rely on `_waitForConnect()`, like `dropDatabase()`, will hang after `heartbeatFrequencyMS * 2`.
I didn't register a separate event listener for each `useDb()` child connection because of memory leak concerns. With this approach, we don't have to clean up the event listener. Also, this pattern of looping over `otherDbs` respects the `noListener` option.
One potential issue: as implemented, `noListener` means the child connection isn't added to the parent db's `otherDbs` …
> fix(connection): propagate changes to _lastHeartbeatAt to `useDb()` child connections

- types/query.d.ts
**Summary**
Resolves issue https://github.com/Automattic/mongoose/issues/15643
**Examples**
Restores the ability to pass arbitrary options and the `timestamps` and `lean` properties to various model query methods.  This feature was removed in 8.17 with [this PR](https://github.com/Automattic/mongoose/pull/15547/files#diff-75b797f8e57c257285bf701a1832cded31d4a5fddb7a38a290a0c6fbf33b114fL34-R34).
> allow passing arbitrary options

- docs/typescript/populate.md
- lib/model.js
- test/schema.test.js
- test/types/aggregate.test.ts
- test/types/collection.test.ts
- test/types/discriminator.test.ts
- test/types/document.test.ts
- test/types/lean.test.ts
- test/types/maps.test.ts
- test/types/populate.test.ts
- test/types/queries.test.ts
- test/types/querycursor.test.ts
- test/types/subdocuments.test.ts
- types/models.d.ts
- types/query.d.ts
- types/schemaoptions.d.ts
**Summary**
For #10090, we added support for a `lean` option in schema options that makes all queries lean by default. This PR adds that option to the TypeScript types, including making functions like `Model.find()` and `Model.findOne()` automatically apply `lean` if the lean option is set on the schema.
Adding this option proved to be very tricky for 2 reasons:
1. `lean.transform` updates the object in place, so TypeScript doesn't know anything about the return type
2. There's some inconsistencies between how Document sees `DocType` and how Schema sees `DocType`, especially with discriminators (with discriminators, the Model sees the merged object properties, but the schema does not)
I made a few other related changes that popped up while debugging (2):
1. Getting rid of `: Schema` type …
> Add `lean` schema option to TypeScript types

- lib/helpers/schema/getPath.js
- test/helpers/schema.getPath.test.js
- test/helpers/update.castArrayFilters.test.js
Fix #15653
**Summary**
The root issue of #15653 is that `getPath()` currently doesn't look out for Mixed paths, this PR adds that fix.
**Examples**
> fix(schema): handle casting array filters underneath maps of Mixed

- lib/helpers/query/castUpdate.js
- test/model.updateOne.test.js
Fix #15642
**Summary**
Make `Model.updateOne({}, { $addToSet: { $each: ['test'] } })` throw an error, because this update attempts to update a path `$each`. By default, Mongoose strips out the `$each` update and makes this update a no-op, but we should likely throw an error. MongoDB doesn't allow this update, the MongoDB server errors out with `The dollar ($) prefixed field '$each' in '$each' is not allowed in the context of an update's replacement document. Consider using an aggregation pipeline with $replaceWith.`
**Examples**
> fix(query): throw error if using update operator with modifier and no path
