lib/model.js
In the documentation for Model.findOne, the argument 'conditions' is not marked as optional, and argument 'callback' is marked.
However, the code clearly shows it's in the other way around.
=> Fix optional arguments doc for Model.findOne

lib/error/messages.js, lib/schema/string.js, test/errors.validation.test.js
Similar to the basic min/max validators for the Number schema type, I've added minlength and maxlength validators for the String schema type, along with tests and default validation messages.
=> Added built in minlength and maxlength validators to the String schema type

docs/guide.jade, lib/model.js, test/versioning.test.js
First of all versioning is super useful. Thanks!
I'd like the ability to exclude certain array paths though. If elements in an array are only ever soft-deleted or properties updated one-by-one there's no point in including it in versioning and can result in false positive ```VersionError```s on concurrent updates.
Suggested syntax: 
```js
schema.set('notVersionedPaths',['safeArrayPath']);
```
Happy to contribute this with whatever other syntax/naming you prefer. 
What do you think? Are you interested in something like this?
=> Allow explicitly excluding paths from versioning

lib/model.js, test/model.hydrate.test.js
It seems like hydrate should work with discriminators.  Also i'm not sure why, but if I require queryhelpers outside of the function it breaks several tests, which is why i'm doing it in the awkward way that I am.  Not sure if there is a workaround for that.
=> make model.hydrate use createModel so that it works with discriminators

lib/document.js, lib/schema/array.js, lib/schema/documentarray.js, test/model.test.js
See #2442. When we're hydrating a doc from the db, if it has a field that mongoose thinks is an array but the db thinks is not an array, we can get some messy behavior where mongoose tries to set `array.0.value` on a non-array. To deal with this, just mark the whole array path as modified if we're initializing the doc and we don't get an array.
=> Fix #2442: mark whole array as modified if db doesn't think its an array

docs/guide.jade
Schemas have a `minimize` option, default to true, which will remove empty objects, see #851. This feature is not highlighted in the guide. Because such behavior can be unexpected for a typical user, it would be valuable for it to be present in the guide.
=> describe minimize option on schemas in guide

lib/schema/array.js, lib/schema/boolean.js, lib/schema/date.js, lib/schema/mixed.js
The `Array`, `Boolean`, `Date`, and `Mixed` schema types don't define an `instance` property in `SchemaType.call(...)`, thus resulting in `undefined` being set when `SchemaType` sets `this.instance` in lib/schematype.js:
function SchemaType (path, options, instance) {
this.path = path;
this.instance = instance;
See previous conversations requesting standard behavior at:
- https://github.com/LearnBoost/mongoose/issues/1430
- https://github.com/LearnBoost/mongoose/issues/1938
This PR is very simple, it just provides these strings so that anyone loading a Mongoose model can check the instance's schema type. This is useful, for example, if one wishes to load Mongoose models and describe their schema programmatically. Even without this use case, though, I think that the `instance` being set …
=> Added "instance" property strings for Array, Boolean, Date, and Mixed schema types

test/model.populate.test.js
See Issue #2729 
Added two test cases to `model.populate`:
- Population does not fail on document with ref of `null`.
- Population **does** fail on document with ref of `{}` - CastError.
=> Created test case to replicate Issue #2729

lib/document.js, test/document.unit.test.js
Fixes #2751. Thanks for pointing this out @whitecolor
=> Set default toObject() options after checking if parameter exists

lib/document.js, lib/model.js, lib/types/embedded.js, test/document.test.js, test/model.test.js, test/schema.validation.test.js
Fixes #2766 et all. Also removes the last dregs of dependency on the janky `$__.saveError` that got pulled in when merging from 3.8.x.
=> Mark paths as valid on successful set

lib/schema/documentarray.js
mongoose/lib/schema/documentarray.js:96
--count || fn(errors);
^
ReferenceError: errors is not defined
=> Fix errors is not defined

docs/populate.jade
The document refers to populating the `author` field on the `storySchema`, but that field does not exist. I assume it meant `_creator`. If not, the `author` property would need to be created.
=> The populate example has an incorrect field.

lib/schema/documentarray.js, test/model.discriminator.test.js
=> don't crash when discriminators have nested schemas

lib/document.js
Ran into a problem using mongoose with webpack, it really dislikes redifining *define*.  This is a tiny patch that would fix this problem.  I know I could fix webpack, but this is way easier and perhaps solves other issues with javascript compilers.
=> Fixing define for global.define in amd scenarios.

lib/schematype.js
Environment:
```
NodeJS 0.10.26
MongoDB 3.0.2
Mongoose 4.0.1
```
The following code will reproduce the issue.
```javascript
mongoose.connect('mongodb://localhost/test');
var Sku = mongoose.model('Sku', {});
var Item = mongoose.model('Item', {
skus: [{ref: 'Sku', type: mongoose.Schema.Types.ObjectId}]
});
(new Sku()).save(function(err, sku1) {
(new Sku()).save(function(err, sku2) {
var skus = [sku1, sku2];
var item = new Item();
console.log(skus); // Output: [ { __v: 0, _id: 553a026e768910b02f6b4a12 }, { __v: 0, _id: 553a026e768910b02f6b4a13 } ]
item.skus = skus;
console.log(skus); // Output: [ 553a026e768910b02f6b4a12, 553a026e768910b02f6b4a13 ]
process.exit(0);
});
});
```
This pull-request will fix the above issue.
However, Mongoose 3.8.x doesn't have …
=> Fix the issue that Array values to be overwritten

lib/document.js
This PR fixes Issue #2879 by allowing self-owned nested properties of virtual objects (or any objects?) to be enumerable. (There is also a minor fix for a case where an undefined property crashes the process.)
Suggest also porting this fix to 3.8.x branch (which we still use in production; will file separate PR if this is approved/etc).
=> Fix for #2879

README.md, docs/connections.jade, docs/models.jade
Clarified that the model name is singular, but the collection it specifies is plural. Also added a note about the mongodb connection, since sometimes if the hostname has been changed, there might be problems connecting to localhost.
=> ClarifyDocs

docs/api.html, lib/model.js
Updated the documents with the correct default value for the 'new' option in the find_and_update methods following https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes#backwards-breaking-changes.
=> Updated docs for find_and_update methods

README.md
Added a compact npm badge. This quickly tells the user what the latest release is, and provides a link to the npm release page without having to do a secondary search.
=> README: compact npm badge

lib/schematype.js, test/schema.validation.test.js
Fix for #3025 where validateSync() throws TypeError when used with required and maxlength
=> fix; validateSync when used with required and maxlength (Fix #3025)

docs/index.jade
Added semicolons to code lines where they were missing to match the rest of the document. The semicolons create uniformity in the code examples and improve clarity. No source code or markdown tags were edited.
=> Add Semicolons to Line-Ends for Uniformity

lib/document.js, lib/schema.js, test/model.middleware.test.js
Asynchronous document post hooks were actually being treated as asynchronous document pre hooks and were being registered as such. This fixes mongoose so it can properly handle these asynchronous post hooks. See issue #3062.
=> Proper support for asynchronous document post hooks

docs/validation.jade, lib/types/array.js, test/document.hooks.test.js, test/types.array.test.js
This fixes setters not being applied for push, unshift, addToSet, and set
Also added tests for MongooseArray#push
Let me know if anything could be improved/changed.
=> Fix for setters not being applied for push, unshift, addToSet, and set

lib/schema/string.js
On String validators minlength and maxlength:
- the special tokens {MINLENGTH} and {MAXLENGTH} were said to be replaced by the 'invalid value'. Changed that to 'minimum allowed length' and 'maximum allowed length'.
- validate() was called on variable s instead of address.
- The minlength example validated min 10, but shows error msg for min 5. Changed to validate 5
- The maxlength example validated max 10, but validates a max 10 string. Changed to validate 9 and show error msg for 9.
=> Fix incorrect examples of some String validators

lib/schematype.js
Ending curly brace and semi-colon missing
=> Fix for Documentation typo #2881

lib/model.js
The docs for functions model.save() and model.remove():
- used unsupported jsdoc formatting instead of markdown. This made it so that most of the function description was ignored and didn't compile into the html docs.
- the callback function params use unsupported jsdoc and got mangled in the output. I've fixed it so it's supported, but it's still illegal jsdoc. (Can't do "@param {function(err,product,Number)}", it should be "@param {Function}")
- The link to options.safe was relative and didn't render as a link; made it into a proper url but it still doesn't render as a link. (Not sure if the markdown syntax is supported inside a @param element)
=> Fixes syntax errors in jsdoc; fixes #3073

lib/services/updateValidators.js, test/model.findOneAndUpdate.test.js
Fixed up updateValidator object checker on encountering null during upsert.
This is because it attempts a `Object.keys(v)` after checking
that a condition is an `object` but this fails for null which.
is an object.
This PR addresses https://github.com/Automattic/mongoose/issues/3135
=> fixed updateValidator object checker

lib/types/documentarray.js, test/types.documentarray.test.js
When trying to use an object _id field ("compound" or "composite" _id) in documentarray (subschema), I have found that the documentarray id() method is improperly casting the id to string (which effectively turn the object into "[object Object]" string).
I've read object _id fields are [not officially supported in Mongoose](https://groups.google.com/forum/#!msg/mongoose-orm/yp_hHanUruo/ffM3WQPD-i8J). However, in my use case they seems to work rather well, apart from that id() issue.
=> Fix documentarray id method when using object _id

lib/types/documentarray.js, test/types.documentarray.test.js
Fixes a bug introduced by a190d41. The tests in this PR pass in 4.0.6 but fail in 4.0.7.
When assigning a new array to a MongooseDocumentArray, with both arrays containing multiple objects/subdocuments (respectively) without _id fields, the resulting array would consist entirely of the first element. This code example explains it better:
var Foo = mongoose.model('Foo', new mongoose.Schema({
things: [{
_id: false,
name: String
}]
}));
var fooInstance = new Foo();
var thingsArray = [
{name: 'qux'},
{name: 'baz'},
{name: 'bar'}
];
fooInstance.things = thingsArray;
console.log(fooInstance.things);
// Works!
// => [
//   {name: 'qux'},
//   {name: 'baz'},
//   {name: 'bar'}
// ]
fooInstance.things = thingsArray;
console.log(fooInstance.things);
// Broken :( …
=> Fix documentarray id method when _id is null-ish.

lib/model.js, test/model.test.js
Currently, calling `Model#save` on an unchanged document results in `numberAffected` in the callback being set to the document itself. According to the docs, `numberAffected` should always be `0` or `1` (never a document):
> ... `numberAffected` which will be 1 when the document was found and updated in the database, otherwise 0.
In mongoose v3.x this used to work as expected, it was only after upgrading to v4 that we noticed this.
=> Bug fix: Model#save should pass numberAffected as 0 when nothing changed

lib/document.js, test/model.test.js
Currently, `document#save` does not clear the 'default' dirty cache. This means when you have a schema field with a `default` specified, sequential `document#save` calls will each execute a query even if no document changes occurred. This PR clears the 'default' dirty cache when a model is saved so the dirty check works appropriately across saves.
=> Bug fix: default fields should not dirty a document across saves

lib/services/updateValidators.js, test/model.aggregate.test.js, test/updateValidators.unit.test.js
This fixes updateValidators for Date fields. It was trying to flatten the Date object and thus not validating the value properly.
=> fix; updateValidators should not flatten dates (Fix #3194)

lib/document.js, test/document.hooks.test.js
Currently, any subdocument with a pre-init hook is hydrated as a promise. For instance, take this schema:
```javascript
var childSchema = Schema({ age: Number }),
parentSchema;
childSchema.pre('init', function() {});
parentSchema = Schema({ name: String, children: [childSchema] })
```
When you issue a query for a `Parent` document, its `children` will be promises as opposed to their actual values:
```javascript
{
__v: 0,
_id: 55b6c665a2f7a9670204c5cf,
name: 'Bob',
children: 
[ { emitter: [Object], emitted: [Object], ended: false },
{ emitter: [Object], emitted: [Object], ended: false } ]
}
```
I'm not sure my solution is the best fix for this problem, please feel free to offer other ideas. The test I added does check this condition. My fix makes the test pass and I *believe* it doesn't …
=> Bug Fix: Pre-init hooks on subdocs should be syncronous

lib/query.js, lib/utils.js, test/model.querying.test.js
Currently, when conditions like `{$or: [Document]}` passed to `find`, `findOne`, `distinct` and `update`, it will cause a core dump.
The following code will reproduce the issue.
```js
mongoose.connect('mongodb://localhost/test');
var Sku = mongoose.model('Sku', {});
(new Sku()).save(function(err, sku) {
Sku.find({_id: sku._id}, function(err, skus) {
Sku.find({$or: skus}, function(err, skus) {
console.log(skus);
process.exit(0);
});
});
});
```
=> Applies toObject to conditions of find and update queries recursively

.eslintrc, examples/geospatial/geoJSONSchema.js, examples/geospatial/geoJSONexample.js, examples/geospatial/person.js, examples/statics/statics.js, lib/utils.js, test/model.populate.test.js
As long as no issues come up with #3191
This is a trivial PR enforcing the `no-trailing-spaces` rule. :smile: 
It also resolves a `no-redeclare` warning in `utils.js`
=> Lint for trailing space

lib/query.js
The problem:
````javascript
// whatever schema
schema.pre('update', function(next) {
console.log('update', this.getUpdate()); // used to be null!
next();
});
var Model = mongoose.model('model', schema);
Model.update({_id: 1}, {hello: 'world'}, {}, function(err, result) {
// whatever
});
````
=> Fixed getUpdate() in pre update hooks

lib/schema/boolean.js, lib/schema/buffer.js, lib/schema/date.js, lib/schema/number.js, lib/schema/objectid.js, lib/schema/string.js, test/model.query.casting.test.js
It seems reasonable that the `handleArray` helper method should validate that the passed value is in fact an array or coerce it into such rather than try and call `map` on a non-array object. The lack of this protection caused me some grief recently when a single value was accidentally passed in for an `$in` condition.
=> handleArray should ensure val is an Array.

README.md
In the description of Embedded Documents, the **Comments** schema should be **Comment** as it's what has been defined previously, or it will be quite confusing
=> Changed Comments to Comment

test/model.test.js
Using `Model.remove({_id: undefined}, cb);` will remove all records from the collection.
I noticed this issue by chance from one of our [broken] tests when i upgraded from 4.1.0 to 4.1.2, my test was fixed and works ok now (no longer sending `undefined`) but this should be addressed here...
=> Deleting with _id undefined will remove all records

test/model.test.js
Mongoose version `4.1.4` broke this functionality.
=> doc.remove() should not remove all docs in a collection

lib/drivers/index.js, lib/index.js
`MONGOOSE_DRIVER_PATH` should not be relative to the mongoose driver folder but must expect a valid absolute path, since it was changed it broke the compatibility of some modules that use it to load there custom drivers, ex: [sergeyksv/tungus](/sergeyksv/tungus).
=> fix a regression with MONGOOSE_DRIVER_PATH

docs/3.0.x/docs/schematypes.html, docs/3.0.x/docs/schematypes.jade, docs/3.1.x/docs/schematypes.html, docs/3.1.x/docs/schematypes.jade, docs/3.2.x/docs/schematypes.html, docs/3.2.x/docs/schematypes.jade, docs/3.3.x/docs/schematypes.html, docs/3.3.x/docs/schematypes.jade, docs/3.4.x/docs/schematypes.html, docs/3.5.x/docs/schematypes.html, docs/schematypes.jade
There are syntax errors making the examples fail in the runtime,
including missing commas and wrong attribute names.
Also, this commit appends semicolons to the ends of some codes to keep
the coding style in the same style.
=> docs; fix typos in SchemaTypes documentation

lib/schema/date.js, test/schema.test.js
This fixes #3134: Empty strings are being saved for date types. Casting an empty string to a date should return null not `''`.
It looks like this was accidentally changed in the fix for #2272 commit 0ac0596368394edec115a47fb78d148f67ea29af
=> Return null if casting an empty string to a date. Fixes #3134.

lib/document.js
Fix a reference error after a valid `find()` 
TypeError: this.get is not a function
at Object.nested.toObject (/home/workspace/programming/code/mongoose/lib/document.js:1481:27)
=> Fix TypeError: this.get is not a function

Makefile, docs/validation.jade
This pull request fixes #3368 which adds maxlength and minlength validation to validation docs
This also has a minor Makefile fix. I have added -e flag to the echo command on the docs build.
=> gh-3368 adding maxlength and minlength string validation

lib/schema/array.js
I found that when 'hasDollarSign' is set to true the value is returned [see here](https://github.com/Automattic/mongoose/blob/389c8d01576ced32f5cbe5e3001b008c83946ab1/lib/schema/array.js#L342-L344).
This causes properties to not get cased to ObjectId and other types.
=> Ensuring properties are casted. This fixes #3435

docs/guide.jade
`timestamps` option is convenient but not documented, I add some simple doc for this option.
=> docs; add doc for options.timestamps when create new Schema

test/aggregate.test.js
var a = undefined;
// v0.10: TypeError: Cannot call method 'b' of undefined
// others: TypeError: Cannot read property 'b' of undefined
a.b();
=> tests; fix unit test error in node v0.10

lib/schema.js, test/schema.timestamps.test.js
mongoose has support `findOneAndUpdate` and `update` middlewares.
when create a schema with  `options.timestamps` on, we'd better update `updatedAt` field in `findOneAndUpdate` and `update` middlewares.
Besides, I add some tests for `options.timestamps` feature.
=> update updatedAt in findOneAndUpdate/update middleware if timestamps on

lib/types/array.js, test/types.array.test.js
Libraries like `should` and `chai` do an array comparison by checking the length of `Object.keys(array)` (among other things).  Because a `MongooseArray` has a few properties that are enumerable, `Object.keys` will return them, and so the equality test fails.  To get around this, you have to call `toObject` on the `MongooseArray`.  This works, but it prevents you from testing a full object at once, and instead forces you to test each property separately.
This pull marks those `MongooseArray` properties as non-enumerable, so that they are not returned by `Object.keys`.  I added a new test to verify this works, and all existing tests pass.
=> Make array props non-enumerable

lib/connection.js, test/connection.test.js
I use MONGODB-X509 authentication with my mongo DB and I have found a problem with the logic around whether mongoose should authenticate or not.
MONGODB-X509 authentication uses certificates to authenticate clients instead of a password. This means that you can leave the password field blank. The problem is that currently if you leave the password as blank than authentication doesn't happen at all and you do not have permissions to execute anything on the database.
I have added a method that checks if the current authentication method needs a password and, if it does not, still calls the mongo driver's authenticate method.
Have I missed any other places where authenticate would be called?
Thanks!
=> Authentication will now still occur when auth method is MONGODB-X509 and no password is supplied.

lib/query.js
Reported in https://github.com/Automattic/mongoose/issues/3470. The old comment referred to `slaveOk`, which is deprecated. This pull request updated the comment to use `readPreference` instead.
=> Fix comment of Query.setOptions to specify correct read preference option

lib/model.js
Currently Mongoose will emit an `index` event when all indexes have finished building. This would happen for example when `ensureIndexes()` is finished. Since some indexes can be quite large and take a long time, it would be nice to know when each individual index is finished competing. 
This pull request adds two new emit events to Mongoose schema objects:
`index-single-start` : when an individual index build begins.
`index-single-done` : when an individual index build finishes.
For example:
```js
Model.on('index-single-done', function(err, fields, options, name)
{
if ( err ) {
Logger.error('[INDEXER] Model:'+Model.modelName+' failed to build index: '+name+'. Options='+JSON.stringify(options)+
'. Err='+err);			
} else {
Logger.info('[INDEXER] Model:'+Model.modelName+' built index: …
```
=> Emit events when each individual index starts and completes

package.json
Differences in filtering between Mongoose and Pluralize resulted in #3490
This update resolves #3490 by using the old filtering system.
=> Pluralize Mongoose 0.2.0

.gitignore, lib/connection.js, test/connection.test.js
As described in #3484 
Removes the null check for the user/pass options
in the optionsProvideAuthenticationData method of Connection. This reverts the logic back to it's previous state before https://github.com/Automattic/mongoose/commit/9af0d5fb0c5ffd4f8382715a1837e3c110b4ed3b
Adds a test to verify empty strings provided for the user/pass options
properly bypass authentication.
connections:
shouldAuthenticate()
when using standard authentication
when username and password are empty strings
=> optionsProvideAuthenticationData logic refactor

lib/aggregate.js
In the current api docs, is said to use `mongoose.Schema.Types.ObjectId(String)` to convert a string to an ObjectId, but the correct is `mongoose.Types.ObjectId(String)`
Regards
=> Fix documentation error for Aggregate

test/schema.validation.test.js
@vkarpov15 so here’s a test scenario for #3521.
It happens in very specific cases (the test may need to be rewritten a little to highlight those specificities).
The subdocument has to be created with `subdoc.create()` and pushed into the mongoose array.
If you also add a `required` attribute to the `votes.vote` field, the validation works fine, for some reason.
I am not sure where to fix that in the code, so here’s a test, that may help you pinpoint where it is failing exactly.
=> repro; #3521

lib/services/updateValidators.js
modifiedPaths() walks the object structure, encounters the Buffer, then
encounters the parent of the buffer, which hangs the server for up to 30
seconds.
=> Fix hang encountered with custom id type that contains a buffer

lib/query.js
1. Short link removed because it's a duplicate of `@see findOne`.
2. `@see Query.select` added because of its relation to the `projection` argument.
Thank you!
=> docs; clarify param projection in findOne

docs/connections.jade
The current docs make it seem like this is a Boolean. According to the [native driver](https://mongodb.github.io/node-mongodb-native/driver-articles/mongoclient.html), the keepAlive is a number of seconds.
=> Docs: Update keepAlive info

lib/document.js
This is in reference to my last comment on https://github.com/Automattic/mongoose/issues/3680
By adding the sub-docs of the single nested first, pre-save can be bottom-up (e.g. embedded > single nested > parent) and post-save can be top-down (e.g. parent > single nested > embedded).
This is a critical flow for encryption tools like https://github.com/joegoldbeck/mongoose-encryption
=> add subdocs of single nested first for proper hook order

lib/schema.js
I encountered other issues along the way that led me to duck-type a couple of extra `instanceof` calls in `schema.js`. Did thought that it was not necessary at first sight.
=> fix(schema): more duck-typing (fixes #3690)

package.json
This fixes the "No primary server available" errors that occur under high load.
https://jira.mongodb.org/browse/NODE-622
=> Update mongo driver to 2.1.2

lib/aggregate.js, test/aggregate.test.js
I have an issue where it's not possible to append an array of pipeline operators to an existing aggregate query object. I searched for a related issue, and couldn't find an explanation as to why this feature is ommited.
The docs state it is possible to use `Aggregate#append` with an array of pipeline operators, but the output is an error: **Error: Arguments must be aggregate pipeline operators**. Support for an array of pipeline operators exists for the `Aggregate` constructor, so I added similar functionality to `Aggregate#append` with the corresponding tests.
=> Fix support for array pipeline argument when using Aggregate#append

lib/aggregate.js
Fixes changes in #3730, messed up the line for changes. Now correctly placed in `Aggregate#append`.
=> fix erroneous change in #3730

lib/query.js
When you make a update like this:
```javascript
TwitterAccountModel.update(
{account: account},
{
$set: {account: account}
},
{upsert: true, new: true},
{type:'object or other type, like number, string. Onlu function is valid as a callback'});
```
as you see you can pass at fourth parameter any, but it cashed if that is not a function
so i made a previous validation of the fourth parameter, and throw an error it that not a function.
I'll be pleased if you take a moment. Tks
=> (fixed) error when passed a callback in updata, and that is not a function

examples/population/population-across-three-collections.js, lib/document.js, lib/types/documentarray.js, lib/types/embedded.js, test/colors.js, test/model.test.js
this PR fixes colorized output
have no idea why you did like so but `Document.inspect` same as `MongooseDocumentArray.mixin.inspect` returns a string instead of object so util.inspect can't colorize it properly
you can check this by running 
```bash
node examples/population/population-across-three-collections.js
```
this fix makes 
`Document.inspect` return `Document.toObject()` with filtered private props
`Document.toString` return string representation of `Document.inspect()`
`MongooseDocumentArray.mixin.inspect` returns array of `Document`
=> colorized output

lib/document.js
#2880 fixed #2879 in master, but it is still broken in the 3.8.x branch.
The real fix would be to make the properties enumerable, however doing so would cause a breaking change (as mentioned in #2211).
=> Fix for #2879 in 3.8.x branch

lib/document.js, test/model.populate.setting.test.js
I didn't see any open issues related to this but currently assigning a nested populated array to a nested document structure casts all sub documents to its respective `_id` and does not retain the populated sub documents
However for document arrays, the document items retains the populated document items, e.g.
```
const EmbeddedSchema = new mongoose.Schema();
const Embedded = mongoose.model('Embedded', EmbeddedSchema);
/**
* Correctly sets the populated document
*/
const ListSchema = new mongoose.Schema({
'items': [
{
'type': mongoose.Schema.ObjectId,
'ref': 'Embedded',
'required': true,
},
],
});
const List = mongoose.model('List', ListSchema);
const list = new List();
list.items = [ new Embedded() ];
expect(list.items[0]).to.be.an.instanceof(Embedded);
list.items = [ ObjectId() ]; …
```
=> Call populated() on ownerDocument for sub documents

docs/guide.jade
Just needed the word `be` in the code example.
=> Adding missing word to timestamps section

lib/types/array.js, lib/types/documentarray.js, test/types.array.test.js, test/types.documentarray.test.js
this is attempt to fix performance degradation caused by usage of `Object.defineProperty`
according this [blog post](https://www.nczonline.net/blog/2015/11/performance-implication-object-defineproperty/) we can improve performance by using one call to `Object.defineProperties` instead of several calls to  `Object.defineProperty`
note: there is possible [zero performance impact](http://webreflection.blogspot.co.id/2014/03/what-books-didnt-tell-you-about-es5.html#zero-performance-impact) in case of using `Object.defineProperty` on `object.prototype` but unfortunately it's impossible because JS doesn't allow subclass builtin objects such as `Array`
also this PR makes `MongooseArray` and `MongooseDocumentArray` consistent as well as its 'duck' tests
=> attempt to fix #3728

docs/includes/nav.jade, docs/schematypes.jade, docs/source/acquit.js, test/docs/customschematypes.test.js
The /docs/schematypes.html was the only page being generated from both a .jade file and acquit.  Moved acquit output into new page and added reference in appropriate area on schematypes.jade.
=> Fix for #3843

lib/schema/array.js, lib/schema/documentarray.js
Helps pinpoint what caused the problem, rather than a generic-ish error from the array
Not sure of how to appropriately add tests for this
=> Include the nested error when throwing CastError from arrays

docs/includes/nav.jade
correct the "plugins" link in the docs navigation menu
=> fix plugins link in nav menu

lib/types/array.js
It took me a while to figure out why my pull operations resulted in actual `$set` operations until I figured out that this is only the case when more then one `pull`s are happening.
=> DOC: add remark about MoongooseArray.pull(...)

docs/guide.jade
Adding more visibility to the `autoIndex` option by adding examples at the connection level
=> Add autoIndex config example at connection level

lib/drivers/node-mongodb-native/connection.js, test/connection.test.js
Currently, if `ssl` and `sslValidate` are specified in the connect string query, and you pass `{mongos: true}` to the `mongoose.connect`, `ssl` and `sslValidate` are not set on the `mongos` opts. You can manually specify `{mongos: {ssl: true, sslValidate: false}}` and it works, but it is [documented](http://mongoosejs.com/docs/connections.html) that `{mongos: true}` is enough. This adds that capability.
=> fix(mongos connection): Allow connecting with {mongos: true} to handle connection query params

lib/drivers/node-mongodb-native/connection.js, test/connection.test.js
closes https://github.com/Automattic/mongoose/issues/4035
=> feat(mongos connection): Support specifying mongos as a connection string query parameter.

lib/schema.js, test/schema.test.js
Prevents the same plugin from being applied to the same schema more than once. See issue #4106 for details.
=> Apply plugins to schemas only once

docs/2.7.x/docs/querystream.html, docs/2.8.x/docs/querystream.html, lib/querystream.js
Currently the doc explicitly says no events will be emitted after calling the `destory()` method on stream. However, that is not true and misleading because it does emit the close event.
=> Updated QueryStream#destroy documentation.

test/schema.validation.test.js
This is very similar to #3533.
The validation of subdocuments’ subproperties is broken when the subdocument is created using `MongooseDocumentArray.create` and no hash is passed to that method.
Creating `child` using 
```js
var child = model.children.create({
prop: {
val: 'valid'
}
});
```
will make this test pass.
=> Add test for broken subdoc subprop enum validation

lib/document.js
`isMongooseObject` was referenced in the top of the file to use `utils.isMongooseObject`, so no need to use `utils.` here
=> chore(document): use function reference

lib/document.js
Unless I'm mistaken, calling `p.originalRequiredValue` with `this` instead of `_this` doesn't pass the correct scope to custom validation functions.
=> Path validation is called with the incorrect scope

lib/model.js, test/model.field.selection.test.js
See #1334 for discussion.
Test "model field selection with $elemMatch projection disallows saving modified elemMatch paths (gh-1334)" will fail, because saving now succeeds.
I do not know exactly, which additional checks are necessary. For example, what does Mongoose do, when an array field is removed or overwritten with a completely new array? Do I have to check for that?
=> Allow saving of array fields selected via $elemMatch

lib/document.js
This change filters out modified chains already present in the list before concatenating.
See #4223
=> Dedupe modified paths

lib/query.js
See #4173
I haven't added a test as I couldn't find one for the `.then()` method either, and it's a pretty trivial implementation. Let me know if anything else needs adding.
=> Add Query prototype `.catch()` method

lib/types/subdocument.js
I don't know why yet, but I get this error in my application:
TypeError: callback is not a function
at Document.Subdocument.remove (/src/xxx/node_modules/mongoose/lib/types/subdocument.js:100:5)
at Document._done (/src/xxx/node_modules/hooks-fixed/hooks.js:101:24)
at _next (/src/xxx/node_modules/hooks-fixed/hooks.js:64:28)
at fnWrapper (/src/xxx/node_modules/hooks-fixed/hooks.js:186:18)
at Document.Object.defineProperty.value.fn (/src/xxx/node_modules/mongoose/lib/schema.js:249:11)
at Document._next (/src/xxx/node_modules/hooks-fixed/hooks.js:62:30)
at Document.proto.(anonymous function) [as $__original_remove] (/src/xxx/node_modules/hooks-fixed/hooks.js:108:20)
at /src/xxx/node_modules/mongoose/lib/document.js:1898:24
at new Promise.ES6 …
=> TypeError--

lib/document.js, lib/types/array.js, lib/types/documentarray.js, test/types.array.test.js
Passing undefined (and only undefined; doesn't occur with either no args, nor other args + undefined, but does crash with undefined + other args) results in an empty MongooseArray on the mongo side (but not locally until a refresh).
See this example:
```js
mongoose.connect('mongodb://localhost/test');
var Cat = mongoose.model('Cat', {
name: String,
colors: [
{ hex: String }
]
});
var kitty = new Cat({ name: 'Zildjian', colors: [{hex:'#FFF'}, {hex:'#FFF'}] });
kitty.save(function (err) {
kitty.colors.pull(undefined);
console.log(kitty) // all fine here
kitty.save(() => {
Cat.find({ _id: kitty.id }).then((res) => {
console.log(res[0]) // array empty
})
})
});
```
Output:
```
{ colors: 
[ { _id: 575b3e792d0799125dea917c, hex: '#FFF' },
{ _id: …
```
=> Passing undefined to MongooseArray#pull pulls all values

lib/connection.js
Problem in `for (var i in `, which can return prototype keys.
I got this problem in Mocha tests. `for (var i in this.collections)` in addition to collections names, became returns `getClassName` value. And this produced following error:
```
TypeError: _this.collections[i].onOpen is not a function
at open (/Users/nod/www/_npm/graphql-compose-mongoose/node_modules/mongoose/lib/connection.js:508:28)
at NativeConnection.Connection.onOpen (/Users/nod/www/_npm/graphql-compose-mongoose/node_modules/mongoose/lib/connection.js:521:5)
at /Users/nod/www/_npm/graphql-compose-mongoose/node_modules/mongoose/lib/connection.js:483:11
at /Users/nod/www/_npm/graphql-compose-mongoose/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:60:5
at …
```
=> Add checks for collection presence for `onOpen` and `onClose`.

lib/querycursor.js
It looks #4255 missed a case where populate() was invoked.
Added the missing code.
Please, review.
Thank you,
Grigoriy.
=> consider lean option in populate

package.json
increase mongodb version to be able to use  gridFS bucket openUploadStreamWithId new function.
=> increase mongodb native client version

package.json
version 2.1.21 is broken per https://jira.mongodb.org/browse/NODE-722?focusedCommentId=1287950&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1287950. revert to 2.1.18
=> Change MongoDB Node driver version from 2.1.21 to 2.1.18

lib/schema.js, test/schema.timestamps.test.js
`createdAt` should always represent the document’s creation date. Whenever
`createdAt` is not selected (so `undefined`) and we update the document – it
should not be set to a new value.
Fix #4340
=> Make sure that createdAt does not get overriden

lib/schema.js, test/types.subdocument.test.js
mongoose@4.5.9, mongodb@2.1.18
When updating a saved document with timestamps, the subdocuments without options create an error, since the 'timestamps' option does not exist on the subdocument:
```
var mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
var Schema = mongoose.Schema
var Thing = mongoose.model('Thing', new Schema({
subArray: [{
testString: String
}]
}, {
timestamps: true
}))
var thingy = new Thing({
subArray: [{
testString: 'not updated'
}]
})
var id
thingy.save(function (err, item) {
if (err) {
console.log(err)
} else {
id = item._id
}
})
.then(function () {
var thingy2 = {
subArray: [{
testString: 'updated'
}]
}
return Thing.update({
_id: id
}, {$set: thingy2})
})
.then(function () {
mongoose.connection.close()
})
.catch(function (err) { …
```
=> fix #4434 subdocuments causing error with parent timestamp on update

lib/model.js, test/model.create.test.js
When create a instance with a callback, an unhandled reject promise event will triggered if create failed.
```
var TaskSchema = new Schema({
name: {
type: String,
maxlength: 4
}
})
var Task = mongoose.model('Task', TaskSchema)
Task.create({
name: 'too long name'
}, function (err, task) {
// here will have an err.
console.log(err)
})
process.on('unhandledRejection', function (reason, promise) {
// and there will a event.
console.log(reason)
})
````
=> should not cause unhandle reject promise when create fail

docs/documents.jade
The current example given for the 'findById' method places the updated document in the callback function while the 'findByIdAndUpdate' method places the original document in the callback. To keep things consistent they should both return the updated document which is returned from the db.
Wasn't sure which branch to put this on, happy to move it.
=> docs(document): clarify the findById and findByIdAndUpdate examples

lib/schema/array.js
I have scema with 'Array of Arrays' field type like
```
let schema = new mongoose.Schema({
name: String,
fieldArray: [[Number]]
}, { strict: true, versionKey: false });
```
Creating new document works fine for this
```
let doc = { name: "asdf", fieldArray: [[12, 654, 8], [-54, -45]]};
new model(doc).save()
```
But findOneAndUpdate throws error
> TypeError: Cannot read property 'castForQuery' of undefined at SchemaArray.castForQuery
> (\node_modules\mongoose\lib\schema\array.js:208:37)
>     at Query._castUpdateVal (\node_modules\mongoose\lib\query.js:2575:17)
>     at Query._walkUpdatePath (\node_modules\mongoose\lib\query.js:2519:25)
>     at Query._castUpdate (\node_modules\mongoose\lib\query.js:2391:23)
>     at castDoc (\node_modules\mongoose\lib\query.js:2598:18)
>     at …
=> Fix an error on findOneAndUpdate with array of arrays

test/model.create.test.js
update test case for PR [should not cause unhandle reject promise when create fail](https://github.com/Automattic/mongoose/pull/4439).
The origin test will not result in a failed test, but a unhandled promise log from Bluebird.
THe new test case will result in a failed test before PR4439 fixed.
=> update test for PR:4439

lib/document_provider.web.js, lib/drivers/index.web.js
With this fix, we can have the browser implementation be compatible with webpack.
Solution derived from @patterncoder's ["hack"](https://github.com/Automattic/mongoose/issues/3578#issuecomment-166437240).
The "solutions" in related issues haven't been satisfactory. The current `lib/drivers/index.js`'s `typeof window === 'undefined'` check doesn't satisfy webpack without extraneous (and irrelevant to mongoose in the browser) loaders. Requiring a separate `<script>` tag also breaks the point of webpack. While webpack isn't a specified case mongoose supports, this one file would handle the problem entirely.
Resolves webpack/webpack#1040
Resolves webpack/webpack#2566
Resolves #3713
Resolves #3578
=> Fix webpack build

lib/index.js
Hi,
I'm looking for a workaround on an issue (on compound primary key). I think I have a Quick & Dirty solution, so I want to override Model.
The following PR allow that by using the Mongoose.prototype.Model = Model; (line 674) and not the require (line 13)
Regards,
Gaël - HungryUp
=> Read Model from this

lib/schematype.js
Existing link didn't go anywhere.
=> fix wrong link in documentation

lib/connection.js
original error on reconnect
```
TypeError: db.close is not a function
at NativeConnection.db.on.error (/home/travis/build/bucket-list/operator/source/utils/mongoose.js:2:1821)
at emitOne (events.js:96:13)
at NativeConnection.emit (events.js:188:7)
at /home/travis/build/bucket-list/operator/node_modules/mongoose/lib/connection.js:288:17
at NativeConnection.Connection.error (/home/travis/build/bucket-list/operator/node_modules/mongoose/lib/connection.js:451:12)
at /home/travis/build/bucket-list/operator/node_modules/mongoose/lib/connection.js:482:15
at /home/travis/build/bucket-list/operator/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:69:21
at /home/travis/build/bucket-list/operator/node_modules/mongoose/node_modules/mongodb/lib/db.js:229:14
at Server.<anonymous> …
```
=> db.open emits error even if it was caught

lib/drivers/node-mongodb-native/connection.js
It looks like the error message emitted by the mongo driver when auto reconnect mechanism fails has been changed recently (https://github.com/christkv/mongodb-core/blob/319f26dcbdf71a13f234ca33aac2a49642984b5b/lib/connection/pool.js#L307) from `...after x retries...` to `...after x attempts...`, thus the regex used to caught the error and emit a mongoose `error` is not matching anymore
=> reconnectFailed error from driver not being caught

lib/services/setDefaultsOnInsert.js
Removes expensive code used to set unused variables at the top of setDefaultsOnInsert, and moves all of the remaining code in to the conditional for options.upsert, which is the only case it would apply in.
=> Fix high process utilization issue #4671

lib/error/validation.js
In ValidationError.toString, the Object.keys fails when this.errors is null. Fixes #4689
=> Object.keys fails when this.errors is null

lib/query.js, lib/querycursor.js, test/query.cursor.test.js
This PR adds 2 (related) features discussed in #4705
- `.cursor(opts)` accepts a `transform` function which is applied when the cursor returns a document
- `QueryCursor#map` which allows additional transform functions to be applied to documents pulled with the cursor (whether by the streams interface or `next()`)
The `transform` option and `.map()` can be combined and happens to be chainable e.g. `.cursor({ transform: function () {} }).map(...).map(...).on('data')`
=> Document transform options for QueryCursor

lib/document.js
(continued from #4682)
If some kind of stack beautification library (like with coffeescript) is used, generating the stack for every query is really expensive (in the order of 1,5s per 1000 queries).
This should still give the same stacktrace, but only generate the beautifyed stack if it's actually used, increasing performance for the common non-error case.
Even without stack beautification, accessing Error().stack is [10x slower](https://jsperf.com/error-vs-error-stack) than just storing Error(), making this a generally applicable optimization.
=> Delay stack generation until it's required

lib/index.js, lib/model.js, lib/schema.js
The reason for this PR is that I noticed that mongoose under the hood is essentially acting as a mixin to a class, and I saw room for improvement with the syntax for defining models. Generally static and instance methods have to be inconveniently defined through helpers on a `Schema` before they are copied onto the model, and `Model.compile` is also being inefficient by manually setting the prototype. So essentially, mongoose is doing work that ES6 already natively supports.
With these changes `mongoose.model` can support taking an ES6 class where `name` is normally provided:
``` javascript
const { Model, Schema } = mongoose;
const schema = new Schema({
_id: Schema.ObjectId,
field1: Number,
field2: String
});
class SomeThing extends Model {
static …
```
=> Integration for ES6 classes

package.json
Mostly excited about a memory leak that was fixed, but there are other fixes in there too.
=> fix: upgrade mongodb -> 2.2.12

test/model.populate.test.js
`npm test` will occasionally fail because the justOne test doesn't cover the case where the alternate populated document is returned
Also added in an assertion that `justOne` virtuals should not be returned as an array for good measure
=> Fix justOne test

lib/schema/string.js
Fix `enu` to `enum` in example for `SchemaString#enum([args...])`
=> Fix typo in docs

lib/document.js
This allows callback to be optional as `$__validate` assumes callback is defined and not optional.  
**Summary**
This is a small fix to handle the issue with callback not being defined, breaking the validation process.  This is tied to #4841
**Test plan**
=> Allowing callback to be optional

lib/query.js
I was getting the following while using Bluebird Promises with mongoose 4.7.5:
```
(node:56) Warning: a promise was created in a handler at app/node_modules/mongoose/lib/query.js:2313:18 but was not returned from it, see http://goo.gl/rRqMUw
at new Promise (/app/node_modules/bluebird/js/release/promise.js:77:14)
```
The code seems innocuous enough:
```js
const point = await Point.findOne({src, dst})
.populate([{path: 'post'},
{path: 'src_profile', populate: {path: 'user'}},
{path: 'dst_profile', populate: {path: 'user'}}])
.exec();
```
All of the paths ``post``, ``src_profile``, ``dst_profile``, and ``user`` are virtual population fields.
Strangely enough, if I remove the two deep populates no errors occur. I did check my own code for runaway promises and I don't think I see any.
I made …
=> Fix warning from Bluebird about promises created but not returned.

lib/schema.js
propagate the 'strict' option to a child schema.
solve this issue [#4823](https://github.com/Automattic/mongoose/issues/4823)
=> propagate strict option to a child schema

lib/model.js
**Summary**
Fixes #4947 - just a missing `new` keyword.
**Test plan**
Tests all run fine locally.
=> Fix #4947 by ensuring class is created with new keyword

lib/query.js, test/model.findOneAndUpdate.test.js
Fix #4925
The `passRawResult` option has proven to be exceptionally cumbersome for 2 reasons:
1. We had to hack around it to make it not break error handler middleware. Because an error handler middleware is defined by the number of arguments it takes, conditionally adding a third param makes it impossible to write error handler middleware that can handle both `passRawResult: true` and `passRawResult: false`. The current hack makes it so that raw result is _never_ passed to error handler middleware.
2. You need to use the callback API or mpromise (deprecated). With ES6 promises, you can never get the raw result.
This PR introduces the `rawResult` option, meant as a replacement for `passRawResult`, which makes the 2nd param to the callback the raw result (as opposed to the 3rd). This works …
=> rawResult option

lib/model.js
People will notice that they can update several documents at once as soon as they learn about the  `multi` attribute a few lines below.
=> Update description said "documents" instead of "one document"

lib/document.js
Small fix in the documentation for the errors that occur [here](http://mongoosejs.com/docs/api.html#document-js) and [here](http://mongoosejs.com/docs/api.html#document_function%20Object()%20%7B%20%5Bnative%20code%5D%20%7D-%24isDefault)
The issue was that `dox` wasn't correctly generating the function names for functions that start with `$` without explicitly specifying `@method` and `@memberOf`.
Current:
`$isDefault()`
`$ignore()`
Fixes:
`$isDefault()`
`$ignore()`
=> document.js fixes for functions prepended with `$`

lib/types/documentarray.js
I was pushing object created by `Object.create(null);` into an array schema type. Since the prototype is `undefined` is causes `Cannot read property 'baseCasterConstructor' of undefined`.
This PR checks that the prototype is defined first.
=> Avoid exception on constructor check

lib/schema/array.js
**Do you want to request a *feature* or report a *bug*?**
bug
**If the current behavior is a bug, please provide the steps to reproduce.**
```js
var mongoose = require('.');
var Promise = require('bluebird');
mongoose.connect('mongodb://localhost/test');
var Cat = mongoose.model('Cat', { name: String, props: [{
name: String
}]});
(async function () {
var kitty = new Cat({ name: 'Zildjian', props: [null, {name: 'abc'}] });
await kitty.save();
kitty = await Cat.findById(kitty._id);
console.log(kitty.props)
await Cat.update({ _id: kitty._id }, { $pullAll: { props: [null] }})
kitty = await Cat.findById(kitty._id);
console.log(kitty.props)
}());
```
**What is the current behavior?**
Returns `[ null, { _id: 58efc1d703b69d6d1f1d2e72, name: 'abc' } ]`.
**What is the expected behavior?**
Should …
=> mongoose 4.8.3 broke $pullAll: null on subdocs

lib/model.js
**Summary**
The `update` option was inadvertently being wrapped by the passed-in `filter` option. Most likely a copy-paste error in the code.
I ran into this issue when trying to do a bulkWrite->writeMany operation.
**Test plan**
No additional tests were added, as it should be easy to eyeball the error.
=> Fix the bulkWrite::updateMany case

lib/document.js, test/document.modified.test.js
**Summary**
This is a proposal to fix the primary issue described in #5189.
**Test plan**
A test has been added that demonstrates the failure case without the included fix. See [`test/document.modified.test.js#468`](https://github.com/Automattic/mongoose/pull/5192/files#diff-2242966c7ef28bf9e498506e1bcff490R468). Steps to manually reproduce can be found in #5189.
**Notes**
I must admit it feels wrong reaching into `val.__parentArray` within `Document.prototype.$__set`. A new method to encapsulate this on `DocumentArray` might be preferable, and I'd be happy to propose one if this direction feels right.
In any case, modifying the value passed to `Document.prototype.set` might itself be quite undesirable, and other more involved solutions may avoid this, for example:
- cloning assigned …
=> Update `parentArray` references when directly assigning document arrays

lib/query.js, lib/services/query/hasDollarKeys.js, test/model.findOneAndUpdate.test.js, test/model.update.test.js
=> When overwriting doc with update+overwrite, validate the whole doc

lib/model.js, package.json, test/model.test.js
=> Pass params to pre hooks

lib/error/validation.js, test/document.test.js, test/model.populate.test.js, test/model.test.js, test/schema.validation.test.js, test/types.buffer.test.js
=> feat(validation): include failed paths in error message and inspect output

lib/aggregate.js, lib/cursor/AggregationCursor.js, test/aggregate.test.js
=> Aggregation cursor

docs/api.jade
fixes #5291
**Summary**
* Missing font-awesome "fa" class caused incorrect font to be used, leading to unicode □ appearing instead of the desired caret.
* Desired "toggling" behavior on first click was added by modifying/simplifying existing javascript.
**Test plan**
Running `make docs` locally leads to correct toggling behavior.
=> reveal subtopics in sidebar on first click

lib/model.js
It seems that the note about the hooks that are called after `updateMany` was copy+pasted into the `updateOne` and `replaceOne` documentation.
It either does not apply, or the reference to `updateMany` needs to be updated to say `updateOne`/`replaceOne`
**Summary**
**Test plan**
=> Tweak updateOne and replaceOne documentation notes

.npmignore
**Summary**
75052328bf5f5544194f15137f1bf749e8125eae added the data directories in tools/ to `.gitignore` but not `.npmignore` resulting in the latest npm release to be 900MiB large. This PR will add these data directories to .npmignore.
=> Add data dirs in tools/ to .npmignore

lib/model.js, test/aggregate.test.js
Sometimes the test would fail (based on the order the database would return the results)
=> Fix(ensureIndexes) manual call with !schema.options.autoIndex

lib/drivers/node-mongodb-native/connection.js, package.json, test/parse.options.test.js
**Summary**
Consider the following code snippet:
```javascript
var mongoose = require( 'mongoose' );
var options = Object.create( null, {
auth: { value: {} }
} );
// internally calls `parseOption( options, connStrOpts /* options that were passed in the connection string, if any */ )`
mongoose.connect( 'mongodb://localhost/my_database', options );
```
The issue is that `parseOption( options )` currently mutates the passed `options` parameter. Should that really happen?
- Library users may not expect that their data will possibly get mutated by mongosse
- If a library user passes a secured object composed with `Object.create( ... )`, the connection attempt will fail
- Mutating users references is not playing-nice, imho
The change in this PR resolves the described issue.
**Test plan**
A unit …
=> Fix `parseOption` mutates user passed option map

lib/model.js, lib/schema.js, test/model.translateAliases.test.js
Follow up from #5321   
Usage:
```
var Character = mongoose.model('Character', new mongoose.Schema({
name: { type: String, alias: '名' },
bio: {
age: { type: Number, alias: '年齢' }
}
}));
// The condition for the 'find' query will become { name: 'Stark', bio: { age: 40 } }
Character
.find(Charater.translateAliases({
'名': 'Stark',
'年齢': 40
})
.exec((err, characters) => {})
// Can be use similarily when constructing new document
var char = new Character(Character.translateAliases({
'名': 'Stark',
'年齢': 40
});
```
=> Query and construct document with aliases with Model.translateAliases

lib/query.js, lib/schema/decimal128.js, lib/services/query/castUpdate.js, lib/types/embedded.js, lib/utils.js, test/model.update.test.js
**Summary**
https://github.com/Automattic/mongoose/issues/5361
**Test plan**
the following script should not error with the changes:
```javascript
const co = require('co');
mongoose.Promise = global.Promise;
exec()
.catch(error => {
console.error(`Error: ${error}\n${error.stack}`);
process.exit(2);
});
function exec() {
return co(function* () {
const db = mongoose.createConnection('mongodb://localhost:27017/gh-5361');
var schema = new mongoose.Schema({
name: String,
pricing: [{
_id: false,
program: String,
money: mongoose.Schema.Types.Decimal
}]
});
var Person = db.model('Person', schema);
yield Person.remove({});
var data = {
name: 'Jack',
pricing: [
{ program: 'A', money: mongoose.Types.Decimal128.fromString('1.2') },
{ …
```
=> Model.update with decimal 128 bug

lib/model.js, lib/query.js, test/query.test.js
**Summary**
Fixes #5396
Renames the `justOne` option to `single`, and correct the docs. `justOne` doesn't work.
**Test plan**
All three cases (default, true, false) are covered.
(Replaces PR #5397, which is caught in some sort of github limbo.)
=> bug(query): justOne is actually single, and it defaults to false

docs/connections.jade
Simple correction for comment in documentation example
=> Fix comment typo in connect example

lib/drivers/index.js
**Summary**
See [5365](https://github.com/Automattic/mongoose/issues/5365)
Using expression in require doesn't work while packaging using Webpack. For those who doesn't intend to override the 'node-mongodb-native' that is included with mogoose, need not have to solve this problem of packaging if the default native driver is loaded first and then override a mongodb driver using the path provided in global.MONGOOSE_DRIVER_PATH
**Test plan**
Ran the full test, below is the result. I don't think the failure are related to the change in this PR.
1814 passing (3m)
5 failing
1) connections: useMongoClient/openUri (gh-5304) with mongoose.connect():
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
2) connections: …
=> Load bundled driver first to avoid packaging problem

docs/populate.jade
The statement "There are no joins in MongoDB" is outdated after the introduction of $lookup by MongoDB in version 3.2.
=> update MongoDB joins info in introduction

lib/schema.js
**Summary**
Currently `runSettersOnQuery` will not run on array with subdocs as this option is not propagated to the child schema, this PR just propagate this option (like it is currently done for the `strict` option)
for example:
```js
var UserSchema = new mongoose.Schema({
friends: [
{
name: {
type: String,
set: function(val) {
var res = '_' + val;
return res;
}
}
}
]
}, {collection: 'users', runSettersOnQuery: true});
var UserModel = mongoose.model('User', UserSchema);
// The setter of friends.name will NOT run
UserModel.find({"friends.name": "aaa"}).exec()
```
**Test plan**
Not sure where to add tests, didnt fins something similar
=> propagate runSettersOnQuery option to child schema

docs/populate.jade
The closing bracket becomes part of the url and takes to "File not found" page. Removed them, as they look unnecessary in the statement anyway.
=> fix wrong reference link to $lookup by removing brackets

lib/model.js
**Summary**
For huge numbers of documents to insert using Model.insertMany produces an ‘CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory’ error.
This PR solves this issue by using parallelLimit() to limit the number of operations per time to 1000. This fits well to the underlying  db.collections.insertMany which itself limit the number of DB operations to 1000 per time.
=> fix: limiting number of async operations per time in insertMany

lib/document.js
**Summary**
Fixes #5542 
Missing a clone() call to get virtual fields when we're applying getters.
**Test plan**
See #5542 -- with that test case, we're now seeing the correct output (the result is a pure JSON object).
=> Fix toJSON() when apply to a virtual populate -- missing a clone() call.

lib/index.js
**Summary**
When setting `mongoose.set('debug', true)`, the IDE indicates wrong argument type.
**Test plan**
Doesn't change any code.
=> fix: added type boolean to options documentation

lib/schema/objectid.js
Let me save a lot of time of our civilization :)
Sometimes we can try to generate an ObjectId or wrap an ObjectId key in somewhere in our code by using 'mongoose.Schema.ObjectId'.
Then we can spend minutes or hours to realize about what happened.
Thanks to this warning many developers may save time.
=> Adding warning regarding ObjectId usage

lib/model.js
Minor issue with readability in the docs, there's a follow up clarificaiton to the "almost*" clause on `findOne`, but the leading asterisk was being converted to a dot point. Took my a while to find what that "almost" refered to.
**Summary**
**Test plan**
=> Asterisk should not render as markdown bullet

lib/schema.js
setupTimestamp method has a misprint [on line 805](https://github.com/Automattic/mongoose/blob/master/lib/schema.js#L805)
When I've try to create `expireAfterSeconds` index on `updatedAt` field, declaring `expires` option in  `Schema` path: `updatedAt: {
type: Date,
expires: '1h'
}`, if `Shema` has `timestamps: true` option, path options replaces with default values and no index creates.
`> db['<collection name>'].getIndexes()
[
{
"v" : 2,
"key" : {
"_id" : 1
},
"name" : "_id_",
"ns" : "<collection name>"
}
]`
**Test plan**
Create model with `Shema`, contains `expires` option on `updatedAt` path:
`
mongoose.model('testCollection', new mongoose.Schema({
updatedAt: {
type: Date,
expires: '1h'
}
}, {
timestamps: true
}));`, and check for `expireAfterSeconds` index created:
`> …
=> fix(schema): replace mistype in setupTimestamp method

lib/query.js
**Summary**
calling model.replaceOne() with the option runValidator = true generates an error ("multi update only works with $ operators"), as when the validation is successful query.updateMany()  is called instead of query.replaceOne().
=> fix replaceOne with validators

package.json
mquery 2.3.1 uses debug 2.6.8 which has the following security advisory: https://nodesecurity.io/advisories/534
mquery 2.3.2 uses debug 2.6.9, which will resolve the security issue.
=> Update mquery dependency

.travis.yml, package.json
**Summary**
Currently there are no checks being done during CI to ensure dependencies are patched for known vulnerabilities. Since mongoose is such a widely-used project, it'd be useful for known vulnerabilities (as reported by tools like nsp or Snyk) to be highlighted quickly.
See #5675 and #5677 for one example of where it would have been useful to have a check like this. 
_An alternative_ (perhaps a better one) would be to integrate nsp's service (see https://nodesecurity.io/#pricing) as well as Snyk - https://snyk.io/
**Test plan**
The CI should pass (though currently it does not due to #5675 / #5677)
Signed-off-by: Dave Henderson <dhenderson@gmail.com>
=> Adding nsp check to the CI build

lib/aggregate.js, package-lock.json, test/aggregate.test.js
**Summary**
MongoDB v3.4 added the $addFields aggregation pipeline operator.
[https://docs.mongodb.com/manual/reference/operator/aggregation/addFields/](https://docs.mongodb.com/manual/reference/operator/aggregation/addFields/)
This PR adds a function `addFields()` to add this stage to the aggregation pipeline.
**Test plan**
Created a `addFields` test in `tests/aggregate.test.js`
=> Add $addFields pipeline operator via a Mongoose Function

lib/document.js
- `Document.depopulate()` now accepts an array of paths, e.g. `['some', 'path', 'other.path']`
- `Document.depopulate()` now accepts space separated paths, e.g. `'some path other.path'`
- Fixes #5797
**Summary**
The `populate()` methods in Mongoose accept arrays of paths, or a string with space separated paths. The `depopulate()` method on a document did not support that.
**Test plan**
Minor code change, not tested yet
=> Accept multiple paths or array of paths to depopulate

lib/services/model/applyHooks.js, test/docs/discriminators.test.js
After the recent changes to applyHooks() in pursue of  #5706  embedded discriminators recursively referencing themselves led to a call stack overflow. The problem was, that the childModel.discriminators tree is descended into before the hooks are applied on the actual discriminator model. That leads to the $appliedHooks attribute, which is to prevent these circular calls, never being set.
I swapped the order of applying the hooks to model first, discriminators second. To be sure there are no implications (because I am new to mongoose), I adapted the embedded discriminators test and wrote a test for these self-referencing/recursive discriminators.
=> Fixed call stack overflow when using recursive embedded discriminators

lib/model.js
Allow the virtual ref function to return an array of model names.
When referencing fields inside an array of subdocuments, the ref function was expecting a single string as the model name. This was very limiting when using dynamic references on an array of subdocuments.
To solve this I just did a simple type check. If the return value of the ref function is already an array, there's no need to change it. If the result is anything else the code resume with the previous behaviour. This enabled me to use something as:
```Javascript
const appointmentServiceSchema = new Schema({
serviceId:    Schema.Types.ObjectId,
serviceType:  String,
providerId:   Schema.Types.ObjectId,
providerType: String,
notes:        String,
cost:         Number
}, { toJSON: { virtuals: true } });
const …
```
=> fix(model): allow virtual ref function to return arrays

lib/schema/boolean.js, test/schema.boolean.test.js
**Summary**
See #5288, #5211 and #4245. Adds an option for schema type Boolean, called `strictBool` (disabled by default to ensure compatibility). When `strictBool:true` is passed, path input is restricted to `true`, `false`, `'true'`, `'false'`, `1`, `0`, `'1'` and `'0'`. Other values throw a `castError`. `null` is also accepted (as before) so the field can be marked as unspecified.
**Test plan**
0fb09d9 (second one) includes a test which verifies that the values we expect to be accepted are indeed accepted. (Need to test that other values are rejected?)
`npm test -- -g 'strictBool'`: test passed
**TODO**
- Document new option.
=> `strictBool` option for schema type boolean (clean)

lib/schema/boolean.js, test/schema.boolean.test.js
**Summary**
Same as #5344 but on Schema level.
**Test plan**
Include a test.
npm test -- -g 'strictBool': test passed
=> Added strictBool option to schema

lib/schema/array.js, package-lock.json, test/schema.validation.test.js
Fixed issues https://github.com/Automattic/mongoose/issues/5139. Fixes one test case related to 5139, but issue https://github.com/Automattic/mongoose/issues/5891 remains.
NOTE: this is technically a breaking change as the validation function now just uses `Array.isArray` versus previously it was checking for the existence of array & array.length. This will break for "array-like" objects which previously would've passed. e.g:
```
{
'0': 'test',
'length': 1
}
```
=> Array's `required` validation no longer requires a positive length.

lib/schema/date.js, test/schema.date.test.js
**Summary**
Fixes casting error for Strings, interpreting them as JavaScript natively does instead of accidentally as a unix timestamp.
See: https://github.com/Automattic/mongoose/issues/5395
=> fixes DateSchema behavior for strings

docs/2.7.x/docs/populate.html
**Summary**
The sentence in question is from here: http://mongoosejs.com/docs/2.7.x/docs/populate.html
"Our Person model has it's stories field set to an array of ObjectIds".
This pull request changes "it's" to "its".
=> Grammar change: it's --> its

package-lock.json, package.json
**Summary**
See https://boneskull.com/mocha-v4-nears-release/ for a list of breaking changes.
Main different is Mocha now requires Node.js v4+ and NPM 2+.
The `--exit` flag has been added to preserve the legacy timeout behavior.
**Test plan**
CI _should_ pass.
=> chore: update mocha to version 4.1.0

package-lock.json, package.json
**Summary**
resolves https://snyk.io/vuln/npm:marked:20170112
shouldn't have any impact on mongoose, still it's good to get the latest patches.
**Test plan**
`make docs`
View `docs/api.html`
=> chore: update acquit to version 0.5.1

.gitignore, package-lock.json, package.json
**Summary**
nyc is the official cli for istanbul 2.0
it adds better support for checking ES6+ code, and is actively supported and maintained.
**Test plan**
`npm run test-cov`
Expect a text view of coverage to be printed and for a `coverage/` folder to be generated with an HTML version.
=> refactor: replace istanbul with nyc

test/connection.test.js
**Summary**
The 'connection events' test cases were failing on my computer, because of the 25 seconds timeout. So I increased their timeout to 60s to avoid this problem on slower computers like mine. I also moved the `server.purge()` command to execute after `server.stop()` because it was causing a test failure when executed right after `server.start()`
**Test plan**
The 'connection events' test cases should pass now even on slower computers.
=> increasing timeout on connection events test cases.

lib/aggregate.js, package-lock.json, test/aggregate.test.js
**Summary**
Using options when executing an aggregate doesn't work and they could not be set
Code (from documentation)
```
// Set the `allowDiskUse` option
var agg = Model.aggregate(..).option({ allowDiskUse: true }); 
```
*Current*
`agg.options; // `{ '0': undefined }``
Fix
`agg.options; // `{ 'allowDiskUse': true }``
**Test plan**
Now when an aggregate is running as the following and setting mongoose to debug code, the options are set propertly
=> fix bug: Using options in aggregates doesn't set anything

lib/schema.js, test/docs/defaults.test.js, test/document.test.js
**Summary**
Sometime after mongoose ~4.6, schemas created with the `timestamps` began overwriting schema defaults in nested properties. For example, schema `{ name: String, misc: { isHappy: { type: Boolean, default: true } }` defined with timestamp `misc.updatedAt` would not instantiate new models with `misc.isHappy` defined.
**Test plan**
Unit test "Declaring defaults in your schema with timestamps defined" defined in `defaults.test.js` captures the logic executing successfully.
Other unit tests pass with this change in place (at least locally for me).
=> Do not overwrite default values in schema when nested timestamps are provided.

lib/model.js, lib/services/model/discriminator.js, lib/services/populate/getSchemaTypes.js, test/helpers/populate.getSchemaTypes.test.js, test/model.populate.test.js
Re: #5970 
This is a substantial change, so I want to put in a PR and review the changes more later. In particular, this change makes it so that `populate()` searches schemas on every doc, rather than once before looking through every doc.
=> handle populating embedded discriminator paths

docs/models.jade, docs/schematypes.jade, docs/subdocs.jade
Sorry for doing this more than once. I wanted to get it right as it's my first contribution.
This fixes 3 of the 4 files mentioned in #6038 removing the :js markdown and replacing it
with backticks (adding :markdown where needed).
This was done to restore formatting to the code blocks on these specific pages in the documentation.
here are screen shoots of the pages in this commit that have been rendered via:
```
make docclean
make gendocs
```
and served via:
```
node static.js
```
=> updating jade files to fix #6038

lib/index.js
**Summary**
This will allow lint tools to know the type of `mongoose.model`.
**Test plan**
I should just work :smile:
=> Add return type in mongose.model docs

lib/document.js
In `_getPathsToValidate` the `doc.modifedPaths()` function is called for every subDoc. the result of the function is same, thereby wasting time and computation to calculate it for every subDoc. This becomes a time hog in documents with a lot of `EmbeddedDocuments`
=> [optimization]re-use the modifiedPaths list

lib/utils.js
**Summary**
Add check when respecting object's `valueOf` to ignore dates. This prevents dates being cast as timestamps when saved to the database as reported in #6145, where `Date.valueOf` returns a timestamp.
**Test plan**
The script described in #6145 functions as expected
=> Prevented converting of dates to timestamps when respecting valueOf()

docs/api.html, lib/cursor/AggregationCursor.js, lib/cursor/QueryCursor.js, lib/query.js
**Summary**
Removes dead link to Strongloop from docs.
**Test plan**
Maybe we should quit referring to just "Streams 3" and instead say
something like "Streams 3 API, the Node.js streams interface since Node.js 6"
=> docs: remove dead link to Strongloop blog post.

migrating_to_5.md
this is also wrong in the documentation http://mongoosejs.com/docs/api.html#Aggregate (or at least not documentated that in mongoose 5 / useMongooseAggCursor flag you have to use eachAsync instead of each)
=> migration doc fix: correct syntax is eachAsync

lib/model.js, lib/queryhelpers.js, lib/schema/array.js, lib/schema/documentarray.js, lib/schema/embedded.js, lib/services/model/discriminator.js, lib/types/documentarray.js
Initial commit.
Allows to make model.discriminator call
using 3rd argument, tied to discriminatorKey Value
Population also works
Changes made from->to using parts of, but no model naming changes!
https://gist.github.com/wentout/2171022fe597e5b2564435d6b44eac49
**Summary**
It probably solves parts of this issue, and I able to add naming composition, check the gist above
https://github.com/Automattic/mongoose/issues/2596
**Test plan**
I made no hard changes, only interface addition is **value**, which means what to be tied to the discriminator key. And, as this is a last parameter, I thought of no additional tests. However I'm not very sure. It works in my environment for my current task. If you can give me a way, I will try to understand what I was able to break with this change.
=> For https://github.com/Automattic/mongoose/issues/2596

docs/guide.jade, lib/schema.js
From #5910 on `emitIndexErrors` option is no longer used.
However on [the reference for Schema](http://mongoosejs.com/docs/api.html#model_Model.ensureIndexes) and [guide](http://mongoosejs.com/docs/guide.html#options) still both mentions `emitIndexErrors` although the anchor links are still there, causing confusion...
This PR changes the JSDoc and the Jade file for the guide. Generated documents are not checked in.
Closes #6181
=> Closes #6181, reflecting changes in the emitIndexError flag

lib/connection.js, lib/drivers/node-mongodb-native/connection.js, test/connection.test.js
**Summary**
- Replace ```connection.otherDbs``` array with a hashmap
- Make the ```useDb``` API use it as a cache
See #3302
**Test Plan**
```
it('cache connections to the same db', function() {
var db = start();
var db2 = db.useDb('mongoose-test-2');
var db3 = db.useDb('mongoose-test-2');
assert.strictEqual(db2, db3);
db.close();
});
```
=> Cache connection in useDb, replace connection.otherDbs array with a hashmap

lib/connection.js
fixes documentation link in connection deprecation message. #6217 
the link used to point to the current docs, now it should point to the 4.x docs.
=> fix url in useMongoClient error message #6217

docs/source/api.js
While looking at createConnection for #6217, I noticed that createConnection is missing from the 5.x api docs. I added index.js to the files array in docs/source/api.js at the top to mimic it's previous placement in the 4.x docs. 
tested with make docclean && make gendocs && node static.js
=> add index.js to api docs

lib/aggregate.js, test/aggregate.test.js
MongoDB 3.6 added the hint option to aggregations. you can currently add a hint with the .option method, but having a convenience method like the one for allowDiskUse makes sense to me.
I also updated the helper method formerly known as onlyTestMongo34. I made the version it looks for variable and changed the name to reflect the new behavior.
Test expects that the resulting array of docs is sorted according to the hint.
=> adding .hint to aggregate for 6251

lib/schema.js, test/schema.timestamps.test.js
**Summary**
`timestamps` were being set for `save`, `update` and `findOneAndUpdate` methods, but not for `updateOne`.
=> Set timestamps automatically by using updateOne method

lib/schema/array.js, migrating_to_5.md
Last week I was migrating my project to mongoose 5. The migration guide was very helpful!
But unfortunately I knew the new `required` behavior for arrays after it reached production. :disappointed:
Later I saw that it is in fact in the change log. But I think this must be in the migration guide because of its relevance.
Also fixing the outdated method documentation.
=> Document new behavior of required validator for arrays

lib/connection.js, lib/drivers/node-mongodb-native/connection.js
Fix #6286
Re: https://github.com/mongodb-js/connect-mongodb-session/issues/50#issuecomment-373041196
@mbroadst I'd appreciate some feedback on this one since it digs into driver internals.
=> refactor(connection): use `client.db()` syntax rather than double-parsing the URI

docs/source/api.js
#6314 shows an example of one of the links on the api docs not being formatted correctly. [This gist](https://gist.github.com/lineus/746d25bdb63b723ca9abc20fe6fa0459) shows that adding these specific lines back into docs/source/api.js causes the markdown to get parsed again, thereby rendering the links correctly.
I verified that the links get rendered correctly with `make gendocs && node static` and compared the effect of these three lines to the intent of the commit in which they were deleted, and they do not appear to effect the create method's api documentation.
=> putting 3 lines back to fix #6314

lib/schema/decimal128.js, test/types.decimal128.test.js
details demonstrated in #6331 . **TL;DR decimal128 can only natively convert from a string. This adds a check for typeof 'number', and if so, converts number -> string -> decimal128.**
There was no test/types.decimal128.test.js, and all of the existing tests involving decimal128 are really testing other feature's compatibility with decimal128. I didn't add a specific test for this, but I'm happy to create a types test file if you like. This PR did not cause any existing tests to fail.
```
issues: ./6331Populate.js
added 1 documents.
issues: ./6331.js
{ _id: 5acf892f4577ef7d036d099b,
__v: 0,
amount: NaN,
id: '5acf892f4577ef7d036d099b' }
issues:
```
```
issues: ./6331.js
{ _id: 5acf892f4577ef7d036d099b,
amount: 10000,
__v: 0,
id: '5acf892f4577ef7d036d099b' }
issues:
```
=> adding ability for casting from number to decimal128

docs/schematypes.jade
**Summary**
There is mention of `minlength` and `maxlength` built-in validators for String type on the [Validation page](http://mongoosejs.com/docs/validation.html#built-in-validators).
But at the same time, these are absent in the list of validators for String on the [SchemaTypes page](http://mongoosejs.com/docs/schematypes.html).
Seemed like a good idea to add them to the list.
**Test plan**
```
make docclean
make gendocs
node static.js
```
Looks like: [screenshot](https://monosnap.com/file/pt75oeV957OIR8ySiwPYUvOY9UEVeu.png)
=> Docs: Update schematypes.jade

lib/document.js
**Summary**
According to [migration](https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md) guide: 
> ### `numAffected` and `save()`
>
> `doc.save()` no longer passes `numAffected` as a 3rd param to its callback.
This change fixes incorrect example from generated API documentation here: http://mongoosejs.com/docs/api.html#document_Document-save
=> Removing mention of "numAffected" from document.save example

docs/layout.jade, docs/source/api.js
**Summary**
The Aggregation and Query Cursor docs aren't included in the API docs. This change adds them in the docs, and the links in the sidebar.
make docclean && make gendocs && node static ( verified visually )
=> adding aggregation/query cursor to api docs #6344

.travis.yml, lib/document.js, lib/drivers/node-mongodb-native/collection.js, lib/internal.js, lib/model.js, lib/query.js, lib/services/query/completeMany.js, test/model.test.js
Re: #6362 
There's two primary changes here:
1) Models now have a `startSession()` function that returns a promise that resolves to the underlying `ClientSession`. You can pass the `session` option to `Model.find()`, `Model.updateOne()`, etc.
2) Mongoose documents now have a `$session()` function that tracks the session associated with the document. If you load a document using `Model.findOne({}, null, { session })`, that document will track `session` and use that same session when you `save()` the document by default.
@mbroadst @daprahamian any thoughts you have would be much appreciated.
=> Session support for docs

migrating_to_5.md
**Summary**
Updates Migrating-to-5 guide to document that passwords in connection strings need to be encoded.
**Details**
In addition to domain sockets, certain passwords may trigger
connection failures in Mongoose 5. This can especially be a problem
if you use simpler passwords in testing and complex ones in production!
Links to related docs and a code sample to resolve the issue are
provided.
Related issue: https://github.com/Automattic/mongoose/issues/6044
=> docs(migration): certain in passwords may cause connection failures

lib/index.js, test/index.test.js
**Summary**
I've...
- fixed the inline documentation for the ``mongoose.pluralize(..)`` function
- added a test, checking the default pluralize function returned by said function
- added a test for setting a custom pluralization function
**Test plan**
**``$ npm run test``**
```
> mongoose@5.0.18-pre test /home/sk/mongoose
> mocha --exit test/*.test.js test/**/*.test.js
```
*...*
```
1867 passing (56s)
8 pending
```
=> Add 2 tests around mongoose.pluralize(..); fix docs

lib/schema/decimal128.js, test/types.decimal128.test.js
This change makes Decimal128 casting honor the valueOf method like Number casting does after #6299.
After adding change, no current tests broke. Added a failing test to types.decimal128.test.js and made it pass:
```
mongoose>: npm test -- -g 'gh-6418'
> mongoose@5.0.18-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6418"
!
0 passing (215ms)
1 failing
1) types.decimal128
uses valueOf method if one exists (gh-6418):
AssertionError [ERR_ASSERTION]: '10.123' === 'xyz'
-10.123
+xyz
at Decorator._callFunc (node_modules/empower-core/lib/decorator.js:110:20) …
```
=> fixes #6418

lib/utils.js, test/model.populate.test.js
As demonstrated by #6451, when sub-populating with a match in the parent, the match wasn't applied. If both a match object and populate object are present on the parent, we need to call populate with 1 arg.
*You can see below the match doesn't get applied to `others.find()` and `anothers.find()` is called when it shouldn't be.*
```
issues: ./6451.js
Mongoose: anothers.insertOne({ _id: ObjectId("5af58aeca0761ee9eb8a1e15"), name: 'testing', __v: 0 })
Mongoose: others.insertOne({ _id: ObjectId("5af58aeca0761ee9eb8a1e16"), online: false, value: 'woohoo', a: ObjectId("5af58aeca0761ee9eb8a1e15"), __v: 0 })
Mongoose: tests.insertOne({ o: [ ObjectId("5af58aeca0761ee9eb8a1e16") ], _id: ObjectId("5af58aeca0761ee9eb8a1e17"), visible: true, name: 'Billy', __v: 0 })
Mongoose: tests.findOne({ visible: …
```
=> fixes #6451 only call populate with full param sig when match is not present

lib/error/version.js, lib/model.js, test/versioning.test.js
Fix #6433
**Summary**
This PR fixes #6433 by adding a `modifiedPaths` property to `VersionError` in order to make debugging easier.
**Test plan**
I've updated an existing test and verified that it passes.
=> Add modified paths to VersionError

docs/guide.jade, lib/schema.js, lib/types/buffer.js
docs change for #6440 
This change adds notes to the schema and api docs that attempt to make clear the distinction between `Schema.methods` and `Schema.method()`.
=> fixes #6440 add notes in api and guide about schema.methods object

lib/services/query/castUpdate.js, test/query.test.js
fix for #6439.
added co to query.test.js and copied the same test from v5. No existing tests broke with this change and made new test fail, then pass.
=> add fix for #6439 to 4.x

lib/aggregate.js, test/aggregate.test.js
As pointed out in #6474, replaceRoot can also take an expression that results in a document. This change retains the current ability to pass a string that refers to a field in the document, but also allows us to pass in an object ( expression ). 
All current tests pass, added a failing test, made it pass:
```
mongoose>: npm test -- -g gh-6474
> mongoose@5.1.2-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6474"
!
0 passing (131ms)
1 failing
1) aggregate:
Mongo 3.4 operators
replaceRoot
works with object (gh-6474):
TypeError: newRoot.charAt is not a function
at …
```
=> fixes #6474 let aggregate.replaceRoot accept objects as well as strings

lib/query.js, test/query.toconstructor.test.js
As described in #6455, custom queries don't currently inherit the model's middleware. This change makes CustomQuery inherit from model.Query instead of Query which fixes this.
All current tests pass, made a failing test, then made it pass:
```
mongoose>: npm test -- -g 'gh-6455'
> mongoose@5.1.2-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6455"
!
0 passing (463ms)
1 failing
1) Query:
toConstructor
gets middleware from model (gh-6455):
AssertionError [ERR_ASSERTION]: 'Romero' === 'romeo'
-Romero
+romeo
at Decorator._callFunc …
```
=> fixes #6455 CustomQuery should inherit from model.Query

lib/model.js
**Summary**
As discussed in [issue #6461](https://github.com/Automattic/mongoose/issues/6461#issuecomment-389696817).
=> fix(model): skip redundant clone in insertMany

lib/document.js, test/document.test.js, test/model.test.js
As demonstrated in #6477, a document returned from a query, with an unset field that defaults to false, subsequently saved would not add the default to the document. This change aligns the behavior with other path defaults.
all current tests pass, made a failing test, then made it pass.
```
mongoose>: npm test
> mongoose@5.1.2-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․,․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․ …
```
=> fixes #6477 prevent default falses from being skipped by $__dirty

lib/types/map.js, test/types.map.test.js
As described in #6478 MongooseMap.toJSON() currently returns a Map. This change results in an object of the map's key value pairs being returned instead.
all current tests pass, added a failing test, made it pass:
```
mongoose>: npm test -- -g 'gh-6478'
> mongoose@5.1.2-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6478"
!
0 passing (130ms)
1 failing
1) Map
toJSON seralizes the map (gh-6478):
AssertionError: { testing: 123 } deepEqual { testing: 456 }
{
-  "testing": 123
+  "testing": 456
}
at Context.<anonymous> (test/types.map.test.js:435:12)
npm …
```
=> fixes #6478 make MongooseMap.toJSON return an object

lib/services/populate/getVirtual.js, test/model.populate.test.js
demonstrated in #6487 
.$nestedSchemaPath wasn't getting set properly in getVirtual, resulting in the failure.
```
mongoose>: npm test -- -g gh-6487
> mongoose@5.1.3-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6487"
!
0 passing (583ms)
1 failing
1) model: populate:
github issues
populates an array of objects
handles embedded discriminator (gh-6487):
AssertionError [ERR_ASSERTION]: 'Test name' === 'zyx'
-Test name
+zyx
at test/model.populate.test.js:6532:18
at Generator.next (<anonymous>)
at …
```
=> fixes #6487 - fix getVirtual, set $nestedSchemaPath to full value of nestedSchemaPath

.travis.yml, package-lock.json, package.json
**Summary**
NPM 6+ prints potential security alerts on install.
The issues flagged don't appear to directly impact mongoose.
This PR resolves the following alerts:
From lodash:
https://nodesecurity.io/advisories/577 
From nyc:
https://nodesecurity.io/advisories/577
https://nodesecurity.io/advisories/157
From nsp ([note NSP is being replaced by `npm audit`](https://blog.npmjs.org/post/173719309445/npm-audit-identify-and-fix-insecure)):
https://nodesecurity.io/advisories/593
https://nodesecurity.io/advisories/566
https://nodesecurity.io/advisories/532
https://nodesecurity.io/advisories/612
**Test plan**
Tests pass, these are mostly test dependencies.
=> Update lodash and nsp

docs/faq.jade, lib/error/duplicateSave.js, lib/error/index.js, lib/error/parallelSave.js, lib/internal.js, lib/model.js, test/model.test.js
This is to address throwing an Error when saving in parallel as discussed in #6456 and #4064 . It's not ready to merge but I wanted to get a sanity check on the logic of the first draft and open the discussion sooner rather than later. All existing/new tests pass with this change ( now ).
=> fixes #6456, fixes #4064 - Throw error when saving the same doc instance more than once in parallel

package-lock.json, package.json
@solotoo pointed out in #6505 that we are dependent on an old version of the async package. After looking at the [changelog](https://github.com/caolan/async/blob/master/CHANGELOG.md) for async, there have been both bug fixes and performance improvements for queue, which could have a positive impact on folks who use eachAsync.
all tests pass with the newer version of async:
```
mongoose>: rm -rf node_modules
mongoose>: npm install >/dev/null 2>&1
mongoose>: grep version node_modules/async/package.json
"type": "version",
"version": "2.6.1"
mongoose>:
mongoose>: npm test
> mongoose@5.1.3 test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js …
```
=> fixes #6505 bump async version to latest

lib/services/query/castUpdate.js, test/model.update.test.js
As demonstrated by #6532, when $set is run with an object instead of an array, the object is stored in the db without being cast to an array. This change separates $set from the other ops in castOps and just returns the cast value instead of potentially only returning the first element.
I created a failing test, made it pass, all current tests pass:
```
mongoose>: npm test -- -g 'gh-6532'
> mongoose@5.1.3 test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6532"
!
0 passing (544ms)
1 failing
1) model: update:
bug fixes
casts objects to array when clobbering with $set (gh-6532): …
```
=> fixes #6532 - dont treat $set the same as the other ops in casting of update docs

lib/utils.js, test/model.populate.test.js
As demonstrated in #6528, when sub populating with options, the options aren't applied. 
created a failing test, made it pass, all current tests pass:
```
mongoose>: npm test -- -g 'gh-6528'
> mongoose@5.1.4-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6528"
!
0 passing (609ms)
1 failing
1) model: populate:
github issues
populates an array of objects
handles subpopulation with options (gh-6528):
AssertionError: 2 === 1
-2
+1
at test/model.populate.test.js:6507:18
at next (native)
at onFulfilled (node_modules/co/index.js:65:19)
npm ERR! Test failed. …
```
=> fixes #6528 honor options when subpopulating

docs/connections.jade
**Summary**
The anchor on the title of Connection Pools in the documentation doesn't work as it does not contain a hash. This PR adds in the hash so that it is the correct URL and works like other anchors throughout the docs. 
I was browsing the docs and wanted to send a link to the Connection Pool section, however clicking the title took me to a 404 page. 
**Test plan**
Visit the connections doc page and click on the Connection Pool title and ensure that it links correctly.
=> Fix broken Connection pools anchor in docs

docs/faq.jade
Whoops. I forgot to add the hr tag in the faq for parallel saves. 
I also added one for something to add. I'm not sure if you want one there, but I liked the look of it. I'm happy to remove it if you don't think it's necessary or looks weird.
=> adding hr tags for parallel save error and add something

lib/model.js, test/model.populate.test.js
As demonstrated in #6554, the ref: as a function doesn't work. This changes adds the capability.
made a failing test, made it pass, all current tests pass 
```
mongoose>: npm test -- -g 'gh-6554'
> mongoose@5.1.5-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6554"
!
0 passing (542ms)
1 failing
1) model: populate:
lean + deep populate (gh-6498)
populates virtual of embedded discriminator with dynamic ref (gh-6554):
AssertionError [ERR_ASSERTION]: 'Test name' === 'Rachmaninoff'
-Test name
+Rachmaninoff
at test/model.populate.test.js:6888:16
at …
```
=> fixes #6554 - add virtual ref function ability to getModelsMapForPopulate

lib/model.js
Raised in #6589, projections is a valid option in the native driver. Both `findAndModify()` and `findOneAndDelete()` take the projection option. Adding this to the docs.
=> fixes #6589 add projection option to docs for findOneAnd{Remove,Delete}

lib/model.js, lib/queryhelpers.js
The feature for simply use of discriminators.
Sample of use:
```javascript 
UserSchema.pre('createModel', function () {
if (this && typeof this.role !== 'undefined' && this.role) {
this.kind = this.role.charAt(0).toUpperCase() + this.role.slice(1) + 'User'
}
})
```
=> The feature for simply use of discriminators.

lib/document.js, lib/model.js
Inspired by #6603, this change further codifies the return value of undefined when using `.save()` with a callback.
=> docs #6603 add undefined return to {model,doc}.save

lib/model.js, test/model.test.js
As demonstrated in #6611, calling save in a post save hook currently throws a parallel save error. This change allows calling save from within a post save hook.
made a failing test, made it pass, verified all current tests pass:
```
mongoose>: npm test -- -g 'gh-6611'
> mongoose@5.1.7-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6611"
!
0 passing (505ms)
1 failing
1) Model
bug fixes
allows calling save in a post save hook (gh-6611):
Uncaught ParallelSaveError: Can't save() the same doc multiple times in parallel. Document: 5b2e26c6a4d63813a90483b7
at …
```
=> fixes #6611 set saving to undefined before emitting save

lib/model.js, test/model.populate.test.js
**Summary**
This fixes the issue reported in  https://github.com/Automattic/mongoose/issues/6612.
When a dynamic ref function returned an array containing more than 1 model, the ```getModelsMapForPopulate``` function was unable to find the correct model because the returned array was nested within ```modelNames```. When the tried to look up the model, it was unable to find a model that matches the entire array thus throwing an error.
This pull requests updates the logic so that the ```normalizedRef``` is concatenated instead to prevent nesting.
**Test plan**
Added a test which failed:
```
npm test -- -g 'gh-6612'
> mongoose@5.1.7-pre test /Users/mac/Documents/code/playground/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6612"
Please set the …
```
=> fixes #6612 - allow dynamic ref to handle >1 model getModelsMapForPopulate

test/docs/validation.test.js
The documentation about the caveats when using update validators (`runValidators`) is excellent.
But I found the section on `required` fields to be overkill, to the point of confusion.
It seems obvious to me that validation will not run on a field which we are not updating. In fact, that is covered by the next section, "Update Validators Only Run On Specified Paths".
So for the sake of brevity, I suggest removing that section. But I have preserved a paragraph that lets developers know that `$unset` does perform validation on required fields.
=> Minimize docs about $unset update validation

lib/types/documentarray.js, test/model.test.js
**Summary**
fix for issue #6635 , if an object had atomics and calling save() on that object failed for some reason, the atomics array of EmbeddedDocuments would already have been converted to POJOs.  So if you tried to save it again it would try to call .toObject() on the POJO which would throw a TypeError.
**Test plan**
Reran @dbellavista gist located here: https://gist.github.com/dbellavista/46df766acc09695f448be339ca96632e
Wrote a new test: 'no TypeError when attempting to save more than once after using atomics':
```
it('no TypeError when attempting to save more than once after using atomics', function(done) {
const M = db.model('M', new Schema({
test: {type: 'string', unique: true},
elements: [{
el: {type: 'string', required: true}
}]
}));
const a = new M({
test: 'a',
elements: …
```
=> fix for TypeError being thrown when calling save() more than once if the object being saved has atomics

lib/connection.js
as demonstrated in #6651, #6648, #6649 and addressed in  https://github.com/mongodb/node-mongodb-native/pull/1771 the new url parser is broken for the moment. this PR forces useNewUrlParser to false.
all current tests pass ( minus deprecation warnings )
[update] removed 6647 from above list as I'm not certain the new url parser will *ever* add the default port implicitly.
=> fixes #6651 dont use newUrlParser until next driver update

lib/model.js, test/model.populate.test.js
As demonstrated in #6669, if you want to reuse a subSchema with a refPath in multiple parent schemaPaths, making the refPath variable requires some gymnastics. This change allows refPath to accept a function that receives the current path as it's 2nd parameter which allows us to dynamically generate the dynamic ref. I included the first parameter as doc in anticipation of folks who use arrow functions that need access to the doc. 
added a failing test, made it pass, all current tests pass.
```
mongoose>: npm test -- -g 'gh-6669'
> mongoose@5.2.2-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6669"
Sharding must already …
```
=>  add ability to define refPath as a function

docs/faq.jade
Currently the FAQ says `You can set the default of the array to a function that returns null` but the example returns undefined. I think it would be useful to have both distinct possibilities in the FAQ.
make docclean && make gendoc && node static
=> fix existing faq for array-defaults 

lib/model.js, test/model.populate.test.js
As demonstrated in #6618, if a getter is defined on the path used in a population, that getter isn't called during population. This change calls the getter, thereby using the potentially mutated value in the subsequent find query to retrieve the foreign doc.
@vkarpov15 This part of the change feels wrong to me:
```
ret = localFieldGetters[0].call(doc, doc[localField]);
```
I've never seen a situation where a path had multiple getters defined, is it safe to always call the first getter in this case?
Made a failing test, made it pass, all existing tests pass:
```
mongoose>: npm test -- -g 'gh-6618'
> mongoose@5.2.2 test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6618" …
```
=> if a getter is defined on the localField, use it when populating

lib/model.js
rawResult option on Model.insertMany currently has `false` twice. It should read, if `true` raw results will be returned.
make docclean && make gendocs && node static
=> fix Model.insertMany rawResult option in api docs 

lib/model.js, test/model.populate.test.js
#6726 shows that the value of `this` in the path getter from #6702 isn't a Model instance. I couldn't find precedent for calling `hydrate` in this context, but this was best solution I could come up with. I'll sleep on it and take another look in the morning. If this isn't as off the wall as it feels....
I added a failing test, made it pass, all current tests pass.
```
mongoose>: npm test -- -g gh-6726
> mongoose@5.2.4-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6726"
(node:20855) DeprecationWarning: current URL string parser is deprecated, and will be removed in a …
```
=> fixes #6726 pass Model instance as context to applyGetters

test/document.test.js
In 5.1.3 changes were made to `$set` to allow positional syntax for embedded discriminators. As #6738 demonstrates, this also affected nested Mixed schema paths (**in a good way**). This change adds a test for a nested Mixed path to ensure that the behavior remains consistent going forward.
added a failing test, made it pass.
```
mongoose>: npm test -- -g gh-6738
> mongoose@5.2.5-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6738"
(node:3620) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass …
```
=> fixes #6738 adding a test to cover $set with positional syntax on nested mixed paths

docs/index.jade
**Summary**
Whilst the existing code works, I thought maybe since `Schema` is a constructor, it makes sense to use the `new` operator. It also seems more consistent with other examples in the documentation :)
**Test Plan**
I don't think this requires any tests ?
=> Prefix mongoose.Schema call with new operator

lib/index.js
per my comment on #6756 this change removes the old parameter signature from the createConnection jsdoc example. 
I'm also thinking we could change line 420 in connection.js from
```
if (options) {
```
to
```
if (options && typeof options === 'object') {
```
but I'm not sure if we should throw an error instead if options isn't an object? @vkarpov15, what do you think?
all tests pass.
=> update jsdocs for createConnection

lib/query.js
Fix #6785 select fields starting with `+` is not working as described See #6785 
Also propagate readConcern options from parent query like readPreference does in #5460
=> Fix #6785 and propagate readConcern options in populate from parent query

lib/helpers/query/castUpdate.js, test/model.update.test.js
as demonstrated in #6768, when $push-ing an array into a multidimensional array, the $each should not be implicitly added. 
```
mongoose>: npm test -- -g 'gh-6768'
> mongoose@5.2.7-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6768"
(node:7202) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. Touse the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
!
0 passing (587ms)
1 failing
1) model: update:
bug fixes
doesn't add $each when …
```
=> Fixes #6768 don't use $each when pushing an array into an array

lib/model.js, test/docs/transactions.test.js, test/model.test.js
**Summary**
1. `insertMany` and `updateMany` support options parameter, so I think `deleteMany` should support too to avoid confusion
2. This will also fix #6805
**Test plan**
Tests are included in the `test/model.test.js` and `test/docs/transaction.test.js`
```sh
╭─Fonger@Fongers-Macbook  ~/opensource/mongoose  ‹delete-many-options›
╰─$ mocha test/docs/transactions.test.js                                    1 ↵
(node:31830) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
․․․․․․․․
8 passing (1s)
```
Locally passed
=> feat(model): support options in `deleteMany`

test/model.test.js
**Summary**
Session tests currently use `session.serverSession.lastUse` time to verify that the session are used in a query.
```js
assert.ok(session.serverSession.lastUse > lastUse);
```
However, Date in JavaScript only support millisecond precision.
If it run too fast, the date may be the same.
I notice that many tests fail on CI because of this
This pull request add delay between requests with 1 millisecond to prevent this
```
1) Model
bug fixes
3.6 features
sessions (gh-6362)
sets session when pulling a document from db:
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
func.apply(thisObj, args)
-false
+true
at Decorator._callFunc (node_modules/empower-core/lib/decorator.js:110:20)
at Decorator.concreteAssert …
```
=> test(model): add delay to session tests to improve pass rate

lib/model.js
**Summary**
This should fix #6819 and also recreate index on `expireAfterSeconds` option change. Added this key to the values to check for when syncing indexes.
=> Fixes #6819 - `Model.syncIndexes()` checks for `expireAfterSeconds` option

test/aggregate.test.js, test/model.querying.test.js, test/query.cursor.test.js
This test fails *frequently*. You can see it in almost every travis build that fails.
Like this one: https://travis-ci.org/Automattic/mongoose/jobs/412335127
[![travis-fail-1](https://user-images.githubusercontent.com/5862369/43701213-f0424a4a-9987-11e8-9d67-b7137ce3530c.png)](https://travis-ci.org/Automattic/mongoose/jobs/412335127)
```
1) model: querying:
with previously existing null values in the db:
Uncaught AssertionError: 0 == 3
-0
+3
at Decorator._callFunc (node_modules/empower-core/lib/decorator.js:110:20)
at Decorator.concreteAssert (node_modules/empower-core/lib/decorator.js:103:17)
at Function.decoratedAssert [as equal] (node_modules/empower-core/lib/decorate.js:51:30)
at test/model.querying.test.js:1983:16 ......
```
The description of mocha output is …
=> greatly improve travis-ci pass rate

.travis.yml, test/connection.test.js, tools/checkNodeVersion.js
**Summary**
- Only run eslint on node.js 10 because there's no need to lint on every version
- Run eslint in parallel so it can help us to distinguish lint error from build failure and also speed up CI
- Fix flaky connection test
[Example travis-ci output:
**Future Work**
Maybe we can run `npm audit` on node.js 10 (because only npm@6+ support it)
However, `npm audit` currently cannot ignore devDependencies
=> Run linter in parallel and only on node.js 10

migrating_to_5.md
**Summary**
This adds the `objectIdGetter` option to the migration docs.
We have functions like this sprinkled throughout our code:
```js
async doThingWithUser(userOrId) {
let user;
if(userOrId._id) {
user = userOrId;
} else {
user = await User.findById(userOrId);
}
...
}
```
So when I read this migration guide I was in a bit of a panic until I found this option.  -_-
**Test plan**
None required.
=> docs: Add `objectIdGetter` option to migrating_to_5.md

docs/populate.jade
Update example of calling '.execPopulate' method with a working example. 
The method doesn't take in any arguments, whereas the example shows that it does, leading to a never-called 'next' method. Use of 'then' works as expected and is the example provided in other parts of the documentation.
Pull request corrects the example code.
=> Update code example in Populate

lib/error/version.js, lib/model.js, test/versioning.test.js
backport to 4.x of dd2483d1167f0878ca075835858d5708dfc307ac
**Summary**
Backports more informative VersionError that includes version to 4.x branch
**Test plan**
=> feat(error): add version number to VersionError (4.x)

lib/query.js, test/query.test.js
as described in #6854, it would be nice to have a method to easily change the current query condition ( example in issue ). 
```
mongoose>: npm test -- -g 'gh-6854'
> mongoose@5.2.8 test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6854"
(node:2675) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
!
0 passing (151ms)
1 failing
1) Query
setQuery
replaces existing query with new value …
```
=> fixes #6854 add Query.prototype.setQuery()

docs/3.0.x/docs/api.jade, docs/3.0.x/docs/index.jade, docs/3.0.x/docs/layout.jade, docs/3.1.x/docs/api.jade, docs/3.1.x/docs/index.jade, docs/3.1.x/docs/layout.jade, docs/3.2.x/docs/api.jade, docs/3.2.x/docs/index.jade, docs/3.2.x/docs/layout.jade, docs/3.3.x/docs/api.jade, docs/3.3.x/docs/index.jade, docs/3.3.x/docs/layout.jade, docs/redirect.jade, index.jade
re: #6856
Does not change html files according to [Contributing.md](https://github.com/Automattic/mongoose/blob/master/CONTRIBUTING.md) Guide. 
We should run `make docclean && make gendoc` in `gh-pages` branch
=> docs(website): fix mixed content warning on https://mongoosejs.com

lib/schema/array.js, test/model.test.js
Fix #6840 
**Summary**
DocumentArray ---(this=doc)---> Array ---(no this bind)---> Custom Default Function
**Test plan**
included in this pull request
=> Fix `this` scope of default functions for DocumentArray and Array

lib/model.js, test/connection.test.js, test/model.test.js
**Summary**
`save()` doesn't work with write concern. Only legacy `safe` options are supported.
(IMO, I think `safe` should be deprecated in the next major release of mongoose) 
**This bug is critical because it makes mongoose lack of durability guarantee.**
Fixes #6862 and now write concern options are correctly propagated to mongodb.
**Test plan**
Add tests for both `writeConcern` defined in schema level and in save(`options`).
1 test to check if `w > 1` trigger error when topology of server is not a replica set
2 tests are skipped by default because they require replica sets and special setup to trigger write concern timeout. These 2 tests passed on my computer.
See the comments in code for details.
=> Correctly propagate write concern options in save()

lib/aggregate.js, test/model.test.js
Fixes #6885 and also replace `slave` to the correct term `secondary`
=> fix(aggregate): support session chaining correctly

lib/aggregate.js, test/aggregate.test.js
```js
Model.aggregate().redact({
$cond: {
if: { $eq: [ '$level', 5 ] },
then: '$$PRUNE',
else: '$$DESCEND'
}
})
```
`$redact` often comes with `$cond` operator, If 3 arguments are supplied,
Mongoose will wrap them with `if`-`then`-`else` of `$cond` operator respectively
```js
Model.aggregate().redact({ $eq: ['$level', 5] }, '$$PRUNE', '$$DESCEND')
```
```js
Model.aggregate().readConcern('m'); // specify majority read concern
```
Included in CI test
=> Add redact and readConcern helper to Aggregate

lib/index.js, lib/model.js, lib/query.js, test/model.findOneAndUpdate.test.js
**Summary**
Only change internal call and options.
If a user calls the deprecated API or use deprecated options on purpose, mongoose should still show the deprecation message. That's why CI tests have so many deprecation warning.
IMO, `useFindAndModify` and `overwrite` options should be deprecated in the next major release
EDIT after review from vkarpov15:
For your own good, please set to false explicitly to suppress deprecation warning because we can't guarantee if this is a breaking change at this moment. Please test if everything still works
**Test plan**
`useFindAndModify` default to be `false` may be a breaking change.
I fix #6887 and all current CI test pass. However I'm afraid the test coverage is not enough.
I check the following option so maintainers have access to add commit on …
=> WIP: fix: findAndModify and options [fields] deprecation

lib/connection.js, lib/index.js, lib/model.js, lib/query.js, package.json, test/collection.test.js, test/common.js, test/connection.test.js, test/docs/discriminators.test.js, test/docs/promises.test.js, test/docs/validation.test.js, test/document.strict.test.js, test/document.test.js, test/index.test.js, test/model.discriminator.querying.test.js, test/model.field.selection.test.js, test/model.findOneAndUpdate.test.js, test/model.indexes.test.js, test/model.populate.test.js, test/model.querying.test.js, test/model.test.js, test/model.update.test.js, test/query.middleware.test.js, test/query.test.js, test/schema.timestamps.test.js, test/types.subdocument.test.js, test/versioning.test.js
=> Clean up remaining deprecation warnings

lib/error/version.js, lib/model.js, test/versioning.test.js
backport #6464 to 4.x
**Summary**
Adds modifiedPaths to VersionError for improved debuggability
**Test plan**
=> feature(error): add modified paths to VersionError (4.x)

.travis.yml, lib/schema/operators/geospatial.js, test/model.querying.test.js
**Summary**
- Use correct `this` scope when casting query with legacy `2dsphere` pairs defined in schema.
Fixes #6937, Re: #6893 (const let eslint auto-fix) and 3b99dbdc96006b565c2b102ec19d606de4fa7a26 (use correct context for castToNumber)
- Wrap npm install with travis_retry to mitigate npm install timeout failure and this is [recommended by travis-ci](https://docs.travis-ci.com/user/common-build-problems/#timeouts-installing-dependencies)
**Test plan**
The test is included in the CI test
=> Use correct `this` scope when casting query with legacy 2dsphere pairs defined in schema

lib/schema/number.js, test/types.number.test.js
As demonstrated in #6927, when a conditional operator is used that doesn't exist in mongodb a regular error is thrown. This change throws a cast error instead.
```
mongoose>: npm test -- -g gh-6927
> mongoose@5.2.11-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6927"
!
0 passing (101ms)
1 failing
1) types.number
throws a CastError with a bad conditional (gh-6927):
AssertionError [ERR_ASSERTION]: false == true
-false
+true
at Context.<anonymous> (test/types.number.test.js:122:12)
npm ERR! Test …
```
=> Fixes #6927 making number.castForQuery return a CastError

lib/document.js, test/connection.test.js, test/model.querying.test.js, test/types.map.test.js
**Summary**
1. Handle sub docs for `Map` and resolve #6938
2. Fix a flaky test for #6937 in my previous pull request. use `yield Model.init()` to ensure 2dsphere index is created.
**Test plan**
Test included in the ci test. Thanks to @lineus's repro script.
I extend it with a new test to make sure the  hooks in child schema of the map value also work.
=> Fix Map sub doc hooks and some flaky tests

lib/helpers/query/castUpdate.js, test/model.query.casting.test.js
#6952 demonstrates that ` { strict: false }` array op casting fails. 
made a failing test, made it pass, all current tests pass:
```
mongoose>: npm test -- -g 'gh-6952'
> mongoose@5.2.13-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6952"
unhandledRejection in "model query castingarray ops don't break with strict:false (gh-6952)": TypeError: Cannot read property 'caster' of undefined
at walkUpdatePath (/Users/lineus/dev/opc/mongoose/lib/helpers/query/castUpdate.js:262:26)
at walkUpdatePath (/Users/lineus/dev/opc/mongoose/lib/helpers/query/castUpdate.js:209:20)
at …
```
=> Fixes #6952 make array op casting work with strict:false and {}

lib/helpers/query/castUpdate.js, lib/query.js, test/query.test.js
Per #5144 this PR adds the ability to override the schema useNestedStrict option on a per query basis.
```
mongoose>: npm test -- -g 'gh-5144'
> mongoose@5.2.12 test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-5144"
!
0 passing (598ms)
1 failing
1) Query
options
read
useNestedStrict
overrides schema useNestedStrict: false (gh-5144):
StrictModeError: Field `nested.v` is not in schema and strict mode is set to throw.
at new StrictModeError (lib/error/strict.js:24:11)
at walkUpdatePath …
```
=> Fixes #5144 add useNestedStrict to query options

lib/index.js
**Summary**
As discussed in #7010 when using mongoose in AWS Lambda along with Webpack, the build succeeds but during runtime it throws the below error
```
"Error: Cannot find module './drivers/node-mongodb-native'"
```
Because we're using dynamic requires in [lib/index.js#L9](https://github.com/Automattic/mongoose/blob/master/lib/index.js#L9) to use `global.MONGOOSE_DRIVER_PATH ||
'./drivers/node-mongodb-native'`
This PR, doesn't change any logical part, it just makes the code friendlier for webpack to parse.
=> Fixes #7010 use dynamic require only when needed

lib/model.js
re #6922 there's a typo in `@5.2.16`, `useCreateIndex` vs `createIndex` that causes any direct call to createIndexes ( *barring the workaround below* ) to always use the deprecated ensureIndexes method. 
*As the variable name is internal only ( it gets added to options when using createIndex directly ) and only causes a deprecation warning, I didn't add any new tests for this change.*
**All current tests pass.**
repo script:
```js
#!/usr/bin/env node
'use strict';
const assert = require('assert');
mongoose.set('useCreateIndex', true);
const URI = 'mongodb://localhost:27017/test';
const OPTS = { useNewUrlParser: true, useCreateIndex: true };
mongoose.connect(URI, OPTS);
const conn = mongoose.connection;
const Schema = mongoose.Schema;
const schema = …
```
=> fixes #6922 fix typo in model.js

migrating_to_5.md
This change adds a note to the migration guide about the change from `console.error()` to `console.info()` for debug messages.
related to #7018
=> add debug output stream change to migration doc

lib/cursor/ChangeStream.js, test/model.test.js
re #7022. This change exposes the underlying ChangeStream `close()` method on mongoose ChangeStreams while honoring mongoose's ability to buffer commands. If a `watch()` operation is buffered when `close()` is called on the ChangeStream, the watch operation will never run on the underlying driver.  
added a couple of failing tests, made them pass locally. Lots of tests fail for me in master at the moment, digging into why. Creating this as is to see if they pass on Travis.
With this code change, the repro script in #7022 can be changed to call `inserts.close()` and it works as expected.
=> fixes #7022 add close() to ChangeStream

docs/connections.jade, docs/deprecations.jade, lib/connection.js, lib/index.js, lib/model.js, test/connection.test.js
**Summary**
Add `useFindAndModify` option to config in the `Mongoose.prototype.connect`.
Also update the relationated documentation.
**Motivation**
To be consistant with the `Mongoose.prototype.set` and `Mongoose.prototype.connect` options.
It would be nice to be able to set the config as the `options` param.
**Example**
```javascript
mongoose.connect(MONGODB_URI, {
useNewUrlParser: true,
useFindAndModify: false,
useCreateIndex: true
});
```
=> fix(connection): add useFindAndModify option in connect

lib/schema.js, test/document.test.js
re #7074 `timestamps: false` is causing timestamps to be added to the schema. This change tests timestamps for a falsey value instead of != null. 
Added a failing test, made it pass, still using a backup computer that is apparently too slow for 30 of the tests to pass, so I'm holding my breath to see if Travis complains :smile:
With this change, the repro code in #7074 no longer adds timestamps to the schema when set to false.
=> fixes #7074 make timestamps false work again

lib/query.js
Fixes issue #7099: "orFail() returns undefined when a match IS found"
**Summary**
=> fixes #7099 orFail() returns undefined when a match IS found

lib/model.js
**Summary**
Failure:
```
❯ node index.js
~/dev/mongoose-collection-bug/node_modules/mongoose/lib/model.js:1400
model.collection.addQueue(create, []);
^
TypeError: model.collection.addQueue is not a function
at ~/dev/mongoose-collection-bug/node_modules/mongoose/lib/model.js:1400:24
at process._tickCallback (internal/process/next_tick.js:61:11)
```
[`Model.init()`](https://github.com/Automattic/mongoose/blob/763ec8cee75406df172faa3cab798cd9235d87a0/lib/model.js#L1005), when the model schema contains an index and the `autoCreate` option is `true`, [will call `Model.listIndexes()`](https://github.com/Automattic/mongoose/blob/763ec8cee75406df172faa3cab798cd9235d87a0/lib/model.js#L1032-L1037), erroring as above.
This is because [within …
=> Model.init() fails when an index exists on schema + autoCreate == true

lib/schema.js, test/schema.test.js
per #3056 This change returns the Schema instance from both `Schema.add()` and `Schema.remove()`
added two new failing tests, made them pass:
```
mongoose>: npm test -- -g 'returns the schema instance'
> mongoose@5.3.3 test /Users/lineus/dev/node/src/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "returns the schema instance"
!!
0 passing (3s)
2 failing
1) schema
#add()
returns the schema instance:
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
func.apply(thisObj, args)
-false
+true
at Decorator._callFunc (node_modules/empower-core/lib/decorator.js:110:20)
at …
```
=> make Schema.prototype.{add,remove} return the Schema instance

lib/types/buffer.js
re: #7173 global.Buffer is undefined in the browser. This change sets NodeBuffer to safe-buffer in this environment.
all current tests pass:
```
mongoose>: npm test -- --no-warnings
> mongoose@5.3.7-pre test /Users/lineus/dev/node/src/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "--no-warnings"
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․,,․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․ …
```
=> fixes #7173 fallback to safe-buffer in the browser

lib/document.js, test/document.populate.test.js
re #6075 when `depopulate()` is called on a doc that has either not been populated, or only has populated virtuals , it throws an error. Also, `depopulate()` does not currently remove populated virtuals whether or not they are passed into depopulate explicitly e.g. `depopulate('$someVirtuallyPopulatedPath')`  or implied with `depopulate()`. 
This change fixes the error, and makes `depopulate()` remove both explicit and implicit populated virtual paths.
I added a test for calling `depopulate()` on an unpopulated doc, and a test for both implicit and explicit depopulation of virtuals. All current tests pass.
```
mongoose>: npm test -- -g 'depopulate'
> mongoose@5.3.6 test /Users/lineus/dev/node/src/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "depopulate"
You're not testing …
```
=> Fixes #6075 make depopulate remove populated virtuals & not throw on unpopulated docs

lib/schema.js, test/timestamps.test.js
re: #7202 when explicitly creating a parent schema with `timestamps: false` that has a childSchema with `timestamps: false` the parent winds up with timestamps because the callback passed to childSchemas.find() only tests for loosely not equal to null. This change fixes that behavior.
added a failing test, made it pass, all current tests pass.
=> Fixes #7202 don't set parent timestamps because a child has timestamps set to false

lib/helpers/query/castUpdate.js, test/model.update.test.js
re: #7098, when updating a value in an array of arrays, we shouldn't skip query casting on the value. This change uses the `schematype.$parentSchema` value to detect if the current array is a top level array, only skipping casting on those that are.
I added a failing test, made it pass, all existing tests pass:
```
mongoose>: npm test -- -g 'gh-7098'
> mongoose@5.3.9-pre test /Users/lineus/dev/node/src/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-7098"
!
0 passing (381ms)
1 failing
1) model: update:
bug fixes
doesn't skip casting the query on nested arrays (gh-7098):
AssertionError [ERR_ASSERTION]: …
```
=> fixes #7098 don't skip casting the update for array of array values

docs/compatibility.html
Mongoose `^4.11.0` use the `2.2.X` version of the MongoDB Node.js driver (https://github.com/Automattic/mongoose/blob/4.11.0/package.json#L26) whereas only versions `>= 3.0` of the driver is recommended for MongoDB 3.6 (https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#reference-compatibility-mongodb-node).
**Summary**
The compatibility documentation currently lists Mongoose `^4.11.0` as compatible with MongoDB 3.6. However, this version of Mongoose does not use the MongoDB Node.js driver version that is recommended for this version of MongoDB 
Removing this range will prevent users from using a not-recommended version of the underlying Node.js driver on MongoDB 3.6.
**Test plan**
Documentation change only; no testing should be needed.
=> Removing ^4.11.0 as compatible with MongoDB 3.6

lib/model.js
**Summary**
Comparing if an model instance is an model instance by using the `constructor.name` property has many collateral effects. One being plugins to not have the ability to incorporate more functionality and override default behavior.
For instance, I came across this issue while having an unexpected behavior during `populate()` of an already fetched document, on a `MongoTenantModel` (a plugin that applies tenancity to mongoose). It works by creating a new instance of the Model, but with a few more pre hooks that prevents user from mutating/reading other tenants.
While this approach is correct, the comparision of `constructor.name` being equal to `model`, is false when in a MongoTenant Context, not populating the virtuals naturally.
**Explanation**
Just explained above …
=> Fixes hardcode instance of class comparation

lib/query.js, lib/utils.js, test/query.test.js
=> Move `Query#map()` functions to run before post hooks to support `orFail()` with `findOneAndUpdate()`

lib/aggregate.js, lib/browserDocument.js, lib/document.js, lib/model.js, lib/query.js, lib/schema/documentarray.js, lib/schema/embedded.js, lib/utils.js, test/model.test.js
Fix #7125
```javascript
// Will print out errors in queries, aggregations, `save()`, etc.
Model.events.on('error', err => { console.log(err); });
```
@Fonger @lineus @NishantDesai1306 any thoughts?
=> feat(model): add `Model.events.on('error')` for reporting all errors that occur on a model

docs/populate.jade
In the section "What If There's No Foreign Document?", I found the sample code confusing, I believe it's a mistake.
After `Story.deleteMany` the story "Casino Ryale" not exists anymore. so we can't `findOne`. the `story` it returned should be `null` and `story.author` will throw `TypeError: Cannot read property 'author' of null`.
**Summary**
**Test plan**
=> Fix mistake in populate documentation

lib/utils.js
* Fix for #7342.
Signed-off-by: Milo Casagrande <milo@foundries.io>
=> Check if EventEmitter is not null

lib/schema.js
**Summary**
Fixes a crash due to a misspelled variable name: `subpath[0]` is evaluated as `undefined[0]`. The [crash was flagged](https://lgtm.com/projects/g/Automattic/mongoose/snapshot/dist-6870015-1548143554293/files/lib/schema.js?sort=name&dir=ASC&mode=list#xcd0143b6ecb7c548:1) by the LGTM.com analysis I am working on.
`subpath` is actually defined in this method, but that happens many lines later. I suppose that is why it escaped ordinary linting.
**Examples**
I suppose a call to `getPositionalPathType({}, "123")` could cause the crash.
=> fix: use correct variable name

.gitignore
Hi,
The current pattern `**.swp` is invalid: 
> A pattern with '**' that does not have a slash on either side used to be an invalid one https://github.com/git/git/commit/627186d0206dcb219c43f8e6670b4487802a4921
Probably you want say `*.swp` ? Because on recent version of git as the link above say your syntax means `*\*.swp`
=> gitignore correct syntax

lib/document.js
Sources:
1. https://github.com/Automattic/mongoose/blob/bee1e1b4669185579168d691c214d17077b8bd6e/lib/document.js#L2031
2. https://github.com/Automattic/mongoose/blob/bee1e1b4669185579168d691c214d17077b8bd6e/lib/document.js#L2101
3. https://github.com/Automattic/mongoose/blob/bee1e1b4669185579168d691c214d17077b8bd6e/lib/document.js#L2035
**Summary**
Document.prototype.validateSync send ValidationError (it inherit of MongooseError).
If your are ok with that thanks sources above, I will make a PR to correct @types/mongoose accordingly
=> Documentation: Document.prototype.validateSync returns ValidationError

renovate.json
resolves #5953
**Summary**
Renovate can open a pull request when a newer version of a dependency, outside the allowed semantic version range becomes available.
**Examples**
Here is the example output PRs based off the current dependencies: https://github.com/ChristianMurphy/mongoose/pulls?utf8=%E2%9C%93&q=is%3Apr+chore+deps
renovate can be run by any user on the project with committer access.
```
npm install --global renovate
renovate --token {github access token} Automattic/mongoose
```
Renovate Website: https://renovatebot.com
Renovate Github: https://github.com/renovatebot/renovate
=> add configuration for renovate bot

lib/model.js, test/model.translateAliases.test.js
**Summary**
Unaliased keys were being deleted, rather than being returned unharmed. Also added a test with an '_id' query key to make sure it checks for this case.
**Examples**
Query
`{ '_id': ObjectId(...), 'someAliasedKey': '123' }
Schema
Schema with an alias for 'someAliasedKey' but not '_id' (or if _id isn't in the user's schema at all).
'_id' query will be deleted from the return of translateAliases, even though 'someAliasedKey' survives.
=> Fixed translateAliases bug.

lib/query.js
* Actually, at https://mongoosejs.com/docs/api.html we could see than `options.multipleCastError` are explained twice, only for :
1. https://mongoosejs.com/docs/api.html#query_Query-findOneAndUpdate
2. https://mongoosejs.com/docs/api.html#query_Query-update
* And not for:
1.  https://mongoosejs.com/docs/api.html#query_Query-updateOne
2. https://mongoosejs.com/docs/api.html#query_Query-updateMany
To correct this, simply add asterisk in the JSDoc
=> Doc: add an asterisk before comment, otherwise the comment line is not generated

lib/error/index.js, test/document.test.js
Actually ValidationError seems to be an hash of CastError and ValidatorError. Therefore I make the proposal to say that in the doc. 
Proof:
```sh
$ grep "new ValidationError" * -R
document.js:    this.$__.validationError = new ValidationError(this);
helpers/query/castUpdate.js:  aggregatedError = aggregatedError || new ValidationError();
helpers/updateValidators.js:        const err = new ValidationError(null);
```
Furthermore, there I've seen a small typo error under  test/document.test.js therefore I propose to push the correction in this current PR.
=> Doc ValidationError

lib/document.js, lib/plugins/validateBeforeSave.js, test/document.test.js
schema option that can be overridden on validate, validateSync, and save
**Summary**
#7421 - ignore validation on unmodified paths
Abandoned yucky post-filtering approach in #7483.
**Examples**
see tests ;)
=> feat(document): validateUpdatedOnly option. only validates modified

lib/model.js, test/document.populate.test.js
Fix for #7520
```javascript
// Will call getters for "bars.bar"
Foo.findOne({ _id: '5c657e2beca6210c78090082' }).populate({ path: 'bars.bar', options: { getters: true } });
```
=> Fixes populate "getter" option on embedded documents

CONTRIBUTING.md
when viewing a .md file not from the root of the repository
(e.g. https://github.com/Automattic/mongoose/blob/master/CONTRIBUTING.md), relative paths add `/blob/master/` thus breaking the link.
Hence I changed the link to an absolute path (url)
There's also a "become a backer" button in the "contributors" section which is probably unwanted because the button in used in the next paragraph, but I didn't edit that.
=> fix anchor tag in CONTRIBUTING.md

docs/guide.jade, docs/migrating_to_5.jade
If you're making a change to documentation, do **not** modify a `.html` file directly. Instead find the corresponding `.jade` file or test case in the `test/docs` directory.
**Summary**
minor fixes related to 5.x migration guide, specifically setter order change. Please confirm that getters are not affected in migration to 5.x.
=> 5.x migration guide: fix setter change example code

lib/helpers/schema/merge.js
**Summary**
Looks like there's a typo in code for merging two schemas. `schema.virtual` is a method, not the map of virtuals.
=> Fix virtuals cloning

lib/schema/date.js
**Summary**
I (and I think everyone else) expect the min and max options of the Date schema type to may a function. So I wrote this pull request.
**Examples**
```
const { Schema } = require('mongoose');
const schema1 = new Schema({
birthday: {
type: Date,
min: () => {
let d = new Date();
d.setFullYear(d.getFullYear() - 50);
return d;
},
max: () => {
let d = new Date();
d.setFullYear(d.getFullYear() - 18);
return d;
},
},
});
```
throw Error: 
```
/home/ubuntu/workspace/node_modules/mongoose/lib/schema/date.js:305
throw new CastError('date', value, this.path);
^
CastError: Cast to date failed for value "[Function: min]" at path "birthday"
at new CastError (/home/ubuntu/workspace/node_modules/mongoose/lib/error/cast.js:29:11)
at SchemaDate.cast …
```
=> Fix schematype Date option min, max (cast to Date) is function

README.md, docs/connections.jade, docs/index.jade, docs/models.jade
**Summary**
Adds `{ addNewUrlParser: true }` to `mongoose.connect()` on some documentation pages. 
Also fixes an outdated mongoose.connect() on the Models page. 
For example:
`mongoose.connect('mongodb://localhost/my_database', {useNewUrlParser: true});`
Instead of:
`mongoose.connect('mongodb://localhost/my_database');`
Please also note that there are further mongoose.connect() lines without `useNewUrlParser` on `connections.jade`, `faq.jade` and `guide.jade`. I haven't replaced those because it looks like their primary purpose is to demonstrate some sort of connection option.
=> docs: add useNewUrlParser to mongoose.connect

lib/helpers/update/applyTimestampsToChildren.js
**Summary**
Error happens when main schema has array of children with timestamps and the array is not exists in model.
When updating "other" field and array "name" is not exists,  error appears.
Error message:
TypeError: Cannot set property 'createdDate' of undefined at applyTimestampsToChildren (/node_modules/mongoose/lib/helpers/update/applyTimestampsToChildren.js:112:41)
**Examples**
```
const nameSchema = new mongoose.Schema({
name: String,
}, { _id: false, timestamps: { createdAt: 'createdDate', updatedAt: false} });
const mainSchema = new mongoose.Schema({
other: String,
name: {
type: [nameSchema],
select: false
}
});
```
=> Fixed issue, when in child schema has timestamp property

lib/query.js
This PR fixes some minor formating-issues within the documentation and, in addition to that, corrects the function-signature of "Query.prototype.comment()" to a `String` instead `Number`.
This is my first PR here, so please tell me, if there is anything that i can do better in the future.
=> Minor documentation-corrections + fixed function-signature "Query.comment"

lib/model.js
**Summary**
The issue is described here: #7634. If the third parameter is used in a `Model.discriminator()` method it should be used as a value to `partialFilterExpression` index instead of the `model.modelName`.
**Examples**
Consider the following example:
```js
let BasePaymentSchema = new mongoose.Schema({
amount: mongoose.Types.Decimal128
}, {
discriminatorKey: 'provider'
})
let BasePayment = mongoose.model('Payment', BasePaymentSchema)
let PaypalPaymentSchema = new mongoose.Schema({
transactionId: {
type: String,
unique: true
}
})
let PaypalPayment = BasePayment.discriminator(
'PaypalPayment',
PaypalPaymentSchema,
'paypal' // This value should be in discriminator field
)
```
Before the fix `db.payments.getIndexes()` returns:
```json
{
"v": 2,
"unique": true,
"key": {
"transactionId": …
```
=> fix modelName being used as value to partialFilterExpression index

lib/query.js
Very minor changes to the "atomic" keyword within the documentation.
I felt like i should link an official MongoDB-ref to the keywords, so new people can directly read about atomic operations in MongoDB. So i did that (https://docs.mongodb.com/manual/tutorial/model-data-for-atomic-operations/#pattern).
=> Minor changes to doc ("atomic" keyword made consistent)

lib/schema/array.js, test/schema.validation.test.js
**Summary**
In mongoose v5.x - the behavior of `required` on array fields was changed. On some SchemaTypes like String, you are able to override the default behavior. This adds the same functionality to Array. See: https://mongoosejs.com/docs/migrating_to_5.html#array-required
**Examples**
This change allows you to revert mongoose v5 behavior back to mongoose v4 behavior for backwards-compatibility purposes:
```js
mongoose.Schema.Types.Array.checkRequired(v => Array.isArray(v) && v.length);
```
=> allow customization of array required validator

lib/helpers/document/cleanModifiedSubpaths.js
I'm receiving this error on `create` and `update` in `feathers-js` app using the `feathers-mongoose` adapter. It only happens on certain models. Could this fix be included? Or does it more like a patch instead of targeting the real root cause?
=> Fix: Cannot read property '$__' of undefined

lib/drivers/node-mongodb-native/collection.js, test/collection.test.js
`insertMany([a,b])` throws
MongoError: docs parameter must be an array of documents
The following code:
collection.insertOne({foo:'bar'}).then(res =>
collection.findOne({_id: res.insertedId})
).then(doc => console.log(doc));
prints
{ '0': { foo: 'bar' }, _id: 5cb71e14f1bb5261dfdd629d }
instead of
{ _id: 5cb71e14f1bb5261dfdd629d, foo: 'bar' }
`arguments` was used as an `Array` argument of `concat` when queuing commands. 
Note:
(function() {return [].concat(arguments);})(1,2,3) === [Arguments]
but
(function() {return Array.from(arguments);})(1,2,3) === [1,2,3]
Wrap `arguments` in `Array.from()`.
=> fix usage of arguments while buffering commands

lib/query.js
**Summary**
Fix breaking changes introduced in 5.5.3
The callback function was `cb`, in 0b849710508566e86194a925f1248a2c3d200f16 became `callback`
```diff
-  this._collection.findAndModify(castedQuery, castedDoc, opts, _wrapThunkCallback(_this, -function(error, res) {
-    return cb(error, res ? res.value : res, res);
-  }));
!  _legacyFindAndModify.call(_this, castedQuery, castedDoc, opts, callback);
```
This PR simply changes `callback` to `cb`
```diff
!  _legacyFindAndModify.call(_this, castedQuery, castedDoc, opts, callback);
+  _legacyFindAndModify.call(_this, castedQuery, castedDoc, opts, cb);
```
=> fix(query): pass correct callback for _legacyFindAndModify

lib/document.js, test/document.populate.test.js
**Summary**
If there's no populatedIds (undefined), don't $set the value to undefined.
depopulate() with no arguments will depopulate all fields and have already handled this case correctly with:
`if (!populatedIds) { continue } `
https://github.com/Automattic/mongoose/blob/9645d87223ce753387a3d393c686b31d4459c807/lib/document.js#L3324-L3332
However the same check is not applied when depopulating with a specific path.
This PR simply fixes this for #7740
**Examples**
see the test
=> Document#depopulate with empty array fields

lib/types/map.js, test/types.map.test.js
**Summary**
Simply set the field to `undefined` to make Model#save works and also call `super.delete(key)` to remove the key from the Map.
**Examples**
See test
=> Support $unset update operation for MongooseMap#delete

lib/schema/documentarray.js, test/types.documentarray.test.js
**Summary**
Fix #7724 that was introduced in 764735b9bb2a577c3b5fce773bc866a75ca86474
**Examples**
See the test case in section `describe('push()', ...)` of `types.documentarray.test.js`
=> Reports Validation Errors for push()-ed Subdocs with Correct Index Path

lib/types/map.js
**Summary**
Not doing this for security reason ( `__proto__` is sanitized correctly ). Just do this check for consistency as we can't set these special proprieties in normal schema.
**Examples**
The following script will save the document in MongoDB successfully without any error.
Show the exact data saved into MongoDB:
```sh
> db.users.find().pretty()
{
"_id" : ObjectId("5cc23627c76b9141f33b0264"),
"name" : "Fonger",
"characteristics" : {
"__proto__" : "1",
"constructor" : "2",
"prototype" : "3"
},
"__v" : 0
}
> 
```
Query in Mongoose:
```
Mongoose: users.insertOne({ _id: ObjectId("5cc238642f34f543e42f6f31"), name: 'Fonger', characteristics: Map { '__proto__' => '1', 'constructor' => '2', 'prototype' => '3' }, __v: 0 })
{ _id: 5cc238642f34f543e42f6f31,
name: 'Fonger',
characteristics: …
```
=> fix(map): disallow setting map key with special properties

lib/query.js
**Summary**
This fixes a typo in `Query.prototype.distinct` docstring
=> Fix a typo in `Query.prototype.distinct` docstring

lib/query.js, test/model.findOneAndUpdate.test.js
**Summary**
This PR fixes the issue desribed in #7770.
Model.findOneAndUpdate() does not return the rawResults when an insert is done with the following options, {new:false,rawResult:true,upsert:true}.
When the result is returned the document can be null and the rawResult should still be returned.  A check to see if the document is present prevents this.
**Examples**
Before the fix the following code returned a null.
```
mongoose.connect('mongodb://localhost/test', {useNewUrlParser: true});
var db = mongoose.connection;
var kittySchema = new mongoose.Schema({
name: String,
type:Number
});
var Kitten = mongoose.model('Kitten', kittySchema);
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function() {
// we're connected! …
```
=> Fix rawResult not returned when inserted with options {new:false,upsert:true,rawResult:true}

lib/helpers/model/castBulkWrite.js, lib/model.js, test/model.test.js
**Summary**
Fix access to `$session()` inside pre validate middleware for bulkWrite(#7769) and insertMany(related bug)
**Examples**
See the test
=> Fix $session inside pre validate hooks for bulkWrite/insertMany

lib/schema/documentarray.js, test/schema.documentarray.test.js
**Summary**
Correctly handle documentarray setters for #7799 
`{ nested: [[ childSchema ]] }`
**Examples**
See test `npm test -- -g "gh-7799"`
EDIT:
Close & Reopen PR to re-trigger travis-ci.
EDIT2:
It seems travis-ci is quite unstable now and always failing with timeout error.
=> Fix Setter of Array of Document Array

lib/schema/string.js, test/model.query.casting.test.js
**Summary**
Apply the fix in #1462 $conditionalHandlers for String schema #7800 
https://github.com/Automattic/mongoose/blob/c08002049442d0f87c99819529177f9ba148048b/lib/schema/array.js#L439-L442
Maybe we can throw an error if `$options` is not of type string.
**Examples**
See test
Close&Reopen to re-trigger travis-ci test.
=> Run string cast on $options

lib/model.js, test/docs/transactions.test.js, test/model.test.js
**Summary**
Related to #6805 #6810 (add missing Model.deleteMany options support)
This PR add missing options argument for `Model.deleteOne` and will fixes #7857
**Examples**
See test
=> Support deleteOne options

lib/model.js
If you're making a change to documentation, do **not** modify a `.html` file directly. Instead find the corresponding `.jade` file or test case in the `test/docs` directory.
**Summary**
There was a small typo in the js doc for [Model()](https://mongoosejs.com/docs/api.html#model_Model): `projetion` instead of `projection` for 
> optional «[fields]» object containing the fields that were selected in the query which returned this document. You do not need to set this parameter to ensure Mongoose handles your query **projetion**.
=> docs(model): fix typo `projetion` to `projection`

lib/document.js, lib/helpers/populate/assignVals.js, lib/model.js, lib/plugins/sharding.js, lib/schema.js, test/document.populate.test.js, test/document.test.js, test/model.test.js
**Summary**
- Prepend 2 document internal methods tagged `@api private` with `$` to avoid conflicts. Resolves #7869
```diff
/**
* Gets a raw value from a path (no getters)
*
* @param {String} path
* @api private
*/
-Document.prototype.getValue = function(path) {
+Document.prototype.$__getValue = function(path) {
return utils.getValue(path, this._doc);
};
/**
* Sets a raw value for a path (no casting, setters, transformations)
*
* @param {String} path
* @param {Object} value
* @api private
*/
-Document.prototype.setValue = function(path, val) {
+Document.prototype.$__setValue = function(path, val) {
utils.setValue(path, val, this._doc);
return this;
};
```
Maybe it's good to use Symbol but I think other if we do that, all other internal methods should be 
updated too.
=> fix(document): prepend private methods getValue and setValue with $

lib/model.js, test/model.findOneAndUpdate.test.js, test/model.test.js
**Summary**
- Reset modifiedPaths after successful insertMany to fix #7852
Handle it like `Model.create` which calls `Model.save` internally.
It eventually calls `this.$__reset()` function on each newly created document.
- Add missing repro script for #7736 because that was a severe regression.
**Examples**
See test
=> Reset modifiedPaths after successful insertMany

lib/connection.js
**Summary**
- Now `fullsetup` event is equvalent to `all` event in mongodb-core driver.
And mongoose no longer listens to `new` event and emits that.
re: #3986 missing in mongoose v5.
- `$internalEmitter` was used in fix of #6967 but was refactored out in #7682
=> Update connection docs and remove unused code

lib/aggregate.js, lib/cast.js, lib/document.js, lib/error/cast.js, lib/helpers/document/cleanModifiedSubpaths.js, lib/helpers/projection/isInclusive.js, lib/helpers/query/castFilterPath.js, lib/helpers/query/castUpdate.js, lib/helpers/query/hasDollarKeys.js, lib/helpers/setDefaultsOnInsert.js, lib/helpers/update/applyTimestampsToChildren.js, lib/helpers/updateValidators.js, lib/queryhelpers.js, lib/schema.js, lib/schema/array.js, lib/schema/documentarray.js
**Summary**
- @vkarpov15 had a commit to replace `.charAt(0)` with `startsWith` re: 8d68ff709ee12a50dd64fd3f0471258feb746a13. Update to keep consistent coding style. 
-  Reuse `mapPath` variable re: https://github.com/Automattic/mongoose/commit/eb5078ee8bd2230dd1564401c4e04dfa0a3cbca5#r33900662
- Replace `indexOf` and `lastIndexOf` with `startsWith`, `endsWith` or `includes` for **String***.
**Caveat**
`arr.indexOf(x) !== -1` is not replaced with `arr.includes(x)`.
The reason is that, unlike `String.prototype.includes` is available after node.js v4.0, `Array.prototype.includes` is available after node.js v**6.0**.
I tested the node.js compatibility and mentioned this before in my PR #6968.
=> chore: use startsWith, endsWith and includes for String

README.md
**Summary**
`example/schema.js` is moved to a different location.
=> Fix reference to example schema.js

index.pug
pug fail to parse the markdown link when mixing with html.
https://mongoosejs.com
=> docs(website): fix OpenCollective sponsor link

lib/query.js
**Summary**
Short-circuiting when passed null or undefined allows for conditional population without having to break out of a chained query call.
**Examples**
```js
const item = await Model
.findById(id)
.populate(populateParams) // no longer throws when populateParams is null or undefined
.lean();
```
=> #7912 - short-circuit populate for falsy arguments

docs/connections.pug, lib/connection.js, lib/index.js, test/index.test.js
**Summary**
This may prevent developers from the misuse of mongoose. Resolves #7814.
EDIT: sorry for the wrong issue reference (not 7813)
=> feat(mongoose): throw an error if calling `mongoose.connect()` multiple times while connected

docs/faq.pug
**Summary**
Simple typo fix for a dead link.
**Examples**
Now the text becomes: [visit it](https://github.com/Automattic/mongoose/tree/master/docs/faq.pug)
=> Fix `visit it` URL in FAQ

lib/model.js
**Summary**
The link from [Model.findById()](https://mongoosejs.com/docs/api/model.html#model_Model.findById) to [Query.prototype.select()](http://mongoosejs.com/docs/api.html#query_Query-select) is broken in the [current docs](https://mongoosejs.com/docs/api/model.html#model_Model.findById).
This change updates the url to [http://mongoosejs.com/docs/api.html#query_Query-select](http://mongoosejs.com/docs/api.html#query_Query-select) in the JSDoc.
=> Fix link to Query.prototype.select

lib/index.js
**Summary**
export the function of cast, so could cast the customer query to native mongodb query 
**Examples**
```js
const Schema = mongoose.Schema;
const cast = mongoose.cast;
let schema = new Schema({x: String,y:Number});
let custom_query = {x: [123, 456],y:'123'};
let native_query = cast(schema, custom_query);
console.log(native_query) //{ x: { '$in': [ '123', '456' ] }, y: 123 }
```
=> export mongoose.cast

lib/query.js
**Summary**
Apply the same fix #6810 #7860 for Query instance. They were only for Model.
This will solve @krlozadan's issue. It seems he gets the model via Query instance.
See https://github.com/Automattic/mongoose/pull/6810#issuecomment-513302970
=> fix(query): add missing options for deleteOne and deleteMany in Query

lib/schematype.js
I updated Schema.path in the comments to the correct s.path where applicable as was asked of me.
I found this error when helping someone debug some code.  It looks like several typo's were made calling path on Schema, which does not exist rather than on the object s which was created as a new Schema.
If you're making a change to documentation, do **not** modify a `.html` file directly. Instead, find the corresponding `.pug` file or test case in the `test/docs` directory.
**Summary**
**Examples**
=> [docs] Updated comments from Schema.path to proper s.path

lib/model.js
**Summary**
Fix #8040 memory leak introduced in ae8206280fa9861495b6bcf62a8fc7b5d6ca60bf
=> fix(model): delete versionError after saving to prevent memory leak

lib/index.js
**Summary**
Fixed typo in `Mongoose.prototype.connection`'s description.
**Examples**
Removed the extra closing bracket in `mongoose.connections][0]`.
=> docs(api): fixed typo in Mongoose.prototype.connection description

lib/helpers/schematype/handleImmutable.js
**Summary**
When casting an Schema type array of objects the `applySetters` is called with no scope leading `immutableSetter` to have this as null and thus breaking at line 20 with the following error:
`Cannot read property '$__' of undefined`
This issue was introduced on version 5.6.0, I can't replicate in version 5.5.15
This change fix the error.
=> Fix issue when using find in a collection with nested schema array

lib/model.js, lib/schema/documentarray.js, lib/types/documentarray.js, test/schema.documentarray.test.js, test/types.documentarray.test.js
Before: 
```
$ time node gh-7895.js 
real	0m10.777s
user	0m11.311s
sys	0m0.354s
```
After:
```
$ time node gh-7895.js 
real	0m7.058s
user	0m7.194s
sys	0m0.048s
```
Should be fine to release in 5.6.8, but I want to see if we can make this a little bit faster, because this is still slightly slower than Mongoose 4.13
=> perf(documentarray): refactor to use ES6 classes instead of mixins, 30% speedup

docs/schematypes.pug
**Summary**
Guide currently states `If you pass an element that has a toString() function, Mongoose will call it, unless the toString() function is strictly equal to Object.prototype.toString()` which is not correct as `.toString()` is also not called for arrays
Related issue: https://github.com/Automattic/mongoose/issues/7619
=> [doc] add information about array to string cast

lib/schematype.js, test/model.test.js
=> feat(document): run setters on defaults

lib/schematype.js
**Summary**
Related to issue https://github.com/Automattic/mongoose/issues/8111, cloning is not well handled.
I update a schematype by adding a setter (`schematype.set(...)`), and then when I clone the schematype, I loose the setters. There is the same behaviour with the getters.
**Examples**
```
(async () => {
const schema = new mongoose.Schema({
field: {type: String, required: true}
});
schema.path('field').set(value => value ? value.toUpperCase() : value);
// Test not ok
const TestKo = mongoose.model('TestKo', schema.clone()); //>> cloned
const testKo = new TestKo({field: 'It shall all be upper'});
console.error(testKo.field);
// Test ok
const TestOk = mongoose.model('TestOk', schema); //>> not cloned
const testOk = new TestOk({field: 'It is all …
```
=> Add missing getters and setters copy when cloning (see issue #8111)

lib/error/index.js
**Summary**
StrictModeError is one of possible Mongoose errors, it should be added to MongooseError
**Examples**
const StrictModeError = require('mongoose').Error
=> Add StrictModeError to MongooseError

lib/helpers/common.js, lib/helpers/updateValidators.js
Fixes #8093
Before this commit the `flatten(..)` function failed to deliver what it promised. Namely, it entered into Mixed paths of objects.
The update validator, on its side, did not pass the casted doc schema into `flatten(..)`. If the casted doc contained a large Mixed field, all its paths were added into the list of updated paths. They were later ignored by now removed check for schemaPath type, but performance was already hurt.
This commit makes sure that inner sub-paths of Mixed paths are not included into the array of paths at all, thus no further checks of that are necessary, and the performance is restored.
=> [#8093] Fixes performance of update validator, and flatten function logic

lib/error/validation.js
Minor refactor to the ValidationError constructor, took a duplicated line out of both conditions.
=> Minor refactor to ValidationError

lib/connection.js
**Summary**
I've fixed jsdoc for Connection.close public method. It's in fact returning a promise, not a Connection object.
=> docs(api) fix Connection.close return param

README.md
Just went through the README again after a long while, with little [curse of knowledge](https://en.wikipedia.org/wiki/Curse_of_knowledge) this time. This PR aims to make the README more appealing to new Mongoose users by showing `await`-style calls. It also moves the Importing section after the Installation section, which I think makes more sense. Once that's done, we can remove the `require` line from the Connecting example.
=> Illustrate Promise API, move Import after Install

package.json
Adds a mocha section to package.json to allow the removal of the
file path arguments in the test script target for mocha. Doing this
enables the developer to now invoke testing on a single file more
easily like so:
`$ npm test test/utils.test.js`
=> build(test) Improve test target

lib/model.js
The original fix in PR #8048 has a typo. This PR really fixes the issue.
=> fix(model): delete $versionError after saving to prevent memory leak

lib/connection.js, test/connection.test.js
WIP fixing some potential issues with mongodb driver v3.3.4
=> fix(connection): bubble up connected/disconnected events with unified topology

test/model.test.js
**Summary**
Add test to make sure `$__.versionError` `$__.saveOptions` are generated during saving and are cleared after saved to prevent memory leak.
https://github.com/Automattic/mongoose/pull/8326#issuecomment-553609848
> vkarpov15: I'll merge this for now, but can you also write a test for this please? Basically make sure that `$versionError` exists before and no longer exists after.
=> test(model): add test for issue #8040 re: #8048 #8326

lib/query.js
**Summary**
Duplicate `omitUndefined ` options are removed from `Query#replaceOne`, `Query#update`, `Query#updateMany` and `Query#updateOne` documentations.
fixes #8348
=> remove duplicate omitUndefined options

docs/connections.pug, lib/connection.js, test/connection.test.js
**Summary**
This solves https://github.com/Automattic/mongoose/issues/8354. It appears that previously SRV connection strings didn't allow for default databases to be in the uri. I'm not sure if that changed recently, but when connecting to our Atlas clusters we are able to specify the default database in the string.
This PR changes the logic when assigning the database name (as outlined in https://github.com/Automattic/mongoose/issues/8354) to look for `options.dbName`, then look for the default database in the connection string, then fallback to the auth db.
**Examples**
```js
mongoose.connect('mongodb+srv://<username>:<password>@cluster0.mongodb.net/defaultDatabase?w=majority')
// => results in a connection with `db.name === defaultDatabase`
```
=> feat(connections): Adds default database connection string support (#8354)

lib/types/documentarray.js, test/types.documentarray.test.js
Will be testing other array methods soon, and fix any broken ones.
@vkarpov15 I am curious, what are the exact changes that introduced this bug?
=> Fixes #8317 map(...)

lib/model.js, test/model.test.js
**Summary**
Fix #8363. Correctly catch the error with callback when insertMany fails to initialize the document.
This can prevent DOS attack when inserting user-provided data.
This fix handles it like [`Model.create([...])` does](https://github.com/Automattic/mongoose/blob/33412d91d044daade5a135c7f35f607591c75a09/lib/model.js#L3021-L3027).
Note: I've tested `Model.bulkWrite()` `insertOne()/replaceOne()` and I can confirm that it's not affected by this bug because `$handleCallbackError` wrap the entire bulkWrite callback handler and it catches the error during `castBulkWrite()`.
However, in `Model.insertMany()`, `parallelLimit()` individual callbacks are not wrapped in that general handler (although $__insertMany is) so we need this fix.
**Examples**
See the test case
=> Correctly catch the error when insertMany fails to initialize the document

lib/helpers/query/castUpdate.js, lib/query.js, test/model.update.test.js
Re: #8225, looks like we're going to need some significant work to support [aggregation pipelines in updates](https://docs.mongodb.com/manual/reference/method/db.collection.updateOne/#updateone-behavior-aggregation-pipeline). This is at least a basic proof of concept.
=> feat(update): basic support for update pipelines in MongoDB 4.2

docs/guide.pug, docs/schematypes.pug, docs/subdocs.pug, lib/index.js, lib/schema.js, test/types.embeddeddocumentdeclarative.test.js
Note: Might also close #7181 and close #7408 too...
- default behaves as previous releases did
- embeddeddocument test copied to cover declarative syntax
- otherwise, type: somePojo turns somePojo into subdocument and Mixed paths are only created when explicitly requested via Mixed or {}
I think it's probably also a good idea to make this option a base option too, but wanted to ask for blessing first.
**Summary**
It creates an option that makes type keys valued as …
=> feat(schema): make pojo paths optionally become subdoc instead of Mixed (closes #7494)

lib/model.js, test/model.indexes.test.js
**Summary**
We have some older indexes with `safe: null` set as an option on a 10s of million documents collection. Because of this index creation fails on them now since the options don't match coming from mongoose, we know this is the case but we don't have time allocated to fix them yet. However, we also noticed that new indexes that are not affected by that problem were not being created because it seems if one index fails, all following indexes for that model are skipped.
**Examples**
This is designed to fix the issue I reported here: #8181 and I also did add a test to show the issue
**Other notes**
I originally just removed the done(err) line, however that seems to have caused a test to fail in regards to errors not being emitted on the model. For that reason I added the more …
=> Fix all indexes not being created for a model if one fails

build-browser.js, package.json, test/files/sample.js, test/webpack.test.js, webpack.base.config.js, webpack.config.js
Fix #7219
**Summary**
Prebuilt mongoose/browser configured in a way that can be consumed in environments that don't have "window" too.  Webpack test also updated to test the exact same webpack config as the build.
**Examples**
=> feat(browser): pre-compile mongoose/browser

package.json
**Summary**
Connecting via `ssl: true` in a Docker Container through a SSH Tunnel fails for me.
Using `mongodb@3.4` and the new `tls: true` parameters works as expected.
Would be great if mongoose could be updated to use the latest `mongodb@3.4` instead of `3.3.4`
**Examples**
Connecting via SSL in 3.3.5:
```js
const options = {
ssl: true,
sslCA: [ fs.readFileSync( process.env.MONGODB_CA ) ],
sslCert: fs.readFileSync( process.env.MONGODB_CERT ),
sslKey: …
```
=> Update mongodb dependency to 3.4

lib/model.js, test/model.test.js
**Summary**
This PR fixes issue #8234.
You can now pass a `lean` option to `Model.insertMany` to bypass validation.
**Examples**
```javascript
MyModel.insertMany(arr, { lean: true }, (err, docs) => {});
```
=> Support `lean` option for `Model.insertMany()` #8234

benchmarks/create.js, lib/document.js, lib/schema.js
**Summary**
Performance improvements for document creation. I used the already present `benchmarks/create.js` to validate these changes. 
The most common case for _pathToPositionalSyntax is that there's no positional syntax present. By avoiding the two calls to Regexp.replace, we can avoid creating two additional copies of the given path string per call. During document creation this function is called very frequently.
By avoiding extraneous calls to string split, we can reduce the number of string copies performed and garbage generated as a result.
**Examples**
On `benchmarks/create.js` locally:
Before:
```
creation of large object took 9617 ms
```
After:
```
creation of large object took 5320 ms, 5.32 ms per object
```
While the raw improvement doesn't seem large, on a larger document …
=> Improve performance of document creation.

lib/document.js, test/document.test.js
It turns out that due to a check which I can't find a reason for the logic for removing subdocuments from the "paths" list when running validators only ran on the root document -- this is not a problem most of the time, it just results in the validators running multiple times on some embedded paths, but in some slightly weird cases it can result in validate being called twice -- and the second time is deeper in the stack from the first validate.
Combined with the check for multiple parallel calls to `validate()` this resulted in a fatal error when saving a document with changes to those documents which triggered that case.
A test has been added in this pull request which reproduced the error and which after the fix no longer reproduces the error.
This fixes #8531
=> test and Fixes #8531 - only call validate once for subdocuments

lib/helpers/model/discriminator.js, test/model.discriminator.test.js
**Summary**
While debugging a problem I was having, I noticed the following issue: the base schema's plugins are not being copied to the discriminator's plugin. I have investigated the change and have not identified anything that would be impacted. At least, as far as I can see, the plugin functions are only called when creating schema or calling `schema.plugin()`. Still, I lost some time trying to work out if this was the cause of my problem and so figured this could be helpful if it saves someone else going down this rabbit hole.
My only concern is that it may be confusing to see a plugin listed that is designed to manipulates the schema when the schema has not been manipulated. I struggled to think of an appropriate example (that wasn't redundant) and the best I could come up with was: …
=> Copy plugins from base schema when creating a discriminator

lib/schematype.js, test/schematype.test.js
I noticed that `SchemaType.clone()` was not copying values where updates had been made after instantiation. 
I figured that testing using `assert.deepStrictEqual` made the most sense here, but perhaps it's overkill and the if (x !== undefined) are unecessary? I'll happily adjust if you have a preference.
Also, I thought the rename schema.type.test.js → test/schematype.test.js made sense as it seems to be testing shared functionality, again will adjust if you prefer the old style.
=> Fix SchemaType.clone()

lib/helpers/model/discriminator.js, lib/schema/SingleNestedPath.js, test/docs/discriminators.test.js, test/model.discriminator.test.js, test/schema.singlenestedpath.test.js
This is a fix to an issue I have been having. 
My understanding of `utils.merge` is that if you merge an object with itself nothing should happen. Therefore, I think the below merge is redundant.
However, more importantly to me, this merge actually has quite of a lot of (I presume) unintended side effects, which I am not clear on the best approach to fix. I will raise this as a separate issue.
=> Discriminator: Remove unnecessary merge of schema with itself

index.pug
This prevents the deprecation warning for unified topology on the example on the homepage.
=> (docs) add useUnifiedTopology to homepage example

lib/aggregate.js, lib/connection.js, lib/cursor/AggregationCursor.js, lib/cursor/QueryCursor.js, lib/document.js, lib/helpers/cursor/eachAsync.js, lib/helpers/model/applyHooks.js, lib/helpers/model/applyStaticHooks.js, lib/helpers/promiseOrCallback.js, lib/index.js, lib/model.js, lib/query.js, lib/types/embedded.js, lib/types/subdocument.js, lib/utils.js, test/helpers/promiseOrCallback.test.js
Trying to make things less dependent of utils.js
**Summary**
I'm just reducing the complexity of some modules dependency reducing unnecessary context import.
**Examples**
`eachAsync.js` that require `utils.js` only to use `promiseOrCallback`, but since `utils.js` requires basically all package.
[Dependency graph](https://github.com/sverweij/) of lib/helpers/cursor/eachAsync.js:
- [Before this change](https://user-images.githubusercontent.com/863299/74076890-2fc03a00-49fa-11ea-9642-7337a21412e2.png) 
- After this change:
=> refactor(utils): moving promiseOrCallback to helpers/promiseOrCallback

lib/browserDocument.js, lib/cast.js, lib/drivers/node-mongodb-native/collection.js, lib/helpers/clone.js, lib/helpers/common.js, lib/helpers/getFunctionName.js, lib/helpers/isBsonType.js, lib/helpers/isMongooseObject.js, lib/helpers/isObject.js, lib/helpers/schema/getIndexes.js, lib/helpers/specialProperties.js, lib/options/PopulateOptions.js, lib/options/SchemaTypeOptions.js, lib/options/removeOptions.js, lib/options/saveOptions.js, lib/queryhelpers.js, lib/schema/mixed.js, lib/types/map.js, lib/utils.js, test/helpers/clone.test.js, test/helpers/getFunctionName.test.js, test/helpers/isBsonType.test.js, test/helpers/isMongooseObject.test.js, test/helpers/isObject.test.js
**Summary**
Trying to make things less dependent of utils.js
This time. `utils.clone`.
Since clone has some dependencies from utils, moved also:
- `utils.specialProperties` to helpers/specialProperties;
- `utils.isMongooseObject` to helpers/isMongooseObject;
- `utils.getFunctionName` to helpers/getFunctionName;
- `utils.isBsonType` to helpers/isBsonType;
- `utils.isObject` to helpers/isObject.
I'd resisted to temptation to refactor methods, with two exception:
- `util.object.vals` changed by `Object.values` (lib/queryhelpers.js);
- `utils.each` changed `forEach` (lib/browserDocument.js).
**Examples**
Instead of require dependencies of [lib/utils.js](https://user-images.githubusercontent.com/863299/74390425-03346580-4de0-11ea-80a3-be3318613acd.png) to these files:
- lib/browserDocument.js; …
=> refactor(utils): moving clone to helpers/clone

test/docs/discriminators.test.js
**Summary**
This fixes Issue 8588 which appears to be an artifact in the documentation from before [this fix](https://github.com/Automattic/mongoose/commit/3f1f1de70b00e84320cdb2cafd983e707d0d39a9) to how the discriminator code handled a custom _id in the base schema.  As I understand it, in the old code the implicit discriminator schema would still override the base, unless _id was set to 'false' in the discriminator options.  This is what the old documentation still reflects (at least in part).  However, it appears that now a custom base _id always overrides the discriminator _id.  This updates the documentation to reflect that behavior.
**Examples**
This is a test file.  The tests still run correctly--it was just the descriptions that didn't match.
=> fix: update documentation of custom _id overriding in discriminators

lib/model.js, lib/options/PopulateOptions.js, test/model.populate.test.js
Fixes #8658
I made changes so that `populate(...)` throws an error when provided both `limit` and `perDocumentLimit`, but I can't catch the error and assert on it in my tests for some reason.
Getting Uncaught Error even though I am using try/catch inside the `co(...)` call. Any idea why that might be?
```js
it('throws an error when using limit with perDocumentLimit', function() {
return co(function *() {
const User = db.model('User',userSchema);
const BlogPost = db.model('BlogPost',blogPostSchema);
const blogPosts = yield BlogPost.create([{title:'JS 101'},{title:'Mocha 101'}]);
const user = yield User.create({blogposts: blogPosts});
let err;
try {
yield User.find({_id:user._id}).populate({ path: 'blogposts', perDocumentLimit: 2,limit:1 });
} catch (error) {
err = error; // doesn't really …
```
=> [WIP] Fixes #8658

test/model.test.js
In response to https://github.com/Automattic/mongoose/pull/8693#discussion_r395913438 cool tips, used `.then(()=>null).catch(err=>err);` to catch the error instead of the try/catch block.
=> refactor test for #8331

package.json
The **mpath** package was recently updated (In mpath repo) because the older version of the **mpath** had vulnerability issue . the following are the PR and issues created for it, in their repo
https://github.com/aheckmann/mpath/pull/9
https://github.com/aheckmann/mpath/issues/8
**mpath** is used as dependency in mongoose , which is why added the change to update the package.
=> updated mpath package version to 0.7.0

lib/helpers/model/castBulkWrite.js, lib/model.js, test/model.test.js
fixes #8745 
However, when using `mongoose.set('debug', true);` this seems to actually send the `timestamps: false` option all the way to the mongo side.
Curious if this will cause any weird scenarios.
=> allow setting timestamps to false for bulkWrite

lib/schema.js
Default getter should return value when it is passed in.
**Summary**
The default getter on virtual populate fields does not work well when trying to apply getters to lean POJO's. In fact, it just returns undefined because it is expecting a mongoose document. Detailed in #8774 . This change will allow the `mongoose-lean-getters` extension to fully work for virtuals and also conceptually makes sense.
**Examples**
Here's the relevant thing that you can do now, even with a lean document:
```js
const virtualKeys = Object.keys(schema.virtuals);
for (let i = 0; i < virtualKeys.length; ++i) {
const virtualPath = virtualKeys[i];
const virtualType = schema.virtuals[virtualPath];
mpath.set(virtualPath, virtualType.applyGetters(mpath.get(virtualPath, doc), doc, true), doc);
}
```
You can now call …
=> Fixing #8774

lib/aggregate.js, lib/cast.js, lib/collection.js, lib/connection.js, lib/document.js, lib/error/validator.js, lib/helpers/clone.js, lib/helpers/model/applyHooks.js, lib/helpers/model/discriminator.js, lib/helpers/populate/getModelsMapForPopulate.js, lib/helpers/populate/getSchemaTypes.js, lib/helpers/query/selectPopulatedFields.js, lib/helpers/schema/applyPlugins.js, lib/helpers/schema/getIndexes.js, lib/helpers/updateValidators.js, lib/model.js, lib/query.js, lib/queryhelpers.js, lib/schema.js, lib/schema/array.js, lib/schema/string.js, lib/schematype.js, lib/types/core_array.js, lib/types/documentarray.js, lib/types/map.js, lib/utils.js, test/document.test.js, test/model.geosearch.test.js, test/types.number.test.js, website.js
I've always found it shorter, and clearer to use for..of
```js
for (const item of arr) {
// do stuff
}
```
instead of using indexes
```js
for (let i = 0; i < arr.length; i++) {
const item = arr[i]; 
// do stuff
}
```
Of course there are cases where indexes are necessary, those will not be changed, waiting to hear if @vkarpov15 approves of these changes, I'd like to take the time and refactor this wherever possible in the codebase.
=> [WIP] refactor: use (for-of) instead of for (let i = 0...) when iterating on arrays

.travis.yml, lib/cursor/AggregationCursor.js, lib/cursor/QueryCursor.js, test/query.cursor.test.js
=> add node 13, and 14 to travis, and fix stream close event listener called multiple times on node 14

lib/document.js, lib/model.js, lib/schematype.js, test/model.test.js
fixes: #8821
but I've been facing an issue with the errors being returned, I am getting {PATH} replaced with `friends.$` instead of `friends.0`, which would make all the errors in an array be omitted except for the last one.
@vkarpov15 I probably spent too much trying to figure this one out, any idea how I can make `SchemaType#doValidate(...)` change `friends.$` into `friends.0`?
**EDIT:** I figured it out, just needed to add `doValidateOptions: { path }`
=> fix: validate nested paths on Model.validate(...)

lib/model.js, package.json, test/model.test.js, test/query.cursor.test.js
To avoid having to manually format the spacing before/after the arrow in an arrow function.
=> add consistent arrow spacing by eslint

lib/helpers/populate/getModelsMapForPopulate.js, test/model.populate.test.js
=> check discriminator existence before accessing schema in getModelsMapForPopulate

lib/helpers/schema/getIndexes.js, test/model.indexes.test.js
=> allow adding descending indexes on schema

lib/query.js
**Summary**
Query options do not get passed to the mongodb nodejs driver when performing a distinct query, e.g. maxTimeMS or readPreference. Fix that by passing the options in.
**Examples**
```js
await mongoose.connect(MONGO_URI);
const Model = mongoose.model(
'model',
...
);
await Model.distinct('field').read('secondary');
```
_debug output before change:_
`Mongoose: models.distinct('field', {})`
query appears in active operations on primary
_debug output after change:_
`Mongoose: models.distinct('field', {}, { readPreference: ReadPreference { mode: 'secondary', tags: undefined }})`
query does not appear in active operations on primary
=> set mongodb options in distinct

docs/faq.pug, docs/populate.pug
=> docs(populate, faq): separate limit-vs-perDocumentLimit into its own section, add FAQ for populate and limit

lib/document.js, lib/internal.js, lib/schema/string.js, lib/schematype.js, lib/types/subdocument.js, test/document.test.js, test/query.test.js, test/schema.test.js
Fix #8629
There's some messy edge cases that come in when you have custom setters underneath nested subdocs, and you're creating a new subdoc. For example:
```javascript
const Model = db.model('Test', Schema({
name: String,
profile: {
type: Schema({ age: Number }, { _id: false }),
set: function(v, priorVal) {
// What should this be if `doc.profile.toObject() === { age: 29 }`
// and I do `doc.profile = { age: 30 }`?
this.age;
// If `this.age === 29`, what happens if I change `this.age` in the setter?
return v;
}
}
}));
```
We've created some messy workarounds, but I think the cleanest way to do this going forward is to pass the current value as the 2nd parameter to the setter. In Mongoose 5, `this.age` will be 29, but with this PR `this.age` will be undefined but `priorVal` will be 29. I …
=> BREAKING CHANGE: call setters with `priorVal` as 2nd parameter, and with new subdocument as context if creating new document

lib/document.js
=> docs: add flattenMaps and aliases to Document#toObject()

docs/3.0.x/docs/guide.jade, docs/3.1.x/docs/guide.jade, docs/3.2.x/docs/guide.jade, docs/3.3.x/docs/guide.jade, docs/documents.pug, docs/guide.pug, examples/geospatial/person.js, lib/browser.js, lib/index.js, lib/model.js, lib/query.js
=> fix(docs): fix broken references to Mongoose#Document API, and prefer mongoose.model(...) over Document#model(...)

lib/helpers/populate/getModelsMapForPopulate.js
**Summary**
Allows the use of a function in `foreignField` when doing a virtual populate, so it can be dynamic just like `localField`.
https://mongoosejs.com/docs/populate.html#populate-virtuals
**Examples**
```
AssignmentSchema.virtual('assigned', {
ref: doc => doc.adminId ? 'Admin' : 'User',
localField: '_id',
foreignField: doc => doc.adminId ? 'adminId' : 'userId',
justOne: true
});
```
=> Fix: allow dynamic foreignField in virtual populate

lib/helpers/model/castBulkWrite.js, lib/helpers/query/castUpdate.js, lib/helpers/update/moveImmutableProperties.js, lib/query.js, test/model.update.test.js
Fixes #8951 
The cause of this issue, as I understand it:
- In `castUpdate()`, the keys of the update are taken _before_ the call to `moveImmutableProperties()` but this call can modify the keys (i.e. it adds a `$setOnInsert` key if it does not exist already and moves immutable properties under it).
- In the case of `bulkWrite()`, contrary to e.g. `updateOne()`, `_decorateUpdateWithVersionKey()` is not called, so the update object does not already have a `$setOnInsert` key. It is then ignored by `castUpdate()`  because `moveImmutableProperties()` is called too late.
The proposed solution:
- Moved `moveImmutableProperties()` a bit earlier, before the keys of the update are taken, so that `castUpdate()` works on the correct set of keys.
- I thought that would be enough, but actually it …
=> fix(update): immutable properties are ignored in bulk upserts

test/model.populate.test.js
This test sometimes falsely fails, because documents aren't always fetched in the order they are `create(...)`ed in.
I'll look more into this, and see if create inserts documents in the order they're passed in, meanwhile, this should fix this test.
=> test(model): fix flaky text for model.populate

lib/helpers/populate/getModelsMapForPopulate.js, lib/helpers/populate/getVirtual.js, test/model.populate.test.js
fixes: #8924
This attempts to find virtuals on the current schema, if nothing is found, it traverses depth-first in discriminators for that field.
=> fix(populate): populate virtuals defined on child discriminators

docs/schematypes.pug
Adds docs for immutable types in `docs/schematypes.pug` under All Schema Types
=> doc: add immutable type to Schema Types

lib/error/validation.js, test/errors.validation.test.js, test/isolated/project-has-error.toJSON.js
fixes #8985
When user code defines it's own Error.prototype.toJSON, which is defined as a read-only property - the fixed line crashes.
It happens specificly because of the old-school `Object.create(prototype)` thing.
**Summary**
fixes #8985
**Examples**
Added tests
=> fix(errors) - user defines its own r/o err.toJSON

docs/faq.pug
We added this question due to #6566
This is fixed in the driver somewhere along the way, and we don't need to manually use `family: 4` anymore.
```js
run().catch(console.error);
const before = Date.now();
console.log(`Connected in: ${Date.now() - before}ms.`);
}
```
Output:
```
Connected in: 22ms.
```
=> docs(faq): remove faq ipv6

lib/types/core_array.js
No need to add it, already defined on https://github.com/Automattic/mongoose/blob/bfccbe53d75bd71eda2a45361bf7c1196672e273/lib/types/core_array.js#L961
=> refactor: remove CoreMongooseArray#map, defined twice

lib/model.js
I think `update` returns [updateWriteOpResult](https://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#~updateWriteOpResult) rather than writeOpResultObject, but please check.
Also made a few absolute URLs, relative.
=> update returns updateWriteOpResult

lib/document.js, test/document.test.js
**Summary**
This prevents Mongoose from overwriting default values with undefined for nested documents
**Examples**
See #9039
=> fix(document): use the complete path name of a property when avoiding overwriting default values with undefined

History.md, index.pug, lib/helpers/setDefaultsOnInsert.js, lib/validoptions.js, package.json, test/index.test.js
=> feat(mongoose): add support for setting `setDefaultsOnInsert` as a global option

lib/error/serverSelection.js
fixes #9006
The current error message could give the impression that this **is** the reason the connection failed, not just a common reason. According to https://github.com/Automattic/mongoose/issues/9006#issue-618882548 there are other possible reasons (such as incorrect credentials), this PR makes it so that the message is less deterministic.
=> enhancement(connection): make server selection error less deterministic

lib/error/browserMissingSchema.js, lib/error/cast.js, lib/error/disconnected.js, lib/error/divergentArray.js, lib/error/missingSchema.js, lib/error/mongooseError.js, lib/error/notFound.js, lib/error/objectExpected.js, lib/error/objectParameter.js, lib/error/overwriteModel.js, lib/error/parallelSave.js, lib/error/parallelValidate.js, lib/error/serverSelection.js, lib/error/strict.js, lib/error/validation.js, lib/error/validator.js, lib/error/version.js
**Summary**
Converts all errors to real ECMAScript classes that extend Error. This gives a significant performance improvement.
CPU profiles for one of the read benchmarks:
Before:
After:
I also corrected a few of the JSDoc type annotations that looked like copy/paste errors along the way.
=> refactor(error): convert errors to classes extending Error

docs/guide.pug
**Summary**
There was an error in a Schema option (`validateBeforeSave`) example. 
**Examples**
The parameter name of the `validate` function is **`value`**, so the inner variable name must be the same as well.
=> fix docs: validateBeforeSave 

lib/helpers/update/castArrayFilters.js, test/helpers/update.castArrayFilters.test.js
**Summary**
When specified an array filter for an update query, only the first field of the filter object is cast. 
With this merge request, all fields of the filter are iterated and cast.  
**Examples**
```
const schema = new Schema({
comments: [{
text: String,
replies: [{ 
beginAt: Date, 
endAt: Date
}]
}]
});
const q = new Query();
q.schema = schema;
q.updateOne({}, { $set: { 'comments.$[x].replies.$[y].endAt': '2019-01-01' } }, {
arrayFilters: [{ 'x.text': 123 }, { 'y.beginAt': { $gte: '2018-01-01' }, 'y.endAt': { $lt: '2020-01-01' } }]
});
```
The `endAt` field in array filter is not cast to Date.
=> fix(castArrayFilters): handle casting on all fields of array filter

lib/helpers/getDefaultBulkwriteResult.js, lib/model.js, test/model.test.js
=> fix(model): allow empty arrays for bulkWrite

lib/document.js
=> docs: specify the array field syntax for invalidate

test/docs/validation.test.js
Add [validateBeforeSave](https://mongoosejs.com/docs/guide.html#validateBeforeSave) and `invalidate()` to the [Validation guide](https://mongoosejs.com/docs/validation.html).
Is there a way to mark a field as valid, so it will be skipped by the pre-save validation?
=> docs(validation): add validateBeforeSave and invalidate

lib/helpers/setDefaultsOnInsert.js, test/model.test.js
=> fix(model): fix conflicting $setOnInsert default values with `update` values in bulkWrite

lib/document.js, lib/helpers/isPromise.js, test/document.test.js
=> fix(document): disallow `transform` functions that return promises

lib/index.js
**Summary**
correction of typo: l. 216: mangaging -> managing
=> correction of typo

lib/helpers/indexes/isIndexEqual.js
**Summary**
On a collection, and in the schema, have an index with and without a collation. Run `syncIndexes()`, it fails at line 21 with `TypeError: Cannot convert undefined or null to object` when `key` is "collation" but `options.collation` is undefined.
**Examples**
Example arguments to isIndexesEqual that throw an error:
```
key = { name: 1 };
options = { unique: true, background: true };
dbIndex = {
v: 2,
unique: true,
key: { name: 1 },
name: …
```
=> don't throw error when comparing options with/without collation

lib/collection.js
**Summary**
I was reading through the `lib/collection.js` while working on a different project, and happened to notice what appears to be a typo in the error message thrown by `Collection.prototype.createIndex`. If `createIndex` is missing, it complains that `ensureIndex` is missing instead.
Perhaps, this is expected behavior, if so feel free to close it. Just thought I'd do my good deed for the day. 😄 
**Examples**
I don't have a working example of this error being thrown.
=> Fix typo in error message thrown by unimplemented createIndex

package.json
Using `mongodb` version `3.6.1` to fix [this issue](https://github.com/advisories/GHSA-pp7h-53gx-mx7r) and update patch changes.
- Remote Memory Exposure in `bl`: https://github.com/advisories/GHSA-pp7h-53gx-mx7r
- `mongodb` changelog: https://github.com/mongodb/node-mongodb-native/releases/tag/v3.6.1
Thanks for review!
=> chore: update `mongodb` to fix secutiry issue from `bl` dependencies

docs/middleware.pug
MD link format fixed
**Summary**
MD url format is fixed in this PR
**Examples**
The problem : MD code was being rendered as is : [`mongoose.model()](/docs/api/mongoose.html#mongoose_Mongoose-model).
=> `mongoose.model() --> mongoose.model()

lib/cursor/QueryCursor.js, test/query.cursor.test.js
**Summary**
This adds a new feature that allows to optimize QueryCursor usage when populate is passed to the query. It requires a batchSize to be defined on the query, otherwise it will work as usual.
**Motivation**
Actually population on cursors iterates one doc at a time, running N population queries per doc which is not the best scenario for large datasets. By using a custom batchSize, the Mongo driver is already getting a batch of documents into memory, which can be safely be passed into Mongoose QueryCursor without triggering a new getMore command to the server. Then those documents can be populated together, reducing the amount of extra queries to the DB.
**Examples**
```javascript
const cursor = Model.find().populate('someRef anotherRef').batchSize(5).cursor()
// The first .next() …
```
=> Implement cursor population in batches, only when batchSize is passed

lib/plugins/trackTransaction.js, test/es-next/transactions.test.es6.js
**Summary**
Fix a bug with transaction tracking when saving a new document that has array fields:
```
TypeError: Cannot convert undefined or null to object
at Function.assign (<anonymous>)
at mergeAtomics (lib/plugins/trackTransaction.js:87:31)
at _getAtomics (lib/plugins/trackTransaction.js:66:31)
at model.<anonymous> (lib/plugins/trackTransaction.js:26:30)
```
**Examples**
See added test for minimal reproduction.
=> fix(transaction): fix saving new documents w/ arrays in transactions

CONTRIBUTING.md, docs/tutorials/query_casting.md
**Summary**
The [Query Casting](https://mongoosejs.com/docs/tutorials/query_casting.html) documentation has a minor spelling error in it for `analogous`. 
While preparing to send this PR, I found another minor one in the contributing guidelines.
**Solution**
Two very minor spelling fixes.
=> Fix minor spelling error in Query Casting documentation

CONTRIBUTING.md, lib/model.js, lib/query.js
**Summary**
The current documentation for [`Model.findOneAndUpdate`](https://mongoosejs.com/docs/api/model.html#model_Model.findOneAndUpdate) inconsistently document the `overwrite` and `upsert` options between the narrative and tagged parts of the source documentation.  The [`Query.prototype.setOptions`](https://mongoosejs.com/docs/api.html#query_Query-setOptions) does not list the `overwrite`.  From what I could tell it looks like `overwrite` is valid for all write operations.
I also found I had to run `npm install` before running the the documentation make commands, so I through that in the instructions to make it obvious.
_Sidenote:_  I noticed some of the other options are inconsistently documented between the tagged and narrative sections of the documentation. Is there a good place …
=> Update Options for Model.findOneAndUpdate

lib/connection.js, test/connection.test.js
fixes #9505
This PR makes `connection.then` consistent with native promises in the sense that they don't throw execute `.then(...)` arguments unless they were functions.
```js
const p = new Promise((resolve, reject) => {
setTimeout(() => {
// only executes `resolve` if it's a function
resolve('Hello');
}, 10);
});
// does not throw
p.then(null);
```
=>  fix(connection): avoid executing promise handler unless it's a function

lib/query.js
**Summary**
Query.prototype.mongooseOptions is set to a function and then immediately overwritten with another function. This change removes the first redundant assignment.
=> Remove redundant code.

docs/middleware.pug
**Summary**
The documentation does not specificly addresses that both properties 'query' and 'document' must be assigned in order for the 'remove' middleware to execute for the right context (that is on the query or the document).
**Examples**
`   	
const schema = new mongoose.Schema({...});
//middleware on document remove only
//like in doc.remove()	
schema.pre("remove", {query: false, document: true});
//middleware on query remove only 
//like in Model.remove()
schema.post("remove", {query: true, document: false});
`
=> Update middlewar.pug file

docs/faq.pug, lib/drivers/node-mongodb-native/collection.js, test/debug.test.js
**Summary**
Closes #8963, adding a new option `shell` to debug option for logging mongodb-shell friendly output to console.
```mongoose.set('debug', {shell: true})```
**Examples**
1. `mongoose.set('debug')` / `mongoose.set('debug', {shell: false})`
```
Mongoose: Test.insertOne({ _id: ObjectId("5fa9417a6b9b371b344e3760"), dob: new Date("Mon, 09 Nov 2020 13:17:46 GMT"), __v: 0}, { session: null })
```
2. `mongoose.set('debug', {shell: true})`
```
Mongoose: Test.insertOne({ _id: ObjectId("5fa9417a6b9b371b344e3760"), dob: ISODate("Mon, 09 Nov 2020 13:17:46 GMT"), __v: 0}, { session: null })
```
=> feat(debug): #8963 `shell` option for date format (ISODate)

docs/schematypes.pug, lib/options/SchemaStringOptions.js, lib/schema/string.js, test/docs/validation.test.js, test/errors.validation.test.js
**Summary**
Fixes #8777. Updated `docs/schematypes` to reflect the same.
=> fix: make minLength/maxLength behave same as minlength/maxlength

lib/document.js, test/document.test.js
**Summary**
PR to resolve issue where nested paths are not properly transformed. See issue: https://github.com/Automattic/mongoose/issues/9543 .
**Examples**
See issue: https://github.com/Automattic/mongoose/issues/9543
=> fix(document): make transform work with nested paths

lib/schema/array.js, lib/schema/number.js, lib/schema/string.js, test/schema.validation.test.js
=> feat(schema): allow using a POJO for `enum` to support TypeScript enums

lib/utils.js, test/utils.test.js
=> fix(utils.deepEqual): make `deepEqual` treat objects with different order of keys as different

index.d.ts, test/typescript/connection.ts
Fixes https://github.com/Automattic/mongoose/issues/9610
This change fixes the TypeScript type definitions so that we return a
full `Connection` object from `createConnection(url)`, not just a
`Promise<Connection>`.
**Summary**
**Examples**
=> TS: Return `Connection` from `createConnection`

index.d.ts, test/typescript/connectSyntax.ts
Updated the TypeScript example to mirror the example given in the
[deprecation warning docs][1].
[1]: https://mongoosejs.com/docs/deprecations.html
=> fix(index.d.ts): allow `useCreateIndex` in connection options

index.d.ts
Example
```
import mongoose from 'mongoose';
name: {
type: String,
required: [true, "please enter a name"],
minlength: [3, "Minimum name length is 3"],
}
});
```
now we can add custom error messages
=> added missing custom error messages

index.d.ts, test/typescript/createBasicSchemaDefinition.ts
With the new types shipping with 5.11, sub-documents in schemas and arrays of sub-documents error on compile.
This PR attempts to resolve the issue.
Fixes #9631.
=> Fix subdocument types

index.d.ts
As-Is
Even when there is no `cb`, the `cb` type is designated according to the type order.
To-be
=> fix(index.d.ts): order when cb is optional in method

index.d.ts, test/typescript/createBasicSchemaDefinition.ts
fix(index.d.ts): add `Document#__v` so documents have a Version by default
**Summary**
__v  was missing in Document.
**Examples**
See more https://mongoosejs.com/docs/guide.html#versionKey
=> fix(index.d.ts): add `Document#__v` so documents have a Version by default

index.d.ts
**Summary**
add the missing generic declaration for Schema
**Examples**
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts#L886
=> fix(index.d.ts): add the missing generic declaration for Schema

index.d.ts, test/typescript/models.ts
`Type 'Promise<unknown>' is not assignable to type 'Promise<Document>'.`
=> fix(index.d.ts): Fix return type of Model#aggregate()

index.d.ts
=> fix(index.d.ts): allow 2 generic types in mongoose.model function

index.d.ts
**Summary**
Allows schemas with an array of validators (`ValidateOpts`) to be passed, currently the typescript type only allows to pass a single validator.
**Examples**
https://github.com/Automattic/mongoose/blob/master/lib/schematype.js#L713-L717
=> Allow array of validators in SchemaTypeOptions

index.d.ts
=> fix(index.d.ts): add missing Aggregate#skip() & Aggregate#limit()

index.d.ts
**Summary**
Add single document populate to typescript definition. 
**Examples**
https://mongoosejs.com/docs/api/model.html#model_Model.populate
=> fix(index.d.ts): add missing single document populate

index.d.ts
**Summary**
When we want make an complex type and change the type of `_id` the typescript say its is `any` if we don't make something like that :
```ts
type FixedDocument<T> = (T extends {_id?: any } ? Omit<Document, '_id'> : Document) & T
// OR
interface Account extends Omit<Document, '_id'> {
_id: number
username: string
}
```
**Examples**
Now this is more easier and we no longer need `Omit<Document, '_id'>`.
```ts
interface Account extends Document<number> {
username: string
}
=> fix(index.d.ts): allow specify type of _id

index.d.ts
**Summary**
When we want use `toObject` on `Map` or `Array` types we need pass unnecessary options.
**Examples**
Before this we need to pass an empty object for call `toObject` like :
```ts
found.array.toObject({})
found.map.toObject({})
```
After this PR we can omit the options like :
```ts
found.array.toObject()
found.map.toObject()
```
=> fix(index.d.ts): make options optional for `toObject`

docs/css/mongoose5.css
**Summary**
Adds media query for ::before, due to overlap of ::before link icon and headings. 
With this change, the heading makes space for the link icon. 
Resolves #9704
=> fix(css): media query for ::before on headings

index.d.ts, test/typescript/models.ts
```typescript
import { Document, Model, Schema, model } from 'mongoose'
import { cryptor, validator } from '../utils'
export interface UserDocument extends Document {
slug?: string
username: string
email?: string
mobile?: string
password: string
comparePassword: (this: UserDocument, plain: string) => Promise<boolean>
}
export interface UserModel extends Model<UserDocument> {
findByIdentity: (this: UserModel, identity: string) => Promise<UserDocument | null>
}
const schema = new Schema<UserDocument, UserModel>(
{
slug: {
type: String,
required: true,
unique: true,
maxlength: 191,
lowercase: true,
trim: true,
validate: validator.isSlug
},
username: {
type: String,
required: true,
unique: true,
maxlength: 191,
lowercase: true,
trim: true
},
email: {
type: String,
unique: true,
sparse: true, …
```
=> feat(index.d.ts): schema methods & statics types

.github/workflows/test.yml, test/common.js, test/connection.test.js, test/es-next/promises.test.es6.js, test/typescript/main.test.js
**Summary**
Add Github Actions for CI.
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing#building-on-a-public-repositories-only
~Issues:~
- ~`server.start()` for `connection.test.js` [times out](https://github.com/YC/mongoose/runs/1521306207?check_suite_focus=true) on 18.04, so I kept it at 16.04~
- ~There seems to be test cases which fail intermittently.~
~https://github.com/YC/mongoose/runs/1523805152?check_suite_focus=true~
~https://github.com/YC/mongoose/runs/1523805216?check_suite_focus=true~
This test case still fails intermittently.
https://github.com/YC/mongoose/runs/1523777151?check_suite_focus=true
https://github.com/YC/mongoose/runs/1530156061?check_suite_focus=true
```
1) connections:
openUri (gh-5304)
connection events
reconnectFailed (gh-4027):
AssertionError …
```
=> chore: add Github Actions

index.d.ts
**Summary**
add missing overloaded function for Document#populate()
**Examples**
```
await post.populate('author', 'id username').execPopulate();
```
=> fix(index.d.ts): add missing overloaded function for Document#populate()

index.d.ts
**Summary**
It adds a missing group() function to the Aggregate class(index.d.ts).
**Examples**
It will make the following code works in Typescript:
```Typescript
const doc = await Document.aggregate().group({
_id: '$groupId',
total: { $sum: 1 }
});
```
=> fix(index.d.ts): add missing function for Aggregate#group()

index.d.ts
**Summary**
Allow to overwrite the first param of `Model.create` ([like in `@types/mongoose`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3ca6e2420bb5dbef73e971871890e5f47f1f0d79/types/mongoose/index.d.ts#L3306-L3315))
**Examples**
when not allowing to overwrite this, then when using classes or an type with set (and/or get), then the user could not overwrite it to exclude them and typescript would complain that this set(&get) would be missing
(use case: typegoose, having properties & functions & static functions in one class, and typescript does not allow to filter for set(&get))
=> fix(index.d.ts): allow Model.create param1 overwrite

index.d.ts
**Summary**
Adds missing project function to Aggregate to type definitions 
**Examples**
```
Users.aggregate().project({username: 1})
```
=> Add missing projection typing

index.d.ts
Make SchemaDefinition accept a model for more stricter type checking and making the schema consistent with typescript models.
=> Make SchemaDefinition accept a model

index.d.ts, lib/document.js, lib/model.js, lib/plugins/removeSubdocs.js, lib/plugins/saveSubdocs.js
=> feat (document): Exposed $getAllSubdocs()

History.md, index.d.ts, lib/document.js, package.json, test/document.test.js
=> feat: implemented getPopulatedDocs()

index.d.ts
Removed a small typo on code comments.
=> Fix: removed the extra word on comment doc

index.d.ts
I've changed the typescript modifier of the 'overwrite' argument in the Query.prototype.setOptions function to be optional, to be consistent with what is described in the documentation: https://mongoosejs.com/docs/api.html#query_Query-setOptions
**Before**
```ts
// the 'false' parameter is required
this.model.find({ ...query, authorIds: author.id }).setOptions({ maxScan: 1000 }, false);
```
**After**
```ts
// the 'false' parameter can be omitted
this.model.find({ ...query, authorIds: author.id }).setOptions({ maxScan: 1000 });
```
=> chore: changed setOptions's 'overwrite' argument to optional

lib/connection.js, test/es-next/transactions.test.es6.js
**Summary**
Currently I am using `withTransaction` to handle the transaction in my code. As mongoose introduced transaction wrapper to handle Mongoose document state https://mongoosejs.com/docs/api/connection.html#connection_Connection-transaction
There is no option to provide the `mongodb.TransactionOption` basically supported by `withTransaction` method.
Added support to pass the `mongodb.TransactionOptions`
**Examples**
const doc = new Person({ name: 'Will Riker' });
await db.transaction(async function setRank(session) {
doc.rank = 'Captain';
await doc.save({ session });
doc.isNew; // false
// Throw an error to abort the transaction
throw new Error('Oops!');
},{ readPreference: 'primary' }).catch(() => {});
// true, `transaction()` reset the document's state because the
// transaction …
=> TransactionOptions support within transaction wrapper

lib/error/validation.js
**Summary**
This makes `ValidationError.toJSON()` to include the `name` field. This fixes issue #9847. 
**Examples**
See #9847 for example code to reproduce the error.
=> Made ValidationError.toJSON to include the error name correctly

lib/document.js, lib/helpers/timestamps/setupTimestamps.js, lib/model.js, lib/types/embedded.js, test/document.test.js
=> actually updated all the isSelected to $__isSelected

index.d.ts
**Summary**
This PR fixes #9877
**Examples**
Now if you type Model.validate({key: "value"}, ["key"]) on a ts project, ts compiler doesn't warn about invalid arguments 
`Argument of type 'string[]' is not assignable to parameter of type '(err: any) => void'. Type 'string[]' provides no match for the signature '(err: any): void'.`
=> Add missing overload to Model.validate (#9877)

index.d.ts, test/typescript/schema.ts
**Summary**
The `required` field supports defining an array with a function and a message. Modifying the typescript definitions to reflect that.
=> fix(index.d.ts): allow required function in array definition

index.d.ts, test/typescript/create.ts
**Summary**
Current typings do not allow array destructuring, as TypeScript chooses `create<DocContents = T | DocumentDefinition<T>>(doc: DocContents): Promise<T>;` definition even while using `create` with arrays.
=> fix(index.d.ts): reorder create typings to allow array desctructuring

docs/guide.pug
**Summary**
I've found a sentence in [the Schema Aliases section](https://mongoosejs.com/docs/guide.html#aliases) that seems to be mistaken and confusing.
---
```
Now accessing `name` will get you the value of `n`, and setting `n` will set the value of `name`
```
I think it should say ```setting `name` will set the value of `n` ```.
The example a few lines below also supports my assumption:
```js
person.name = 'Not Val';
console.log(person); // { n: 'Not Val' }
```
=> 📝 fixed confusing sentence in Schema docs

lib/index.js
**Summary**
Importing from paths generated at runtime breaks 
parcel, see (https://github.com/parcel-bundler/parcel/issues/4031),
or esbuild, see (https://github.com/evanw/esbuild/issues/480).
By removing the calls to the deprecated global MONGOOSE_DRIVER_PATH
this issue can be resolved.
**Examples**
Lines linke this cause problems because the path will not be resolved by eslint etc.
```
const Connection = require(driver + '/connection');
```
Fixes: https://github.com/Automattic/mongoose/issues/9603
=> remove dynamic import statements

index.d.ts
**Summary**
After 5.11 mongoose started to provide its own types. Some parts of types still use `any (compare the same places with @types/mongoose e.g)
**Examples**
```ts
const { deletedCount } = await Model.deleteMany({ fieldFromModel });
```
while with some tsconfig settings tsc will not complain. But you will need to do the same for typescript-eslint.
=> Improve types

lib/connection.js
**Summary**
When a user calls openUri and attaches more than one callback to its return value with 'then' method, it should be able to pass the result of the first callback to the second one. Currently, openUri always pass 'undefined' to the second callback, making it behave differently from a regular promise. This is unlikely to be an expected behaviour.
To fix it, modify openUri to propagate the return value of the user-provided callback to the 'then' method of the promise.
**Examples**
```javascript
const mongoose = require('mongoose')
mongoose.createConnection('mongodb://localhost:27017/test', {
useNewUrlParser: true,
useUnifiedTopology: true,
}).then((conn) => {
console.log('callback 1', typeof conn);
return 2;
}).then((x) => {
console.log('callback 2', x);
return 3;
}).then((x) => { …
```
=> fix(connection): fix promise chaining for openUri

index.d.ts, test/typescript/queries.ts
Implement query method types and improve `create` method's types by excluding internals and infering children types.
Fixes
#9850
=> Refactor: improve types

index.d.ts
**Summary**
Update the typescript definition for `plugin()` on Schema to add generic support. Currently, the plugin() complains when trying to add a plugin with custom Document/Model definitions.
**Examples**
```
const myDocumentSchema = new Schema<MyDocument, MyModel>({ name: String });
export default function myPlugin(mySchema: Schema<MyDocument, MyModel>): void {
mySchema.add({
plugin: Boolean
})
}
myDocumentSchema.plugin(myPlugin); // <-- this does not work since Schema in plugin does not support generics
```
=> fix: Add generic to plugin schema definition

lib/connection.js
Listening to events on the DB object is deprecated in v3.x and will be unsupported in v4 of the mongodb drivers. Adjusted remaining listeneers to use the DB client object, as per the MongoDB Driver API docs
resolving https://github.com/Automattic/mongoose/issues/9930
**Summary**
**Examples**
=> Fix Event Listeners to comply with (new v3 & v4) MongoDB Driver API changes

index.d.ts
**Summary**
The `query` field on the Schema class is typed incorrectly. It types `this` as the Model type, whereas it should actually be the Query type.
Only thing I'm not sure about is if query functions always return another query, or if they can return other values. Let me know if I need to change anything!
**Examples**
=> fix: query object types on schema

package.json
**Summary**
I was using `mongoose@5.12.0` and was getting this warning on start-up:
```bash
(node:21965) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
``` 
Some research led me to this: https://stackoverflow.com/questions/66049860/cannot-connect-to-mongodb-because-of-wrong-uri/66102270#66102270
Basically `mongodb`, one of this package dependencies, had this bug on 3.6.4. 
2 days ago `mongodb@3.6.5` was released and seems to fix this bug. Hence I am opening a PR to bump the version.
=> Upgrade mongodb dep to 3.6.5 to eliminate inside circular dependency error

index.d.ts
The current implementation is using the same signature for the static level `cast` and instance level `cast`.
However, the instance level `cast` is different.
The use of `any` is crucial here, to allow sub types to specify their narrowed types.
This is true as long as generics is not introduced to `SchemaType`
=> invalid  cast method for instance method of SchemaType

lib/cursor/QueryCursor.js, lib/document.js, test/query.cursor.test.js
It passed all the already failing tests but now introduces 4 failures.
=> fix? hooks now return an array only and typescript bugs fixed?

lib/helpers/model/castBulkWrite.js, test/model.test.js
**Summary**
bulkWrite use `if (model.schema.options.timestamps != null)` to check that it should run `initializeTimestamps()` or not, so it will got error when set `timestamps: false` in schema.
I saw `Model.$__insertMany` use `if (doc.initializeTimestamps)` to check, so I make bulkWrite use the same condition to fix issue.
**Examples**
#10048
=> fix: make bulkWrite can work with `timestamps: false`

index.d.ts
**Summary**
It adds a missing type for discriminator.
**Examples**
This commit will make the following code works in TS:
```Typescript
Image.discriminator<ImageChildDoc, ImageChildModel>('ImageChild', imageChildSchema);
```
=> fix(index.d.ts): add a missing type for discriminator

index.d.ts, test/typescript/middleware.ts
**Summary**
Current typescript method declarations for `insertMany` pre-hook misses parameters passed to original `insertMany` method
**Examples**
Following code
```typescript
schema.pre<Model<ITest>>("insertMany", function (this, next, docs) {
console.log(docs);
});
```
produce compilation error:
```
error TS2345: Argument of type '(this: any, next: any, docs: any) => void' is not assignable to parameter of type '(this: Model<ITest, {}>, next: (err: NativeError) => …
```
=> Fixes #10072

index.d.ts
**Summary**
To ensure consistency in `discriminator()` declarations across
Model, Array and DocumentArray, create a common interface that
has the declarations found in Model, and have the other two classes
implement the interface
- Move `Model.discriminator()` declarations to AcceptsDiscriminator
- Adjust the declarations so that both accept a Schema with at least
the type argument for Document, to line up with expected type argument
of the returned Model
- Implement AcceptsDiscriminator in Array and DocumentArray by copying
the method declarations into the respective class declarations
**Example**
```ts
interface SubDocument extends Document {
// ...
}
const subSchema = new Schema<SubDocument>({
// ...
})
const baseSchema = new Schema<Document>({
// ...
})
const Base = …
```
=> refactor(index.d.ts): move `discriminator()` to common interface

lib/options.js
**Summary**
This fixes issue #10100 by adding `useProjection: false` into `internalToObjectOptions` variable in "/lib/option.js" file so that when calling `Model.save()`, it would save all the fields, including the fields set `select: false` in schema-level.
**Examples**
Model.save() should store all the fields.
```js
const User = mongoose.model('users', new Schema({
username: { type: String, required: true },
password: { type: String, required: true, select: false },  // hidden by default
}, {
toObject: {
useProjection: true,  // to enable projection in schema-level
},
}));
const user = new User({ username: 'testuser', password: 'password' });
await user.save();    // this should do users.insertOne({_id: ObjectId("xxx"), username: 'testuser', password: 'password', __v: 0});
```
=> fix: Model.save does not store fields set with select:false in schema-level

index.d.ts
**Summary**
Fixes #10093. According to [documentation](https://mongoosejs.com/docs/queries.html#streaming), a `Query` instance has an async iterator (which is in fact the `.cursor()`'s async iterator). This pull request makes it possible in Typescript.
**Examples**
Now it is possible to do the following in Typescript:
```
for await (const doc of Person.find()) {
console.log(doc); // Prints documents one at a time
}
```
=> fix: add missing asyncInterator to Query type def

lib/model.js, test/model.test.js
Fixes the bug when `insertedDocs` property may contain docs that were not actually inserted. It only happens when `Model.insertMany()` called with `ordered: true` option. 
Example:
```js
const Test = mongoose.model('Test', new mongoose.Schema({ _id: { type: String } }), 'tests');
Test.insertMany(
[
{ _id: 'test_id' },
{ _id: 'test_id_2' },
{ _id: 'test_id' },
{ _id: 'test_id_3' }
],
{ ordered: true }
).catch(error => {
console.log(error.insertedDocs);
// =>
//
// [
//   { _id: 'test_id', __v: 0 },
//   { _id: 'test_id_2', __v: 0 },
//   { _id: 'test_id_3', __v: 0 }
// ]
// mongo$ > db.tests.find()
//
// { "_id" : "test_id", "__v" : 0 }
// { "_id" : "test_id_2", "__v" : 0 }
});
```
=> fix(model): `insertedDocs` may contain docs that weren't inserted

lib/connection.js, lib/helpers/processConnectionOptions.js, test/connection.test.js
**Summary**
Implements sensible defaults discussed in #9374 if connection readPreference is 'secondary'  or 'preferSecondary'.  If readPreference will be set to 'nearest' or 'primaryPreferred', it warns but otherwise behaves as before.
**Examples**
Several tests added for Mongoose.prototype.connect and Mongoose.prototype.createConnection.
=> Gh 9374 from 6.0

index.d.ts
**Summary**
[In Mongoose 5.12.x official document](https://mongoosejs.com/docs/api/query.html#query_Query-merge), type of `source` parameter in `Query.prototype.merge()` is `Query | Object`.
So, I add `FilterQuery<DocType>` to `source` parameter type.
Please check it :)
=> fix(index.d.ts): add parameter type in merge

docs/css/mongoose5.css, docs/css/style.css, index.html, index.pug
**Summary**
Update the Carbon format on the homepage and documentation page so it's still visible in smaller viewport without using display: none. The CTR will affect the earnings, so this update will increase the ad revenue. I've also made some changes to how the sponsors are displayed:
- Remove border surrounding the image.
- Change to flex layout with margin between each image.
- Restrict the height to 50px to ensure they look sharper and aligned.
You can check out the screenshot for desktop, docs, and mobile here: https://dropover.cloud/fcb1e7
=> style: update carbon format

lib/document.js
This links to an anchor, but the target is on a different page, so this link is broken.
I checked the other links to see how to link, but there are three different approaches used throughout the docs:
- Relative links: `/docs/api/model.html#model_Model.replaceOne`
- http links: `http://mongoosejs.com/docs/api/model.html#model_Model.replaceOne`
- https links: `https://mongoosejs.com/docs/api/model.html#model_Model.replaceOne`
I opted for the https link (`https://mongoosejs.com/docs/api/model.html#model_Model.replaceOne`) since that seemed like the best choice to me.
If you're making a change to documentation, do **not** modify a `.html` …
=> Fix: broken link in document.js

index.d.ts
**Summary**
Basing on https://mongoosejs.com/docs/middleware.html
```
// If you call `next()` with an argument, that argument is assumed to be
// an error.
```  
In the scenario posted below executing just `return next()` is not possible due to TS errors;
```
const RandomSchema = new mongoose.Schema({
id: {
type: String,
required: true,
maxlength: 128,
trim: true
}
}, { _id: false });
RandomSchema.post('findOneAndUpdate', (doc, next) => {
if (doc === null) {
return next();
}
// do sth
} 
```
The only way is to pass `null` as `next` param, but it isn't intuitive.
=> fix: (index.d.ts) don't require error value in pre/post hooks

index.d.ts
Fixes #10250
1. The async iterator is supposed to be a method and not a property;
2. According to underlying implementation, it returns an asyncIterator
and not a query cursor.
**Summary**
This PR addresses #10250
**Examples**
The following code now compiles:
```
import { Schema, model } from "mongoose";
interface Test {
test: string;
}
const schema = new Schema<Test>({
test: { type: String, required: true },
});
const TestModel = model<Test>("Test", schema);
async …
```
=> ts: fix query async iterator definition

index.d.ts
Closes #10252
**Summary**
This PR implements #10252 
**Examples**
Currently, the following TypeScript code compiles, with the bug in the code:
```
import { Schema, model } from "mongoose";
interface Test {
test: string;
}
const schema = new Schema<Test>({
test: { type: String, required: true },
});
const TestModel = model<Test>("Test", schema);
async function main() {
const cursor = TestModel.find({}).cursor();
for await (const test of cursor) {
console.log(test.tedt); …
```
=> ts: strictly typed query cursor async iterator

index.d.ts
**Summary**
The type declaration file was missing `Document.prototype.parent()` this is a method as can be seen here 
https://github.com/Automattic/mongoose/blob/80245edf5aeab304411681035f7f4153dbd2b692/lib/document.js#L3725
It is reflected in the docs [here](https://mongoosejs.com/docs/api/document.html#document_Document-parent).
I just added: the definition, and the description from the documentation. Made sure to put it in alphabetical order with the rest.
**Note**
You still need to keep the type declarations for `EmbeddedDocument.prototype.parent()` and `Subdocument.prototype.parent()` because they narrow the return type from `Document | undefined` to `Document`.
=> Added Document.prototype.parent to type declaration

test/model.update.test.js
This PR adds more test cases to verify the behavior in #10200 works with `new Model(...)` as well as `Model.create(...)`.
It also verifies that nested fields that do not exist in the schema are removed by default.
=> test(model): add more test cases re #10200

lib/query.js
Fixes a small documentation typo for the function Query.prototype.read
before: preferrences 
after: preferences
=> fix typo: preferences

index.d.ts
**Summary**
When using `.map()`, I noticed that the return type wasn't right.
```js
users.find().map((user) => user); // Query<UserDocument, UserDocument>
```
or it should be `Query<UserDocument[], UserDocument>`.
This PR fixes that issue while keeping non-array queries capable of using `.map()`.
=> `.map`'s `ResultType` must be an array if used over an array

lib/schema.js
**Summary**
Originally mentioned here:
https://github.com/Automattic/mongoose/issues/10193 which was (at least partially for us) fixed by @vkarpov15 
When checking if `isUnderneathDocArray` should be true for a given schema the root object of a sub document can be just 'nested' and so it throws an error: "Cannot create property '$isUnderneathDocArray' on string 'nested'".
This fix just slightly extends the work of @vkarpov15 by adding his fix to `schemaType.schema.paths` and `schemaType.schema.subpaths` in addition to `schemaType.schema.singleNestedPaths`.
More recently mentioned here:
https://github.com/Automattic/mongoose/issues/10357
**Examples**
Slightly modified version @IslandRhythms  example (removed need to connect to db since this happens on schema compilation):
```
const …
```
=> check that schema type is an object when setting isUnderneathDocArray

index.d.ts
**Summary**
Fixed typo.
`compatability → compatibility`
=> fix typo (compatability → compatibility)

index.d.ts
**Summary**
Query.cast() args should be optional
reference source:
https://github.com/Automattic/mongoose/blob/6904cdeb83e936ea4e8d370496d1667d0b747594/lib/query.js#L4906
=> fix(TypeScript): Query.cast()

lib/helpers/timestamps/setupTimestamps.js, lib/helpers/update/applyTimestampsToUpdate.js, lib/model.js, lib/query.js, test/model.update.test.js, test/timestamps.test.js
So there is a failing test, however I'm not sure If the test needs to be fixed or my solution needs to be changed. The test is gh-9105
=> enhancement: timestamps createdAt property immutable by default

index.d.ts
**Summary**
As described in the issue #10421, the `.discriminator` function is yielding an error when trying to use an interface that doesn't extends `Document`.
Since Model enforces Document when needed, the discriminator type parameter doesn't need to extend it.
Fixes #10421
**Examples**
```typescript
import { Model, model, Schema } from 'mongoose';
const options = { discriminatorKey: 'kind' };
interface IEvent {
time: Date;
kind: string;
}
const eventSchema = new Schema<IEvent, Model<IEvent>>({ time: Date }, options);
const Event = model<IEvent, Model<IEvent>>('Event', eventSchema);
interface IClickedLinkEvent extends IEvent {
url: string;
}
// ClickedLinkEvent is a special type of Event that has
// a URL.
const ClickedLinkEvent = Event.discriminator<
IClickedLinkEvent, // <-- no more …
```
=> fix(types): remove discriminator type requirement

index.d.ts, lib/schema/array.js, lib/types/embedded.js, test/typescript/middleware.ts
**Summary**
ESLint doesn't throw errors or warnings after removing these comments. Some of the rules have already been globally disabled.
=> lint: remove unnecessary 'eslint-disable' comments

index.d.ts
**Summary**
Added `MongooseOptions` interface and adjusted `Mongoose` constructor, `Mongoose#get` and `Mongoose#set` types.
**Examples**
=> Add `MongooseOptions` interface

index.d.ts, test/typescript/main.test.js, test/typescript/populate.ts
**Summary**
When we call `toObject()` on a populated document, it also modifies the subdocuments. The type signature of `LeanDocument` does not reflect this change. The reason is that `(ObjectId | Document)` does not extend `Document`, so `LeanDocument` ignores it. This PR modifies the definition of LeanDocument, so it becomes distributive over union types.
**Examples**
```typescript
import { PopulatedDoc, Document } from "mongoose";
import { ObjectId } from "mongodb";
interface Child {
name: string;
}
interface Parent {
child?: PopulatedDoc<Child & Document<ObjectId>>,
}
const parent : Parent & Document = {} as Document; // just for type check
const leanChild = parent.toObject().child;
if (leanChild != null && !(leanChild instanceof ObjectId)) {
leanChild.save(); // works, but should not …
```
=> Make LeanDocument work with PopulatedDoc

lib/document.js
**Summary**
Currently the documentation indicates that if a path for depopulate(path) is not provided, then it's a no-op. This is absolutely not true -- in fact, all fields are depopulated. This change fixes the documentation issue.
**Examples**
E.g., depopulate() is not a no-op, it depopulates all populated virtuals.
=> Update depopulate documentation for document.js

index.d.ts
**Summary**
Related #10349 
You can use the repro at https://github.com/andreialecu/repro-mongoose-slow-ts
Output of `yarn tsc --extendedDiagnostics`.
Before:
```
Identifiers:                 82983
Symbols:                    128042
Types:                       42997
Instantiations:             291774
Memory used:               148795K
Assignability cache size:    13123
Identity cache size:             3
Subtype cache size:              0
Strict subtype cache size:       0
I/O Read time:               0.02s
Parse time:                  0.39s
ResolveModule time:          0.03s
ResolveTypeReference time:   0.00s
Program time:                0.45s
Bind time:                   0.19s
Check time:                  1.21s
transformTime time:          0.00s
commentTime time:            0.00s
I/O …
```
=> perf: improve typescript type checking performance

index.d.ts
**Summary**
The type definition for the Query.map() function is incorrect. As an example, it does not understand that a `Model.find()` returns an array nor "pass the mapped value foward" in a correct way
**Examples**
Old:
```typescript
Model.find().map(v => v) // v has type `DocType`
```
New:
```typescript
Model.find().map(v => v) // v has type `DocType[]`
```
Old:
```typescript
Trade.findOne().map(v => v._id).map(w => w) // w has type `DocType`
```
New:
```typescript
Trade.findOne().map(v => v._id).map(w => w) // w has type `ObjectId`
```
=> fix: Fixed incorrect type definition for Query's .map function

index.d.ts
**Summary**
Add missing types for Model's `diffIndexes()` function introduced in 5.13.0.
**Examples**
Will allow using `diffIndexes()` in TypeScript:
```
const MyModel = mongoose.model("MyModel", mySchema);
const indexesDiff = await MyModel.diffIndexes()
```
=> fix(index.d.ts): add missing type for diffIndexes

index.d.ts
**Summary**
Improve types of `Schema#get` and `Schema#set` in order to get better IDE autocomplete.
**Examples**
Same example as shown in #10471.
=> fix(index.d.ts): improve types of `Schema#(g|s)et`

index.d.ts
**Summary**
The current `IndexOptions` definition is missing some mongo-allowed properties, like `partialFilterExpression`.  Since mongoose simply passes the value along (after handling the added `expires` property), the type should be defined in the same way: as a simple extension to the mongo `IndexOptions` type.
**Examples**
This allows the following to work properly (in Typescript)
```ts
export const schema = new mongoose.Schema({ whatever: String, useWhatever: Boolean });
schema.index({ whatever: 1 }, { partialFilterExpression: { useWhatever: true } });
```
=> Define `IndexOptions` in terms of `mongodb.IndexOptions`

index.d.ts
**Summary**
See issue #10561: the Typescript typings for `Schema.index()` were recently broken.  Commit 1c66cc972c90529bd0ffe8496e9de866b92a97fa broke the typing for `Schema.index()` by making `fields` look like mongo's `IndexSpecification`, when it's not: mongoose has its own idea about what the index specification looks like.  This not only undoes that breaking change, but adds additional type-safety so that only actual schema fields can be used in the index definition.
(I'm not 100% sure about the changed return value on `Schema.indexes()`... there may be prefixing and a `background` field added, as per https://github.com/Automattic/mongoose/blob/master/lib/helpers/schema/getIndexes.js.)
Fixes #10561.
**Examples**
With this change, the following code (as Typescript): 
```ts
import …
```
=> Fix type for schema.index() to reflect actual mongoose API

index.d.ts
**Summary**
Array Push Type accepts the T type parameter, it was any
**Examples**
```ts
//typescript
const x = [1,2,3];
x.push('x') // error
//mongoose array
const x = [1,2,3];
x.push('x') // ok
```
```ts
//mongoose array
const x = [ { a: 1 }, { a: 2 } ];
x.push('x') // ok
x.push({ a: 3 }) // no intellisense
```
=> updated array push type definition

index.d.ts
**Summary**
Add TSDoc to `IndexOptions#expires`
Examples adapted from 
https://github.com/Automattic/mongoose/blob/ec41d2222e4692169d15c6f0a968c71ed256fd56/lib/schema/date.js#L125-L142
Note: the tests failing should not have anything to do with this PR, because "only a comment is added" inside types
=> style: add tsdoc to "IndexOptions#expires"

index.d.ts, test/typescript/queries.ts
**Summary**
Mongoose 5.10.x version `QueryOptions` method populate property type allow to use `string`, `ModelPopulateOptions`. This make it easy to develop generic mongoose crud operation. I checked and realized after mongoose version 5.10.x some method is changed. I changed to populate property type for adapt new version.  
**Examples**
Mongoose 5.10.x index.d.ts :
```ts
interface QueryFindBaseOptions {
/** Sets a default collation for every query and aggregation. */
collation?: CollationOptions;
explain?: any;
lean?: boolean;
populate?: string | ModelPopulateOptions;
/** like select, it determines which fields to return */
projection?: any;
/** use client session for transaction */
session?: ClientSession;
}
```
Mongoose 5.13.7 index.d.ts :
```ts
interface QueryOptions {
arrayFilters?: …
```
=> allow QueryOptions populate parameter type PopulateOptions

.github/workflows/test.yml
This PR removes the step "Upgrade Node 5 npm" from GItHub workflows, shouldn't be necessary anymore since we're not using node 5 anymore.
=> chore: remove node 5 upgrade npm from workflows

index.d.ts, test/typescript/populate.ts
**Summary**
According to [mongoose docs](https://mongoosejs.com/docs/api/document.html#document_Document-populate), `Document#populate()` receives, as the first argument, the path to populate or an options object or an array of paths and/or options objects.
However, in the following code, there is a TypeScript error:
```js
import { Schema, model } from 'mongoose';
const personSchema = new Schema({
name: String,
stories: [{ type: Schema.Types.ObjectId, ref: 'Story' }]
});
const storySchema = new Schema({
title: String,
author: { type: Schema.Types.ObjectId, ref: 'Person' },
fans: [{ type: Schema.Types.ObjectId, ref: 'Person' }]
});
const Person = model('Person', personSchema);
const Story = model('Story', storySchema);
(async () => {
const story = await Story.findOne().orFail(new …
```
=> fix(index.d.ts): fix `Document#populate()` type

lib/model.js
**Summary**
`Model.update()` and `Model.remove()` provoke deprecation warnings on the console output. Details can be found on the official [Deprecation Warnings](https://mongoosejs.com/docs/deprecations.html) page.
This PR marks `Model.update()` and `Model.remove()` as deprecated.
**Examples**
Using `Model.update()` or `Model.remove()` result in deprecation warnings like these:
```
(node:5345) [MONGODB DRIVER] Warning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
at emitWarning (/[...]/node_modules/mongodb/lib/utils.js:1109:20)
at Object.emitWarningOnce (/[...]/node_modules/mongodb/lib/utils.js:1122:16)
at Collection.update (/[...]/node_modules/mongodb/lib/collection.js:457:17)
at NativeCollection.<computed> [as update] …
```
=> Mark Model.update and Model.remove as deprecated

.github/workflows/test.yml
**Summary**
Adds test for latest Ubuntu LTS, while preserving 4.0 (which has built binaries up to 18.04). 
Can add other versions if/when necessary.
=> ci: add test for ubuntu-20.04

docs/migrating_to_6.md, lib/document.js, test/document.populate.test.js
When migrating to mongoose 6 I found that the new populate syntax for `Document#populate` was missing some documentation and it was hard to migrate without having a look at the code and guessing that the syntax was the same as `Query#populate`.
I'm not so familiar with documentation, but I copied the one from `Query#populate` which seems like an improvement.
Maybe a "sub-page" could describe what arguments `Query#populate, `Model#populate` and `Document#populate` accept in a single place instead of maintaining that in 3 different places, but I'll leave that up to you.
Also added a few tests to demonstrate the arguments I was adding do work.
=> Improve Document#populate documentation, tests
