README.md

Using yo generator is better for developer to create their own new mongoose plugin. :beers: 
Hopefully I can add generator here.
*also on the website.*

Add generator-mongoose-plugin in Document/plugin section

---

lib/query.js
lib/schema.js
test/model.findOneAndUpdate.test.js

Pre and post hooks for findOneAndUpdate

---

lib/schema.js
test/model.indexes.test.js

Support indexes for schemas that are embedded multiple times

---

lib/model.js
lib/query.js
lib/schema.js
package.json
test/query.middleware.test.js

count() middleware

---

History.md

Fix history dates (2014->2015)

---

History.md

Chetvernikov -> Chetverikov

---

lib/schematype.js

Apply setter on array of objects before array caster setters
Fixes #2698

Fix setter apply order

---

lib/document.js
test/schema.validation.test.js

Create CastError when setting a nested path to a non-object

---

lib/document.js
test/document.test.js

Use correct child transform

---

lib/query.js
test/document.strict.test.js

Enable setting strict as option to findOneAndUpdate

---

lib/document.js
test/schema.onthefly.test.js

On the fly schemas for getters

---

lib/query.js
lib/services/updateValidators.js
test/model.update.test.js

Run update pre hooks before update validators

---

lib/document.js
test/schema.select.test.js

Apply defaults to nested path when parent is selected

---

lib/query.js
lib/schema.js
test/model.findAndRemoveOne.test.js

I want to use findOneAndRemove hooks.

Pre and post hooks for findOneAndRemove

---

CONTRIBUTING.md

Changed the preview information in the Documentation section from 3.6.x to 3.8.x
This is for the stable branch.

Updated info to 3.8.x from 3.6.x

---

lib/schema/documentarray.js
lib/services/updateValidators.js
test/document.unit.test.js
test/model.update.test.js
test/updateValidators.unit.test.js

Enable update validators to run on nested objects and doc arrays

---

lib/document.js
lib/model.js
lib/schema.js
test/model.discriminator.test.js
test/model.middleware.test.js
test/schema.test.js

See #2462. Somewhat janky solution until #2754 can be done.

Make sure pre('validate') runs before pre('save')

---

lib/schema/array.js
test/model.querying.test.js

Properly cast operators in $elemMatch

---

lib/document.js

Corrected `only-the-fly` to `on-the-fly`

Correct typo in documentation

---

lib/document.js
lib/schema/documentarray.js
test/schema.validation.test.js

See issues brought up in #2819

Improve CastError handling for subdocs

---

lib/model.js

As was noted in https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes the signature of a callback was changed to return raw response from update command.

Update docs for Model.update to describe new signature

---

lib/document.js
lib/schema/documentarray.js
lib/types/array.js
lib/types/documentarray.js
lib/types/embedded.js
test/model.update.test.js
test/schema.validation.test.js
test/types.document.test.js

Make cast know about what index the subdoc should be in

---

lib/document.js

Fixes #2867 that I just submitted.

Fixes #2867 - implement addListener on document

---

lib/document.js
test/document.test.js

Properly call non-hook functions from schema call queues

---

lib/schema/documentarray.js

Fixed performance degradation mentionned in #2809  and caused by @6ce5a6c.
According to by benchmarks, it's not the only performance degradation, though it's the most severe one.

Fixed performance degradation

---

lib/model.js
lib/schema.js
test/model.discriminator.test.js
test/schema.test.js
test/schema.validation.test.js

Make sure discriminators get only one copy of default middleware

---

lib/document.js
test/document.test.js
test/model.test.js

Don't apply schema options toJSON() transform to all populated docs

---

lib/model.js
test/model.populate.test.js

prevent null assignment to populated values that didn't match any doc

---

docs/middleware.jade

Corrected pre update hook, confused a lot of users.
#3088 #3038

Corrected pre update hook

---

lib/query.js

ref https://travis-ci.org/ChristianMurphy/nicest/builds/71825514#L269

Scope `projection` to the query module

---

.travis.yml

Allows for faster test start up.
ref http://docs.travis-ci.com/user/workers/container-based-infrastructure/

Switch to Travis CI container infrastructure

---

lib/schema.js
test/schema.test.js

Not sure if you guys might find this useful, but I've already encountered several use-cases, so I thought it would make a good addition to Mongoose.
Unit tests included.

Add method to remove path from schema

---

lib/model.js
lib/utils.js
test/model.populate.test.js

Resubmitting PR #2916 from my master branch because I'm a git noob and it's easier this way lol.

added subPopulate functionality

---

lib/model.js
lib/schema.js
test/document.hooks.test.js
test/model.discriminator.test.js
test/schema.test.js

Pre-save middleware fires on subdocs prior to their parent

---

lib/model.js
test/model.querying.test.js

fixed bug where findById with undefined returned the first doc

---

docs/guide.jade

Provide documentation for the feature discussed here: https://github.com/Automattic/mongoose/issues/1875#issuecomment-104413082
Just a quick addition to the autoIndex documentation.

Docs: Write about the global autoIndex

---

.travis.yml

Adds Node 4 as a test environment in Travis CI

Node 4 Travis CI

---

.eslintrc
benchmarks/populationHeavyLoad.js
examples/promises/promise.js
examples/querybuilder/querybuilder.js
examples/replicasets/replica-sets.js
examples/schema/schema.js
package.json
test/browser/schema.validation.test_.js
test/crash.test.js
test/document.strict.test.js
test/document.test.js
test/model.aggregate.test.js
test/model.discriminator.test.js
test/model.field.selection.test.js
test/model.findOneAndUpdate.test.js
test/model.populate.divergent.test.js
test/model.populate.setting.test.js
test/model.populate.test.js
test/model.querying.test.js
test/model.test.js
test/model.update.test.js
test/query.test.js
test/schema.validation.test.js
test/types.buffer.test.js
test/types.document.test.js
test/versioning.test.js

**Commit Overview**
* Update ESLint to 1.5
* Adds ability to autofix `space-infix-ops`

Lint Infix Operators

---

docs/2.7.x/docs/virtuals.html

Virtual property should display on client side.

updated doc for 2.7.x

---

docs/guide.jade

remove unexpected indent for options.skipVersioning

---

lib/document.js
lib/model.js
lib/query.js
lib/schema.js
lib/schema/boolean.js
lib/schema/buffer.js
lib/schema/date.js
lib/schema/embedded.js
lib/schema/index.js
lib/schema/number.js
lib/schema/objectid.js
lib/schema/string.js
lib/schematype.js
lib/services/updateValidators.js
lib/types/embedded.js
lib/types/index.js
lib/types/subdocument.js
test/document.test.js
test/model.update.test.js
test/schema.test.js
test/updateValidators.unit.test.js

Single embedded schemas

---

lib/utils.js
package.json

Replace internal pluralize with pluralize package

---

lib/schematype.js
test/schema.validation.test.js

gh-1936 - dynamic messages for validators with callback

---

.eslintrc
.gitignore
README.md
package.json
test/docs/promises.test.js
test/document.test.js
test/model.findOneAndUpdate.test.js
test/model.populate.test.js

**Commit Overview**
* Updates `README.md` examples to comma last style
* Updates ESLint to latest version
* Adds a separate lint script to the `package.json`
* Alphabetizes lint rules
* Adds `key-spacing` lint rule
* Resolves various lint warnings

ESLint Update

---

.travis.yml

**Commit Overview**
* Test against Node 4 LTS and Node 5 Stable
ref https://github.com/nodejs/LTS/

Travis CI Node Update

---

lib/schema/string.js

This was breaking make test on a fresh clone of the repo

fix; remove unused npm library

---

lib/schema.js
lib/schema/number.js
test/document.test.js

Removes unused and duplicated variables

General Linting

---

lib/aggregate.js
test/aggregate.test.js

Backporting changes from #3718

backport Aggregate#append fix for arrays from master

---

lib/document.js
lib/schema.js
lib/schema/documentarray.js
lib/types/documentarray.js
lib/types/embedded.js
package.json
test/aggregate.test.js
test/colors.js
test/document.strict.test.js
test/model.findAndRemoveOne.test.js
test/model.findOneAndUpdate.test.js
test/model.geonear.test.js
test/model.geosearch.test.js
test/model.hydrate.test.js
test/model.indexes.test.js
test/model.mapreduce.test.js
test/model.middleware.test.js
test/model.populate.divergent.test.js
test/model.populate.setting.test.js
test/model.populate.test.js
test/model.test.js
test/model.update.test.js
test/schema.test.js
test/types.buffer.test.js

* General lint fixes
* More of the test folder converted to comma last style
continuation of #3657

Comma last test folder part 2

---

lib/model.js

make save/remove/ensureIndexes/mapReduce use promise from provider

---

lib/model.js

make geoSearch return promise obtained from provider

---

lib/schema/date.js

use valueOf to cast date

---

package.json

Updated mongodb dep to 2.1.6 to avoid kerberos error message

---

index.jade

fix Discover Plugins link to plugins.mongoosejs.io

fix Discover Plugins link

---

lib/schema.js
test/schema.timestamps.test.js

This pull request resolves #3951

Allow setup timestamps by Schema.prototype.set

---

lib/model.js

I am going to make a promise for #3946, but meanwhile i found that it has wrong doc.

Wrong doc.

---

package.json

Dependency update with bug fixes.
Bluebird1.10.0 / 2016-03-16 - updated; bluebird to latest 2.10.2 version

Update mquery to 1.10

---

lib/connection.js
lib/drivers/node-mongodb-native/connection.js

As described on https://jira.mongodb.org/browse/NODE-677, I expose the 'all' event here: https://github.com/christkv/mongodb-core/pull/84
Now I want to add it to mongoose as well

Add 'all' event

---

.eslintrc.yml
examples/aggregate/aggregate.js
examples/geospatial/geospatial.js
examples/lean/lean.js
examples/mapreduce/mapreduce.js
examples/promises/promise.js
examples/querybuilder/querybuilder.js
examples/replicasets/replica-sets.js
package.json
test/browser/document.test_.js
test/document.populate.test.js
test/model.field.selection.test.js
test/model.populate.test.js
test/model.stream.test.js
test/versioning.test.js

Improved stability and performance.
Improved indent handling.
Adds textual reporting levels for rules (`0: off, 1: warn, 2: error`).

Update ESLint to 2.4.0

---

docs/schematypes.jade

Fixed https://github.com/Automattic/mongoose/pull/4012.

Added whitespace

---

lib/schema.js
test/schema.timestamps.test.js

* Make sure timestamp functionality does not trigger any unnecessary update

Fixes #3991

---

lib/query.js
lib/querycursor.js
lib/querystream.js
test/query.cursor.test.js

Add QueryCursor to replace QueryStream

---

lib/schema.js
test/schema.test.js

Reverts Automattic/mongoose#4107

Revert "Apply plugins to schemas only once"

---

docs/2.7.x/docs/querystream.html
docs/2.8.x/docs/querystream.html

Word "than" is repeated in documentation.

Remove repeated words 

---

lib/schema.js
lib/types/embedded.js
test/common.js
test/document.test.js
test/model.discriminator.test.js
test/schema.test.js

Trigger remove hooks on subdocs when removing parent

---

lib/drivers/node-mongodb-native/connection.js
lib/error/disconnected.js
lib/model.js
lib/query.js
lib/schema.js
package.json
test/document.test.js
test/query.middleware.test.js

Add support for express-style error handling middleware

---

README.md

change build badge to svg

---

docs/populate.jade
lib/model.js
lib/query.js
lib/schema.js
test/model.populate.test.js

Re: #2562
@alexmingoia thanks for your great work on [mongoose-populate-virtuals](https://www.npmjs.com/package/mongoose-populate-virtuals) - as the resident expert, can you take a look at my changes and see if I missed anything obvious? Docs are still WIP but tests show the general idea of how this works

Expose mongoose-populate-virtuals API in core

---

lib/document.js
test/document.modified.test.js

this clears the modified state on the specified field.

add unmarkModified method

---

lib/querycursor.js
test/query.cursor.test.js

this should close https://github.com/Automattic/mongoose/issues/4253

lean() for migrating from stream() to cursor()

---

lib/connection.js
lib/document.js

Connection#global as shown in the docs is undefined
Should be Connection#config

Small doc fixes

---

lib/types/embedded.js

fix documentation for new 'options' parameter, and set it as optional one

fix embededDocument removal

---

lib/query.js
test/query.cursor.test.js

Respect projection when using cursor

---

lib/schema/array.js
lib/services/common.js
lib/services/updateValidators.js
lib/types/array.js
lib/types/documentarray.js
lib/types/embedded.js
lib/types/subdocument.js
test/model.update.test.js
test/query.test.js
test/types.document.test.js

Ensure nested single embedded errors bubble up to update validators

---

lib/model.js
lib/schema.js
lib/services/updateValidators.js
package.json

Async 2 gives more modularity and performance.
[async changelog](https://github.com/caolan/async/blob/master/CHANGELOG.md)
Was unable to test properly with npm Test, with or without the change.

upgrade async to 2.0.1

---

lib/connection.js

Reverts Automattic/mongoose#4564

Revert "db.open emits error even if it was caught"

---

lib/index.js

schema looses toJSON option, fixes #4601

fixes problem with global plugins and cache

---

lib/schema/string.js

Added $not to SchemaString.prototype.$conditionalHandlers.

Fixed issue #4592

---

lib/document.js
lib/model.js
lib/query.js
lib/schema.js
lib/schema/embedded.js
lib/utils.js
package.json
test/common.js
test/document.test.js
test/model.query.casting.test.js
test/query.test.js
test/query.toconstructor.test.js
test/schema.validation.test.js

retainKeyOrder option

---

lib/error/validation.js

Related issues:
https://github.com/Automattic/mongoose/issues/4675
https://github.com/Automattic/mongoose/issues/4706

Prevent Uncaught TypeError with nodejs v7.

---

docs/2.7.x/docs/schema-options.html

I think the author simply forgot to edit that sentence after adding third option! :)

small typo fix in 2.7.x dics

---

test/document.modified.test.js
test/types.array.test.js

test/types.array.test.js
comparator should now work with Timsort algorithm
test/document.modified.test.js:
made sure a different date is used for update

fixed two tests

---

lib/query.js
test/model.findOneAndUpdate.test.js

Fix #4761: findAndModify passRawResult with lean

---

test/browser/example.test_.js

docs: added in additional information to help others configure webpack to play nice with mongoose

Add webpack configuration instructions

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

I think it could be helpful to guide people opening issues/prs.
Took the files from yarn.

chore(github): add ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md

---

lib/model.js

**Summary**
Change "qurery" to "query".

docs(lib/model.js): fix spelling mistake

---

lib/query.js

Remove unused property and arguments

Micro optimisations

---

README.md

**Summary**
I noticed count is outdated.
**Test plan**

Update Contributors Count

---

lib/model.js
lib/schema/documentarray.js
lib/services/model/applyMethods.js
lib/services/model/applyStatics.js
lib/services/model/discriminator.js
test/model.discriminator.test.js

Discriminators for embedded document arrays

---

lib/schema/buffer.js
test/types.buffer.test.js

Fix bug where updaing a Buffer to null it threw exception

---

index.jade

Dashbox is a business intelligence tool from Softbox (BI). We use mongoose in production
**Summary**
**Test plan**

Add Dashbox new case We use mongoose in production

---

lib/model.js
lib/query.js
lib/services/query/castUpdate.js
test/model.test.js

`Model.bulkWrite()`

---

lib/document.js

Return this from `depopulate()`

---

lib/schematype.js
test/docs/validation.test.js
test/schema.validation.test.js

Support isAsync option for validators

---

lib/schema/array.js
lib/schema/operators/type.js
lib/schematype.js

**Summary**
Fix #5079
allow $type for array fields
**Test plan**
Test script from bug report works as expected with this version

fix(query): handle $type for arrays

---

lib/schema.js

**Summary**
Solve issue #5141 caused by a regression in #5098 
**Test plan**
Cloned schemas are executing hooks again

Solves issue #5141, regression caused by #5098

---

lib/query.js

Reverts Automattic/mongoose#5151

Revert "fix blue bird "a promise was created in a handler but was not returne…"

---

lib/model.js

**Summary**
The first line of in code documentation is contradictory with the second. Updating the first to be consistent with the actual functionality.
**Test plan**
Simple documentation/comment change so no test changes necessary.

Updating documentation to not be contradictory

---

lib/cast.js
lib/query.js
test/model.findOneAndUpdate.test.js

strictQuery option

---

lib/model.js

fix(model): return saved docs when create() fails

---

lib/schema.js
test/timestamps.test.js

feat(timestamps): support already defined timestamps

---

lib/schema.js

**Summary**
Indexes were not being cloned, so the deep clone was not completed. 
**Test plan**

Update clone method to include indexes

---

lib/schema.js
lib/schema/boolean.js
lib/schema/buffer.js
lib/schema/date.js
lib/schema/decimal128.js
lib/schema/embedded.js
lib/schema/number.js
lib/schema/objectid.js
lib/schema/string.js
lib/schematype.js
test/model.query.casting.test.js

Run setters on query option

---

docs/guide.jade

Change custom => customize for readability
**Summary**
**Test plan**

docs: update guide.jade

---

lib/aggregate.js
lib/cursor/AggregationCursor.js
lib/cursor/QueryCursor.js
test/query.cursor.test.js

addCursorFlag

---

lib/schematype.js
lib/types/embedded.js
test/document.test.js

Custom error constructors for custom validators, object form for required

---

lib/schema.js
lib/types/subdocument.js
lib/utils.js
test/document.test.js

emit remove on single nested subdocs when removing parent

---

lib/document.js
lib/schema/embedded.js
test/document.test.js

ensure consistent setter context for single nested 

---

lib/schema.js

Small typo in lib/schema.js

---

docs/populate.jade

**Summary**
Populate Virtuals justOne description was "misleading"

docs: populate virtuals fix justOne description

---

lib/query.js

**Summary**
Fixes #5453
**Test plan**
Reproducable code in bug #5453

Proper handling of 'strict' option per query #5453

---

docs/schematypes.jade

**Summary**
Documents functionality that was added in 4.5 (https://github.com/Automattic/mongoose/issues/1361).
**Test plan**
Tests already exist.

document nested array types

---

docs/schematypes.jade

**Summary**
Fixes spelling
**Test plan**
n/a

Fix property name

---

.travis.yml
test/common.js
test/connection.test.js

Add test coverage for stopping/starting single server

---

lib/document.js
lib/index.js
lib/plugins/idGetter.js
lib/schema.js
lib/schema/objectid.js
test/document.test.js
test/model.field.selection.test.js
test/model.test.js
test/model.update.test.js
test/schema.alias.test.js
test/schema.test.js
test/types.documentarray.test.js

Still 1 failing test, needs some more work

allow setting `id` property after schema was created

---

docs/populate.jade

**Summary**
Found it confusing to read creator instead of author as defined in story schema. This pull request will improve docs.
**Test plan**

Use story schema defined key author instead of creator.

---

lib/model.js
test/docs/validation.test.js

Make unique validator test robust

---

index.jade

Fixed example to work with current stable version

---

docs/schematypes.jade

Fixes typo in `docs/schematypes.jade`
**Summary**
Fixes typo in `docs/schematypes.jade` about adding indexes
**Test plan**

Fixes typo in docs/schematypes.jade

---

package-lock.json
test/plugin.idGetter.test.js

Added idGetter plugin tests
#5713

idGetter plugin tests - confirms #5713 has been solved

---

lib/aggregate.js
lib/cursor/AggregationCursor.js
lib/schema.js
package-lock.json
test/aggregate.test.js

Middleware for aggregate()

---

lib/model.js
lib/utils.js
test/model.test.js

feat(model): report validation errors from `insertMany()` if using `ordered: false` and `rawResult: true`

---

.travis.yml

**Summary**
Adding a check in Travis for Node Js 8 since it is now the recommended version on Node JS download page.
**Test plan**
Testing with travis to see if everything is still working. Everything seems fine when testing on my branch.

Travis Add a check for node js 8

---

docs/faq.jade

There were some grammar errors in this sentence.

Grammar fixes to `unique` FAQ

---

.travis.yml

**Summary**
Adding a check in Travis for Node Js 8 since it is now downloadable on Node JS download page.
I allowed it to fail because this version of node is still in developpement. It can help to see if there are possible bugs with the next version of Node.
**Test plan**
Testing with travis to see if everything is still working. Everything seems fine when testing on my branch.

Add node 9 in travis allowing failures

---

docs/guide.jade

Add link to bufferCommands

---

lib/index.js

**Summary**
This pr will fix and optimize default connection setter, ref connection models with default models (Mongoose.modelNames).
**Test plan**
```javascript
mongoose.connection = 'not connection instance'; // it is not suitable 
```

fix(Mongoose): fix connection setter

---

lib/services/cursor/eachAsync.js

https://github.com/Automattic/mongoose/issues/5874

fix: eachAsync - Treat reject() as a Promise rejection (gh-5874)

---

lib/schema.js

Adds https://github.com/Automattic/mongoose/issues/4973. No test added for this.

Sets saveErrorIfNotFound to true by default in Schema Options

---

lib/model.js
lib/query.js
lib/schema.js
lib/schema/string.js
lib/schematype.js
lib/services/model/discriminator.js
test/model.discriminator.test.js

BREAKING CHANGE: remove getSettersOnQuery, always run setters

---

lib/document.js
test/document.unit.test.js

Merge default options rather than replacing for toObject() + toJSON()

---

lib/document.js
migrating_to_5.md
package-lock.json
package.json
test/docs/validation.test.js
test/document.unit.test.js

BREAKING CHANGE: merge rather than overwrite toObject() and toJSON() options

---

package-lock.json
package.json

**Summary**
resolves https://snyk.io/vuln/npm:marked:20170112
shouldn't have any impact on mongoose, still it's good to get the latest patches.
**Test plan**
`make docs`
check the `docs/api.html` page

chore: update marked

---

History.md

Updated year

---

lib/schema/objectid.js

I was skimming the source code for mongoose and I noticed this typo.

fixed typo in regular expression

---

lib/document.js
lib/services/projection/isExclusive.js
test/docs/defaults.test.js
test/model.populate.test.js

Fix #3781. Put as a separate PR because this is a large change that we want to mull over.

Apply defaults after setting initial value

---

docs/source/api.js

#6135 the api docs for 5.0.5 only show model. 
**Test plan**
make docclean, make gendocs, verified manually after running node static.js

removing comments from docs/source/api.js to restore the api docs

---

lib/aggregate.js
test/aggregate.test.js

**Summary**
These changes make it easier to use replaceRoot, count, and sortByCount aggregate commands.
**Test plan**
Unit tests have been added.

add replaceRoot, count, and sortByCount aggregate helpers

---

benchmarks/benchjs/delete.js
benchmarks/benchjs/insert.js
benchmarks/benchjs/multiop.js
benchmarks/benchjs/read.js
benchmarks/benchjs/update.js

**Summary**
I was trying to test the benchmark of mongoose but saw they are not working with mongodb 3+ version so here is a fix :) (see https://github.com/mongodb/node-mongodb-native/blob/3.0.0/CHANGES_3.0.0.md#api-changes)

Fix benchjs tests for mongodb 3+

---

lib/collection.js
lib/index.js
lib/query.js
test/model.findOneAndUpdate.test.js

`useFindAndModify` option

---

docs/guide.jade

**Summary**
I've updated a broken link to MongoDB's "Compound Indexes" documentation.
**Test plan**
N/A

Update link to MongoDB's "Compound Indexes" docs

---

lib/cursor/AggregationCursor.js
test/aggregate.test.js

**Summary**
I implemented the feature that I requested in #6168. It's pretty much a copy-pasta from how the QueryCursor handles it. Please let me know if you think I should make any changes. If possible, I would love to have this merged into the 4.x branch as well <3
**Test plan**
I made a test that's almost identical to 'parallelization' test for QueryCursor.

AggregationCursor.eachAsync behaves like QueryCursor.eachAsync (#6168)

---

docs/faq.jade

adding a couple faqs per #6170 and #6176

adding faqs for 6170 and 6176

---

lib/query.js

I am changing the example model passed into query.collection() to match the model used to create the query instance. 
model.collection isn't defined in the example.
#6266

updating model name in query api docs. example found while working on #6266 

---

test/aggregate.test.js

Fixed typo in aggregate.test.js

---

docs/faq.jade

adding middleware to list of places on the FAQ not to use arrow functions.
make docclean && make gendocs && node static

adding middleware to faq arrow function warning

---

docs/compatibility.jade

**Summary**
fix the link of the compatibility table of the native mongodb driver
**Test plan**
Test for Docs?

fix link of compatibility table

---

lib/schema.js

**Summary**
Fixes a typo in schema.js docs
**Test plan**
N/A

Docs: visualsOny -> virtualsOnly

---

lib/connection.js

**Summary**
The create connection.createCollection docs used the word delete when I think they meant to use create
**Test plan**
Read the docs please :)

Change docs for create collection

---

docs/source/api.js

The list of links for each sub-section of the api docs is easier to scan through visually when they are in 'alphabetical order'. *where alphabetical in this case is really unicode point order*.  
This change adds a call to `sort()` on the props array based on the value of the string property. 
**This not only reorders the list of links, but also the order that the documentation appears within each sub-section.** 
make docclean && make gendocs && node static

sort api methods based on their string property

---

package.json

mongodb upgrade to 3.0.8 to fix #6357

---

package-lock.json
package.json

**Summary**
Ensures bson before version 1.0.5 is out of version range (https://snyk.io/vuln/npm:bson:20180225).
Closes #6199

chore: update bson

---

migrating_to_5.md

Update geoNear link

---

lib/schema/date.js

fix gh-6443

---

test/schema.date.test.js

**Summary**
provide test for #6444

test for gh-6443

---

docs/guide.jade

**Summary**
Updated guide.jade to include new SchemaTypes, Decimal128 and Map, for consistency with SchemaTypes docs.
Was motivated to update SchemaTypes on the Guide page because I was initially confused by the inconsistency.  Looks like it was an oversight that they were not updated in this location.
**Test plan**
No test; minor change to docs only.

Updated guide.jade to include new SchemaTypes

---

docs/connections.jade

fixes #6492 add simple example to connection docs for multiple hosts

---

lib/error/validator.js
test/schema.validation.test.js

**Summary**
This PR allows passing a function to the validation message.  
In that way the message can be evaluated at the time the model is being validated.
Issue Automattic/mongoose/issues/6523
**Test plan**
```
> mongoose@5.1.3-pre test /Users/lucas/Code/tests/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh6523"
․․
2 passing (77ms)
```

Adding support for dynamic message

---

lib/model.js
test/model.populate.test.js

As shown in #6509, when a refPath points to a path under an array, only the first element is successfully populated. This change addresses that problem by falling back to the whole list of ids instead of returning undefined. 
adding failing test, made it pass, all existing tests pass:
```
mongoose>: npm test -- -g 'gh-6509'
> mongoose@5.1.4-pre test /Users/lineus/dev/opc/mongoose
> mocha --exit test/*.test.js test/**/*.test.js "-g" "gh-6509"
!
0 passing (631ms)
1 failing
1) model: populate:
github issues
populates refPath from array element (gh-6509):
AssertionError [ERR_ASSERTION]: null == true
at …
```

fixes #6509 - allow population of refpath under array

---

docs/queries.jade

**Summary**
`Model.findOneAndUpdate` link on Queries page doesn't work as expected. This PR fixes it
**Test plan**
Visit the page and ensure that it works correctly

Update `Model.findOneAndUpdate` link

---

lib/model.js

updating projection parameter on find, findOne, and findById to reflect the usage of query select.

docs - add string option to projections that call query select

---

docs/guide.jade

As suggested by @LK in #6567, this change updates the query helper example in the guide. It uses where instead of adding the search directly to the condition of the find. 
This is intended to show off the flexibility of query helpers. 
*I added the new line between the model creation and the first query because the addition of the 2nd query threw off the balance of the code block visually*

reworking query helper example just a bit

---

migrating_to_5.md

**Summary**
Fixed a typo on migrating guide
**Test plan**
No code was changed

fixes typo on migrating to 5 guide

---

docs/faq.jade

I've seen this question come up a couple of times recently in the slack channel, and issues like #6742.
make docclean && make gendocs && node static

fixes #6742 add 12 char objectid to FAQ

---

docs/schematypes.jade

**Summary**
Just small changes :) Hope it's correct to just edit the *.jade files.
**Test plan**
Checked the documentation locally too!

SchemaTypes guide improvements

---

lib/helpers/populate/getSchemaTypes.js
test/model.populate.test.js

**Summary**
Fix #6845 introduced by the fix of #6571 ( 6909d3070564161cb23da13eeebf388eb17a732f )

populate with undefined fields without failure

---

History.md
lib/query.js
test/query.test.js

**Summary**
re: #6906 and clean remains of merge conflict of 4.x branch in History.md
**Test plan**
Included in the CI test

Add Query.getOptions() helper

---

lib/document.js
test/document.test.js

**Summary**
This fixes #6925 however I'm not that familiar with the code base so I'm not sure what the potential for other breakage is.
**Test plan**

Fix for #6925. Get value of doubly nested sub doc field.

---

lib/index.js

adding dbName option to list of options for `mongoose.connect()`

fixes #6923 add dbName to api docs for .connect()

---

lib/document.js
lib/model.js

**Summary**
This is just an update to documentation. The callbacks to model.save() and document.save() take two ~~documents~~ arguments, not three, but that wasn't updated everywhere in the docs.
**Test plan**
n/a
These are only documentation/commenting changes.

update documentation for document.save() and model.save()

---

lib/schematype.js

**Summary**
The variable fixed was being used out of context. Simple fix.

Fixing variable not defined - out of scope

---

docs/transactions.jade

docs(transactions): update supporting OS of run-rs

---

lib/document.js
lib/model.js
test/document.test.js

per #6940 
adding doc.replaceOne, doc.updateOne, and an alias from doc.delete to doc.remove.
added a new test for each one, they all pass, all existing tests pass.

Fixes #6940 add doc.{updateOne, replaceOne}. add alias doc.delete for doc.remove

---

docs/faq.jade
docs/schematypes.jade

per #6956 This change adds a note to the schemaTypes page and the faq about mongoose map keys needing to be strings.

Fixes #6956 add note/faq about map keys needing to be strings

---

test/docs/promises.test.js

As pointed out in #6982 The first sentence is incorrect. 

Fixes #6982 fix wording on promise docs to not imply queries only return promises

---

test/query.test.js

add test for updating child timestamps in arrays of subdocs gh4412

---

docs/guide.jade

**Summary**
before: `createdAt`
after: `created_at`
for using customized field name
**Test plan**
n/a

Fix field name

---

lib/index.js

**Summary**
[Current docs](https://mongoosejs.com/docs/api.html#mongoose_Mongoose-connect) are messed up for this option
**Test plan**
N/A

Fix markdown in options.useCreateIndex documentation

---

lib/model.js

The api docs currently state that aggregate doesn't trigger any middleware.

aggregate triggers aggregate middleware

---

lib/aggregate.js

fixed anchor link in Aggregate() section
**Summary**
**Test plan**

Documentation fix: fixed anchor link

---

package.json

**Summary**
Bump version of bson dependency from ~1.0.5 (npm installs 1.0.9) to ~1.1.0 (npm installs 1.1.0).
mongodb-core 3.1.7 has it's dependency set to bson 1.1.0 (^1.1.0)
**Test plan**
Differences between bson 1.0.5 and bson 1.1.0:
https://github.com/mongodb/js-bson/compare/0ea96bd7177839f652393deea69f992136c86f67...39215f038b6787d015bdd1525e4b9db060603350
Differences between bson 1.0.9 and bson 1.1.0:
https://github.com/mongodb/js-bson/compare/765680420a5b83b9e2e50f3d9635a549a28fe6ad...39215f038b6787d015bdd1525e4b9db060603350

Bump version of bson dependency to match mongodb-core

---

lib/index.js

Fixed description of deferred connection opening

docs: Fixed connection description

---

lib/cast.js
lib/helpers/query/castFilterPath.js
lib/helpers/update/castArrayFilters.js
lib/query.js
test/helpers/update.castArrayFilters.test.js
test/model.test.js

Re: https://github.com/Automattic/mongoose/issues/7079

WIP: casting arrayFilters

---

docs/queries.jade

The [(QueryCursor)](https://mongoosejs.com/docs/queries.html#streaming) hyperlink was pointing to something else which I think is not valid.

Fix broken link

---

lib/drivers/node-mongodb-native/collection.js

Palliative correction for issue #7446 .

fix: get debug from options using the get helper

---

lib/helpers/symbols.js
lib/schema.js
lib/schema/array.js
lib/schema/documentarray.js
lib/schema/embedded.js
lib/schematype.js
lib/utils.js
test/model.discriminator.test.js
test/schema.test.js

Clone all schema types when cloning an array

---

docs/index.html
docs/index.jade

'occurred' instead of 'occured'.

[docs] Fix typo

---

lib/browser.js

It allows to import objects from a file using mongoose models, without having it crash

Stub model for browser

---

docs/source/api.js

Fixed document:
`Model.prototypedelete` => `Model.prototype.delete`
`Aggregate.prototypeaddCursorFlag` => `Aggregate.prototype.addCursorFlag`

Fix typo in prototype

---

lib/schema.js

Fix shardKey type to object instead of bool
If you're making a change to documentation, do **not** modify a `.html` file directly. Instead find the corresponding `.jade` file or test case in the `test/docs` directory.
**Summary**
Fixes https://github.com/Automattic/mongoose/issues/7643

Fix shardKey type to object instead of bool

---

lib/types/array.js
test/types.array.test.js

**Summary**
Expose the `MongooseArray#includes` method (fixes https://github.com/Automattic/mongoose/issues/6354).
**Examples**
See `types.array.test.js` for details :-)

feat: support MongooseArray#includes

---

test/docs/discriminators.test.js

**Summary**
https://github.com/Automattic/mongoose/issues/7422

Fix discriminator function parameters doc

---

docs/tutorials/lean.md

Fixed a little typo

---

.github/PULL_REQUEST_TEMPLATE.md
.npmignore
CONTRIBUTING.md
README.md
website.js

**Summary**
- This targets branch 5.6. re: #7880
- Update docs to use `pug`
- Update variables to use `pug`

[5.6] update variables and docs to use 'pug'

---

README.md

**Summary**
Fix casing so that it's correctly indicating that it's a class

Fix casing

---

lib/utils.js

**Summary**
The `if` and `else` cases do exactly the same thing here. No need for the `if`.

remove meaningless conditional

---

docs/guide.pug
docs/schematypes.pug
lib/schema.js

**Summary**
just edit some links

docs: fix some href

---

lib/aggregate.js
package-lock.json
test/aggregate.test.js

**Summary**
Backporting a bugfix to version 4 to fix the aggregate options (see PR #6011)

Backport aggregate options bugfix from #6011

---

lib/schema.js

**Summary**
Help users know this usage
**Examples**
I tested locally this syntax works well on v5.6.6

[docs] add example for issue #7803

---

docs/async-await.pug

**Summary**
Add a guide for using Mongoose with ES6 Async/Await

[docs] add .pug for async-await guide

---

lib/drivers/node-mongodb-native/collection.js

**Summary**
#6403 debug with color as optional.
**Examples**
I tested with 
`mongoose.set('debug', true);`
`mongoose.set('debug', false);`
`mongoose.set('debug', { color: true });`
`mongoose.set('debug', { color: false });`
All works well
I would like to write some unit tests but I do not know how to catch console.info in mocha.

debug support {color: false}

---

docs/faq.pug

**Summary**
add disable debug mode color instruction to FAQ

[doc]add disable color instruction

---

docs/deprecations.pug

fix "using using" typo

---

lib/helpers/parallelLimit.js

fix #8128
**Summary**
new parallelLimit has a bug in an edge case
**Examples**
check #8128

fix(parallel): fix parallelLimit when fns is empty

---

docs/guide.pug

**Summary**
Update link; avoid extra-long source line.

Fix significant performance impact of index creation link in guide

---

lib/schema.js

I have updated a typo for Schema.prototype.plugin() example. 
**Summary**
**Examples**

fix example typo for Schema.prototype.plugin()

---

index.pug

**Summary**
Broken image on home page
According to archives, it is identical to the source link's avatar

Updating link to broken image on home page

---

lib/model.js
test/model.test.js

feat(model): add PoC for Model.validate()

---

lib/model.js
test/document.test.js
test/model.discriminator.querying.test.js

Add test for #8371 verifying that setting `document.isNew = true;` makes `document.save()` tries to insert a new document.

Fixes #8371

---

.npmignore

**Summary**
Fixes missing dist folder in published package
**Examples**

allow browser build to be published (fix #8427)

---

package.json

Fixes #8664 
Upgrading mongodb driver to v3.5.5

Fixes #8664

---

docs/guide.pug

**Summary**
Small typo fix in guide.pug
**Examples**
Fix typo in docs

Small typo fix in guide.pug

---

docs/guide.pug

**Summary**
Correct some minor typos in the guide docs.
**Examples**
animls -> animals

Fix: typos in guide docs

---

lib/model.js
test/document.test.js

fixes #8739
This is WIP, creating a pull request to use the CI to see if I am making any breaking changes quickly.

[WIP] pass custom options from save to Model.exists(...) when no changes are present

---

lib/helpers/model/castBulkWrite.js
lib/model.js
test/model.test.js

Make Model#bulkWrite accept `strict` option

---

lib/queryhelpers.js
test/model.field.selection.test.js

fixes #8806 
Also refactored analyzePaths to be defined at the end of the function instead of in the middle of it, following [the stepdown rule](https://dzone.com/articles/the-stepdown-rule).

Make helpers.applyPaths(...) accept user provided value

---

lib/model.js
test/model.create.test.js

Make Model.create() return an empty array when passed an empty array

---

docs/faq.pug

Docs: make questions on FAQ anchorable

---

lib/options/PopulateOptions.js
lib/schema.js
lib/types/embedded.js
package.json
test/connection.test.js
test/helpers/clone.test.js
test/model.findOneAndUpdate.test.js
test/model.populate.test.js

Add more eslint rules

---

lib/model.js

docs: add options.path for Model.populate(...)

---

benchmarks/create.js
lib/document.js
test/document.populate.test.js

make doc.execPopulate(options) a shorthand for doc.populate(options)

---

docs/lambda.pug

docs: fix race condition in creating connection for lambda

---

lib/schematype.js
test/aggregate.test.js
test/schema.test.js
test/schematype.test.js

fix(schemaType): treat `select: undefined` and `select: null` as not specified

---

test/model.test.js

I mistakenly added this on #8782

Remove unnecessary { strict: false } from test

---

package.json

upgrade mongodb to v3.5.7

---

History.md

I see we're creating changelogs from PR titles, will try to take that into account next time.

correct changelog

---

lib/schema.js
test/schema.test.js

throw error on schema with reserved key with type of object

---

lib/model.js

docs(model): adds options.limit to Model.insertMany(...)

---

lib/helpers/populate/getModelsMapForPopulate.js
test/docs/discriminators.test.js
test/model.discriminator.test.js

fix(model): fix throwing error when populating virtual path defined on child discriminator

---

lib/queryhelpers.js
test/model.field.selection.test.js

fix(query): Query#select({ field: false }) should not overwrite schema selection options

---

lib/model.js

BREAKING CHANGE: drop support for Model#model

---

lib/document.js
test/document.test.js

update Document#save docs

---

lib/aggregate.js
lib/cursor/QueryCursor.js
lib/helpers/cursor/eachAsync.js
test/query.cursor.test.js

fix(cursor): add index as second parameter to eachAsync callback

---

test/query.test.js

This already works, no need for a fix.

add test case to assert #8892

---

lib/model.js
test/model.discriminator.test.js

fix(model): allow POJOs as schemas for model.discriminator(...)

---

lib/helpers/discriminator/getDiscriminatorByValue.js
lib/helpers/model/castBulkWrite.js
test/model.test.js

fix(model): cast bulkwrite according to discriminator schema if discriminator key is present

---

lib/document.js
lib/model.js

docs(document): elaborate on how Document#save() works 

---

docs/schematypes.pug

docs: add note about throwing error only after validation and fix broken reference to api/CastError

---

lib/types/core_array.js
test/types.documentarray.test.js

fix(documentarray): make sure you can call `unshift()` after `map()`

---

lib/helpers/model/castBulkWrite.js
test/model.test.js

fix(bulkwrite): cast filter & update to schema after applying timestamps

---

lib/document.js
lib/model.js

docs(document): add validateModifiedOnly to Document#save(), Document#validateSync() and Document#validate()

---

docs/api/mongoose.html
lib/index.js

The variable name "Schema" is changed to "schema". This will solve the issue of getting undefined when you call "Schema" as it has been than in the snippet.

Corrected a typo in a code snippet.

---

docs/index.pug

Where this file has "var" I am proposing it be changed to "const".
**Summary**
**Examples**

Updated index.pug to ES6

---

docs/index.pug

I am in the process of reading all the sections under Guides, I'll add fixes (broken references, typos, different wording) to this PR to limit the number of PRs to review. Will mark as `Ready to review` once done.

WIP docs: fix typos and broken references

---

test/docs/validation.test.js

docs: minor English fix in Validation

---

lib/helpers/arrayDepth.js
lib/schema/array.js
test/document.test.js

Fixes https://github.com/Automattic/mongoose/issues/9215

fix(array): only cast array to proper depth if it contains an non-array value

---

lib/schema/boolean.js

Proposed fix for https://github.com/Automattic/mongoose/issues/9242

Make Boolean _castNullish respect omitUndefined

---

lib/types/core_array.js

**Summary**
Fixed the link to array.pull

[doc] Fix link to pull

---

lib/query.js

**Summary**
The documentation for Mongoose Query get seems to be slightly inaccurate. This PR fixes the documentation.

Fixing documentation for Mongoose Query get

---

docs/guide.pug

replace var with const

---

lib/document.js
test/document.test.js

enhancement(document): pass document to required validator

---

lib/connection.js
test/connection.test.js

fix(connection): make connection.then(...) resolve to a connection instance

---

lib/query.js

**Summary**
Closes #9551. 
**Examples**

fix(query): maxTimeMS in count, countDocuments, distinct

---

docs/tutorials/dates.md

**Summary**
Fixes a broken example.
**Examples**
Fixes a broken example.

Update dates.md Fixes a broken example.

---

lib/document.js
test/document.test.js

fix(document): allow setting fields after an undefined field

---

lib/index.js
test/connection.test.js

fix(connection): connect and disconnect can be used destructured re #9597

---

docs/middleware.pug

**Summary**
The documentation makes an assumption on gender. This amends that to be more inclusive.

Amend gender assumption

---

lib/schematype.js
test/document.test.js

enhancement(schemaType): pass document to default functions

---

index.d.ts
test/typescript/collection.ts
test/typescript/main.test.js
test/typescript/ts.config.json

fix(types): add collectionName to Collection

---

index.d.ts
test/typescript/base.ts
test/typescript/main.test.js
test/typescript/ts.config.json

types(base): add mongoose.models re #9660

---

index.d.ts

**Summary**
allow the next() argument to be optional
fixes #9664

fix(index.ts): allow the next() argument to be optional

---

index.d.ts

**Summary**
Fixes the post part of https://github.com/Automattic/mongoose/issues/9664

optional next() parameter for post middleware

---

index.d.ts
package.json
test/docs/custom-casting.test.js
test/docs/date.test.js
test/docs/defaults.test.js
test/docs/discriminators.test.js
test/docs/promises.test.js
test/docs/schemas.test.js
test/docs/schematypes.test.js
test/docs/validation.test.js
test/typescript/aggregate.ts
test/typescript/base.ts
test/typescript/collection.ts
test/typescript/connectSyntax.ts
test/typescript/discriminator.ts
test/typescript/methods.ts
test/typescript/middleware.ts
test/typescript/modelInheritance.ts
test/typescript/models.ts
test/typescript/queries.ts
test/typescript/querycursor.ts
test/typescript/subdocuments.ts

**Summary**
this PR adds ts eslint support, and therefoer allows linting the index.d.ts file.
After that, I will add more PRs regarding typedefs support and will address some more "eslint-disable" exceptions.

chore: add eslint typescript support and lint index.d.ts file

---

index.d.ts
test/typescript/models.ts

Dts schema

---

index.d.ts

**Summary**
add missing pre hook for findOneAndUpdate
**Examples**
```
UserSchema.pre('findOneAndUpdate', function() {})
```

fix(index.d.ts): add missing pre hook for findOneAndUpdate

---

.github/workflows/test.yml
README.md

**Summary**
- Run tests on PRs also (apologies for missing this in #9688)
- Update Build Status badge to Github Actions

ci: run on PRs and update badge

---

docs/index.pug

"You should set this option to true, except for the unlikely case that it prevents you from maintaining a stable connection."
**Summary**
**Examples**

Added recommended connection option.

---

History.md

**Summary**
Changed an improper date in the History.md file to prevent confusion.

Correct improper date in History.md

---

History.md
index.d.ts
lib/model.js
lib/query.js
package.json
test/model.test.js
test/typescript/main.test.js
test/typescript/methods.ts

feat: Implemented setting explain flag

---

lib/document.js
lib/schematype.js

fix: changed dependency

---

lib/helpers/populate/getModelsMapForPopulate.js
lib/helpers/populate/getSchemaTypes.js
lib/model.js
test/model.populate.test.js

fix: no more phantom arrays

---

lib/document.js
test/document.test.js
test/model.populate.test.js

These changes worked in my local environment but for some reason when I run it, the code ignores everything

changes not being reflected

---

package.json

**Summary**
* Fixes issue when connecting to a replica set - https://github.com/mongodb/node-mongodb-native/pull/2719
* Possibly related to https://github.com/Automattic/mongoose/issues/9836

Upgrade mongodb driver to 3.6.4

---

docs/api/querycursor.html
index.d.ts
lib/helpers/cursor/eachAsync.js
test/helpers/cursor.eachAsync.test.js

feat: Add batch processing for eachAsync

---

lib/types/map.js

This is described in issue: #9936
Thanks for your time.

Enhancement: Cast ObjectId to string inside of MongooseMap.

---

docs/populate.pug

It's just a small typo fix in the docs. Honestly, I don't think it's a worthy contribution to open PR and I don't expect this to be merged. But still leaving it open, so that you guys may change it when you update your docs or something...
**Summary**
Nothing much, I was going through the docs and found this.
**Examples**
Nothing.

small typo fix

---

lib/helpers/promiseOrCallback.js

Fix for 'ee.listeners is not a function' error.

Fix for 'ee.listeners' error

---

lib/model.js
test/model.indexes.test.js

collation not added to text indexes

---

lib/schema/mixed.js
lib/utils.js
package.json
test/model.test.js
test/utils.test.js

fix(schemaType): make type Mixed cast error objects to pojos

---

lib/helpers/populate/assignVals.js

removed a redundant if statement

---

index.d.ts

**Summary**
Should fix https://github.com/Automattic/mongoose/issues/10146

fix(index.d.ts): add CastError constructor

---

docs/2.7.x/docs/model-definition.html

Added a navbar so that doesn't overlap in devices with screen width less than 1100px
**Summary**
**Examples**

Added a navbar for responsive screen

---

index.d.ts

added onlyVirtuals to loadClass

---

lib/model.js

Enhancement 10254

---

lib/connection.js

**Summary**
This option was added to close #9961, but not documented.

Document noListener option to useDb

---

lib/document.js
test/document.test.js

`pathsToSkip` option for `validate()` and `validateSync()`

---

lib/query.js
test/model.findOneAndUpdate.test.js

fix: make `returnDocument` work (close #10321)

---

lib/model.js

Add Options Parameter Description to Model.exists

---

index.d.ts
test/typescript/virtuals.ts

**Summary**
Created `VirtualTypeOptions` interface, improved `VirtualType` class and adjusted `Schema` methods related to virtuals.
**Examples**
I added a test file in `test/typescript/virtuals.ts`.

fix(index.d.ts): improve typings for virtuals

---

lib/model.js
test/model.indexes.test.js

Feat 10316: Can now do a dryRun of syncIndexes using Model.diffIndexes()

---

lib/document.js
test/document.test.js

Feat 10120: added pathsToSkip option to virtuals

---

index.d.ts

**Summary**
FIxes #10366
**Examples**
Here is POC &dArr;

Added typings for near() in model aggregation

---

docs/tutorials/findoneandupdate.md

**Summary**
The original URL is outdated and it needs to use the new URL on the MongoDB site.

[doc] Fix outdated URL about unindexed upsert

---

lib/document.js
test/model.test.js

**Summary**
Proof of concept and fix for #10441 
**Examples**
check #10441

fix(model): applying object defaults

---

lib/document.js
test/document.test.js

always pass unpopulated path to validator closes #8042 closes #8018

---

test/model.test.js

refactor(test): prefer co/yield over callbacks re #10441

---

lib/model.js
test/model.test.js

test(model): assert Model.bulkSave(...) works if some document is not modified

---

lib/document.js
lib/helpers/document/compile.js
lib/helpers/model/discriminator.js

refactor(defineKey): delete unused parameter, and prefer named parameters over unnamed params

---

package.json

Reverts Automattic/mongoose#10489

Revert "bump bson to 1.1.6 on 4.x"

---

index.d.ts

fix(index.d.ts): fix `debug` type in `MongooseOptions`

---

package.json

Fixes problems with bundling mongodb/mongoose with webpack

bump mongodb to 3.6.11

---

index.d.ts

added proper types to arguments of index method on Schema class.

update type declarations of Schema.index method

---

docs/typescript.md

as mentioned here #10632
**Summary**
New .connect() options  in docs for TS

update TS docs to reflect connect Opts

---

docs/deprecations.md

Update deprecations.md to reflect version 6

---

docs/connections.md
lib/connection.js

Fix #10726 
Didn't see any test to update

Fix username parameter for MongoDB driver

---

docs/typescript/schemas.md

**Summary**
Updating docs to represent breaking changes from https://github.com/Automattic/mongoose/issues/10570 (specifically https://github.com/Automattic/mongoose/commit/86d73f864fe0c66fcc98d9fed167493e2efe2491)

Update to Typescript Schema Documentation 

---

index.d.ts

**Summary**
Fixes #10743
**Examples**
Can be used to return a custom error message
```
new Schema(
{
email: {
type: String,
trim: true,
lowercase: true,
match: [/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w+)+$/, 'Invalid email address']
}
},
{ _id: false }
);
```

fix(typescript definition): schema options for match

---

examples/express/connection-sharing/app.js
examples/express/connection-sharing/routes.js

**Summary**
Adjusted express examples with async and arrows functions
**Examples**
This PR is a simple refactoring of the files in `/examples/express/connection-sharing` folder

Adjusted express examples with async and arrows functions

---

lib/helpers/timestamps/setupTimestamps.js

:bug: Fix error on timesStamps when typeKey is set

---

index.d.ts

Fixes https://github.com/Automattic/mongoose/issues/10790

fix(query): Add type definitions for allowDiskUse

---

docs/populate.md

**Summary**
Corrected grammar issue / missing word, sentence does not read properly without it.
**Examples**
n/a - doc grammar fix

Added missing 'to'

---

lib/model.js

**Summary**
recieve -> receive

chore: fix typo in model.js

---

index.d.ts

**Summary**
This fixes the Buffer type issue mentioned [here](https://github.com/Automattic/mongoose/issues/10838#issuecomment-976006026). It essentially just copies the same fix that was used for Map types from the previously linked thread (this [PR](https://github.com/Automattic/mongoose/commit/317b35b7c2467e1b3d0db5e7d14110582548d600))
**Examples**

types: handle buffer type

---

package.json

latest mongodb driver update for mongoose 6.1

mongodb driver 4.2.1 update

---

package.json

Update mongodb driver to 4.2.2

---

lib/query.js

**Summary**
I discovered a code comment using `/* */` format was causing problem.
I changed it to `//` format which resolves compile issue.
resolves #11095

awaitdata comment fix, resolves #11095

---

index.d.ts

**Summary**
The replaceRoot type was incorrect. The current type requires `newRoot` to be passed to `replaceRoot` which results in a wrong output in an aggregation.

fix replaceRoot type

---

index.d.ts

As discussed in #11059. Thanks to @rpenido @jeremyben.
Fixes #11059 and #11067.
TypeScripts experts reviews are appreciated.

fix(index.d.ts): fix typings in Group stage

---

docs/populate.md

**Summary**
Trying to use the latest es6 features like object destructuring.

docs: use es6 object destructuring instead of regular dot operator for accessing value in object

---

lib/schematype.js

fix(docs): add missing parameter

---

index.d.ts

@vkarpov15 
Corresponding to https://github.com/Automattic/mongoose/commit/36c9e6a2f75f3b27a11673c9988343df38f7811d

bulkSave Typings

---

docs/defaults.md

**Summary**
Remove extraneous backquote from defaults.md

fix(documentation): remove extraneous backquote

---

docs/compatibility.md

MongoDB docs changed where this table lived

Fix Node.js Driver compat link

---

lib/aggregate.js

Replace the deprecated "util.isArray" with Array.isArray.

Replace util is array

---

docs/migrating_to_6.md

docs(migration): add note to change default functions to schema

---

benchmarks/benchjs/casting.js

fix casting benchmark

---

CONTRIBUTING.md
static.js

fix: port for documentation testing in CONTRIBUTING.md

---

test/model.mapreduce.test.js

chore: remove console.log in unit tests

---

lib/document.js
lib/helpers/populate/getModelsMapForPopulate.js
lib/helpers/populate/modelNamesFromRefPath.js
lib/helpers/update/applyTimestampsToChildren.js
lib/helpers/update/castArrayFilters.js
lib/helpers/update/updatedPathsByArrayFilter.js
lib/schema.js
lib/schema/SubdocumentPath.js
lib/schema/array.js
lib/schema/documentarray.js
test/docs/lean.test.js
test/docs/schemas.test.js
test/document.test.js
test/model.findOneAndUpdate.test.js
test/typescript/docArray.ts
test/util.js

Not a big change, but substr is annoying as it always shows me in vscode, that .substr is "deprecated".

chore: replace substr with substring

---

test/model.findOneAndUpdate.test.js

follow up to #11268 
It was easier to rebranch then to revert the changes :P

chore: rename unit test to clarify its purpose

---

lib/index.js
lib/model.js
lib/validoptions.js
test/index.test.js

Reverts Automattic/mongoose#11222

Revert "Sync indexes global option"

---

.github/workflows/test.yml
CONTRIBUTING.md
package.json
tools/repl.js

This PR improves the Developer Experience:
- Added a npm script to automatically symlink mongoose so that typescript tests can run without a hassle. As it uses npm link, it should work reliably across all platforms.
- Added information regarding npm run sym-link-mongoose and npm run mongo.
- modified the github actions script
- fixed repl.js to do actually work with different versions.

improve-dx: make it easier to start development for the project

---

lib/aggregate.js

Fix to aggregate documentation as it was incorrect.

Add "new" to ObjectId class in aggregate.js docs

---

test/docs/debug.test.js
test/docs/transactions.test-quiz.js
test/docs/validation.test.js
test/docs/virtuals.test.js

Fixed missing semicolon and use const instead of let. that can't be changed through reassignment

Fixed missing semicolon and use const instead of let

---

index.pug

(docs): update changelog file to CHANGELOG.md

---

lib/model.js

This is just a little bit golfing. Not a biggy.

simplify a little bit in save handler

---

lib/aggregate.js
lib/browserDocument.js
lib/connection.js
lib/cursor/AggregationCursor.js
lib/cursor/QueryCursor.js
lib/document.js
lib/helpers/printJestWarning.js
lib/index.js
lib/model.js
lib/options/SchemaTypeOptions.js
lib/query.js
lib/schema.js
lib/schema/buffer.js
lib/schema/string.js
lib/schematype.js
lib/types/DocumentArray/index.js
lib/types/array/ArrayWrapper.js
lib/types/array/index.js
lib/types/array/methods/index.js
lib/types/buffer.js

This PR changes urls with http to https.

chore: change http to https in urls in lib-folder

---

lib/document.js
lib/schema/array.js
lib/schema/date.js
lib/schema/decimal128.js
lib/schema/number.js
lib/schema/objectid.js
lib/schema/string.js
lib/schematype.js

Small PR for replacing typeof x == 'string' to typeof x === 'string'

triple equal signs for typeof 

---

test/helpers/arrayDepth.test.js

I wanted to see if there is any opportunity to improve the perf of arrayDepth. Could not improve the perf, but because I wanted to refactor it, I wrote unit tests for it.
So this is just covering all branches of this function.

add unit tests for arrayDepth

---

lib/aggregate.js
test/aggregate.test.js

This PR is more a question. Why do we manually create an object and then assign each field from the source object to the target object, if we  can do the same with Object.assign?

PoC for Object assign

---

lib/types/array/index.js

@vkarpov15 
I fixed mongooseArray error #11397 but this PR is just about to fix the issue for now. I plan to benchmark further so that I know if there is a better solution (performance-wise).

fix broken MongooseArray

---

.lgtm.yml

I use lgtm.com to also find some code smells. With this PR we only check the lib folder and avoiding noise in lgtm.com

add .lgtm.yml for lgtm.com

---

test/types/schema.test.ts
types/index.d.ts

Added definition for Schema pick method.

Schema pick definition

---

types/index.d.ts

Add documentation to types: FilterQuery, UpdateQuery, and LeanDocument.

add docs to: FilterQuery, UpdateQuery, and LeanDocument, types

---

docs/guide.md

docs(timestamps): explain how `timestamps` works under the hood

---

lib/model.js

Fix broken link findAndModify from (node-mongodb-native 2.0 ) to (node-mongodb-native 3.0).
**Summary**
**Examples**

fix: broken link rawResult (findAndModify)

---

.github/.dependabot.yml

This will make dependabot check daily for new versions of packages that we use and create PRs for each dependency.

chore: add dependabot config file

---

examples/statics/statics.js
test/index.test.js

**Summary**
add missing `await` for an async function call

fix: missing await for an async function call

---

package.json

**Summary**
mongodb 4.4.1 has bugfixes https://github.com/mongodb/node-mongodb-native/blob/main/HISTORY.md
**Examples**

Update mongodb driver to 4.4.1

---

test/types/models.test.ts
types/index.d.ts

Reverts Automattic/mongoose#11588

Revert "Bug/types/update query"

---

test/types/populate.test.ts
types/index.d.ts

Related to: https://github.com/Automattic/mongoose/pull/11560

Fix: RawDocType returned from populate FN

---

.github/workflows/test.yml

**Summary**
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
**Examples**

Add permissions to GitHub actions

---

docs/typescript.md

**Summary**
Don't use prefixes in names for interfaces! See the official TS naming guidelines: <https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines>
**Examples**
Instead of `IUser` write `User`

Rename IUser to User

---

docs/typescript.md

Reverts Automattic/mongoose#11631

Revert "Rename IUser to User"

---

lib/schema.js

**Summary**
Fix the [Schema.prototype.post()](https://mongoosejs.com/docs/api/schema.html#schema_Schema-post) example in the documentation.

docs: fix example on Schema.prototype.post()

---

CONTRIBUTING.md

This PR adds infomation regarding the typings tests, which were legit claimed to be missing in #11690

add information regarding typings-tests

---

types/index.d.ts

**Summary**
An option mentioned in [docs](https://mongoosejs.com/docs/populate.html#limit-vs-perDocumentLimit) is missing in typings
**Examples**

fix: populate typing

---

docs/populate.md

Add missing code snippets for Refs to children
For saving Refs to children you may have first save the story before pushing it to author.stories
**Summary**
**Examples**

docs: add code snippets for Refs to children

---

.github/workflows/benchmark.yml
.github/workflows/test.yml
.github/workflows/tidelift-alignment.yml
.github/workflows/tsd.yml

Deactivate node 18 with mongo 4 workflows as we dont run code coverae.

Deactivate node 18 with mongo 4 workflows

---

.github/workflows/benchmark.yml
.github/workflows/test.yml
.github/workflows/tidelift-alignment.yml
.github/workflows/tsd.yml

workflows, change order to tests -> test-replica-sets -> coverage

---

lib/query.js
test/model.populate.test.js

Fix: Recursively populate virtual

---

types/index.d.ts

Mentioned here https://github.com/Automattic/mongoose/pull/11650/files#r863203098

fix typing error for $gt command

---

lib/query.js

clarified docs on populate

---

README.md

Fixes the broken slack badge. Question remains if it is possible to join the slack channel or you still need to get invited...

fix slack badge

---

.github/codeql/codeql-config.yml
.github/workflows/codeql.yml

This action runs GitHub's industry-leading semantic code analysis engine,
CodeQL, against a repository's source code to find security vulnerabilities.
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql
https://github.com/ossf/scorecard/blob/main/docs/checks.md#sast
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Enable codeql action

---

docs/typescript.md

**Summary**
#11682 have rename a doc file and by mistake forget a reference.

Fix a broken link introduced by #11682

---

lib/helpers/path/setDottedPath.js
lib/helpers/topology/isAtlas.js

I checked the codeql warnings. We had three false positives, which i dismissed. I hope this will fix the valid positive security warnings.

Fix codeql sec warnings

---

lib/error/index.js

fix documention of error handling

---

CONTRIBUTING.md
package.json

Add a dev tool that help to watch and benchmark mongoose types.
Screenshot:
one time benchmark:
watch mode:

dev tool: Ts-benchmark

---

test/types/Errors.test.ts
types/error.d.ts

fix: typings mongoose.Error should reference to MongooseError

---

lib/cast/objectid.js
lib/index.js
lib/schema/string.js

this improves the interoperability

impr: use isBSONType instead of instanceof for better interoperability

---

.lgtm.yml
lgtm.yml

should have always been lgtm.yml and not .lgtm.yml

chore: rename lgtm.yml

---

lib/index.js

**Summary**
arugments -> arguments

fix(index): comment typo

---

lib/document.js
test/document.test.js

**Summary**
For `doc = model.findById(id, projection)`, `doc` may not contain some paths because of `projection`.
`doc.toJSON()` should not contain those paths even work with transform.
**Examples**
See unit test in the changes.

fix: toJSON with undefined path, add unit test

---

types/models.d.ts
types/schematypes.d.ts

Reverts Automattic/mongoose#11898

Revert "fix: Discriminator generic type not being passed to schema"

---

lib/document.js

fix documentation of $assertPopulated

---

docs/validation.md

add a next page link as in other guides
**Summary**
**Examples**

docs: Update validation.md

---

docs/schematypes.md

add a next page link as in other guides
**Summary**
**Examples**

docs: Update schematypes.md

---

docs/typescript/subdocuments.md

**Summary**
Properties was missing an i.
**Examples**

Update subdocuments.md to change `propertes` with `properties`

---

test/types/schema.test.ts
types/index.d.ts
types/utility.d.ts

Fix for https://github.com/Automattic/mongoose/issues/12003

Refactor Schema constructor type

---

benchmarks/benchjs/delete.js

Fixed benchmark implementation and formatting

fix benchmark

---

test/types/expressions.test.ts
types/expressions.d.ts

**Summary**
Fixes https://github.com/Automattic/mongoose/issues/11995

Allow null at ne expression second parameter

---

benchmarks/benchjs/insert.js
benchmarks/benchjs/multiop.js

Fixed benchmarks

---

types/indexes.d.ts

Solves `syncIndexes` type error on `continueOn Error` option

---

.github/workflows/benchmark.yml
package.json

Related to https://github.com/Automattic/mongoose/pull/11798#issuecomment-1177796889
Screenshots:
Result when the test has been passed:
Result when the test has been failed:
Live preview links:
https://github.com/Automattic/mongoose/actions/runs/2653201841
https://github.com/Automattic/mongoose/actions/runs/2653233374

Ts-bechmark V1.1.5 for better integration with GitHub workflow actions.

---

package.json

Reverts Automattic/mongoose#12103

Revert "chore: upgrade mongodb driver to 4.8.0"

---

test/schema.test.js
types/mongooseoptions.d.ts

**Summary**
PR #12067 has added some lint problems, which this PR fixes

style: fix lint from #12067

---

lib/document.js
lib/error/index.js
lib/helpers/populate/markArraySubdocsPopulated.js
lib/helpers/projection/hasIncludedChildren.js
lib/index.js
lib/model.js
lib/options/SchemaNumberOptions.js
lib/options/SchemaObjectIdOptions.js
lib/query.js
lib/schema.js
lib/schema/SubdocumentPath.js
lib/schema/documentarray.js
lib/schema/string.js
lib/types/buffer.js
lib/types/map.js

**Summary**
This PR changes JSDOC headers to have a consistent empty JSDOC line

style: change jsdoc headers to have a consistent empty jsdoc line after

---

docs/schematypes.md

docs(fix): fix the link to next page in schema types page

---

docs/typescript/schemas.md

Fix typo `emaill` to `email`

---

test/aggregate.test.js
test/model.test.js

**Summary**
The change from #12236 introduced some flakey tests, this PR fixes those
**Examples**

Fix some flakey tests from #11999

---

.github/workflows/test.yml

**Summary**
This PR adds mongodb 6.0.0 to the tests
fixes #12257

chore(test.yml): add mongodb 6.0.0 to test

---

docs/guide.md

**Summary**
This PR fixes some wrong indents and missing spaces in `guide.md`
i found this while going through some stuff for #3707

docs(guide.md): fix some code indent and missing spaces

---

scripts/website.js

**Summary**
This PR adds watching to the `docs/layout.pug` file, and reload all files from the `filemap` if a change is detected
also de-duplicate file-watching

Reload local documentation on `docs/layout.pug` change

---

types/document.d.ts

As the current code already implements it, just a type declaration fix:
- Change arg type from `string` to `string | Array<string>`.

fix: Update isDirectModified typing

---

.github/workflows/test.yml
package.json

**Summary**
Fix test failures from #12297. I'm not sure exactly why these changes fix the build - `@types` dependencies are notoriously brittle. But the build now passes with no runtime changes.
**Examples**

Fix 5.x build issues

---

types/query.d.ts

Added findById type definitions

---

lib/connection.js
lib/drivers/node-mongodb-native/collection.js
lib/drivers/node-mongodb-native/connection.js
lib/model.js
test/document.isselected.test.js
test/document.populate.test.js
test/document.test.js
test/document.unit.test.js
test/model.discriminator.test.js
test/schema.test.js
test/types.document.test.js
test/types.documentarray.test.js

use setPrototypeOf() instead of __proto__ to allow running on Deno

---

types/middlewares.d.ts

Added findOneAndReplace and replaceOne to query middleware type

---

docs/compatibility.md

Fixed a typo in compatibility docs.

fix(docs): minor typo in compatibility table header

---

test/types/models.test.ts
types/models.d.ts

Fixed replaceOne model's return type

---

docs/index.md

**Summary**
I was studying about how mongoose works and i felt it was missing an important information for a getting started page, how to make a "connect" logged in. I think it can make learn path easier for beginners.

documentation: add info about connect logged in

---

test/schema.validation.test.js

**Summary**
This PR adds a test that tests that `doValidateSync` ignores `async function()` and ignores returned promises
re #8703

Add Test that `doValidateSync` skips async functions and ignores promises

---

test/model.test.js

**Summary**
This PR improves the flakey `expire` + `timeseries` tests by doing:
- change existing tests to only check that all the collection options are set correctly
- also changes existing tests from using `listCollections` to get the options to use `Model.collection.options`
- add a new (single) test to test that mongodb enforces deletion (though having a high timeout)
the new test can go on very long, so it has a measure in place to finish faster if possible, see [Timing of Delete Operations
](https://www.mongodb.com/docs/manual/core/timeseries/timeseries-automatic-removal/#timing-of-delete-operations)

test(model.test): improve flakey "expire" timeseries tests

---

test/types/expressions.test.ts
types/expressions.d.ts

Added TopN to AccumulatorOperator type

---

package.json

upgrade mongodb to v4.10.0

---

lib/document.js
test/document.test.js

Set $inc default value in case field has not been specified on the document

---

lib/queryhelpers.js
test/query.test.js

fix(query): select: false was ignored for Map

---

lib/document.js
lib/helpers/timestamps/setupTimestamps.js
lib/plugins/clearValidating.js
lib/plugins/removeSubdocs.js
lib/plugins/saveSubdocs.js
lib/plugins/sharding.js
lib/plugins/trackTransaction.js
lib/schema.js

**Summary**
This PR adds names (again) to previously unnamed functions, this time focusing on hook functions.
This will help when having to debug how / if any hooks were applied (for example having to debug why a hook as been applied 2 times)
continuating of #12470

Add more names to previously `anonymous` functions

---

lib/helpers/timestamps/setupTimestamps.js
test/timestamps.test.js

fix(timestamps): findOneAndUpdate creates subdocs with timestamps in reverse order

---

lib/model.js
lib/schema.js

Fix #12455
**Summary**
Quick docs fix since the current example doesn't use the actual function the docs are describing
**Examples**

docs(schema): correct example for `Schema.prototype.discriminator()`

---

docs/models.md

Fix #5694
**Summary**
Right now there isn't any info on the docs on how to use Mongoose with MongoDB views. Admittedly I haven't used views in production, so I can't say I'm an expert on the subject. But this new docs section at least demonstrates how to get started with creating a new View in Mongoose.
I also replaced h2 with h1 and h3 with h2 in the models docs, because it doesn't make much sense for the main title of the page to be an h2.
**Examples**

docs(models): add section on MongoDB Views

---

docs/guide.md

**Summary**
This PR fixes some broken (404) read-preference links
fixes #12525

docs(guide): update broken read-preference links

---

lib/connection.js

addresses #11187
Added a short example to describe the usage of the function.

docs(connection): improved useDb() documentation

---

lib/helpers/query/castUpdate.js
test/query.test.js

(fix): Throws error when updating a key name that match the discriminator key name on nested object

---

lib/connection.js
lib/drivers/node-mongodb-native/collection.js
test/docs/debug.test.js

feat(debug): allow setting debug on a per-connection basis

---

.npmignore

Resolves #12725 
**Summary**
**Examples**

Ignore tgz files in .npmignore

---

test/errors.validation.test.js

**Summary**
Added timeout to test which was failing on certain occasions as suggested [here](https://github.com/Automattic/mongoose/pull/12721#issuecomment-1328097084).

fix: increased timeout for flaky test

---

docs/middleware.md

docs(middleware): added note about execution policy on subdocuments

---

docs/middleware.md

**Summary**
Fixed a couple of 404s

docs(middleware): fix broken links

---

docs/index.md

by using `mongoose.connect('mongodb://localhost:27017/test')`  by node application, running on windows, is throwing this error : 
```txt
MongooseServerSelectionError: connect ECONNREFUSED ::1:27017
at Connection.openUri (C:\Users\lenovo\Documents\webistes projects\Node\node prac\mongo\node_modules\mongoose\lib\connection.js:824:32)
at C:\Users\lenovo\Documents\webistes projects\Node\node prac\mongo\node_modules\mongoose\lib\index.js:412:10
at C:\Users\lenovo\Documents\webistes projects\Node\node prac\mongo\node_modules\mongoose\lib\helpers\promiseOrCallback.js:41:5
at new Promise (<anonymous>)
at promiseOrCallback (C:\Users\lenovo\Documents\webistes projects\Node\node prac\mongo\node_modules\mongoose\lib\helpers\promiseOrCallback.js:40:10)
at Mongoose._promiseOrCallback …
```

Not Working: Throwing error with "localhost:27017"

---

test/query.test.js

**Summary**
This PR adds a write-concern to a create, in hopes it fixes some inconsistent replica set tests
for example: https://github.com/Automattic/mongoose/actions/runs/3762716559/jobs/6395685798

test(query.test): add write-concern option

---

docs/js/search.js
docs/search.js

**Summary**
Will need to backport this change for 5.x for it to take effect. But the idea is that the search page currently hits [this project](https://github.com/mongoosejs/backend) to search a `Content` collection, which is generated by `docs/search.js`. With this change, `Content` will have a `version` parameter, and we'll filter search results based on `version`.
**Examples**

Search content by version

---

package.json

Reverts Automattic/mongoose#12858

Revert "chore(deps-dev): bump axios from 1.1.3 to 1.2.2"

---

package.json

fix: upgrade kareem -> 2.5.1, Fix #12836

---

.github/ISSUE_TEMPLATE/bug.yml

Fix #12693
**Summary**
Quick fix to use https://www.compart.com/en/unicode/U+1F41B for the bug emoji
**Examples**

chore: use bug unicode character for issue template

---

docs/validation.md

fixes  Automattic#12921
replace dead links with working links

docs(validation): fix dead links

---

docs/populate.md

fixed typo
**Summary**
**Examples**

fixed typo

---

README.md

update README.md: fixed typo

---

docs/populate.md

Fix #12895
**Summary**
**Examples**

docs(populate): fix out of date comment referencing `onModel` property

---

test/model.findOneAndUpdate.test.js

refactor complete for find one and update tests

---

test/model.findOneAndUpdate.test.js

Reverts Automattic/mongoose#13012

Revert "refactor complete for find one and update tests"

---

index.pug

**Summary**
This PR updates a sponsor image with something that is not 404 or "Resource not found"

style(index.pug): update sponsor image

---

lib/model.js
test/model.test.js

fix(model): fixed post('save') callback parameter

---

lib/helpers/query/castUpdate.js
test/model.discriminator.querying.test.js

https://github.com/Automattic/mongoose/issues/13055

feat(discriminator.querying): allows update doc with discriminatorKey

---

lib/cast.js
test/docs/cast.test.js

Reverts Automattic/mongoose#12898
Re: #13086

Revert "fix(cast): remove empty conditions after strict applied"

---

lib/aggregate.js
test/aggregate.test.js

fix(aggregate): added `await` to prevent exception in aggregate exec

---

test/query.test.js

test(query): added tests for empty projection fix (gh-13059)

---

types/query.d.ts

**Summary**
I added a more precise type definition to the `select` method. 
[Docs](https://mongoosejs.com/docs/api/query.html#query_Query-select)
**Examples**
In the code editor, it gives more information about the argument type

Extend argument type definition of select method

---

test/common.js
test/util.js

**Summary**
This PR tries to add a fix to the "operation interrupted" error in the CI
@vkarpov15 is this what this option will fix / do, or am i understanding the option wrong?

test: try to fix "operation interrupted" errors for CI

---

docs/faq.md
docs/geojson.md

**Summary**
This PR changes some things i had noticed:
- remove the duplicate `cpc` script from `geojson.md`, it gets automatically added from `website.js`
- add a anchor for `not-local` id in `faq.md`

Miscellaneous Docs changes

---

docs/tutorials/findoneandupdate.md

Re: #13221
**Summary**
Added a quick half sentence to clarify why `save()` is preferred over `findOneAndUpdate()`. Don't want to go into too much detail because this is a `findOneAndUpdate()` tutorial.
**Examples**

docs(findoneandupdate): add a quick note about why `save()` is preferred over `findOneAndUpdate()`

---

lib/query.js
test/query.test.js

clearer error message

---

lib/query.js

Fix #13219

---

docs/check-version.md
docs/guides.md
docs/layout.pug
docs/migrating_to_5.md
docs/migrating_to_6.md
docs/source/index.js
docs/version-support.md

Fix #13193
**Summary**
Added a page explaining our support policy for Mongoose versions, including setting an EOL for Mongoose 5. On a related note, also added a page about how to check what Mongoose version you're using.
**Examples**

docs: add version support and check version docs

---

lib/schematype.js

**Summary**
This PR changes another error link slightly above what #13301 changed (the same url)

style(schematype): fix another error link

---

lib/types/index.js
lib/types/uuid.js
package.json
test/schema.uuid.test.js

Fix #13103
**Summary**
Export UUID type from bson, and make sure we handle that type for UUID schema type.
**Examples**

feat: handle MongoDB's new UUID type, export `mongoose.Types.UUID`

---

package.json

Fix #13075
**Summary**
Upgrade for https://jira.mongodb.org/browse/NODE-5200 . We will need to change 6.10.6 milestone to 6.11.0 for this because we're bumping minor versions of the MongoDB node driver
**Examples**

feat: upgrade to mongodb 4.16.0 for Deno+Atlas connection fix

---

index.pug

**Summary**
https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png is a broken link ATM. This PR changes to using https://simonwhitaker.github.io/github-fork-ribbon-css/ - thanks @simonwhitaker :+1:
**Examples**

docs: fix broken "fork me" on home page

---

docs/guide.md

add `excludeIndexes` to the guide schema options

---

lib/document.js
lib/schema.js
test/document.test.js
test/model.populate.test.js

closes #13325 
I'm not sure how to test the if the `toJSON` aspect is correct.

enhancement: propagate `toObject` and `toJSON`

---

docs/tutorials/virtuals.md
lib/schema.js
test/docs/virtuals.test.js

**Summary**
This PR mentions option `virtuals` as possible schema-option, also adds a entry for definition in the `tutorials/virtuals` guide (re-using existing code)

[docs] Add `virtuals` schema options

---

lib/helpers/timestamps/setupTimestamps.js
lib/schema/SubdocumentPath.js
test/schema.test.js

fix: timestamps on subdoc when not set on parent doc

---

lib/schematype.js

Island rhythms/error templating

---

README.md
docs/connections.md
docs/models.md
docs/populate.md
docs/queries.md
docs/schematypes.md

docs: remove callback based examples

---

test/model.findOneAndUpdate.test.js

Re: #13413
**Summary**
Address @AbdelrahmanHafez 's comments on #13437 
**Examples**

test(findOneAndUpdate): add extra assertions from code review for #13437

---

lib/connection.js
lib/model.js

Fix #13334
**Summary**
API docs for `Collection.prototype.collection()` and `Model.collection` are pretty sparse. This provides a bit more info.
**Examples**

docs(connection+model): expand docs on accessors for underlying collections

---

docs/connections.md

**Summary**
Re: @hasezoey 's comments on #13449 
**Examples**

docs(connections): remove unnecessary mongoose.connect() call

---

lib/model.js
test/model.create.test.js
types/models.d.ts

Model.create() ordered option

---

lib/connection.js

**Summary**
Current docs for `destroy()` don't do much to explain why `destroy()` is different from `close()`.
**Examples**

docs(connection): clarify how `Connection.prototype.destroy()` is different from `close()`

---

lib/schematype.js

docs(SchemaType): validate members are validator & message (not msg)

---

docs/guide.md
lib/model.js
lib/schema.js
test/model.test.js
types/schemaoptions.d.ts

Reverts Automattic/mongoose#13513

Revert "feat(schema): add collectionOptions option to schemas"

---

docs/guide.md
lib/model.js
lib/schema.js
test/model.test.js
types/schemaoptions.d.ts

**Summary**
#13526 re-applied to 7.4 branch
**Examples**

Revert "Revert "feat(schema): add collectionOptions option to schemas""

---

docs/connections.md

Fix #12967
**Summary**
`serverSelectionTimeoutMS` is important and occasionally confusing, especially when it seems like `mongoose.connect()` hangs forever. This PR breaks out a separate section in the connection docs on `serverSelectionTimeoutMS`.
**Examples**

docs(connections): expand docs on serverSelectionTimeoutMS

---

docs/middleware.md

Fix #13498
**Summary**
Middleware docs right now use a lot of `console.log('Hi')` examples for middleware, which isn't very useful because typically you want to access some params from the operation that triggered the middleware. This PR adds an example of how to access query filter and update; as well as how to access save options.
**Examples**

docs(middleware): explain how to access query and save() parameters in middleware

---

package.json

5.x - bump mongodb driver to 3.7.4

---

docs/typescript/schemas.md

"descibing" -> "describing"
**Summary**
**Examples**

docs(schemas): fix typo in schemas.md

---

docs/queries.md
docs/schematypes.md
docs/tutorials/ssl.md

**Summary**
This PR does a routine `yarn lint --fix` with plugin `markdown` enabled

docs: routine lint for markdown code run

---

package.json

**Summary**
This PR updates the dev dependencies `@typescript-eslint/*` and `mkdirp`

Update dev dependencies `@typescript-eslint/*` and `mkdirp`

---

lib/query.js
test/model.findOneAndUpdate.test.js

`includeResultMetadata` option

---

docs/guide.md

**Summary**
This PR fixes 7.4 markdown lint errors

docs(guide): fix md lint

---

lib/schema/string.js
test/schema.validation.test.js

allow null values for string enum

---

lib/helpers/schema/idGetter.js
test/schema.alias.test.js

disable id virtual if `alias:id` set

---

lib/schema.js
test/schema.alias.test.js

enhancement: can index using the alias

---

index.d.ts
lib/aggregate.js
test/typescript/generics.ts

Some tests are failing on 5.x related to geoSearch. Is that something I should concern myself with?

Island rhythms/backport pull 12954

---

lib/model.js
test/model.test.js

**Summary**
Backport #13684 to Mongoose v6.

Backport empty bulkwrite fix #13684 to Mongoose v6

---

docs/field-level-encryption.md
docs/guides.md

Fix #13412
**Summary**
Got another question about CSFLE, figured we should write up a quick doc so we don't have to dig through GitHub issues every time. This doc encourages using `schemaMap` rather than collection-level validators.
@alexbevi can you take a look at this too please?
**Examples**

docs: add basic field level encryption docs

---

docs/field-level-encryption.md
docs/source/index.js

**Summary**
This PR does:
- add languages to code-blocks
- add file to file index
re #13471

Fix Markdown (`field-level-encryption.md` )

---

docs/migrating_to_6.md

Re: #12671
**Summary**
Re: https://github.com/Automattic/mongoose/issues/12671#issuecomment-1670998489.
**Examples**

docs(migrating_to_6): add note about incompatible packages

---

docs/layout.pug

**Summary**
The v7 docs' "Migration Guide" link, links to the v6 guide.

docs: link v7 migration guide

---

.github/workflows/test.yml

**Summary**
This PR adds nodejs `20` to the CI test matrix

chore(workflows/test): add node 20 to test

---

lib/helpers/schema/idGetter.js
test/document.test.js

remove id setter

---

scripts/generateSearch.js

**Summary**
Mostly for me so I don't worry that the `generateSearch` script is stuck
**Examples**

chore: print progress when running generateSearch script

---

docs/faq.md

Amend some awkward FAQ wording

---

package.json

Fixes https://github.com/Automattic/mongoose/issues/13926

Upgrade mongodb driver to v5.9.0

---

lib/document.js
test/document.modified.test.js

**Summary**
Backport this PR to 6.x:
- https://github.com/Automattic/mongoose/pull/13674
I just cherry-picked 9968adbb769 in #13674 (and format)

Backport document.isModified fix #13674 to 6.x

---

lib/document.js

**Summary**
This PR fixes a missed import that needed to be changed because of #13909

fix(document): fix import file naming

---

docs/plugins.md

**Summary**
- There is no `lastMod` path in the page: https://mongoosejs.com/docs/plugins.html
- I think `loadedAt` is correct here

fix(document): fix differences between sample codes and documentation

---

docs/migrating_to_7.md

Fix #14020
**Summary**
Add a quick note to the Mongoose 7 migration guide
**Examples**

docs(migrating_to_7): add note about requiring `new` with `ObjectId`

---

lib/schema.js
lib/schema/SubdocumentPath.js
lib/schema/documentarray.js
test/schema.test.js

closes #14055 
It works but the simplicity of the solution makes me feel like I might have broken a bunch of other stuff.

Island rhythms/gh 14055

---

package.json

Bumping mongodb driver to 5.9.1 for mongoose 7.x
**Examples**

Bump mongodb driver to 5.9.1

---

scripts/website.js

**Summary**
This PR changes `scripts/website.js` to automatically fetch and use all `test/docs/` files (unless ignored) plus additional files outside of that directory.
And some additional style changes i noticed.

Update `scripts/website.js` to fetch all `test/docs/` files automatically

---

README.md

**Summary**
This PR updates the README's "breaking changes" version to 8.0.0, because it is now the latest

docs(README): update breaking change version

---

lib/types/ArraySubdocument.js

@vkarpov15 added this null check due to the error I'm facing ( refer below screenshot ). hoping this can be merged, if this is a straight forward use-case. If not,  I will work on a reproducible when I find time.

 null check

---

docs/tutorials/findoneandupdate.md
lib/model.js
lib/query.js

Fix #14246
**Summary**
`overwriteDiscriminatorKey` is a bit hard to find in the docs, this PR adds it to a couple of more places for discoverability.
**Examples**

docs(model+query+findoneandupdate): add more details about `overwriteDiscriminatorKey` option to docs

---

test/docs/lean.test.js

**Summary**
bson@6.4.0 was recently released, and it contains some changes that make `v8Serialize()` make ObjectIds slightly larger. This is causing a test failure, so this PR just updates the tests to use the new serialized length.
**Examples**

test: fix lean test for bson 6.4

---

lib/index.js

Fix #14387
**Summary**
Missed a spot when documenting `overwriteModel`
**Examples**

docs(mongoose): add `options.overwriteModel` details to `mongoose.model()` docs

---

types/query.d.ts

**Summary**
Adds types for the `pre` and `post` functions on the Query class
Fixes: #14432

Added pre and post function types on Query class

---

docs/source/api.js
test/document.test.js

chore: fix typos in comment

---

package.json

**Summary**
It looks like kareem had a `files` entry in `package.json` which prevented us from publishing `index.d.ts`. This PR bumps to a version that has `index.d.ts`.
**Examples**

fix: update kareem -> 2.6.3 for index.d.ts

---

lib/model.js

**Summary**
Fix a typo added in 9fb1d81fc1e81a8523aead9c9fea800bec5fd3af

style(model): fix typo in "$__updateConnection" docs

---

package.json

**Summary**
@vkarpov15 This is a bug fix of a connection leak found in the mongodb driver 5.9.1 (used in mongoose 7.x). Please see release notes https://github.com/mongodb/node-mongodb-native/releases/tag/v5.9.2

Bump mongodb driver to 5.9.2

---

package.json

feat: upgrade mongodb -> 6.6.1

---

package.json

**Summary**
This PR updates some dev-dependencies

Update some dev-dependencies

---

docs/index.md

Provided the correct updated link
**Summary**
Provided the correct updated link. Old link for MongoDB moves to the wrong page
**Examples**

Docs: Fix docs links in index.md

---

lib/helpers/query/cast$expr.js
test/helpers/query.cast$expr.test.js

Fix #14751
Backport #14755 to 7.x
**Summary**
**Examples**

fix(query): handle casting $switch in $expr

---

docs/middleware.md
docs/subdocs.md

**Summary**
re [7.0: Removed remove()](https://mongoosejs.com/docs/migrating_to_7.html#removed-remove)
22f0722a217b69ed37caa905400f15a2a1cae889 was only partially updating everything related to "remove"
found this while browsing through #14808
EDIT:
now also includes another fix i found while making sure #14808 didnt break anything

docs(middleware): update some more "remove" related notes

---

docs/populate.md

Update populate.md to fix missing match: { }

---

lib/document.js
test/document.test.js

**Summary**
Backport a minor bugfix (#14870)
**Examples**

fix: backport #14870 to 6.x

---

package.json

feat: upgrade mongodb -> 6.9.0

---

types/models.d.ts

**Summary**
Remove an unnecessary inconsistency between Mongoose types and MongoDB types
**Examples**

types(model): convert InsertManyResult to interface and remove unnecessary insertedIds override

---

docs/migrating_to_7.md

Re: #13431
**Summary**
Add note about keepAlive deprecation to Mongoose 7 migration guide re: comments from #13431
**Examples**

docs(migrating_to_7): add note about keepAlive to Mongoose 7 migration guide

---

lib/helpers/query/wrapThunk.js

Backport #15039 to 6.x
**Summary**
**Examples**

fix: save execution stack in query as string

---

CHANGELOG.md

**Summary**
Don't want to see merge conflict syntax when reading/browsing it.

docs: Remove merge conflict markers

---

lib/document.js
lib/schema.js

**Summary**
Improve error message for #15071 to help clarify what the issue might be, and also a potential fix. The only possibility I can see for childSchemas `path` property to not be a string is if the schema's `paths` for some reason includes a symbol. Unlikely, but without a repro script in #15071 this is the best we can do.
**Examples**

fix(document+schema): add potential fix for #15071

---

lib/model.js
types/indexes.d.ts

**Summary**
Without this PR, TypeScript complains about `Model.cleanIndexes()` not existing
**Examples**

types: add cleanIndexes() to IndexManager interface

---

types/index.d.ts

**Summary**
`remove()` signature is meant to be `removeIndex()`
**Examples**

types(schema): add missing removeIndex

---

lib/schema/map.js

Re: #15184
**Summary**
Applying comments from [this code review](https://github.com/Automattic/mongoose/pull/15184#discussion_r1923485088), good catch @hasezoey 
**Examples**

refactor(schema): consolidate unnecessary conditionals in map toJSONSchema

---

lib/document.js
lib/model.js
lib/utils.js
test/document.populate.test.js
types/populate.d.ts

Reverts Automattic/mongoose#15231

Revert "Introduce populate ordered option for populating in series rather than in parallel"

---

lib/document.js
lib/model.js
lib/utils.js
test/document.populate.test.js
types/populate.d.ts

Introduce populate ordered option for populating in series rather than in parallel

---

lib/connection.js

Reverts Automattic/mongoose#15245

Revert "fix(connection): unref the "_waitForConnect""

---

lib/types/double.js
lib/types/index.js
test/types/schema.test.ts
types/inferschematype.d.ts
types/types.d.ts

**Summary**
Missed a spot when we added Double schematype in 8.10.
**Examples**

types: add mongoose.Types.Double

---

lib/schema/date.js
types/indexes.d.ts

**Summary**
I just wanted to understand the options for `expires` but the link was outdated.

docs: update references to the `ms` module in date schema documentation

---

test/types/middleware.preposttypes.test.ts
test/types/schema.test.ts
types/index.d.ts
types/middlewares.d.ts

Reverts Automattic/mongoose#15331

Revert "types: make `init` hooks types accurately reflect runtime behavior"

---

lib/error/index.js
test/types/models.test.ts
types/error.d.ts

Fix #15369
**Summary**
Add `MongooseBulkSaveIncompleteError` to `mongoose.Error`
**Examples**

fix: export MongooseBulkSaveIncompleteError

---

package.json

feat: upgrade MongoDB driver -> 6.16

---

docs/jest.md

**Summary**
Found some more quirky behavior with Jest. Add a recommendation to avoid resetModules option re: #15499
**Examples**

docs(jest): add note about resetModules

---

lib/document.js

Fix #15584
**Summary**
Documentation example that, if copied, throws an error.
**Examples**

docs(document): fix code sample that errors with "Cannot set properties of undefined"

---

package.json
types/index.d.ts

feat: use mongodb 6.20
